### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by AlexAti** [serverless/serverless#1]
JAWS is a popular software for blind people, I propose a name change. You could use for example Jama, for Javascript + Amazon stack. You'd need to change the logo to perhaps a Llama (spanish sounding: https://en.wikipedia.org/wiki/Llama).

**Comment by josefdlange** [comment]
No offense to those who require the use of screen readers, but I think this is an excellent name. I don't think there is a lot of overlap of "people who use screen readers" and "people who are writing web applications using Amazon Web Services"

Though, if you want to brainstorm new names:

JawaScript
LambdaStack
J-SAWS (I don't know -- maybe it's some celebrity power couple's mashup name though)
JQSQLAWSda Enterprise Edition 3.0+
JavaSwift (to get those early adopters thinking it's something cool)
AWScript
ObjectiveJavaThonRubyClojForterlTalk-F#-++

**Comment by gliderjockey** [comment]
JawaScript. Brilliant!

**Comment by ChristianBagley** [comment]
I think JAWS is a fitting name. While it may also be the name of a popular software for the blind, I think that the two target audiences are spread widely enough apart that there shouldn't be much confusion.

**Comment by ac360** [comment]
Lol, JawaScript.

**Comment by janraasch** [comment]
JawaScript. Very nice indeed.

**Comment by sergiotapia** [comment]
I like JAWS.

**Comment by sebastiaandegeus** [comment]
@AlexAti  How can this name be any more confusing than a screen reader which shares the name with a swimming animal, James Bond villain and movie classic?

It's a completely different field. What could happen? I wanted to install a screen reader and end up with a js AWS stack...

**Comment by AlexAti** [comment]
@sebastiaandegeus Well I think it was obvious, sorry.

It is not a completely different field. Both JAWS and JAWS are software, as opposed to animals, films and fantasy characters. So there is a huge overlap on use cases where you start with the name.

Both JAWS and JAWS have or will have: official documentation to search for, the need to be installed on hardware, prerequisites, issues, bugs, online communities, services offered for their installation, courses and tutorials for their use, etc.

Add to that the fact that the most usual persona for the use case in one of the two scenarios is BLIND. And then consider for a moment the sorry status of accesibility on the internet.

Also consider that most of the terms that you will use to disabiguate both scenarios will mean nothing to a non-technical person. If your mother was blind, would she be sure that a random page is not talking about JAWS, but about JAWS, or would she be just confused?

So pros of the status quo: the project has a cool name with a cool logo. Cons of the status quo: you harm blind peoples' internet experience.

Please don't let the argument for keeping the name be "well this is not intended for blind people, so they will manage as well as I can do".

**Comment by sebastiaandegeus** [comment]
@AlexAti You cannot be serious. Blind people cannot see, but they can think. They are not mentally disabled. You grossly underestimate the abilities of people who are blind.

**Comment by waynebloss** [comment]
JAWS is a *cool* name and I like it, but for this project it seems inaccurate since the AWS stack can contain a lot more than just Lambda + S3. A more accurate name might reflect that, but honestly, it's not a big deal.

I do not think this will ever be confused with a screen reader, @AlexAti because there is already other software and frameworks out there named JAWS:

- [Judicial Automated Workflow System](http://jaws.fljud13.org/system/howto/JAWSuserManualSinglePageOriginal.html)
- [JAWS Web Server Framework](http://www.dre.vanderbilt.edu/JAWS/)
- [JAWS PDF Creator](http://jaws-pdf-creator.findmysoft.com/)

**Comment by adamburmister** [comment]
I'd keep JAWS :+1: 

If you're searching for JAWS (the screen reader) you're going to be searching for something like "jaws screen reader"... it's a very different vertical.

**Comment by AlexAti** [comment]
@sebastiaandegeus That's not the point, don't be purposely obtuse. I can think and deal with bad design and confusing websites, for example, but I prefer when things are clear and I don't HAVE to think. I didn't meant that blind people will be flabbergasted and abandon the internet.

It is suboptimal to have two overlapping concepts with the same name. This is a project *one day old*, that's why I thought of proposing a name change. I'm sorry if I you think it is ridiculous.

**Comment by hj1980** [comment]
@AlexAti @sebastiaandegeus It's probably worthwhile having a look at this: https://www.google.com.au/trends/explore#q=jaws

**Comment by daveloyall** [comment]
Has anybody here heard of JAWS but still recommends this project take on that name?

I think it's important to note that JAWS isn't a screen reader... it's THE screen reader.

It's also worth noting that lots and lots of sighted people know of (deal with) JAWS because they have to make their products (software, websites) compatible with JAWS.  The person who sits on the other side of this cubicle wall is frequently talking about JAWS on the phone.  I think he's responsibility for Accessibility around here.

Anyway, in general, FYI, when a bunch of your peers tell you that a name is already taken, your response should be "sh*t!", not "f*ck it!". :)

**Comment by austinrivas** [comment]
This is no longer constructive and just bike shedding. I'm sure author wants to focus on features and not this artificial name debate.

**Comment by robertdean** [comment]
If you search Stack Overflow for JAWS you will have to comb through a ton of questions related to the screen reader. This is a promising project. It would be best to change the name now before it becomes a problem. 
I say we call it Python  :)

**Comment by mattheyan** [comment]
JAWS is an excellent name. Naming things is hard, so I understand why you would want to keep this name. And in the spirit of good will towards all, I hope this project succeeds. With that in mind...

* I think it's unfair to call this bike shedding. Overloaded project names can be a real problem and will only get worse over time. It happens and we deal with it when it does, but if it can be avoided early enough in the lifetime of the project, it really should be.
* When I first saw this project the first thing that I thought of was the screen reader. As @daveloyall pointed out, JAWS is *THE* screen reader. Its a significant project that lots of people know and care about.
* Sure, most people searching for JAWS are interested in the movie. Even so, @AlexAti makes a valid point that this is overlap *in the same field*. It's extremely unlikely that the blind will accidentally install this instead of the screen reader, but many developers *will* be searching for information about JAWS (the screen reader), and hopefully they will also be searching for information about JAWS (the web stack). This will cause the need to disambiguate, as I am having to do in this comment.

Anyway, if you decide to keep the name then that's fine. The world isn't coming to an end because of it. But please don't be dismissive of the OP, because this is a valid point to make and should at least be considered carefully.

**Comment by michaelsmanley** [comment]
I noticed in npm this is called jaws-stack. So why not just name it that? Would that not solve the searchability issue, keep the distinction from the well-known JAWS and preserve a convenient acronym?

**Comment by SOSANA** [comment]
Name is fine just Google jaws.js there is yet another name besides jaws for the blind, there's jaws for HTML5 game engine too.

This project is just what I was looking for after checking out the aws lambda doc's. Cool name and can't wait to hack with.... JAWS :)

**Comment by mbilokonsky** [comment]
Surprised this issue hasn't been closed - given that you've left it open can I assume you're still interested in feedback?

FWIW +1 to pick any other name. Naming things is a powerful responsibility and there are very few times in this life when we have the power to decrease the confusion in the universe. 

Not only does JAWS create ambiguity with existing highly popular software but it locks you into Amazon's tools. This lambda architecture thing is, I suspect, going to take off - we will see non-AWS implementations of the same principle. 

Were I you I wouldn't be trying to be the AWS App Dev project, I'd be trying to be the Lambda App Dev project. In a year or three, if this takes off, I guarantee you'll have lots of people wanting something like this for alternate implementations.

**Comment by josefdlange** [comment]
LAWS

+10000000

**Comment by callmeStriking** [comment]
@mbilokonsky I get the feeling that this won't be the only project he works on for Lambda implementations, and that this is locked to AWS while he gets the general feel of a Lambda client library down. It's always a good idea to write code that works first, then to make it generic enough to fit any use-case.

There's probably a reason this issue is open. :)

**Comment by ollierattue** [comment]
JAWS is a fun interesting name. Bigger fish to fry than reworking all logo, command names, documentation etc. Keep JAWS.

**Comment by sopel** [comment]
I think all those arguing in favor of a name change have raised very reasonable concerns, and polluted search spaces for developers have harmed other projects before.

That being said, I came here from the _Branding_ section in the [JAWS v1.0.0 spec](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit):
> We’ve strongly considered changing the name of this project to something else, like SAWS: Server-less AWS.  We even bought saws.io.  But, it’s hard to give up JAWS since people have responded to it so favorably.  At this time, we think we are going to disassociate from JAWS: Javascript + AWS.  Instead, JAWS won’t stand for anything.  It’s just…  JAWS!

There you have it - given the proclaimed exclusive focus on AWS, it's all in the name, and seemingly on par with [GNU](https://en.wikipedia.org/wiki/GNU):
* **JAWS** is **J**ust **A**WS **W**ithout **S**ervers

A really unfortunate naming conflict indeed ...

**Comment by eahefnawy** [comment]
We're now rebranded to Serverless ;) ... closing!
