### ISSUE TITLE
How to set 'Invoke with caller credentials' in an APIG Integration Request

### ISSUE THREAD

**Issue by carlhunterroach** [serverless/serverless#1030]
In my s-function.json under "endpoints" I have "authorizationType": "AWS_IAM"

I'd also like to set "Invoke with caller credentials" in my APIG's Integration Request as it is currently reset to false on each sls deploy.

Can I set this value using SLS?

**Comment by flomotlik** [comment]
@carlhunterroach currently thats not possible. In the future this will be possible with V1 of the service.

**Comment by flomotlik** [comment]
In V1 you can set this up through custom resources.

**Comment by carlhunterroach** [comment]
thanks

**Comment by acaeti** [comment]
For the peanut gallery, though this is possible with custom resources as @flomotlik suggested in 2016, it was not clear to me how to do so.  This serverless forums post by @camhart has the right idea, but it is painful to implement as one must override every lambda's generated CF (or, at least it was for me, with my not-so-great grasp of variables and functionality in serverless.yml): https://forum.serverless.com/t/enable-invoke-with-caller-credentials-on-api-gateway/206/2

I also found this not-published plugin, but haven't tried it, so cannot vouch for it: https://gist.github.com/nachoab/c61c618c4dc5e0abc8e63fd22748cbb2

It seems someone else ran across this and opened #279 in the past, which seemed to have been fixed, but perhaps I am misreading that as having been fixed in a fork or something.  Would be great to get this back for apps using Amplify's API module.
