### ISSUE TITLE
v3 `sls --version` output missing when installed locally in project

### ISSUE THREAD

**Issue by d-fay** [serverless/serverless#10381]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Some weird behavior here after globally installing `serverless@pre-3` globally, then locally. 

When installed globally and outside of project directory running `sls --version` returns the expected output:
```
Framework Core: 3.0.0-pre.7ec1d95c
Plugin: 6.0.0-pre.7d6455ab
SDK: 4.3.0
```

...but after creating the package json file and installing `serverless@pre-3` locally in a project directory, I run `sls --version` and output is missing:
```
Running "serverless" from node_modules

```

-----

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

`serverless --version`

### Command output

```shell
Running "serverless" from node_modules
 
```

**Comment by medikoo** [comment]
@d-fay great thanks for reporting! It's an interesting issue I've diagnosed that, and know the cause, It'll be fixed shortly.

Note, that v3 pre-release branch doesn't have all the updates yet. This issue is related to quirky local fallback behavior which will be revamped in v3 pre-relead before public v3.0.0 release (and having that, such issues will no longer surface)
