### ISSUE TITLE
[RFC] Multi-service deployment in monorepositories

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#10753]
We are exploring ideas for monorepository scenarios where the **deployment of multiple services** must be orchestrated.

For example a repository with the following layout:

```
my-app/
    service-a/
        serverless.yml
    service-b/
        serverless.yml
    service-c/
        serverless.yml
```

Here are the problems we want to resolve:

- Deploy multiple services in parallel
- Optionally order some deployments (e.g. service A must be deployed before service B)
- Pass outputs between services (e.g. service A deploys a database, and service B needs to reference the table name/ARN)

We are exploring some ideas and we want to **gauge the interest** in such features.

If you are using such a setup, and if you are interested, you can:

- **subscribe** to this issue: we plan on sharing updates here in the coming weeks
- add a 👍  to this issue
- post a comment explaining your current setup and challenges

---

**Edit:** we have published a beta version of the feature here: https://github.com/serverless/compose

It will be released in Serverless Framework in the next weeks.

**Comment by fargito** [comment]
Hello !

I have used such setup several times. For me the ideal setup for now is: 
- A monorepo with several `package.json`
- Yarn workspaces to provide hoisting
- [Nx](https://github.com/nrwl/nx) for orchestrating build and deploy operations
- Sharing resources is done through CloudFormation imports and exports (not ideal)

In your example that would give:
```
my-app/
    service-a/
        package.json
        serverless.yml
    service-b/
        package.json
        serverless.yml
    service-c/
        package.json
        serverless.yml
```

I am also very interested in feedbacks for this solution. I have set up a [template repository](https://github.com/fargito/serverless-monorepo-microservices-template) in order to share good pratices and learnings, feel free to take a look!

**Comment by AlphaJuliettOmega** [comment]
I'm looking for any information for something similar,
I'm getting a `x cannot be updated as it is in use by y`

Where another service being used inside a state machine flow has to be `sls remove`'ed but I really don't want to do that.  

WIth multi service setups like above, how do you redeploy a service if another service is dependent on it?

**Comment by mnapoli** [comment]
@AlphaJuliettOmega could you detail a bit more, this is interesting.

The `x cannot be updated as it is in use by y` error you're seeing is caused by "another service being used inside a state machine flow" -> do you mean a Lambda step function?

And how is it used exactly? What gives the `x cannot be updated as it is in use by y` error message? Does this message has anything to do with CloudFormation exports/imports? Any extra detail would be useful.

**Comment by deathemperor** [comment]
I'm using this structure

```
my-app/
    service-a/
        package.json
        serverless.yml
    service-b/
        package.json
        serverless.yml
    service-c/
        package.json
        serverless.yml
```

With Github Actions I'm able to build services in parallels by having a workflow per service with this option:

```
on:
  push:
    branches: [main]
    paths:
      - "my-app/service-c/**"
```

**Comment by mrdck** [comment]
I'm working with own solution that extends package.json with additional deployment specification. This specification is used to generate deployment order.

Each service in monorepo needs to have additonal object in `package.json` which describe service dependencies
```
deployment: {
 dependsOn: ['service-a', 'service-'b]
}
```
At project that I'm working for at work I have quite complex script that generates deployment order using dependency-graph algorithm which generates output something like this `['service-a', 'service-b', 'service-c']` and based on this output I'm executing deployments scripts (sls deploy). This solution gives developer ability to don't care much about deployment order since all what is needed is defining dependencies in package.json.

below there is simple example

// service-a
```
deployment: {
 dependsOn: []
}
```
// service-b
```
deployment: {
 dependsOn: ['service-a']
}
```
This should generate output that looks something like this (deployment is simply iterating over list and executing deploy script)
```['service-a', 'service-'b]```

However this solution is quite trivial despite complex script as it yet lack out of parallel deployment ability. This mean that deploying 10 or more service take a little while. I was thinking about tuning this process a bit however i;m not convinced if this is right direction.

1. Deploy services that other services depends on (deploy until there is no service with dependencies)
2. Deploy the rest using parallel jobs on CI

**Comment by mnapoli** [comment]
Hey everyone, a quick update: we are aiming for a release of that new feature next week 🤞 

I've opened a PR for the documentation here: #10976, if you are interested, feel free to review it (any question you have will help us improve the docs). We'll have a proper public announcement and blog post on release next week.

You can also still beta test it before the stable release next week.

**Comment by mnapoli** [comment]
We released [Serverless Framework Compose](https://www.serverless.com/blog/serverless-framework-compose-multi-service-deployments) last week  🎉 

I'll close this issue. Feel free to add feedback and go through RFCs in the [Compose repository](https://github.com/serverless/compose).
