### ISSUE TITLE
Implement AWS and Lambda support in new Plugin Infrastructure

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1125]
To support AWS as a provider several integrations need to be integrated (or more specifically need to be moved from the current plugin system to the new one). Through this new infrastructure all our basic code should be completely separate from AWS and allow for further provider integrations.

**Comment by ac360** [comment]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

AWS CloudFormation Lambda Resource now offers a `FunctionName` property.  I don't believe this was available before and hopefully it helps us.  CF traditionally added CF data to any Lambda Function Name it deployed.  This sucked, especially since Lambda Name character limit is low.  We should see if using the newly available `FunctionName` prevents CF from adding CF data to the Lambda Function name.

**Comment by flomotlik** [comment]
This is handled in #1124 and #1150 , closing here
