### ISSUE TITLE
Extract project loading to ProjectLoad action

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#1133]
I would like to propose to extract the loading of the project configuration to a separate action, like `ProjectLoad`.

The reason why this would be valuable is that it would allow plugins to hook in on the project loading (pre/post), for example to add functions/endpoints, change existing assets, etc. These modifications would then be reflected in all actions, like Function/EndpointDeploy, DashDeploy, FunctionRun, etc. In the current version (v0.5) it would require to hook in on several different hooks to perform a single modification.

If we agree this is a good idea, I would be happy to submit a PR.

This is related to https://github.com/joostfarla/serverless-cors-plugin/issues/19

**Comment by flomotlik** [comment]
Hi @joostfarla sorry for the late reply on this. Since we've been pushing hard on Serverless V1 over the last 2 months this is a bit outdated as the new plugin system works completely differently and should allow what you're asking for.

We're also currently talking about getting CORS support into our new API Gateway integration. Would be interesting to get your view on it.

I'm going to close this issue for now as its not targeting V1 for now.
