### ISSUE TITLE
Manual confirmation of changes in AWS - dry deployment

### ISSUE THREAD

**Issue by timon2013** [serverless/serverless#11413]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hi, 
In AWS before deploy I want to create "change set", look on this and after manual confirmation deploy this. This is the only thing I miss. It would be a useful feature. 

I started discussion about this https://github.com/serverless/serverless/discussions/11407 

It will be useful in CI/CD workflows. In production deployment, we will be able to reduce the risk of downtime.
Once this functionality is added, I will probably start using Serverless Framework for production deployments.

**Comment by medikoo** [comment]
Thank you @timon2013 for opening that. It's definitely a great idea, let's keep it open for future consideration.

**Comment by medikoo** [comment]
@amuroBosetti we'll be very happy in welcoming this contribution, but let's start first with implementation proposal. Do you have an idea on how best to tackle that?

**Comment by amuroBosetti** [comment]
I definitely do not have one, as I don't have much experience with the codebase or how everything works. I can take a look, maybe look into some smaller issues first, and get back to you :smile:

**Comment by amuroBosetti** [comment]
@medikoo I believe it would be beneficial to have a CLI command only devoted to generating the change description. 
- This way, you can run a sort of `sls plan` only to understand what the impact would be, even if you're not planning on deploying right now.
- This would be useful for setting up a CI workflow in which one step is to do a `sls plan`, print the output, let the developers review it, and then trigger a deploy in a second step. If it's all part of the same command, it would be cumbersome when used in CI.
- It shouldn't be hard to use `createChangeSet`, and after that `DeleteChangeSet` in order to remove it, because we don't intend to actually execute that Change Set. But I'm not that familiar with CloudFormation, so there could be something I'm missing

**Comment by amuroBosetti** [comment]
@medikoo sorry for the late reply, yes, seems like we're talking about the same feature. I don't see much activity in that issue though, is the conversation still going somewhere?

**Comment by medikoo** [comment]
@amuroBosetti afaik it's the only place were it was discussed. To not dilute it further, let's move the discussion there. I'll close this issue as duplicate
