### ISSUE TITLE
Provide a way to configure API gateway endpoint rate/burst limit

### ISSUE THREAD

**Issue by konrad-garus** [serverless/serverless#1183]
It would be nice if Serverless allowed me to tweak API Gateway method settings such as rate and burst limit. The defaults can be too high for some applications, and account-wide settings are too coarse-grained.

While we're at it, it may be beneficial (and not much more work) to support other settings, listed under methodSettings in createStage callback here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#createStage-property.

It seems that the implementation would have to follow up the deploy with a number of PATCH requests (one for each parameter).

**Comment by kylecordes** [comment]
+1 on this.

**Comment by flomotlik** [comment]
@konrad-garus do you know if thats possible to set through Cloudformation? I could see this as an extension in our new V1 services and to be set through Cloudformation.

**Comment by flomotlik** [comment]
As we now have full support of Cloudformation and custom resources you should be able to set this in cloud formation (in case this is already exposed)

**Comment by jthomerson** [comment]
@flomotlik is there a documented way to configure throttling in the serverless.yml file? Since the API Gateway resource is created for you by Serverless, I don't see anything [documented](https://serverless.com/framework/docs/providers/aws/events/apigateway/) about how to add this information to the CloudFormation resource that Serverless creates for you.

**Comment by pmuens** [comment]
@jthomerson there's nothing documented about throttling yet but you should be able to use the `resources` section in `serverless.yml` to add the corresponding `UsagePlan` CloudFormation resource: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html

Here's a link to the docs for the `resources` section: https://serverless.com/framework/docs/providers/aws/guide/resources/

**Comment by Siyfion** [comment]
@jthomerson Isn't that something quite different though? There seems to be two different throttle controls, one as you state is Usage Plan, which (I think?) controls the users of the API Keys generated in the API Gateway settings.

But there is also a "Default Method Throttling" in the API Stage Settings itself, my understanding is that these don't relate to API Key users, but simply, anyone using the API endpoint.

**Comment by HyperBrain** [comment]
Yes. It's two different things - the APIKey usage plans offer an own configuration (throttling etc.) that is only applied for api keys that belong to that usage plan.

The other configuration is a configuration of the API stage, that means that a deployed API stage can be configured to have CW logs/metrics enabled, throttling set to specific values, etc. Currently the global API stage settings cannot be set with Serverless, but I'll add it to my plugin in the next version (see my comment here: https://github.com/serverless/serverless/pull/3715#issuecomment-310033802) which will be released soon.

**Comment by Siyfion** [comment]
@HyperBrain Ah, that's exactly what I thought (glad to know I'm along the right lines!).

And fantastic to see that a solution is already underway and an-end in sight! Great work.

**Comment by jthomerson** [comment]
@Siyfion as @HyperBrain explained, what I was referring to was the method settings throttling. The stage can have a default method settings (see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html#cfn-apigateway-stage-methodsettings).

As shown in the GUI:

![default-method-throttling](https://user-images.githubusercontent.com/171934/27384778-321a9bac-565e-11e7-9f63-a6ab98caa2a3.png)

**Comment by zommerfelds** [comment]
Can someone point to a documented way to set the rate and burst values? I don't mind if it's in CloudFormation, but it needs to be documented by Serverless because the API Gateway is created by Serverless and this requires to modify an existing hidden resource. Thanks!

**Comment by dblackhall-tyro** [comment]
For anyone looking how to do this, I was able to use this plugin: https://www.npmjs.com/package/serverless-api-stage

**Comment by hamletrp** [comment]
Hi Mr. @dblackhall-tyro,
Thank you for sharing about this plugin, could you please also share your setup in the yml file, showing how you did it ?

**Comment by cnliusen** [comment]
I am using [https://www.npmjs.com/package/serverless-api-stage](https://www.npmjs.com/package/serverless-api-stage) as mentioned by @dblackhall-tyro . 

```
plugins:
  - serverless-api-stage

custom:
  stageSettings:
    MethodSettings: 
      ThrottlingBurstLimit: 20
      ThrottlingRateLimit: 20
```

**Comment by adieuadieu** [comment]
In case anyone else lands here and is unhappy with the above solutions, especially in regards to the unmaintained plugin, here's how you can do it in the `serverless.yml`'s Resource section without any 3rd-party dependencies:


**serverless.yml**:
```yaml

resources:
  - ${file(./resource-api-gateway-stage.js)}

  - Resources:
      DynamoDBTable:
        Type: AWS::DynamoDB::Table
        # ... etc.

  - Outputs:
      SomeOutput:
        Export:
          Name: SomeResource
```

**resource-api-gateway-stage.js**:
```js
const HttpMethod = '*'
const ResourcePath = '/*'
const ThrottlingBurstLimit = 50 // <-- set your desired throttling values here
const ThrottlingRateLimit = 10 // <-- set your desired throttling values here

module.exports = (serverless) => {
  const { instanceId } = serverless
  const stage = serverless.getProvider('aws').getStage()

  return {
    Resources: {
      [`ApiGatewayStage${stage}`]: {
        Type: 'AWS::ApiGateway::Stage',
        Properties: {
          RestApiId: {
            Ref: 'ApiGatewayRestApi',
          },
          DeploymentId: {
            Ref: `ApiGatewayDeployment${instanceId}`,
          },
          StageName: `${stage}`,
          MethodSettings: [
            {
              HttpMethod,
              ResourcePath,
              ThrottlingBurstLimit,
              ThrottlingRateLimit,
            },
          ],
        },
      },
      [`ApiGatewayDeployment${instanceId}`]: {
        Properties: {
          StageName: { Ref: 'AWS::NoValue' },
        },
      },
    },
  }
}

```


Unfortunately it can't be done only with YAML because the `AWS::ApiGateway::Deployment` resource Serverless creates has a dynamically generated Logical ID (e.g. `ApiGatewayDeployment1614957901394`) which is unique to each deployment. As far as I'm aware it's not possible to create dynamically generated key names in YAML. I hope someone tells me I'm wrong, because dropping the `.js` file would be nicer.

**Note 1**: note the slight change to the `serverless.yml`'s `resources` section when including values from another file. `resources` becomes a list of `Resources` and `Outputs`. Further documentation [here](https://www.serverless.com/framework/docs/providers/aws/guide/variables#multiple-configuration-files). 

**Note 2**: you'll need to include this the first time you deploy the specified stage or you'll get the error `ApiGatewayStage - development already exists.` Simple fix for that error is to go to the stage in the API Gateway console and deleting it, then redeploying with serverless. Do be aware that deleting the stage will make all requests to your endpoint return a 403
Forbidden until re-deployment is complete... watch out in production! 💥 

Further documentation on Stage method settings [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html)
