### ISSUE TITLE
Invocations missing in Serverless Console

### ISSUE THREAD

**Issue by x1i4b1x2** [serverless/serverless#12027]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Invocations missing in the Console Explorer vs the old one.

New Console with missing invocations:
<img width="247" alt="Screenshot 2023-06-16 at 4 53 22 PM" src="https://github.com/serverless/serverless/assets/100806945/e20c2413-3643-4b81-a5b3-b9eb79454418">

Old Console that correctly shows all invocations:
<img width="305" alt="Screenshot 2023-06-16 at 4 53 50 PM" src="https://github.com/serverless/serverless/assets/100806945/8dae46f2-845c-4b73-b3db-9efc062e8306">

The New Console though shows correctly the number of invocations.

Thoughts? Thanks

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
latest
```

**Comment by garethmcc** [comment]
@x1i4b1x2 Serverless Console has a sampling feature enabled on functions enabled for Prod mode so that only 20% of all invocations will be shown. Could you open a support case in Serverless Console (console.serverless.com) by clicking the question mark to the bottom left, then choose "Chat with us" so we can directly confirm details of your account we cannot do on a public forum such as GitHub?
