### ISSUE TITLE
Question: model_aws used to handle common AWS.config.update 

### ISSUE THREAD

**Issue by jodagm** [serverless/serverless#121]
Hi there, 

In earlier versions there used to be /lib/models/ as common place for AWS config update (and also all dynamodb models). This is no longer part of the generated project.

what is your recommended approach to getting a configured AWS sdk object: 
var AWS = require('aws-sdk');

I understand that the dymanodb models should actually be lambdas defined under 
/back/lambdas/users-dynamodb-crud/lambda-create
/back/lambdas/users-dynamodb-crud/lambda-update
/back/lambdas/users-dynamodb-crud/lambda-delete
/back/lambdas/users-dynamodb-crud/lambda-get

other lambdas can then invoke them by API-GW

however, the common AWS initialization is still required for the AWS object, possible also dynamodb client and others (SNS, SQS etc)

thank you for this awesome framework!

Jonathan

**Comment by ac360** [comment]
@jodagm Sorry for the slow response!

Your question is about JAWS V0 architecture.  We are currently rolling out JAWS V1 BETA, which is entirely different than JAWS V0, but much, much better.  If you wait just a few more days we will be publishing lots of educational material which answers a lot of your questions in the context of JAWS V1.

With respects to JAWS V0 architecture, keep in mind you don't need extra lambdas to invoke other lambdas.  API Gateway endpoints should integrate with one lambda function each.  I recommend using the `aws-sdk` that comes with the lambda environment and configuring it in a module of shared code (not a lambda itself) which other lambdas can require in.  It's most always better to instantiate and config the `aws-sdk` in one location (a shared code module which your lambdas can require in) so that you can easily change it's configuration settings in one place.

Again, if you could wait just a few days, JAWS V1 is seriously impressive and we've been working 24/7 on making the best serverless architecture possible.  Good luck to you Jonathon!

Cheers,
Austen

**Comment by jodagm** [comment]
Thanks, Austen

I am looking forward for V1, as I our company is just starting a big project and JAWS framework is just what we were looking for.

Cheers,
Jonathan

**Comment by jwulf** [comment]
How do I access the AWS SDK or models in V1? I have lambdas that use SNS. I'm happy to write an SNS awsum - just need to know how to access the configured AWS object.

**Comment by jodagm** [comment]
@jwulf I am still doing that as it was done in v0, by aws models under back/lib 
this pattern still works for me as I have multiple aws modules that require dynamo, swf, sns 
so back/lib is where is keep all common things.

**Comment by ac360** [comment]
@jwulf Doing `back/lib` works.  Not sure what your use-case is, but you could also try this:

```
back
   aws_modules
      awsm-sns
         lib
            aws_object
         snslambda1
         snslambda2
         package
```
