### ISSUE TITLE
Suddenly getting permission issue (iam:GetRolePolicy) starting September 20 during lambda deployment

### ISSUE THREAD

**Issue by jmonte-sph** [serverless/serverless#12174]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Past few weeks, our serverless deployment hasn't required the iam:GetRolePolicy permission (following least privileged permission) but starting yesterday we have been getting this error when deploying our lambda on different AWS Accounts:

Unable to retrieve Arn attribute for AWS::IAM::Role, with error message User: arn:aws:sts::xxxxxxxxxxxxx:assumed-role/CodeBuildServiceRole-1P1J29TFE6948/AWSCodeBuildxxxxxxxx is not authorized to perform: iam:GetRolePolicy on resource: role xxxxxxxxxxxx because no identity-based policy allows the iam:GetRolePolicy action (Service: Iam, Status Code: 403, Request ID: d0358089-2c45-4402-ba9e-9896f78e3a58)

Checking why it suddenly requires it starting yesterday.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Environment: linux, node 16.20.1, framework 3.35.2 (local) 3.35.2v (global), plugin 7.0.3, SDK 4.4.0
```

**Comment by delfuego** [comment]
@jmonte-sph You closed this as completed — what fixed this for you? I'm now seeing this same error on a deploy of a project of mine; I didn't require this role previously, and successfully deployed this project as recently as the end of August.

**Comment by eliseumds** [comment]
Same issue here, out of nowhere.

**Comment by jmonte-sph** [comment]
@delfuego , it was a change on the AWS side for Cloudformation.  Contacted the AWS support and they told me to check this command to see the required roles.

`aws cloudformation describe-type --type-name AWS::IAM::Role --type RESOURCE --region ap-southeast-1`

```
-----------------
Partial Output:
-----------------

"create": {
            "permissions": [
                "iam:CreateRole",
                "iam:PutRolePolicy",
                "iam:AttachRolePolicy",
                "iam:GetRolePolicy",
                "iam:TagRole",
                "iam:UntagRole"
            ]
        },
        "read": {
            "permissions": [
                "iam:GetRole",
                "iam:ListAttachedRolePolicies",
                "iam:ListRolePolicies",
                "iam:GetRolePolicy"
            ]
        },

```

**Comment by delfuego** [comment]
@jmonte-sph I'm glad that it was a change to requirements on the AWS side, since that explains why all of a sudden we all couldn't deploy our projects when previously we could.

But I'll say that that command doesn't exactly explain or show that that's the case; unless I misunderstand, the `aws cloudformation describe-type` command simply shows you the definition for a CloudFormation extension, including the names of all the roles that it defines. So, in this case, it's just showing you that CloudFormation understands the concept of roles, and has a permission named `iam:GetRolePolicy` (among others) that you can reference in your CloudFormation templates... but it doesn't explain why this role became mandatory for deploying certain serverless projects at some point in the past few months.
