### ISSUE TITLE
Add support for .NET 8

### ISSUE THREAD

**Issue by martincostello** [serverless/serverless#12367]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Add support for the forthcoming .NET 8 support in AWS Lambda.

[Runtime ID added to botocore](https://github.com/boto/botocore/blob/021a6594d3d53e39b6490b02caee0fd8b992a86e/botocore/data/lambda/2015-03-31/service-2.json#L5278).

### Proposed solution (optional)

Add `dotnet8` to the known list of AWS Lambda runtimes.

**Comment by martincostello** [comment]
I guess this was resolved by serverless 4 beta, though it's a pity the team wouldn't take the trivial change to support for v3.

**Comment by protchenkos** [comment]
Really weird... The team did v3 release adding support for java21 while skipping similar trivial change for dotnet8 😞

**Comment by slang25** [comment]
I had the same feelings until I dug a bit deeper and saw that the java21 issue was not the same as dotnet8, in that it's not _just_ a warning, there's also a line of code that specifically checks the java runtime version in order to invoke the lambda locally, and this check doesn't exist for dotnet.

https://github.com/serverless/serverless/commit/e4dfebdcf66a0f26138f6774b057924128efbfa5#diff-a9b73bb11f3695264fd5588c011cff0aa048ae0bce44ddd7430f96b4c6e06033R269
