### ISSUE TITLE
Serverless support command occasionally includes the wrong command in report

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#12398]
### Issue description

When running `serverless support --summary` the `command` property is sometimes wrong.

After a `serverless deploy`, it reports `command: ['deploy', 'remove']` and `options: { help: true }`. I ran these in previous commands and they appear to be persisted still in the meta.json.

### Context

N/A

**Comment by skierkowski** [comment]
The persisted `Meta` object performs a deep merge on each deploy in order to preserve some of the previous context, like CF Stack, as it may be lost in subsequent commands. However, the deep merge means that fields like `options` are persisted.

To fix this I'll special-case some fields (`command`, `options`), such that they are overwritten (not merged) if new values are available. If new values are not present, then the old values will be persisted. Currently there shouldn't be cases where `command` is not set, but this will ensure the logic continues to work if `command` is not present, either due to errors or future design changes to `Meta`.
