### ISSUE TITLE
V4 - serverless.ts is not handled correctly

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#12517]
### Issue description

If using serverless.ts as the configuration file format, an error is thrown. For example: 

`Could not read the config file in the directory "/var/lib/xxxxx/xxxx/xxxxxxxxx/xxxxxxx" due to this error: Cannot load "serverless.ts": Initialization error: Typ eError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /var/lib/xxxxxx/xxxxxxx/xxxxxxxxx/xxxxxxxx/serverless.ts`

### Context

N/A

**Comment by MNorgren** [comment]
Also started running into this. It started happening within the last couple of days... Was working prior to the latest version(s)

**Comment by ac360** [comment]
@MNorgren Thanks. We are on it 👍

**Comment by gsavvidis96** [comment]
In windows I get `✖ Could not read the config file at path "C:\Users\sav\Desktop\test\serverless.ts" due to this error: Cannot parse "serverless.ts": Register of "ts-node" failed with: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`.

In v3 it was working fine though.

**Comment by ac360** [comment]
@gsavvidis96 We're aware of this and we are working on a fix.

**Comment by Mmarzex** [comment]
This fixed in [v4.0.34](https://github.com/serverless/serverless/releases/tag/v4.0.34)
