### ISSUE TITLE
Serverless v4 beta has stable version in npm.js

### ISSUE THREAD

**Issue by martincostello** [serverless/serverless#12524]
### Issue description

Serverless v4 beta uses a stable version number in npmjs.org: `4.0.24`

### Context

If serverless v4 is in beta, why is it versioned `4.0.24` in npm without any pre-release SemVer (e.g. `4.0.24-beta.1`)?

This is causing automated tooling such as dependabot to offer upgrades to non-stable software.

**Comment by kyl0b1te-red** [comment]
yeah, It looks wrong and already raised following error in my local setup:
```
$ sls -v
panic: Get "https://install.serverless.com/releases.json": tls: failed to verify certificate: x509: certificate signed by unknown authority

goroutine 1 [running]:
main.main()
	/home/runner/work/framework-core/framework-core/binary-installer/main.go:473 +0x614

$ npm list -g
       /usr/local/lib
            +-- corepack@0.20.0
            +-- npm@10.1.0
            +-- serverless-offline@13.6.0
            `-- serverless@4.0.24

```

**Comment by Mmarzex** [comment]
@martincostello Semvar doesn't require a pre-release identifier to be appended to versions. Since v4 is a new major version we released it as such. Our intention is to provide frequent updates to help close the gap between beta and GA quickly. I'd suggest pinning to v3 for now if you are concerned about stability. 

@kyl0b1te-red Since your issue is not related to what was reported in this issue, can you please open a different issue? Looking at it though it appears you have an issue with your SSL certificate chain. `install.serverless.com` certificate is issued by AWS ACM and should be trusted in any systems default chain.

**Comment by martincostello** [comment]
The suffix should have been used as a way for automated tooling to understand that this is considered a beta. That can then be dropped when you consider it stable for adoption.

**Comment by Mmarzex** [comment]
Sorry that this may have impacted tooling you use @martincostello, but again as I mentioned semver does not require it. You should be able to pin to a major version to get the same affect as any automation with suffixes.

**Comment by martincostello** [comment]
Sure I can (and did) do that, but it's going to do the same thing to countless other users.

I already ignored these updates before opening the issue, but it's noise. Just because something isn't _required_ doesn't mean it isn't a good idea.

Just two examples of two completely different tools doing automated upgrades with no obvious hint to the user of the version being a beta:

![image](https://github.com/serverless/serverless/assets/1439341/6a832eae-9f60-49cb-b3d4-99ab8968f030)

![image](https://github.com/serverless/serverless/assets/1439341/c130ce20-3d50-4966-9c69-949f3785c87e)

**Comment by jonasduever** [comment]
Sorry, but for me, this is not mainly a semver issue. The main issue is to use the `latest` npm tag for v4 while it's still beta. Why didn't you use another tag, like `next` (see Angular, express, axios, ...) or `beta` (see React)?
Imagine other big projects would do it like this and the docs of the latest stable(!) version would be outdated because it would install the beta version.

**Comment by jonasduever** [comment]
Related: Even if it would not be a semver issue, I cannot understand why v4 is now the `latest` npm tag while it's still beta. Why didn't you use another tag, like `next` (see Angular, express, axios, ...) or `beta` (see React)?
Imagine other big projects would do it like this and the docs of the latest stable(!) version would be outdated because it would install the beta version.
