### ISSUE TITLE
[Installation failure] Serverless deploy asks for login/license followed by AWS credential retrieval error

### ISSUE THREAD

**Issue by SanketD92** [serverless/serverless#12523]
### Issue description

Hello,

Our team is responsible for the [Service Workbench on AWS](https://github.com/awslabs/service-workbench-on-aws) application, which utilizes `serverless v3.x.x` for packaging its modules and deploying them to AWS. The deployment process traditionally involves each `serverless.yml` file in the application picking up AWS credentials stored locally as AWS profiles.

Recently, we observed a significant change in this workflow. During deployment, Serverless now prompts users to register or log in to its platform and then requests AWS credentials. This deviation has caused consistent failures in our application's installation process.

Based on the online documentation for Serverless, this behavior was anticipated only in version 4. However, we are currently using version 3.x.x and encountering these issues.

Even after signing up and logging in to the Serverless platform, the `serverless deploy` command fails, reporting an inability to locate AWS credentials on the system. We attempted to pass the `--aws-profile <profile>` flag with the `serverless deploy` command and hardcoded the `provider.profile` and `provider.region` values in the `serverless.yml` file, but the issue persists.

Could you please confirm if this is a known issue with Serverless v3.x.x and suggest any potential workarounds?

Thank you for your assistance.

### Context

`serverless.yml` files from our repository: 
- https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/infrastructure/serverless.yml
- https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/backend/serverless.yml
- https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/pre-deployment/serverless.yml
- https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/ui/serverless.yml

Deployment [script](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/scripts/environment-deploy.sh) that runs `serverless deploy` commands.

Example stage [file](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/config/settings/example.yml) that contains the AWS profile value.

System information:
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              18.17.1
     Framework Version:         2.49.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

Initial error:
```
✔ Please login/register or provide a license key 

<options to login or provide license key>
```

AWS credentials error after logging in:
```
✖ AWS credentials missing or invalid. Run "serverless" to set up AWS credentials, or learn more in our docs: http://slss.io/aws-creds-setup.
```

**Comment by ac360** [comment]
Hi @SanketD92. There is no way authentication is required in `v3`. Nothing has changed in v3 wrt to that. Something else appears to be happening here.

Based on the CLI prompt for login, it looks like V4 is being installed and called somewhere, rather than the lower version you expect. I looked at the project, but it's quite large. 

If you have any install commands or package.json files with the Serverless Framework in it, be sure they always pin to a specific version, or you will be getting the latest version. And always fetching the latest version of a dependency can lead to unexpected consequences. We are seeing a lot of users running `npm i serverless -g` in CI/CD rather than `npm i serverless@3.38.0` which pins to a specific version.

Additionally, we're fixing a behavior where if Serverless Framework V.4 is installed globally on your machine, it will override  a version that is installed in your project. This is a bug on our end. We're almost done with the fix. https://github.com/serverless/serverless/issues/12519

Lastly, I see in here that V2 is actually being called which is odd.

```
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              18.17.1
     Framework Version:         2.49.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

Is this being experienced in a CI/CD deployment and can you check the serverless framework version being used there?
