### ISSUE TITLE
Serverless4 with Typescript Support No Longer Automatically Verifies Typescript Compilation

### ISSUE THREAD

**Issue by NicoHinderling** [serverless/serverless#12686]
### Issue description

This is a simple one. Back in serverless v3 world using `serverless-plugin-typescript`, it would automatically run `tsc` under the hood and find type issues.

We had an issue pop up that would have been caught this way, but you are now able to run commands like `npx sls package` or `npx sls deploy` with typescript issues. We've been able to mitigate this for now by just running `tsc` ourselves in our sls related github actions, but I wanted to raise this to the team's attention because I suspect this wasn't intended.

🍻

**Comment by Mmarzex** [comment]
Hi @NicoHinderling , since our builtin support is using `esbuild` under the hood which does not do any sort of `tsc` checking. We can definitely consider an option where we run `tsc` if users opt-in to it. 

In the meantime, what you can do is use an `npm` script like `deploy: tsc && serverless deploy`. That is how we do it for ourselves internally.

**Comment by NicoHinderling** [comment]
got it, yep that's how we did it too. Thanks for the clarification!
