### ISSUE TITLE
ServerlessV4 fails to install and run

### ISSUE THREAD

**Issue by Roanmh** [serverless/serverless#12802]
### Issue description

Serverless v4 fails to install.

Upon running any command, the first 'update' fails with `Error: exit status 1`.

This happens whenever the new version of serverless is installed (I've been repeating the process with `rm -rf ~/user/.serverless/releases/4.2.4`). Afterwards, I get the error `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from /Users/haydenr/.serverless/releases/4.2.4/package/dist/sf-core.js`.

My colleagues are not experiencing this issue and we are not able to isolate the difference. Please advise on methods to get more information about this error or additional system information for diagnosis. For starters:

- Mac OS X Sonoma (M2)
- Node 18.18.2

# Minimal Repro:

1. new directory
2. `touch serverless.yml`
3. `npm init`
4. `npm i serverless@^4`
5. `./node_modules/.bin/serverless version`
6. Observe `Error: exit status 1`

### Context

`serverless support --summary` fails in the same manner as above.

**Comment by Mmarzex** [comment]
@Roanmh can you try updating to Node 20 and trying again?

**Comment by Mmarzex** [comment]
If you install a global version of serverless using `npm i -g serverless` what happens? I'm not able to duplicate any of this though so not sure what the problem could be. Also are you pinning to `4.1.24`? If you are can you update it to a newer version to see if that works?

**Comment by humodz** [comment]
I'm having this issue on my gitlab runners, but I found a really weird workaround:

This fails with "Error: exit status 1"
```
npx sls deploy
```

But this works, for some reason?
```
SLS_BINARY="$(node -p 'require("serverless/binary").getBinary().binaryPath')"
"$SLS_BINARY" --version
npx sls deploy
```

In the above code, SLS_BINARY is something like `(...)/node_modules/serverless/node_modules/.bin/serverless-linux-amd64-0.0.2`

Does anyone have a clue on why would that work?

**Comment by nicwise** [comment]
I've just come here cos I had to google for what our CICD was doing to return this same error.

Turns out, a new release of serverless was released between the point where our dev env was deployed, and when our prod env was deployed.

dev worked. prod failed.

So... we bake serverless into our build containers. They are otherwise immutable. So I rebaked the container (which picks up the latest serverless), rerun the deploy (no rebuild, just retry the step on a new agent so it gets the new container)

And it works. We are now on 4.14.2 not 4.14.1

FFS. Seriously. Has anyone at serverless read the 12 factor stuff? or ever done CICD based engineering?

Doing an update on serverless DURING A CICD RUN is

a) fucking unprofessional
b) will fail due to said immutability
c) did I mention unprofessional?
d) a very bad idea. I've baked an image with VERY specific versions which I do not expect to change.
e) have you heard about my good friend "supply chain attacks"?

Damn. Terraform and a build script is looking really good right now.
