### ISSUE TITLE
Depromisify codebase

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1290]
Promises are hard to understand and get by.

Our application is a CLI which should basically run synchronous as much as possible so it might be an option to drop Promise code whenever possible.

**Comment by Whoaa512** [comment]
I disagree.

>  Promises are hard to understand and get by.

This mostly comes down to proper education about promises and when & how to use them effectively. These resources were quite helpful in my own learning:
  - [Promises in Node](https://alexperry.io/node/2015/03/25/promises-in-node.html) (A promise primer)
  - [Promise Visualizer](http://bevacqua.github.io/promisees/)
  - [Promise Rookie Mistakes and How to avoid them](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html)


> Our application is a CLI which should basically run synchronous as much as possible so it might be an option to drop Promise code whenever possible.

Two things in there.
While it is true that your app is a CLI at its core, it is not inherently synchronous. In fact it would benefit greatly from the control flow that you are afforded by using promises properly. Also maintaining a common internal API for control flow that uses promises throughout will enable you to have levers for managing complexity down the road. Not to mention the clean and clear error handling that you get when using promises.

Just my opinion, though I think that it's not a coincidence that most of the community is headed in the direction of promises. Simply because promises allow you to focus on the interesting application logic instead of the mundane procedural code that can be error prone or unintuitive.

**Comment by mhahn** [comment]
async/await making working with promises lovely as well
