### ISSUE TITLE
Binary responses?

### ISSUE THREAD

**Issue by mojodna** [serverless/serverless#13]
Have you figured out a way to output binary responses (like dynamic images, etc.)?

Last time I looked, API Gateway can be configured to pass through anything from upstream, but Lambda will only return JSON-formatted responses (i.e. no binary responses without base64-encoding, which couldn't be decoded on API Gateway at the time).

**Comment by brianklaas** [comment]
Based on my experience, the response from an AWS solutions architect would be to write your dynamic image or binary data to a bucket on S3 from within the Lambda function and have information about that binary file be returned within the JSON response from Lambda.

**Comment by ac360** [comment]
@mojodna I believe (though I may be wrong) that you are limited to serving JSON.  API Gateway was just released last month.  AWS is very competitive, I hope that they can allow this because being able to serve dynamic static assets would be so damn cool :+1: 

Please let me know if you see them offering this somehow.  I want to hack with it asap.

**Comment by hj1980** [comment]
@mojodna - I'm proposing a slightly different architecture in issue #25, which would address your challenge as you can return binary data.

**Comment by ac360** [comment]
@hj1980 You're right!  I'm going to publish a JAWS Road Map this weekend.  In there, I'll suggest to incorporate more of your architecture, especially for special use-cases like this one.  Perhaps we can include the AWS Javascript Browser SDK in the JAWS site boilerplate and add some simple examples for common use-cases (like the one above).  Since you're familiar with this architecture already, perhaps you can help with this part and provide some awesome boilerplate code?
