### ISSUE TITLE
Use a Node.js CLI library in V1

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1401]
The CLI functionality is missing a lot of fundamental functionality:

- [ ] shortcuts
- [ ] parameters
- [ ] spinner
- [ ] better UI
- [ ] subcommand support

This can be gained via a battle-tested CLI lib.  The question is which one?

**Comment by MrRio** [comment]
I recommend blessed. I used it in vtop
On Mon, 27 Jun 2016 at 08:20, Austen <notifications@github.com> wrote:

> The CLI functionality is missing a lot of fundamental functionality:
>
>    - shortcuts
>    - parameters
>    - spinner
>    - better UI
>    - subcommand support
>
> This can be gained via a battle-tested CLI lib. The question is which one?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/serverless/serverless/issues/1401>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAC5sz4lxw2PkvkGhdtlovPVM7csQPiNks5qP3m_gaJpZM4I-0cb>
> .
>
-- 
James Hall
Director
Parallax Agency Ltd
M. 07894950320

**Comment by pmuens** [comment]
A nice Node.js CLI library is e.g.:
https://github.com/dthree/vorpal

**Comment by ac360** [comment]
**My thoughts on Vorpal:**

Benefits:
* It is battle-tested across operating systems
* It looks like it is well supported
* It supports params/args (and multiple words as params/args)
* It supports options (and shortcuts)
* It supports multi-word commands
* It supports autocomplete
* Offers a cancel function to run if a user cancels mid-command (interesting for a infrastructure management CLI)
* Auto-generates a help menu
* Does validation on the users input
* Tons of UI methods for clearing and redrawing interfaces
* Built in history support
* Built in local storage support
* Has extensions which extend its functionality
* Built in prompts via inquirer
* Includes chalk for coloring

Downsides:
* It creates a session, which may be a benefit actually and is an overall cool experience.  Further, I believe this can be turned off.

**Comment by eahefnawy** [comment]
For full CLI frameworks, I think our best options are either Vorpal or Blessed as mentioned above. On top of that we might use the following for extra functionality:

- [term-img](https://github.com/sindresorhus/term-img): Add images to terminal. Would be cool to have the serverless logo in the terminal.
- [insight](https://github.com/yeoman/insight): Report CLI usage to Google analytics. Super cool project by the Yeoman team. They got an awesome CLI.
- [node-progress](https://github.com/visionmedia/node-progress): add progress bar to `deploy` command. Would be awesome for users to know how much time is left instead of just waiting for the spinner.
- [cfonts](https://github.com/dominikwilkowski/cfonts): Nice fonts for branding.
- [ora](https://github.com/sindresorhus/ora): Pretty spinners. There's also [node-multispinner](https://github.com/codekirei/node-multispinner#examples) for async operations. Although now that we deploy with CF, I don't think we need async very much

Not all of those are super important, but I really vote for Insight and maybe term-img. Spinners and progress bars could come with vorpal/blessed.

**Comment by pmuens** [comment]
Right now we're moving forward with our own CLI implementation and wait for users feedback if more features are interesting / necessary.
