### ISSUE TITLE
Implement support for service plugin loading

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1442]
Right now the `PluginManager` only loads core plugins as the path to service plugins is not resolved.

**Comment by ac360** [comment]
@pmuens @eahefnawy @flomotlik  I would make this a priority.  This is fundamental because it's going to inform how all plugins should be written.  I see a few things in the core plugins which will not work in external plugins, like how dependencies are loaded.  Easy to implement, and there learnings will be important to know early on.

**Comment by flomotlik** [comment]
Implemented and merged by @kid . Closing this issue therefore.
