### ISSUE TITLE
Question: how do I grant my lambads access to more resources

### ISSUE THREAD

**Issue by jodagm** [serverless/serverless#145]
My lambdas are starting to access more AWS resources (DynamoDB, SNS, SQS) and I need to add these policy statements to my LambdaRole.

I see that cloudformation resources-cf.json defines these roles and I tried to update this file, allowing access to additional resources, but this does not sync with AWS. 

What should be the procedure of updating the LambdaRole?
Can I add multiple Lambda Roles and use different roles for different lambdas? Is there an example showing how its done?

Thanks,
Jonathan

**Comment by doapp-ryanp** [comment]
`resources-cf.json` is indeed the place to update ACL for your lambda role - specifically `IamPolicyLambda.PolicyDocument.Statement`.  After you make updates , you will have to manually run the update via CloudFormation admin UI or AWS CLI.  We are working on adding JAWS cmds to do this.

There are tons of docs on CloudFormation and IAM.  [Here is a decent place](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-iam.html#scenario-iam-policy) to start on Policy

**Comment by jodagm** [comment]
@doapp-ryanp thank you for the pointers.

**Comment by Nopik** [comment]
I'm missing this functionality a lot, too. In the ideal world I would like to see JAWS being able to take all resource definitions (including separate IAM role for each lambda!) from `awsm.json` files scattered through the project and update+deploy `resources-cf.json`. So, when I add lambda, or I update it, I also update the corresponding `awsm.json` file, `resources-cf.json` gets updated for me and deployed. 

Now, it seems like we have 99% of it in place, if I understand correctly. Yet, it is done in so convoluted way that it is barely usable, at least in some scenarios. If I'm not mistaken, when doing `jaws module install <url>` that is exactly what is happening - `awsm.json` are scanned, `resources-cf.json` for each stage gets updated. Yet, thats where JAWS stops at this moment. You want to update definitions? Too bad, you have to update each and every `resources-cf.json` by hand. Do you have all modules in single repo, so `jaws module install <url>` doesnt apply? Out of luck, you have to update all `resources-cf.json` files manually.

I'm starting new project with my team, so I'm expecting to add lots of lambdas soon and lots of different resources, too. On top of that we do not want to create 50 git repos with 50 lines of code each, we'd prefer to stay with 1 repo, at least for time being (we can always split it later). Thats the use case where JAWS isn't helping at all to manage `resources-cf.json`, unfortunately. So, while JAWS is doing excellent job in other areas, I would love to see increased awesomeness here, too. Maybe this should be promoted to separate issue. Anyway, I hope that this topic gets into roadmap soon ;)

**Comment by doapp-ryanp** [comment]
@Nopik thanks for the input.  Can you explain what you mean by "You want to update definitions?"?  Are you saying updating the attr values of the CF resources? Our hope was people would be able to use CF "Ref"s and add a user input hook on module install.  Check out https://github.com/jaws-framework/JAWS/issues/167 there is tons of convo going on in there around this area.

**Comment by Nopik** [comment]
@doapp-ryanp so, by "update definitions" I meant that during the course of development resources and privileges used by lambda will change. Lets assume that I have lambda which talks to dynamo, therefore in its awsm.json there is relevant entry to get dynamo access privileges. Maybe even there are dynamo tables defined, too. Then, week later I decide that this lambda need to send SQS message too. So, I add relevant entry to awsm.json. And here things start to fall apart. If I have all modules within single repo, I need to update my resources-cf.json manually. For each and every stage. In a team with few developers, where each dev has its own stage configured in JAWS, that quickly becomes overwhelming. If `jaws module install url` is used, I think it will be a bit easier, but probably only a bit.

**Comment by doapp-ryanp** [comment]
I see. In your 'add sqs perms' example - do you typically roll out new function (and permissions) to all stages at once?  My experience is typically do feature work on a stage and promote that stage up the ranks (feature stage -> test -> staging -> prod).  I'm in a similar boat as you (small dev team, tons of code bases) so trust me that this use case will always be getting lots of thought :)

Admittedly, we haven't put enough thought into scenarios like this because we have been so swamped with core function - and I would argue this is indeed core function.

With that said, I currently don't envision a scenario where I want to make bulk/wide spread updates to CF files.  In any sort of real world production app, I am always extremely careful of any CF updates given the power that CF has (a mistake can propagate quickly and cause serious damage).  The way I envisioned the work flow for your example would be as follows:

1.  I need my lambda role to be able to write to SQS to support feature X. I manually update the cf.json for the stage and region I'm actively working on adding the feature to (for development test phase).
1.  After completing the feature and testing in my dev stage, I "promote" it to the test stage by merging it into the other stages/regions the feature is targeted for. I would do this via IDE,diff+patch etc.
1.  I then do a git diff to make sure I understand what has change before running CF update (via jaws deploy resources or via CF UI per our [best practices](https://github.com/jaws-framework/JAWS/wiki/Best-practices#security))

I understand its more work (and manual at that) but I would argue that check and balance is a necessity in a multi developer, multi stage, multi region production product.

We could make a command/tool that takes a source CF (using it as the master copy) that will add attrs that are in the src CF but not in the target CFs.  Would this be useful?

**Comment by doapp-ryanp** [comment]
one more thing I forgot to add. Initially I was a proponent of having one CloudFormation file, that leveraged parameters to indicate stage and region values.

@ac360 why did we go away from this again. I cant remember.... was that because we wanted to segment function that could not be yet promoted to every stage at once?

**Comment by Nopik** [comment]
Well, I see your point. But, please try to see mine as well.

So, when we have multiple devs in the team, we create a separate stage for each dev, so we can avoid conflicts during development. In team with 5 devs we end up having like 8 stages (dev1..5, test, staging, prod). In such case, when I push something to git, I need to update my stage, and test stage manually, since CI will pick it up quickly. Then, all my coworkers need to add the related resources when they update, or things will stop working for them. Sure, that can be done by git diff/patch, with IDE support and whatever. But it screams about inefficiency and being error prone. Or I'm missing something?

**Comment by jodagm** [comment]
I am also facing similar issues with lambdas that depends on SNS resources and publish to topics. I would like to be able to define the SNS topic as the  lambda-source in the lambda's awsm.json file, but which CF file defined the SNS Topic creation? what if several lambdas are triggered by this Topic? The CF that creates the Topic should take precedence (project's CF file?) so each lambda awsm.json can assume the topic has been created and can be referenced as a source.
not sure how the deployment process works here.

**Comment by doapp-ryanp** [comment]
@Nopik yep I have the exact same work flow - stage for each dev and I got 4 devs.  Sometimes we each have our own stage or sometimes we are working together on one.  When your done adding resources to your stages CF and have tested, dont' you merge your changes to some upstream branch? Then your co-workers merge in from upstream? Its akin to git workflows IMO.

Ex (each line is a stage):

ryan-cool-feat
kamil-cool-feat
prod

You add SNS resources and perms to `cloudformation/kamil-cool-feat/us-east-1/resources-cf.json`. Test against `kamil-cool-feat/us-east-1`. Once your happy with stability. You merge your changes into `cloudformation/prod/*/resources-cf.json` (diff,IDE etc) then merge into master (most people will have 1 prod region, some will have 2, very few will have > 2).  

I'm working in `ryan-cool-feat` and I see upstream master has changed.  I do a git diff on `cloudformation/prod/*/resources-cf.json` to `cloudformation/ryan-cool-feat/us-east-1/resources-cf.json` and merge in upstream (just like your doing a merge on code).

With all this said, I'm all for making your life (and other devs) live's easier.  Does my suggestion above help eleiveate some of the pain? "We could make a command/tool that takes a source CF (using it as the master copy) that will add attrs that are in the src CF but not in the target CFs." 

So in the example above you could do something like `jaws propagate resources kamil-cool-feat/us-east-1 all`, where `all` would mean propagate diffs to all other stage+regions. We could add stuff like `jaws propagate resources kamil-cool-feat/us-east-1 kamil-cool-feat/*` (for all regions in stage) or `jaws propagate resources kamil-cool-feat/us-east-1 [lists] [of] [targets]...` (for specific target cf.jsons)

If tooling is needed, and my suggestion above does not help solve your problem, do you have a proposal for something that would?

**Comment by doapp-ryanp** [comment]
Hopefully I'm not coming across abrasive here - I really do value your input, and want to make a solution that works for you, just trying to flesh out if work needs to be done and if so whats the best algorithm todo so that is maintainable and future proof

**Comment by Nopik** [comment]
I think that almost any kind of resource-cf.json sync would do. Indeed the flow you described (merge to master/prod then back to stages/feature branches) is simpler than what I described. Still, some support from jaws would be great, and `jaws propagate resources` or something similar could solve the problem, if done right.

I.e. in addition to just copying resources between stages, the problem is slightly bigger. If I have existing lambda and I want to add dynamo table resource to its awsm.json, currently I'm out of luck with jaws. I need to update my resources-cf manually. Even if my awsm.json is in another repo and I do `jaws module install url` (which is not the case for me), things will fall apart one step further, when I will want to change resource definition (e.g. change dynamo table name from 'my-users' to 'my-members'). Then, if few lambdas are using the same table, thats another problem. So, the 'if done right' in previous paragraph has quite big 'if' in my opinion.

The discussion in #174 revolves around similar topics, maybe it is worth to join those discussions.

**Comment by doapp-ryanp** [comment]
in `v1.3` we are getting rid of `jaws module install` and leveraging npm (for nodejs runtimes) and its `postInstall` hook. So now in your dynamodb resource add scenario, you'd update ur aws module's awsm.json to indicate new CF extension point additions and then run `npm install <any of the supported urls: git | private | https | npm registry etc>` and it will automatically update the resources-cf.json for EVERY stage and EVERY region in your project.  One big TODO in this logic is handling removed resources - which I think will require implementing a package manger (npm in this ex) `preInstall` hook so we can grab a snapshot before install.

Take a look at [postinstall.js](https://github.com/jaws-framework/JAWS/blob/v1.3/lib/commands/postinstall.js) for more details.

Not sure if this eliminates the need for `jaws propagate resources` yet or not.  I'm honestly at capacity with other work ATM but will continue to ponder this.

**Comment by Nopik** [comment]
Well, what you wrote is a part of the solution, but I dont think it covers everything. Namely, if I have all lambdas/modules within one repo, I'm not really using npm install on them (there is some changes to that in v1.3, so maybe this is not true anymore).

Also, if I already have some resource added and I change it (e.g. rename dynamo table from my-users to my-members), we'd need to handle that somehow. This is almost the same as removing removed resources, and I guess it will get implemented soon. Maybe you'd need to add some internal IDs to the resources to be able to tell them apart, or something.

Once those 2 things will be handled, I guess that my use case will not need anything more.

**Comment by doapp-ryanp** [comment]
ok sounds good. This is on the list of TODOs
