### ISSUE TITLE
Serverless v1.0 Provider "Templates"

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless#1452]
*Further to my conversation with @ac360 I'm opening this issue to provide feedback about the Provider API. I've been reviewing the API and AWS & Auzre implementations to help understand how to deliver the OpenWhisk provider plugins.*

Provider Templates
--

This [template file](https://github.com/serverless/serverless/blob/v1.0/lib/templates/nodejs/handler.js) is used to scaffold the Node.js handler for new services. The template matches Lambda's [handler interface](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html). Both Azure and OpenWhisk use different handler signatures. 

Is there a way for the providers to provide their own templates?

**Comment by pmuens** [comment]
Hey @jthomas!
Thank you for jumping in on the OpenWhisk implementation!

Right now we simply copy the handler file (see https://github.com/serverless/serverless/blob/v1.0/lib/plugins/create/create.js#L77-L80).
The `create` plugin only supports the `create:create` lifecycle. https://github.com/serverless/serverless/tree/v1.0/lib/plugins/create#provided-lifecycle-events

We should definitely move the handler creation process into a provider specific `create` plugin (so that each provider can copy it's own files) and keep the main `create` plugin Serverless related (it should only create the serverless files).

We should furthermore extend the `create` lifecycles (e.g. a `create:createServiceDir` or something similar) so that plugin authors can hook into them easily (like we've done with the `deploy` plugin).

P.S. we're about to provide an option to make plugins provider specific (https://github.com/serverless/serverless/issues/1429). This way the plugins will only run when the services provider matches.

What do you think @eahefnawy

**Comment by eahefnawy** [comment]
@jthomas yep we will just update the `create` plugin to choose a certain `handler.js` template file based on the passed provider as an option just like @pmuens described. Will merge that tomorrow!

Happy to have you here James 😊

**Comment by jthomas** [comment]
FYI I'm working on the OpenWhisk implementation here:
https://github.com/jthomas/serverless/tree/v1.0-openwhisk
Hoping to have basic deploy working next week.

I'll also be at the Serverless meetup in London on Monday if anyone wants to say hello!

**Comment by pmuens** [comment]
Hey @jthomas 
Great! Really looking forward to the OpenWhisk support! I'll attend the meetup as well.

See you there!

**Comment by pmuens** [comment]
Heavily discussed in #1470

**Comment by pmuens** [comment]
Is discussed in detail in #1470 

and should be available soon. Will close this one here. Thanks for the proposal @jthomas
