### ISSUE TITLE
How to get error message from "serverless function run"

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [serverless/serverless#1473]
Hey, I am trying to get the error message from ```serverless function run```. I have a simple function with this body:
```
module.exports.handler = function(event, context, cb) {
  cb("Some error");
```
But the output of ```serverless functio run``` simply is:
```
Serverless: Failed - This Error Was Returned:  
Serverless: undefined  
```

I am on fedora 24 running serverless 0.5.6

**Comment by jeroenleenarts** [comment]
It is due to discrepancies in Serverless. By the looks of it you are running the function locally. I see no parameters defining a stage, region and -d parameter. More info on those here: http://docs.serverless.com/docs/function-run

Why are you seeing undefined?
Well, you are passing a string as the error parameter on the callback handler. Running the deployed version should result in output along the lines of:
```
{
    "errorMessage": "Some error"
}
```

But since the local invocation type you are using actually tries to get two properties from your string, the result is undefined. Please see here for the two lines resulting in the undefined message: https://github.com/serverless/serverless/blob/b89200769695680106e9a3e8929a868da3f30156/lib/RuntimeNode43.js#L49

So, to see a result in line with your expectations, make sure to run the deployed version, or make sure to return a proper node.js error object in your CB call. More info on those: https://nodejs.org/dist/latest-v4.x/docs/api/errors.html#errors_error_message

Interesting to see this big difference in local and deployed testing.

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
