### ISSUE TITLE
Include directories out of serverless service?

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1512]
Let's pretend we have the following directory structure:

```
_shared
  |_ lib
    |_ authenticate.js
service1
  |_ serverless.yaml
service2
  |_ serverless.yaml
```

Our current packaging approach (see #1494 and #1486) will only zip the whole service without external directories.

What if I want to re-use the authenticate feature which is available in `_shared`?

Only possible solution right now would be to deploy `_shared` as an own service with an APIG event and call this service from `service1` and `service2` via a HTTP request.

An idea would be to do something like this in the services `include` array: `../_shared`.

I stumbled upon this issue while writing a prototype with v1.

Any thoughts @eahefnawy @flomotlik

**Comment by flomotlik** [comment]
Imho this should be handled by the dependency management system of the user. If they want to share code between services they need to install it through the package management and pull it in here.

A service should only take whatever is in the current directory into account imho.

For something like you mentioned they could npm install <Folder> to get it into the service. https://docs.npmjs.com/cli/install

This is a little more effort on their part, but imho makes the whole tooling a lot easier and cleaner

**Comment by ac360** [comment]
Just some context:  The npm local workflow in a microservice architecture can be painful.  It caused a lot of people to turn away from the Framework initially because it's tedious and slow to keep updating your core npm packages across a bunch of functions.  So, we created in `includes` option because it simply lets people get started more quickly by making a `lib` folder and an easy way to include it.  No dependency management system getting in your way when you are first getting started with the Framework.  This is meant as a short-term solution for beginners.

However, @flomotlik is right.  Shared code should be handled through the dependency management system.  We write this everywhere in the docs of V.0.  Great support for [symbolic links](https://docs.npmjs.com/cli/link) in our V.1 packaging process can help this.  Further, in V.1, dependencies are at the service level, so everything gets a bit easier too.  Just writing this for reference, since we lost a lot of people to this issue initially.  So something to look out for.
