### ISSUE TITLE
Are v.56 plugins supported in v1.0?

### ISSUE THREAD

**Issue by davidjnelson** [serverless/serverless#1527]
##### TLDR:

Trying to decide to use v .56 vs v 1.0 alpha for a new project.  Lots of plugins I'd like to use are mentioned on the v .56 docs.  Do these work with v 1.0 alpha, or is it a better idea to stick with v .56 for now?  Thanks :-)

**Comment by pmuens** [comment]
Hey @davidjnelson 
The v1 plugin system was rewritten from the ground up and is different to the one in v0.5.

v1 is in alpha right now but will be ready early fall. Right now we recommend to use v0.5 for projects which should run in production. Otherwise it's a good idea to start a new project with v1.
