### ISSUE TITLE
Serverless Developer Tooling Direction

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1582]
We recently discussed our developer tooling and offline support for Serverless. This issue will discuss a few of our conclusions and potential next steps to open them up for more discussion.
# Goal of the Serverless Developer tooling

We want to make sure that developers have a great experience when developing with Serverless, not just for building the service and deploying it through their CI/CD tooling. We need to make sure that they can get fast feedback on any change they make and understand, test and validate the impact of any change they make immediately. Otherwise Serverless and with it the whole approach to building Serverless micro-services won't be able to take off.
## Offline Support

We extensively discussed offline support and came to the conclusion that Offline Support in the quality that is expected of developer tooling across multiple languages and with integration of various services that each cloud provider is a very large task that will take a while to implement.

While simply executing a function and testing that it does the right thing is comparatively easy to do with unit testing frameworks, once you actually want to test and develop a function in connection with all the services it depends on running your functions locally becomes a lot more complex. A few of the questions that we need to answer there:
- How do you emulate services that simply aren't available locally (e.g. Kinesis, S3, Aurora, ...)
- If you emulate these services how can you make sure that they actually behave like they do in their service version
- What if your micro-service depends on many other micro-services that are deployed? Is setting all of them up locally feasible? Including their dependencies?

Therefore we decided to push back the implementation of Offline support for now and want to reach out to the community to give more feedback and help us building this feature. Instead of focusing on offline support we're going to focus on building better tools to quickly deploy into Lambda first and make all the available data inside of lambda easily accessible for you to inspect and debug.

We do think offline support is an interesting feature going forward, we just think that other features can have a larger impact at first and want to learn more and work with the community to release those.
## Ideas to work on

Following are a number of different areas we want to improve Serverless to make the developer experience better.
- Deploy plugin to deploy single functions instead of all functions at once. This help with development as you can quickly and individually update function code.
- Watching local code changes and automatically redeploying functions when code changes
- Logging Plugin to inspect and tail Lambda Logs #1240 
- Metrics Plugin to inspect AWS and general provider metrics when executing functions #1241 
- Better templates that include test setup to easily run a function locally through test frameworks and validate it

Those are just some of the things we want to work on to make sure developers have a great experience and would love to get more feedback about it. /cc @worldsoup @ac360 @eahefnawy @pmuens @mthenw @nikgraf @ryansb @erikerikson 
## Discussions

Join the discussion in the separate issues
#1652 (Function based deployment plugin)
#1468 (Info plugin)
#1650 (Metrics plugin)
#1653 (Optimize plugin)
#1654 (Logging support)
#1765 (Test plugin)

**Comment by erikerikson** [comment]
> Watching local code changes and automatically redeploying functions when code changes

This is awesome.  This could be particularly useful if it included distinguishing the consequences of a modification.  This file is a CFT and requires update of the stack.  Time to redeploy my gateway.  This one is a code file deployed in lambdas X, Y, and Z which must now be deployed.  Et cetera.

**Comment by eahefnawy** [comment]
Yep, just like @nikgraf mentioned before, if we could just make deployment "fast enough", we wouldn't really need offline support at all, and testing on the `test` stage would be a much more accurate test.

**Comment by codepreneur** [comment]
Minification of lambda functions is very important.

**Comment by pmuens** [comment]
Just updated the issues description mit links to the corresponding issues where we can discuss developer tooling plugins in detail!

Happy to have your feedback in the corresponding issues!

**Comment by hassankhan** [comment]
@eahefnawy My 2 cents: I wouldn't be too sure about writing off offline support, it's still super useful for testing purposes.

**Comment by flomotlik** [comment]
@hassankhan Its not that we don't think offline support would be great, but more how high the priority of it is. In our opinion a lot of the upside of Offline support can be reached by other means (e.g. good until testing examples, fast deployment into developer specific environments, integration testing support, invoking and debugging deployed functions easily) but some of the downsides, especially not having AWS Services around locally or the need to mock them locally, would require so much work that we think its better to invest that time into the aforementioned features.

It would be possible to make it work in one language, but making a system that works well across languages, across providers and mocking essential services provided by AWS and Google would be a massive amount of work and we just think other things are more important to do with our resources. If somebody does want to take that task though and run with it we'd be very interested.

**Comment by kennu** [comment]
My experience has been that incomplete/inaccurate offline emulation is bad. It causes developers to be confused about things that work slightly differently in actual Serverless deployments (e.g. template handling, timeout handling). They also start to blame the whole Serveless paradigm for problems that are actually just bugs in the offline emulation and don't occur in real deployments.

**Comment by flomotlik** [comment]
@kennu 

![Hitting Nail on the head](https://media.giphy.com/media/26BRDHKnjgXuhjlde/giphy.gif)

**Comment by hassankhan** [comment]
Thanks for the reply @flomotlik, I generally agree with you so long as things like unit/integration testing are baked into core from the start.

If Serverless is going to be used against multiple hosting environments, wouldn't it make sense to make an abstraction in Serverless itself? As @kennu mentioned, things like template handling and timeout handling are different in deployments, I would assume they are even more different across different providers. Surely an abstraction would make even more sense, then?

**Comment by kennu** [comment]
IMHO Serverless works so well because it's _not_ an abstraction, only a deployment and management tool.

At least for me, and many of my colleagues, using Serverless has been an simultaneous investment in learning the underlying AWS technologies. We want to be primarily AWS experts, because that expertise is what we sell to our customers.

I could see a possible future where Serverless gets so big that customers want dedicated Serverless consultants, but I don't think we're there just yet.

For comparison, consider something like CliQr (a multi-cloud abstraction layer offered by Cisco). To use it, you have to learn all their custom abstractions, instead of just leveraging your existing AWS knowledge. That makes it fit only specific use cases where you can afford to spend the time. Regular developers quickly lose interest.

**Comment by hassankhan** [comment]
I may be completely wrong here, but I thought Serverless was trying to aim for developers who had no background knowledge of AWS (or any other service for that matter).

**Comment by flomotlik** [comment]
>I may be completely wrong here, but I thought Serverless was trying to aim for developers who had no background knowledge of AWS (or any other service for that matter).

The group we're mostly targeting are users of AWS who want a better experience building applications on top of Lambda and including different AWS services. In the future the same holds true for other Providers as well.

We're not trying to hide all of the complexity of AWS from people who are just starting with the Cloud. While we of course want to make it easy for people to get started with Serverless and Lambda and even help them if they have no prior AWS knowledge, we're definitely not focusing on that group of people. We see many teams with lots of existing AWS knowledge get frustrated by the complexity of Lambda, APIG and how to use them to build micro-service FaaS infrastructure. Thats where we come in.

And as a company thats also where we can in the future sell other commercial products which we eventually will and have to do.

Regarding the Abstraction, in our opinion FaaS providers are already so simple and have such a reduced amount of features that further reducing it to the most common denominator would make them unusable. Instead we think the power in FaaS is actually not in abstracting them, but having a common experience to configure and deploy into them. In our opinion in the future FaaS providers will compete more on features than on price because lower prices are inherently built into the FaaS model (no more running servers when they are not used, less development effort, less operation effort). So e.g. if Google has the better translation API's you might want to run a function there even though all your other stuff is running in AWS. This was much harder to do in the past as getting into a specific provider was really hard. With Serverless/FaaS this should be much easier now.

**Comment by hassankhan** [comment]
Cool, thanks for taking the time to explain!

**Comment by jstangroome** [comment]
I'd be happy with a helper so that I can execute (eg) `serverless invoke --function example --path anEvent.json --local` and have it use a locally installed node, python, or java (matching the version in `serverless.yml` naturally) to execute the function, passing the necessary arguments and capturing the result.

This is just to improve the speed of the feedback loop as even a small number of certain npm modules in the package zip can quickly grow the deploy time.

I don't believe that emulating local S3, Kinesis, Aurora should be the responsibility of the serverless project. For example, I could choose to set serverless variables so local invoking will still reach out to a real remote S3 bucket, or I could choose to use an S3 library/wrapper that has its own method for local mocking or emulation.

Unit tests can exercise the non-Lambda-coupled parts of my function and the `dev` stage running in AWS is still the best way to reliably reproduce the Production environment.

**Comment by flomotlik** [comment]
@jstangroome the way we want to approach this in the future is to provide you a simple testing library in the different languages that allow you to invoke your function in a unit test with good pre-defined data that looks like its executing on Lambda directly. The problem for implementing a `--local` is that its quite a bit of effort to get it to work, especially calling different languages from our Node application and making sure all the dependencies work properly, ...

That would all not be an issue if there is a simple unit testing library as you include it in your own dependency graph and simply use it

**Comment by rowanu** [comment]
Can I add a feature to this list? Serverless (internal) logging. Please note that this is completely separate from function logging (which is provided by `sls logs`).

Basically I want `SLS_DEBUG` on steroids. I don't want extra logging just when errors are thrown, I want to see every step that is taken internally so I can understand quickly where things are going wrong/different to what I expect. A similar example (but focused on CloudFormation) was the addition of the `sls deploy -v` option; now instead of just looking at `Serverless: Checking Stack update progress...` I get to see each and every CFN operation - If something goes wrong I know where to look already (without leaving the console).

An example I had today was playing with the `package > include/exclude` configuration options. It wasn't clear if file globs would be supported (they aren't), and the docs made it sound like `include` behaved like a whitelist if it is present (it doesn't, it acts as a whitelist *only* if `excludes` are present). If I could have switched on debugging and see all the generated configuration being used to package my functions, it would have been a much smoother experience.

For my own projects, I've used the great [debug library](https://github.com/visionmedia/debug), which allows you to do split your logs in to different groups (e.g. deploy vs invoke, etc) and selectively switch on logging output through environment variables.

**Comment by andymac4182** [comment]
What @rowanu suggested would be great. I was debugging moving to the new variable format and had to add `console.log` to a local copy of the framework to understand how it was working.

Another thing that would be great would be to have a way to export a fully replaced version of the serverless.yml file with all the variables enumerated.

**Comment by flomotlik** [comment]
Closing as we're not using it any more for discussion.
