### ISSUE TITLE
Deploy error: Cannot read property 'OutputValue' of undefined

### ISSUE THREAD

**Issue by wasenbr** [serverless/serverless#1615]
Serverless Framework Version: alpha 2

Operating System: Win 10

Expected Behavior: 
deploy
it works on alpha 1 version

Actual Behavior: error: 
Serverless: Zipping service...

  Type Error ---------------------------------------------

     Cannot read property 'OutputValue' of undefined

     For debugging logs, run again after setting SLS_DEBUG env var.

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

**Comment by eahefnawy** [comment]
@wasenbr is that the same service you were working with Alpha 1? If so, I don't think it'll work since there are now required output variables that didn't exist in Alpha 1. So you need to create the stack from scratch.

@pmuens any further thoughts here?

**Comment by codepreneur** [comment]
I opened this very same issue (#1614) literally a minute before you did

**Comment by wasenbr** [comment]
I created the stack from scratch with alpha 2 and it works .

Thanks!!

**Comment by activescott** [comment]
FYI: As mentioned [here](https://gitter.im/serverless/serverless?at=579176bb9d1dc62e491676b3) this also appears to happen when a deploy fails and gets the cloudformation stack into a bad state.

**Comment by ianserlin** [comment]
We diagnosed this by finding a bad CloudFormation stack with our service's name in the AWS console. In our case, the stack's status was `DELETE_FAILED`.

To fix: Either manually deleting the stack before trying to re-deploy, and/or renaming your service in `serverless.yml` from what it currently is (here's the aws nodejs template's default: `service: aws-nodejs`) to something new (for example `service: mycustomservice`) fixed the issue by disassociating our service with the bad cloudformation stack so that we could deploy again.

**Comment by flomotlik** [comment]
This should be resolved with #1638
