### ISSUE TITLE
Redeploying Lambdas increases file size as reported by Lambda Management Console

### ISSUE THREAD

**Issue by gebrits** [serverless/serverless#1622]
When doing `sls function deploy` multiple times (i.e.: after updating code) the file size as reported by Lambda Management Console increases. e.g.: 

> You have 2 Lambda function(s) using 13.3 MB of code storage.

After a while it's listing

> You have 2 Lambda function(s) using 126.8 MB of code storage.

Removing the lambda from the management console and doing a `sls function deploy` afterwards solves it. 

Is this expected behavior?

**Comment by codepreneur** [comment]
What is your serverless version ?

**Comment by eahefnawy** [comment]
@gebrits since you're using the `sls function deploy` command I'm guessing you're on version 0.x...in that serverless version, we publish a new version of your function on each deployment, so the old deployments are also kept in AWS. This allows you to version control your functions and its a flow that is recommended by AWS. So yep, that's expected.

Also remember that the limit for Lambdas that you have is 75GB at the moment.

**Comment by gebrits** [comment]
Ok cool. Makes sense.
