### ISSUE TITLE
Add gateway routes prefix

### ISSUE THREAD

**Issue by boushley** [serverless/serverless#163]
As I've been working on [an awsm module](https://github.com/boushley/awsm-cloudfront) I found that I wanted to make it easy to prefix all of my API Gateway endpoints with a particular prefix, something like `api/`.

Would this be something reasonable to add to JAWS directly? I can't think of a ton of other uses cases for it though, other than this one (which I think is really important) so I want to get some other peoples feedback.

Thoughts on adding something like a `prefix` variable that would be added to the start of all API Gateway paths?

**Comment by boushley** [comment]
@remicastaing you might care about this one

**Comment by joostfarla** [comment]
When using custom domains in API gateway, you can add path mappings and set a base path which is essentially a prefix for all your resource paths (e.g. for versioning or hosting multiple API's on a single domain). However, if you're using this behind Cloudfront, this probably doesn't make sense, since the custom domain is probably configured in Cloudfront. In that case, defining the prefix as a resource may not be the most elegant solution, but it might be the only one at this time.

**Comment by eahefnawy** [comment]
This is now possible with Serverless variables :)
