### ISSUE TITLE
Middleware Support In jaws-core-js

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#165]
Our next big priority is to include middleware support within the jaws-core-js module.  The benefit here is that it defines a middleware standard for awsm's to use.  Things to consider:

* AWS has announced versioning support coming soon (re:invent) for Lambda.   ES6 features (i.e., generators) are very cool.  But what are the consequences of building ES6 features into jaws-core-js?  If we are going to provide middleware within jaws-core-js, should it work on all versions of Node? 

* Small codebase.  @jwulf's [awsm-middleware](https://github.com/jwulf/awsm-middleware) is wonderful.  Though I am in favor of writing our own middleware code to get the codebase even smaller and reduce/eliminate dependencies (awsm-middleware currently relies on a deprecated modul "fn-wrap").

* What does the middleware syntax look like and how far should the middleware syntax stray from lambda's `event` and `context` syntax?  Right now, I like the idea of adding a simple context.next() method to the context object.

* Should jaws-core-js be an npm-module, instead of an aws-module?  This could help the versioning issue.  It's not meant to be modified.  Further, it contains no lambda, apigateway endpoints or CloudFormation templates.  Therefore, it seems making it a npm module is most appropriate.

**Comment by boushley** [comment]
I think this is a great idea.

It's true that we should think about this a bit since upgrading will be a pain as things grow (at least if the change isn't backwards compatible).

I think it's essential that we figure out how we want to handle middleware.

Do we want to use a request, response and error flow, similar to express? This has the benefit of being similar to flows that many Node.js developers are already familiar with. One down side here will be that our abstraction won't be perfect and the imperfections could cause extra confusion. This would also be less sensible if/when we support Java, but we would want to use different patterns there anyway.

Do we want to stick to something closer to how lambda works natively? This has the benefit of being clearer to people how to interact if they understand Lambda already. It also makes the implementation fairly simple.

We should probably consider ensuring there's at least one object where we control the methods / properties on it. Maybe we pass along a single object that has an event and context property. (Problem being what do you call it? The mega context? jaws-context?) The value of this would be that we could easily add new properties / methods to this object. If we only pass context and event we have no extension points. We could also pass along context, event and another jaws-context object that provides our extension point.

My thoughts aren't super put together, but they're a start.

@dekz you will probably be interested in this topic.

**Comment by jwulf** [comment]
Here's a middleware module: 

https://github.com/jwulf/awsm-middleware

**Comment by joostfarla** [comment]
Implementing a standard way of handling middleware could definitely be a booster for the ecosystem!

I think building an own middleware layer is the best option, since we would gain full control on how things can be optimized for working with Lambda and JAWS. It might be worth waiting for Re:Invent, strongly hoping they announce Node v4 support with all the ES6 goodies. With ES6 we could leverage the power of generators (like Koa does) for handling middleware.

I would suggest implementing something which is in some way compatible with community standards (like Express/Koa), so that people might be able to re-use existing components. JAWS might profit from the work that already has been done in these communities. We could accomplish this by providing one or more bridges which make Express middleware suitable for using it within JAWS.

About the upgrading concerns, for JAWS to be able to grow it's time to start thinking about versioning strategies and dependency management. There's already a starting discussion on module versioning in another issue (https://github.com/jaws-framework/JAWS/issues/148).

**Comment by ac360** [comment]
I'm now very much favoring middleware in jaws-core-js.  I think this is going to be our next big priority.

I'm going to update my original post in this thread with these new considerations.  What do you guys think about these points?

* AWS has announced versioning support coming soon (re:invent) for Lambda.   ES6 features (i.e., generators) are very cool.  But what are the consequences of building ES6 features into jaws-core-js?  If we are going to provide middleware within jaws-core-js, should it work on all versions of Node? 

* Small codebase.  @jwulf's [awsm-middleware](https://github.com/jwulf/awsm-middleware) is wonderful.  Though I am in favor of writing our own middleware code to get the codebase even smaller and reduce/eliminate dependencies (awsm-middleware currently relies on a deprecated modul "fn-wrap").

* How far should the middleware syntax stray from lambda's `event` and `context` syntax?  Right now, I like the idea of adding a simple context.next() method to the context object.



@boushley I like the idea of keeping event and context.  It sticks close to lambda.  

Looking at @jwulf's great code, we could make it slightly cleaner by adding a next method to context.  It seems most intuitive since context already has a done method.  As long as AWS doesn't add their own `next` method for any reason...

@jwulf Do we need everything in segment's ware module?  Could we borrow some of its code, roll out our own solution and make it even leaner.

```
context.next()
context.done()
```

**Comment by doapp-ryanp** [comment]
My 2c: Agree version handling, dependency mgmt, awsm  registry, Middleware and user input on module install /upgrade should be priorities. 

Re Middleware - I think waiting till after reinvent is essential to see if they announce node 4 and more importantly es6. It will be crucial in keeping codebases lean and small and will help us define Middleware that can grow (that doesn't need to be rewritten for es6).I am not a fan of babel as a stopgap.

There's enough work with list above to keep us busy til re invent.

**Comment by ac360** [comment]
At this point, I think we should consider making `jaws-core-js` an npm module instead of an aws-module, to deal with versioning issues.

Further, `jaws-core-js` doesn't have any of the aws-module qualities.  It's not meant to be modified. It contains no lambda, apigateway endpoints or CloudFormation templates.  Therefore, it seems making it a npm module is most appropriate.

As a JAWS principle, perhaps all of the `jaws-core` modules for each lambda-supported language should be written as a module for the most popular package manager for that language.

**Comment by ac360** [comment]
We're going to hold off on this.  With the new changes to the aws-module format, we may not need this.  Going to wait a bit longer before we implement this.
