### ISSUE TITLE
Is it possible to use serverless 1.0 as a library?

### ISSUE THREAD

**Issue by MylesBorins** [serverless/serverless#1678]
Thanks for putting together this awesome project, I managed to get a hello world running super quickly! 

After taking a bit of time to dig into the code it appeared to me that the project has been primarily designed as a cli. Is it possible to use programmatically as a library?

From what I can tell these would be the steps, I have not yet tried to implement as I am not entirely clear if this is **a)** possible or **b)** a good idea
- require `Serverless`
- instantiate `Serverless` with a yaml file
- run `Serverless.init()` which will return a promise
  -  there is currently no way to pass `inputArray` and thus you are forced to use `process.argv` to pass the values, which can get realllllllly weird
- when the returned promise from `Serverless.init()` is resolved call `Serverless.run()`
  - I believe that this would then run the `plugin` that is being passed to init

_phew_

So a few things that I am not sure about
- do the individual `plugins` rely only on the filesystem? Is there a way to do everything in memory?
- is there any intention to make serverless available as a userland api rather than a cli?

Thanks in advance for taking the time to respond!

**Comment by eahefnawy** [comment]
@TheAlphaNerd could you let us know your use case? what exactly are you trying to accomplish by requiring Serverless?

I think the closest thing to what you're requesting is creating a plugin, other than that, Serverless is not really meant to be requried. You can defenitly hack your way into it, but maybe if you let us know how that would solve your problem, we can help make it easier 😊 

Thanks for starting this discussion btw. It's an interesting use case 💪

**Comment by animeshsingh** [comment]
Well a lot of providers would rather call the apis programmatically rather than going cli route -if serverless is the abstraction here, we would want apis to be primary mechanism

**Comment by eahefnawy** [comment]
We are calling their APIs programmatically so you wouldn't have to. After all Serverless is mainly a CLI tool that you can use so that you wouldn't have to programmatically do it. Unless you have a specific reason for it?

I'm still not super clear on your use case, but it sounds like a plugin might solve your issue? or is there a specific reason you don't think a plugin is what you need?

**Comment by mbehrendt** [comment]
the use case is...imagine i want to offer a self-service ui to the users of my cloud. in that ui i want to display a number of serverless-defined templates these users can select and get deployed automatically. for achieving that, the ui business logic would have to somehow do programmatically what a user would normally do manually via the serverless cli.

does that make sense to you?

**Comment by eahefnawy** [comment]
Yep that makes perfect sense. Thanks for clearing all this up 😊 . That definitely sounds like a useful addition. It's not currently implemented as we're currently focused on the CLI, but I think we can put this together based on our current architecture. 

Maybe @serverless/team could chime in with their thoughts as well?

**Comment by flomotlik** [comment]
Imho this is still very early and we'd like to get more input how different teams want to use this feature. Its definitely something we've heard before, but compared to other feature requests it also comes a little more rarely.

Currently I don't think it will be available with V1 directly (as there are so many other things we need to put in place as well, but I can definitely see that after V1)

**Comment by jagi** [comment]
I'm also interested in such a feature and my use case is as follows. I have a project that has `client` and `server` directories. Everything runs using webpack and I have some scripts defined in the `package.json` file. What I want to do is run a command like `npm run deploy server` which would build bundle and deploy it using serverless. Right now I must have serverless installed globally but if I could add it as npm dependency and run it programatically then it would be nice.

**Comment by rowanu** [comment]
@jagi you can run it as an npm dependency; Just make sure `./node_modules/.bin` is in your `$PATH` and any commands you run in your project directory (or via `npm`) will use the local binary. No global installs required.

FWIW these use-cases sound completely different (and much more meta) to what Serverless is currently aimed at. I don't think in these early days that it's feasible for Serverless - or anyone for that matter - to be an abstraction layer over the various FaaS providers (e.g. GCF are still in Alpha!). Maybe one day, but not yet.

**Comment by dougmoscrop** [comment]
Outside of the context of a feature, I think this helps enforce separation. Right now the code has some 'circular' dependency between CLI, and the rest of the project. I think you want the CLI to 'wrap' the inner stuff.

I mean this is kind of how it works anyway, right, you have your `bin/serverless` and that's a JS file that requires `lib/Serverless`. It all comes down to separation of concerns.

`new Serverless().command('deploy', { x: 'y' });` (I made that up) only skips the minimist part.

The `init` call only exists because of circular dependencies from what I can tell (a bunch of stuff gets newed up and all put in a global context, then init takes stuff and calls setXYZ back  and forth all over the place).

**Comment by erikerikson** [comment]
We are doing this in serverless-artillery in order to provide a standard capability via a serverless deployment and execution mechanism.  We are using the noted approach of setting argv, loading SLS, calling init and then run.

This allows us to deploy a function and invoke it to load a service without requiring any configuration.  There are limits to what can be loaded but we allow users to execute the simple case in two minutes to discover the value and then dive in iteratively deeper after we've proved the value and they want to satisfy more complex needs.

Our use:
https://github.com/Nordstrom/serverless-artillery/blob/master/lib/serverless-fx.js
https://github.com/Nordstrom/serverless-artillery/blob/master/lib/index.js#L6
https://github.com/Nordstrom/serverless-artillery/blob/master/lib/index.js#L121
https://github.com/Nordstrom/serverless-artillery/blob/master/lib/index.js#L58

Touching argv **is** weird and we'd like to avoid it.  The easy path to allow this is altering `Serverless.init()` (https://github.com/serverless/serverless/blob/master/lib/Serverless.js#L48) to accept `inputArray` as an argument and pass that as the second parameter to the `CLI` constructor (https://github.com/serverless/serverless/blob/master/lib/classes/CLI.js#L10) so that it uses that instead of argv (https://github.com/serverless/serverless/blob/master/lib/classes/CLI.js#L30).

**Comment by erikerikson** [comment]
Small change on #2444 to at least avoid violating `argv`.

**Comment by flomotlik** [comment]
@ac360 please share your thoughts as discussed in #2444 here.

**Comment by erikerikson** [comment]
In serverless-artillery we created parity between the valid commands and the functions implemented to handle them.  This allows the same knowledge to be used to use the tool at the command line or programmatically.  That said, we have a simpler use case that doesn't include dynamic plugability.  Something similar would be great.  The error cases should be reasonably easily handlable by remarking that a command could not be found and that this could be due to a missing plugin or simply its non-existence.

**Comment by gdeividas** [comment]
Hey any updates on this ticket/feature request? I see that it is suggested to discuss this matter here #2444 , but that ticket is closed with no merge?

**Comment by pmuens** [comment]
Hey @gdeividas we're currently looking into ways to work with Serverless programatically.

However there's nothing set in stone yet. Maybe you could provide some feedback how this would look like in your use case?! That would be helpful! 💯

**Comment by ssemyonov** [comment]
I'll just leave our use case here. We ended up calling ```serverless deploy``` from node_modules of the service folder (required so different services can upgrade minor versions independently) from C#/.NET code. Serverless framework is installed as local NPM dev dependency in each service. By generating YAML files with our specific variables we were able to integrate Serverless deployments into our continuous delivery pipeline.

**Comment by gdeividas** [comment]
Push aws serverless functions live based on our config data which is coming from our database. Check various statuses and info of the `functions`, how many are live, endpoints, etc.., currently in order to archive this you need to use serverless CLI and to parse the output or/and query aws api yourself for some of the data..

**Comment by jdchmiel** [comment]
https://github.com/Nordstrom/serverless-artillery/blob/master/lib/index.js#L190

Was there ever any work around when using serverless as a library to get the results of the serverless invoke command?  It gets to the screen least, unlike trying to run it in a child_process exec, but I cannot seem to capture it into a variable.  I was trying to capture directly from stdout like this:
```
 19 global.slsResult = "";
 20 var stashedWrite = process.stdout.write;
 21
 22 var captureOutput = function() {
 23     process.stdout.write = (function(write) {
 24         return function(string, encoding, fileDescriptor) {
 25             global.slsResult += string;
 26             // do not echo it anywhere
 27             write.apply(process.stdout, arguments);
 28         };
 29     })(process.stdout.write);
 30 };
```

**Comment by pmuens** [comment]
Right now, the only possible ways to use Serverless programatically were outline in the discussion in this thread.

I'm going to close this one to keep the issue count low, however feel free to continue the discussion.

**An important note:** Programmatic support is on our roadmap for Serverless v2.

**Comment by brianneisler** [comment]
Reopening this for product tracking.

**Comment by erikerikson** [comment]
Glad to see this reopened.

It's not quite true that Serverless doesn't have a programmatic interface.  We'll be taking advantage of its API shortly because it turns out breaking the build when acceptance tests fail is really important. 

For reference, see lines 188-199: 
https://github.com/Nordstrom/serverless-artillery/pull/75/files#diff-6d186b954a58d5bb740f73d84fe39073R188

Through this integration, we get the response given by the remote lambda so we can decide on an exit code.  Not pretty but it works.

It would be far more preferable to extend the promise chain and be given the programmatic result after command execution (i.e. sls.run) where it makes sense.

**Comment by sielay** [comment]
Any updates. Really miss that after 0.5

**Comment by eslynunez** [comment]
+1

**Comment by signal-intrusion** [comment]
Any updates or links to docs?

**Comment by Jaikant** [comment]
+1

**Comment by mattccrampton** [comment]
I see serverless 2.0 is out now, is this supported now?

**Comment by SamCullin** [comment]
+1 Currently developing a nrwl nx plugin that supports serverless but it quite slow with out any documentation
