### ISSUE TITLE
Consider custom function name in "invoke" and "logs" plugins

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1697]
The `invoke` and `logs` plugins construct the name with the help of the service name, the stage and the function name ( e.g. `aws-nodejs-dev-hello`). This works for most cases but will break if the user has added the `name` property of the function in the `serverless.yml` file.

**Comment by eahefnawy** [comment]
FYI I looked into this today, and it's fortunately it only affects the `logs` and `invoke` plugins but will not affect function deployment nor any of its event sources. The reason is, for event source specially , we reference the function by the logical id of the CF template of the function, not the function name itself, so regardless whether it's the default function name or a custom name, AWS will figure it out because it both cases they have the same logic id, which is **the function name in serverless (the key inside the `functions` object)**.

For invoke and logs, the fix looks easy. Will send a PR for it soon. 🎉

**Comment by pmuens** [comment]
Awesome @eahefnawy!
[This issue](https://github.com/serverless/serverless/issues/1718) came up after this is should be considered when resolving this one...

**Comment by eahefnawy** [comment]
Resolved with #1753
