### ISSUE TITLE
Add integration test coverage for event sources support

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1723]
We currently have basic integration tests for a simple single function service. After adding a lot of other features and event sources, we need more integration tests to cover all those new features.

cc/ @flomotlik @pmuens

**Comment by flomotlik** [comment]
Imho that integration test should be done in a separate repository so we can run through event integration tests against separate serverless versions. Imho putting it into the repo directly might lead to issues

**Comment by eahefnawy** [comment]
@flomotlik so how would that look like? Travis would just clone this repo that contains a complex service and run certain tests against it? (deploy, invoke...etc)

**Comment by pmuens** [comment]
Yes. one repository which includes all test cases. This will then be picked up by e.g. Travis on a nightly basis and runs all the tests in there.

We can then remove the integration test section in our main repo.

Additionally we should run the integration test we have right now on each PR / Push so that we can make sure that the most simple usage still works.

**Comment by eahefnawy** [comment]
Alright so here's what I have in mind. The structure of the repo would look like this:

```
first_complex_service
    serverless.yml
    **other files/folders**
    test.js # test suite for this complex service
second_complex_service
    serverless.yml
    **other files/folders**
    test.js # test suite for this complex service
node_modules # will include mocha along with other test utils
package.json
test.js # the main test script. Will mostly just require the test suites that we have in the services above
```

On ever test run:

1. Script will clone our master branch into the root of the repo, insuring that we have the latest changes for each test run.
2. Script will `npm install` the cloned master, and globally set the path to the serverless bin
3. Script will require/run each complex service test suite. One thing to keep in mind is that each test suite should insure the service is removed at the end to start again from scratch on the next test run.

We can easily add more complex services along with their test suites, hence creating a framework for integration tests.

This solution could work both on travis or locally.

**Comment by eahefnawy** [comment]
@flomotlik I've thought about Docker for a while. What I have in mind is for us to create an image for each complex service/test suite. This should offer great isolation, but it also means we'll have to duplicate functionality (ie. each image would pull/npm install from master independently). Might be an overkill for our use case.

I don't have a lot of experience with Docker though. How do you think a Docker setup would look like? and how does it compare with the setup I proposed above?

**Comment by pmuens** [comment]
Good proposal!
Here are some thoughts:

I would like to stick to JavaScript for everything for now so that we can e.g. use Axios or node-fetch to query against the API Gateways.

How do we deal with shared code? E.g. if I have multiple tests for API Gateway I don't want to rewrite the same logic again and again.

Would be great to have a global "cleanup" functionality.

Furthermore we need to think about running those tests in parallel to speed things up. This will make things a little bit more complicated.
E.g. we need to rename the service each and every time, make sure that everything is isolated and that the cleanup won't remove stacks which are currently processed.

Maybe we also need a watcher which removes failed stacks and re-initializes them etc.

**Comment by flomotlik** [comment]
2 additions:

1. we should have area specific folders on the highest level, so e.g. `api-gateway` and then in there we can have other subfolders for specific tests, e.g. `cors`so we have a folder structure that is easy extensible and its clear where stuff should be put.

2. I don't think we should use Javascript for programmatic stuff necessarily. Imho best thing to do would simply to have a Makefile in each test folder and then have a script that goes through each folder, finds the makefile and runs `make test`. This way we're not bound to a specific language or testing tool and can use things like grep easily where they make sense. Imho often times things that are very easy to test with grep or jq (for parsing and testing JSON on the CLI) are overly complex in a testing framework. We can use JS where applicable though.

Happy to help with the docker stuff

**Comment by pmuens** [comment]
@eahefnawy @flomotlik added a first implementation in this PR: https://github.com/serverless/integration-test-suite/pull/1

**Comment by pmuens** [comment]
This is done in the "integration test suite" repository (see: https://github.com/serverless/integration-test-suite).

/cc @flomotlik
