### ISSUE TITLE
JawsError 'Invalid Method identifier specified', when deploying Endpoint

### ISSUE THREAD

**Issue by jodagm** [serverless/serverless#173]
I sometimes get the following error when deploying lambda & endpoint from dash

```
{ name: 'JawsError',
  message: 'Invalid Method identifier specified',
  messageId: 1 }
```

when I re-run the command it works fine. does anyone else experience this inconsistency?
When it failed, it was during endpoint deployment. These were the last log lines before failure:

```
JAWS: Endpoint Deployer:  Deploying endpoint(s) to region "us-east-1"...  
JAWS: Endpoint Deployer:  "dev - us-east-1": found 1 endpoints to deploy  
JAWS: Endpoint Deployer:  "dev - us-east-1": found existing REST API on AWS API Gateway with ID: 21hbak0l4b  
JAWS: Endpoint Deployer:  "dev - us-east-1": found 9 existing resources on API Gateway  
JAWS: Endpoint Deployer:  "dev - us-east-1 - resourceA/{dynamicResourceId}/resourceB": created method: POST  
```

when it completed successfully, the next log line was:

```
JAWS: Endpoint Deployer:  "dev - us-east-1 - resourceA/{dynamicResourceId}/resourceB": created integration with the type: AWS 
```

**Comment by ac360** [comment]
I've been seeing this too.  I'm not entirely sure where this is coming.  Here's my first guess...

When creating API Gateway resources, methods, integrations, etc. some things return a RequestID response, instead of a "Successfully Created" response.  This leads me to believe that API Gateway then queues those resources to be created.  However, JAWS does not currently wait for that, it hopes the resource gets created asap and then tries to build further resources on top of the one that returned a request ID.

Putting a delay on creating API Gateway assets could  solve this problem.  If indeed this is the problem.  However, it slows down the deployment process.  I'll try adding this soon.  In the interim, just deploy the endpoint again.  Sorry!

**Comment by jodagm** [comment]
Understood. 
Thanks!

**Comment by dcrockwell** [comment]
+1 for fixing this

**Comment by eahefnawy** [comment]
I think this is fixed with the Serverless release. I'll close now and feel free to reopen if this is still an issue :)
