### ISSUE TITLE
Should there be a more effective support forum

### ISSUE THREAD

**Issue by Bilal-S** [serverless/serverless#1758]
I would submit for consideration to create a more effective support forum besides Gitter and Git-Hub issues list.
Most organizations (open or closed) have some sort of structured support forum, this can be as simple as a google group. It allows users to find non-code related conversation threads easily and track questions and answers together.

Searching on gitter is like needle in an haystack method, with many false positives across unwanted rooms. After you learn the search syntax, you still do not get the correct search results. This causes unnecessary repetition of same questions.

Probably the existing forums (http://forum.serverless.com/) could be expanded with distinct support areas, e.g. by programming language or development or lifecylce stage.

I'd be glad to create a google group to get things started if desired,  but I do want to make sure that I am not missing something that is already out there.

Best,
B.

**Comment by flomotlik** [comment]
Hi @Bilal-S , thanks for reaching out. The Forum (forum.serverless.com) is definitely the right place for this. We're currently establishing a dev evangelist team and will spend more time on this in the forum.

Its still in its infancy and we're getting started on it, but would love for more people to participate and join in on this. I'm going to close this issue here just to keep our open issues down, but yeah this is definitely very important to tackle and the forum should turn out to be the right place for this.
