### ISSUE TITLE
Feature Request: Serverless Variables

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#1801]
#### Feature Request: Serverless Variables

We need a single, simple, consistent way to specify variables + interpolation syntax in our `serverless.yml/.json` files.  If we get this right, these variables should accomplish these goals:

* Allow referencing of options (stage, region, etc.)
* Allow referencing of data in serverless.yml
* Allow referencing of ENV variables
* Allow referencing of other files and properties in those files
* Remove need for multiple standards (JSON REF, JSON Pointers, YAML Anchors, Bleh!  Also, these multiple standards still don't offer us all the features we need.), reducing the learning curve, and making `serverless.yml` files neater and easier to read.
* Be safe to use within `serverless.yml` and `serverless.json` files.)
* Execute shell commands within variables.

Here are two proposals for the variable syntax.  Suggestions wanted.

##### Option Reference:
References a CLI option
```
${opt.stage}
```

##### Local Reference:
References data in the current file (e.g., `serverless.yml`)
```
${self.data} // A root property of serverless.yml
${self.data.subProp} // A subproperty of serverless.yml
```

##### ENV Reference:
References an ENV variable.
```
${env.my_arn}
```

##### Provider Reference:
References outputs from the provider's resource manager (e.g., AWS CloudFormation Outputs) and possibly more in the future (e.g., AWS Account ID)
```
${prov.prop}
```

##### File Reference:
References variables inside another file.
```
${file("./config.yml").data.subProp}
```

##### Shell Command Reference
```
${exec("shell commands").prop}
```

##### Nesting:
Nest variables inside each other.
```
${env.${opt.stage}_arn} // Possibly limit to 1 nested var
```

##### Local, ENV, Option and CF Output Reference:
All of these use `var` with the following override hierarchy: *CLI Option > ENV > CF Outputs > serverless.yml*
```
${var.data.prop}
```

##### File Reference - Same as Proposal 1:
References variables inside another file.
```
${file("./config.yml").data.subProp}
```

##### Shell Command Reference - Same as Proposal 1:
```
${exec("shell commands").prop}
```

##### Nesting:
Nest variables inside each other.
```
${var.${var.stage}_arn} // Possibly limit to 1 nested var
```

#### Related: 
* #1711 
* [Terraform Interpolation Syntax](https://www.terraform.io/docs/configuration/interpolation.html)
* #1707

**Comment by eahefnawy** [comment]
Beautiful! 👏 That pretty much summarizes the best ideas in #1707 & #1711. Regions/Stages are no longer a core concept in Serverless, but rather an optional flexible approach with the help of `Serverless Variables`.

This offers complete flexibility for all users with all styles of config, whether they want to use env vars, config files, or single `serverless.yml` file for configuration.

**Comment by flomotlik** [comment]
@ac360 I like this syntax a lot. Looks very clean.

**Comment by nicka** [comment]
@ac360 This is freaking perfect, let's get it!

Only thing I still would like to see implemented is getting access to stack outputs. We could create a plugin which outputs CloudFormation Outputs to a file`(yml|json)` and reference those variables with the proposed solutions. And off course access to variables within functions.

**Comment by flomotlik** [comment]
@nicka what use cases would you have for adding outputs back into the serverless.yml? As we're basically translating things to Cloudformation you should also be able to use something like Ref directly and can point to specific other resources.

And yes variable access in the function itself (basically how do I get keys or other config into a running Lambda function) is another important feature we need to figure out.

**Comment by pmuens** [comment]
Great proposal!
One thing I'm curious about is how we can use this inside actual function code as this is something most applications rely on (see https://github.com/serverless/serverless/issues/1455) when e.g. using external APIs

I'd also like to /cc @mthenw to take a look at the proposal!

**Comment by nicka** [comment]
@flomotlik the problem is that AWS Lambda has no support for ENV variables. And since the functions are archived before the deploy we can't just inject them with variables during the CloudFormation deploy. The only way to get them into the function archive is by storing CloudFormation Outputs into a file which you would then reference for example in the `serverless.yml`. And as mentioned before, we first need a way to actually get a variable into the function.

In `v0.5` it was easier since the framework first deploys the resources, any stack output ends-up in a `_meta/resources/s-resources-cf-STAGE-REGION.json` file. You would then deploy your functions(without CloudFormation) separately with Serverless and the variables would already be present.

With `v1` this would be only possible with two CloudFormation deploys, since the functions are part of the CloudFormation template.

**Comment by flomotlik** [comment]
@pmuens imho its separate from this. Especially providing keys or other data (e.g. Kinesis stream ARN) to a lambda function is a critical feature (as @nicka also just pointed out).

But yeah imho its separate from this here and basically we need a way to let people inject custom data (e.g. security keys, ...) into lambda functions and give them access to data from CF (e.g. Kinesis stream access, or some endpoint or something)

**Comment by nicka** [comment]
Maybe we should start a separate discussion about injecting variables into functions? Because the solutions proposed by @ac360 are awesome!

**Comment by flomotlik** [comment]
@nicka its basically #1455

**Comment by mthenw** [comment]
I like the syntax. It's much cleaner than JSON REF et al.

Though, I think it should be simpler. There should be no distinction between source of variable (`opt`, `env`, `self`). It's a _great limitation_. I should be able to load value of variable from different sources. On my local environment I should be able to load some vars from ignored file. In CI environment I should be able to load the same values from environment variables. I should be able to override variables using CLI param. Variable value can't be bound to any particular source.

Let say we have following `serverless.yml`

```
service: hello_world

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: ${var.memorySize}

functions:
  hello:
    handler: handler.hello

vars:
  memorySize: 128 // this is default value
```

If I want to override that (because I want to deploy to prod) I should be able to do

```
serverless deploy --var 'memorySize=1024'
```

or 

```
export SERVERLESS_VAR_memorySize=1024`
serverless deploy
```

or

```
echo '{"vars": {"memorySize": 1024}}' > var.json
serverless deploy --var-file var.json
```

**Comment by ac360** [comment]
@mthenw Super interesting.  I cannot yet tell if that will result in unintended complications, but I like it.  A few thoughts:

* A clear override order must be established (e.g., *CLI Option > ENV > serverless.yml*).

* How can we reference other files with this syntax?  Perhaps keep the `${file().props.prop}`

* This seems like a way we can also include CF Outputs.  In my example above, `self` refers to the current `serverless.yml`, but I felt it should also be used for CloudFormation Outputs, yet that could cause weird conflicts.  @mthenw's suggestion solves that problem: `${var.cfOutput1}`.  Then the override order looks like this:  *CLI Option > ENV > CF Outputs > serverless.yml*

**Comment by flomotlik** [comment]
@ac360 @mthenw we could also enable both, e.g. if you just do a variable name it takes the one with precedence according to the defined order. If you do ${env.whatever} it definitely goes to the environment variables so you're able to set it specifically. Not sure if that feature is needed, maybe we can ignore it but this would be a way of hardcoding it for users to go around the overrides

**Comment by mthenw** [comment]
> A clear override order must be established (e.g., CLI Option > ENV > serverless.yml)

Absolutely. This has to be clear

> How can we reference other files with this syntax? Perhaps keep the ${file("./vars.yml").props.prop}

Assuming that I can do `serverless deploy --var-file var.json` not sure if this `${file}` is needed.

> This seems like a way we can also include CF Outputs

That's the tricky one. Not sure here but I think it should have own namespace `${cfOutput.foo}` or `${provider.resources}` ?

**Comment by jordanmack** [comment]
Great work with the new syntax. Very clean and straightforward. 

I'd like to also see a convenience function for shell execution:

`${exec("date --iso-8601")}`

`${exec("node ./config_generator.js --some-option").data.subProp}`

**Comment by ac360** [comment]
@mthenw:

> Assuming that I can do serverless deploy --var-file var.json not sure if this ${file} is needed.
 
It's still early and I'm not sure how people are going to structure their projects/services (e.g., multiple services in a single parent folder), and therefore how they are going to organize config (e.g., one file or multiple files, in one or more locations).  So, I favor `${file("./file.json").prop}` because of its flexibility.

> That's the tricky one. Not sure here but I think it should have own namespace ${cfOutput.foo} or ${provider.resources} ?

What I liked about your "var" proposal, @mthenw, was its simplicity.  I think any exceptions/happenstances bring us back to the original proposal at the top.  I'd like to go with either we have unique roots for each source (env, self, option, provider) or we use var for as much as possible.

@jordanmack:

Awesome idea!!! +100

@flomotlik @mthenw @jordanmack @nicka @pmuens @eahefnawy @nikgraf @DavidWells:

I've updated the OP.  There are now two proposals, each has more detail.  Please let us know which one you like best, or if further changes are necessary. 

Personally, I like **Proposal 2**  as it is simple.  My only concern is that people potentially run into strange scenarios with all of the overriding happening automatically.  Not sure how big of a problem this will be.

**Comment by jordanmack** [comment]
> - `serverless deploy --var 'memorySize=1024'`
> - `SERVERLESS_VAR_memorySize=1024`
> - `serverless deploy --var-file var.json`

I do not anticipate using this syntax. I prefer `${file()}` for my use cases. However, I support the inclusion of this functionality because it does have clear advantages for some setups. It's addition to the platform is beneficial, and will be used.

> ${env.${opt.stage}_arn} // Possibly limit to 1 nested var

I would recommend there be no hard nesting limit, but set a soft recursion limit for resolution. 

> There are now two proposals, each has more detail. Please let us know which one you like best, or if further changes are necessary.

If I absolutely had to chose one or the other, I would go for Proposal 1. The reason being that Proposal 2 could lead to unexpected behavior, which in turn would lead to reliance on hacky work arounds.

I also see a possible minor issue with the override ordering, specifically with `CF Outputs > serverless.yml`. CF Outputs are dependent on serverless.yml, so this ordering is essential. But what if I need to specifically override something coming out of CF? You can't place the override in your config file anymore, even though this is where all the settings will reside for the vast majority of users. You should not be forced to use CLI or ENV methods to override a configuration option.

With all that said, I support the use of `${var}` as a more convenient method, in addition to the individual references. In common usage, `${var}` should probably be the default recommended convention.

**Comment by jordanmack** [comment]
Another suggestion for shell execution:

Execute a shell command with data piped to STDIN
```
${exec("shell commands", ${self.data}).prop}
```

Other functionality that I don't  think is needed now, but could be beneficial someday:
- If conditions: ${if("evaluated condition", "condition was true", "condition was false")}
- Check if set: ${ifset(${env.var})}
- JS Evaluation: `${eval("if(${env.var}) return 'foo'; else return 'bar';")}`

**Comment by eahefnawy** [comment]
We've talked about it internally and it seems that most people are leaning towards Proposal A. So I'm gonna start implementing this change. Here's what the basic version/MVP would look like:

1. populating from env vars: `${env.my_arn}`
2. populating from cli options: `${opt.stage}`
3. populating from the self `serverless.yml` file: `${self.service}`
4. populating from another file: `${file("./serverless.env.yml").data.subProp}` (`serverless.env.yml` is now optional with any structure/name)
5. Nesting: `${env.${opt.stage}_arn}`

### Later on:
* populating from CF outputs: `${cfo.prop}`
* populating from shell commands: `${exec("shell commands").prop}`

I'll be working on this PR incrementally according to the steps above.

@serverless/core any further thoughts?

**Comment by nicka** [comment]
@eahefnawy Regarding `${cfo.prop}`:
Wouldn't `${file("./serverless.env.yml").data.subProp}` already fix this? If you think about how the framework wants to support multiple providers. We could keep it global by sticking to the `${file("./serverless.env.yml").data.subProp}` and output any CF stack output to this file?

Maybe even with `${file("./serverless.env.yml").${opt.stage}.${opt.region}.prop}`?

**Comment by eahefnawy** [comment]
@nicka the `serverless.env.yml` in that scenario is just an example. You can name it whatever you want (ie `config.yml`). We don't want to restrict the user on a specific file by outputting CF output to this file.

I'm not exactly sure how CF outputs would work exactly at this point though, but it's imho we can set it up at a later stage.

**Comment by nicka** [comment]
@eahefnawy Alright let me know if you plan to start working on it. Would love to give my opinion and maybe help out. Sorry if I'm hammering the CF Outputs to much 😊

**Comment by eahefnawy** [comment]
@nicka for sure! Your help in that area would be super valuable! 😊

**Comment by flomotlik** [comment]
>Sorry if I'm hammering the CF Outputs to much

Never have to be sorry for pushing us in any specific direction. We REALLY appreciate all the feedback and insight we get from everyone :D. The harder you guys push on something the better our understanding is what the needs are.

**Comment by ianserlin** [comment]
Couple thoughts:

Proposal 2 is actually preferable for me so that conditional logic doesn't need to be implemented in order to override values in different execution environments (command line for local development, env vars for ci/staging/production).

I could be missing something, but I don't understand how this obviates the need for JSONRef specifically in order to include additional CloudFormation configuration with the `serverless.yml` file. Since all CF templates are already in json, converting to yml by hand is not fun/great/useful. Maybe the `file()` syntax will accomplish this as well if I don't specifying any additional props off of it?

**Comment by flomotlik** [comment]
@ianserlin file() should support both JSON and Yaml. JSON Ref is also not going away.

We're going to implement the specific version first and then add an inheritance model on top of it, so you can be specific (e.g. read only from env vars) or ready from anywhere or possibly read only from those 2 sources. But we will collect more feedback at first before we decide a specific direction with overrides

**Comment by Christoph-Schabert** [comment]
Whats abour nested cf stacks?
The primary stack deploys the lambda functions, API gateway and lambda policies.
The nested resource stack deploys the parts of the resource section in the yml file.
Then the outputs of the nested stack could get before the lambda functions are deployed.

Then it would be possible to reference the outputs of the resource nested stack in the primary stack.

**Comment by flomotlik** [comment]
But can't you already reference them directly in the stack and simply create a depends On relationship? Or how would you use this specifically?

**Comment by Christoph-Schabert** [comment]
Simply put a depends on for the nested resource stack for the api gateway.

Then the nested resource stack deploy before the functions are deployed.
After that it is possible to get the output of the nested stack with GetAtt from the resource.

An alternative approach is to split the  stacks  completely.  So that the service stack just deploy the api gateway, lambda functions and policies.

And the resource stack would be (inside/outside) of the service as a separate stack than it would be possible to get the stack outputs on lambda packaging and implement the old way how outputs are injected into the lambdas.

**Comment by flomotlik** [comment]
Sorry I wasn't clear in my question. As you can already use Ref inside a Stack to reference other elements I'm not clear how embedding the stacks and then accessing the Output Variables helps there? What use cases would this make possible that aren't currently possible?

**Comment by eahefnawy** [comment]
@serverless/vip FYI I've finished implementing Proposal A in [PR #1834](https://github.com/serverless/serverless/pull/1834) and it's now under review/testing. Would be awesome if you guys could check it and try it out. Feedback and rigorous testing is essential for such a big change, and is highly appreciated 😊 .

**Comment by flomotlik** [comment]
Closed with #1834

**Comment by jgardezi** [comment]
Hi,

can anyone provide an example for development and staging environment variables using configuration file or as per documentation https://serverless.com/framework/docs/providers/aws/guide/variables/.

Kind regards,
Javed Gardezi

**Comment by pmuens** [comment]
@jgardezi Sure!
Can you go into a little bit more detail about your use case? What do you want to accomplish with the help of the variable system?

**Comment by jgardezi** [comment]
@pmuens Thank you for the quick reply.

Well I am using serverless to trigger Lambda function when a new file is uploaded to S3. That works fine.

We have multiple environments development, staging and production. Each environment has its own configurations for example development has configuration of S3 bucket name `dev-hosting` and staging env has bucket name `staging-hosting`. Also different database connection string for Lambda function.

Is their way to store these bucket and database configurations into a seperate files. So when issue a command `sls deploy --env=dev` or `sls deploy --env=stag`. It takes the configuration s3 and database variables from the respective file and deploy into lambda function.

**Comment by pmuens** [comment]
@jgardezi sure!

You can store your config / bucket names in a separate `.yml` file and then reference those config. Here's a link to the docs which will show you how this works:
https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files

And here's an example `serverless.yml` file which drafts how this might look like:

```yml
# myConfig.yml

devBucketName: myDevBucket
prodBucketName: myProdBucket
```

```yml
# serverless.yml
frameworkVersion: "=1.2.0"

service: my-service

custom:
  buckets:
    devBucket: ${file(./myConfig.yml):devBucketName}
    prodBucket: ${file(./myConfig.yml):prodBucketName}

provider:
  name: aws
  cfLogs: true

functions:
  bucketTrigger:
    handler: handler.bucketTrigger
    events:
      -s3: ${self:custom.buckets.${opt:stage}Bucket}
```

This way you'll get the `prodBucketName` from the `myConfig.yml` file when you deploy via `serverless deploy --stage prod` and the `devBucketName` form the `myConfig.yml` file when you deploy via `serverless deploy --stage dev`.

Hope it helps!
