### ISSUE TITLE
Unable to set request and response templates for AWS API Gateway

### ISSUE THREAD

**Issue by zachheine** [serverless/serverless#1811]
Going off of the old `s-function.json`:

```
      - http:
          path: users/create
          method: post
          requestTemplates:
            "application/x-www-form-urlencoded": "{\"postBody\" : \"$input.path('$')\"}"
          responses: 
            400: 
              selectionPattern: "^\\[BadRequest\\].*"
              statusCode: 400
            403: 
              selectionPattern: "^\\[Forbidden\\].*"
              statusCode: 403
            404: 
              selectionPattern: "^\\[NotFound\\].*"
              statusCode: 404
            default: 
              statusCode: 200
              responseParameters: 
              responseModels: 
              responseTemplates: 
                "application/xml": "#set($inputRoot = $input.path('$'))\n$inputRoot"
```
doesn't seem to work.  Trying to set up a Twilio endpoint.

**Comment by flomotlik** [comment]
We're discussing this issue in #1593 at the moment. We got a few proposals in, but nothing merged yet. I'll close this issue as it is a duplicate to the other one. Would be great to get your feedback there.

**Comment by zachheine** [comment]
Thanks.  Didn't have much to add as far as implementation but did list my use case.

**Comment by yonahforst** [comment]
@zachheine - I'm struggling with the same issue, trying to implement a Twilio endpoint. Did you come up with a solution?

**Comment by flomotlik** [comment]
We're going to release a new integration soon that will make all of this much easier over the next days

**Comment by yonahforst** [comment]
awesome! i'll keep an eye out for it.

**Comment by andymac4182** [comment]
@flomotlik Do you have a roadmap for things like this that are coming?

**Comment by flomotlik** [comment]
Generally its good to follow the Milestones on the repo. Thats where we put the milestones. As we're very close to V1 release in general we don't have a lot of planning on that in place yet, because we're just fixing last things and don't plan to launch anything else that is larger soon.

Going forward one of my big priorities though is making this WAY easier to understand to everyone. Generally our roadmap should be public, with the only exception being when we work on integrations with a partner where the partner hasn't made it public and we have to keep things private until the partner releases things (e.g. AWS releases a new feature, we're launch partner but can't publicly talk about it until they released their stuff)
