### ISSUE TITLE
Use modern ES6 syntax

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#1846]
##### Feature Request:
Not sure if this would be a priority, but would be nice to have for those of us who've made the switch 😉

I'm guessing this would be something that wouldn't be forced on users, so probably better as a plugin? At it's heart, it should probably just be a reimplementation of the Serverless Optimizer plugin (but maybe use Webpack?).

##### Benefits:

* Modern syntax

##### Drawbacks:

* Yet another layer of abstraction

##### Additional Details:
It also occurred to me that the reason Webpack wasn't used before was because AWS-SDK is a mighty PITA to get working with it. If that is the case, I'm happy to lend a hand.

**Comment by hassankhan** [comment]
Current handler:

```js
module.exports.hello = (event, context, cb) => cb(null,
  { message: 'Go Serverless v1.0! Your function executed successfully!', event }
);
```

ES6 handler:

```js
export default function hello(event, context) => { 
  return new Promise((resolve, reject) => {
    return resolve({ message: 'Go Serverless v1.0! Your function executed successfully!', event });
  });
}
```

**Comment by chris-olszewski** [comment]
I'm currently using webpack to do this. Here's my [config file](https://gist.github.com/chris-olszewski/8dbbfd014161105878d9374cdc4c5fdc)

**Comment by hassankhan** [comment]
IIRC the AWS-SDK is included by Lambda by default, so you don't *need* to add it as a dependency. However, some people prefer using the latest version from NPM so it might be handy for them.

**Comment by flomotlik** [comment]
@hassankhan @chris-olszewski by default we only want to support what is available in Lambda, otherwise we're pretty sure to introduce issues to users. As we are simply deploying whatever you build in your local folder you can easily run your JS code through any tool (e.g. babel) to create Lambda compatible code.

But I can see adding documentation for it. If you guys are interested in working on docs that show how to set this up we'd definitely be open to it as long as they are clearly marked as something only advanced users might want to do.

**Comment by DavidWells** [comment]
@hassankhan checkout https://github.com/serverless/community-plugins/issues/2 for the webpack plugin for es6 syntax

**Comment by flomotlik** [comment]
Thanks @DavidWells for posting. Those plugins are a great way to make sure this is possible in the future. I don't think we'll implement anything in that direction anytime soon though, so I'm closing for now and will reopen in the future if we're planning to go there at some point.
