### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#1847]
##### Feature Request:

Use a Swagger definition file to set up API Gateway endpoints and map them to Lambda functions.
##### Benefits:
- Lessens the need of obtaining a PhD to understand CF's arcane syntax.
- Integrates with all of Swagger's awesome toolage so you can get other things done.
##### Drawbacks:
- Swagger and CF don't play too well
##### Additional Details:

From the last time I tried creating a template, I think there were problems where I needed the ARN of a Lambda I had not yet deployed, so there will likely be some weird sync issues that'll need to be resolved post-deploy.
##### Discussion:
- #963

**Comment by flomotlik** [comment]
At the moment we see swagger as something that can be supported in the future if they integrate it in CF (e.g. point to swagger file to set up CF resources, which I believe is possible somehow), but as you mentioned CF and swagger don't work well together and we decided to go with CF and create our own simple syntax to create API Gateway resources.

As we don't have any plans to go there at the moment and to keep our open issues small I'm going to close here and we'll reopen in case we want to go towards swagger in the future.

**Comment by jancona** [comment]
CF supports configuring RestAPI's with Swagger. See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
I've used that successfully (without Serverless). What makes you say that Swagger and CF don't play well together?

**Comment by flomotlik** [comment]
@jancona the main problem with Swagger and CF in my opinion is that you have part of your infrastructure definition in one definition (CF template) and another in the swagger file. This means you can't easily reference or even overwrite configuration that Serverless would create.

Using Swagger  is definitely possible at the moment through custom resources in Serverless where you can simply point to your own deployed swagger file (or embed it through e.g. the `${file(swaggerfile.yml}` syntax in-line) but to actually support it in the framework "natively" would mean users can't easily reference, overwrite or edit the template.

**Comment by jancona** [comment]
Thanks for the response @flomotlik! I'm not very familiar with Serverless, so please excuse any misunderstandings. The model we have implemented is that we have a Swagger document that specifies our API endpoints. This Swagger is "clean", with no AWS-specific extensions. We then process the Swagger as part of our deployment pipeline to add the AWS extensions to properly setup Lambda functions, etc. In my mind a similar model might make sense for Serverless, where I would specify the service interface using Swagger and the rest of the configuration in serverless.yml, which would contain a reference to the Swagger, instead of endpoint specification within serverless.yml itself.

At that point, I would be agnostic as to how Serverless implements the deployment of the configuration. 

So the TL;DR is that I'd rather define my service endpoints in Swagger rather than in Serverless format, because there are lots of tools that understand it, and I can reuse that Swagger in other places (i.e. for documentation).

I hope this clarifies what I'm looking for. Again, I'm a newbie with Serverless, so my apologies if I'm missing obvious things about how it works.

**Comment by flomotlik** [comment]
>So the TL;DR is that I'd rather define my service endpoints in Swagger rather than in Serverless format, because there are lots of tools that understand it, and I can reuse that Swagger in other places (i.e. for documentation).
I hope this clarifies what I'm looking for. Again, I'm a newbie with Serverless, so my apologies if I'm missing obvious things about how it works.

Yup and I totally agree that this should be a workflow that should be possible to do. At the moment the way you would accomplish it is basically only managing your functions through serverless and deploying your swagger endpoint independently and pointing to the functions you've deployed through Serverless.

We needed to make a decision if we either go with Swagger or CF for V1, because supporting both would have meant too much work. But I can see this becoming something more interesting again int he future, so I'm going to reopen the issue.

I don't think we're going to work on this soon though, but if somebody would be interested in building a plugin for example that integrates Swagger with Serverless I could definitely see this becoming part of our Community Plugin repo where we put plugins that are of high quality, but aren't part of the core.

**Comment by hassankhan** [comment]
How would you recommend that be done? Should the service folder have a `swagger.yml` file that overrides any settings from `serverless.yml`?

**Comment by flomotlik** [comment]
I don't think that swagger.yml would have to overwrite any settings in serverless.yml. Basically when using swagger the serverless.yml would not be used to set up any APIG infrastructure and the swagger file would be deployed independently. A plugin could then, after the CF deployment of Serverless read the deployed CF template (e.g. through Output variables), update the swagger.yml (as @jancona mentioned before in a pre-processing step before deployment) so the infrastructure that is created through the swagger file points to the before mentioned functions and then swagger gets deployed (through the plugin)

**Comment by hassankhan** [comment]
Ok, so should a Swagger file be specific to each service then?

**Comment by flomotlik** [comment]
Depends, If you want to have multiple services run in the same API Gateway API, then not. That becomes interesting when we go down the road of service composition, e.g.

1. You create one API Gateway with a mapping of path to functions. Those functions then call other backend services to deliver results
2. You create one API Gateway and that API Gateway points to functions created by multiple services. So you have one HTTP Frontend service, but multiple backend services that are all connected to the one API Gateway

Personally I prefer 1, but that would introduce lots of additional latency and is not an option for everyone.

**Comment by flomotlik** [comment]
Closing as we don't plan on Swagger support directly in the framework. You can of course do it through custom resources.

**Comment by ZauberNerd** [comment]
As discussed with @pmuens, this is a blocker for me right now - I created my own set of tooling around aws lambda instead of using the serverless framework mostly for this reason only.
Seeing swagger become the Open API initiative under the umbrella of the linux foundation and a lot of baking of high profile companies behind it, it seems like a good idea to bet on swagger.
http://swagger.io/introducing-the-open-api-initiative/

My use case is:
I want to generate everything HTTP related from swagger (client libraries, type definitions, request validations (using json schema), (maybe even server handlers) but most importantly the API Gateway).
So, I'll either have:
- a swagger definition "as master" which generates (most if not all) other entities or
- a swagger file wich is being generated from docblock comments on the handler functions which then in turn generates the API Gateway.

At the moment I have written a custom cloudformation resource that is baked by a lambda function, that reads a swagger file from s3, generates the API GW, and writes the updated swagger file back to s3 - but as you can see, this is rather suboptimal and I think it'd be great, if the serverless framework would have support for this use-case, as I suspect that it will become even more popular with the recent up-rise of the Open API intiative (fka swagger).

**Comment by pmuens** [comment]
Hey @ZauberNerd!
Thanks for the detailed description and the discussion we had about this the other day! 👍  💯 

Pinging @eahefnawy and @flomotlik about this. Any updates on this one?
Should we start by adding docs how people can use Swagger via `resources`?

BTW. Here's an old (v0.5) plugin I found: https://github.com/serverless/serverless-swagger-plugin maybe it's worth to port it over.

**Comment by flomotlik** [comment]
Yup adding docs sounds reasonable. At the moment while swagger support in
Serverless has very passionate proponents, its simply not something we hear
often enough to invest a lot of time into it and take the added complexity
into the core of Serverless. A swagger plugin that makes this easier could
definitely be a very interesting advancement, we don’t have the resources
to do it ourselves now though.


On 16 November 2016 at 07:16:04, Philipp Muens (notifications@github.com)
wrote:

Hey @ZauberNerd <https://github.com/ZauberNerd>!
Thanks for the detailed description and the discussion we had about this
the other day! 👍 💯

Pinging @eahefnawy <https://github.com/eahefnawy> and @flomotlik
<https://github.com/flomotlik> about this. Any updates on this one?
Should we start by adding docs how people can use Swagger via resources?

BTW. Here's an old (v0.5) plugin I found:
https://github.com/serverless/serverless-swagger-plugin maybe it's worth to
port it over.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/serverless/serverless/issues/1847#issuecomment-260871802>,
or mute the thread

**Comment by hassankhan** [comment]
If Serverless was to use Swagger (via plugin or core) would/should it be able to use the APIG-Lambda proxy or will it only use the old (horrible) way of request/response mapping?

**Comment by eric-tucker** [comment]
Are there any other updates on this issue?  It would be nice to see a plugin that isn't tagged with "not ready". :)

**Comment by pmuens** [comment]
@eric-tucker thanks for reaching out.

The best way to do this right now is to use a Serverless Swagger plugin. Both of them look solid in terms of feature set and maturity:

- https://github.com/Reckon-Limited/serverless_swagger
- https://github.com/AKIRA-MIYAKE/serverless-import-swagger

**Comment by eric-tucker** [comment]
@pmuens thanks for the suggestions, but both of these aren't what I am looking for.  I simply want a way to parse the swagger file paths and generate ONLY the events section of the serverless.yml file.  

serverless_swagger generates JS snippets for every single API endpoint and declares a new Lambda function for each, which is exactly the opposite of what we want in swagger.

serverless-import-swagger doesn't seem to do anything, though I could be using it wrong.  The docs are definitely lacking [examples].

**Comment by pmuens** [comment]
@eric-tucker thanks for the feedback on those plugins and the detailed information regarding your use case.

Just dropping some other plugins / options here (haven't evaluated them for your specific use case though):

- https://github.com/search?utf8=%E2%9C%93&q=serverless+swagger&type=
- https://github.com/doapp-ryanp/serverless-plugin-swag
- https://github.com/kennu/serverless-plugin-swagger-export

**Comment by dkirrane** [comment]
Any tools that can generate a aws-java-gradle service from a swagger.yaml?

i.e. parse the swagger.yaml and generate the serverless.yaml and various Java handlers.

**Comment by edholland** [comment]
just adding a +1 for the concept

**Comment by sridharrajagopal** [comment]
+1

**Comment by deanpeterson** [comment]
Unfortunately at the State of MN we will be moving away from the serverless framework for this very reason. Spec Driven Design is a must and the Swagger spec seems to be key. To me, not supporting this early on will be what inevitably leads to the failure of the Serverless Framework. I think in hindsight this will seem ridiculously obvious to the Serverless Framework team.

**Comment by LucasBadico** [comment]
Took the path to make those two work tooguether, swagger and serverless, I do not have the option to walk away. I will be reporting the process here.

**Comment by TomCawthorn** [comment]
+1

**Comment by francoalbornoz92** [comment]
+1

**Comment by cwienands** [comment]
@et304383Not sure if it is still relevant but I got serverless-import-swagger to work. Take a look at the test/index.js file and other files in that folder for guidance on how to use the tool.
