### ISSUE TITLE
New CloudFormation Logical IDs

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1931]
We're redesigning the CloudFormation Logical IDs that are generated by the framework to follow a specific pattern to help make them predictable based on #1869 discussion. The general pattern is `functionNameTypeResourceName` Here's a guideline of this pattern:

- `functionName`: Some resources are dependent on functions, in this case, the logical id will be prefixed with the function name. If it doesn't depend on function name, no function name will be added. We just use common sense and our best judgement.
- `type`: The logical ID would include the **type** of resource we're creating (ie. S3, Schedule...etc)
- `resourceName`: Each logical ID would have a name or identifier. This name depends on the resource itself. Some names would require an id number at the end if there's a chance of duplication or having multiple of the same resources for different functions.

### New Logical IDs for each resource we create

- `S3DeploymentBucket` -> the core deployment bucket
- `IamRoleLambda` -> the core IAM role for the lambdas
- `IamPolicyLambda` -> the core IAM policy for the lambdas
- `FunctionHello` -> an example `hello` function
- `HelloSchedule1` -> schedule event for the `hello` function. We include the function name because we can have a schedule for each function, and we include an id because we can have multiple schedule events for a single function. Without those schedule resources would collide and overwrite each other.
- `HelloSchedulePermission1` -> permission for the above schedule.
- `S3BucketName0` -> S3 event. We include an id at the end because the BucketName could be used in another S3 event in the service.
- `S3BucketNamePermission0 ` -> permmission for the above S3 event.
- `S3BucketNamePermission0 ` -> permmission for the above S3 event.
- `ApigRestApi` -> the REST API for the service
- `ApigDeployment1471876466561` -> the deployment resource for the Rest API. It includes a unique token at the end to always update the resource on deployment.
- `ApigResourceUsers` -> APIG resource for http event with path `users/create`. This resource is the `users` resource
- `ApigResourceUsersCreate` -> APIG resource for http event with path `users/create`. This resource is the `create` resource that has a parent of `users`
- `ApigMethodUsersCreateGet` -> APIG method for the `users/create` path or `UsersCreate` resource.
- `helloApigPermission` -> permission for APIG to invoke the `hello` function. It's function bound because we can have multiple permission resources for each function that has an http event.
- `ApigApiKey0` -> resource for an API key defined for the service rest API. It ends with an index because you can have multiple API keys.
- `ApigAuthorizerHello` -> resource for setting the `hello` function as an authorizer function.
- `HelloSns1` -> resource for SNS event. It includes the function name because you can have multiple SNS for multiple funcitons, and it includes an id at the end because you can have multiple SNS events for the same function.
- `HelloSnsPermission1` -> permission resource for the SNS event above.

@flomotlik @pmuens I'm gonna go ahead and put this in place. Let me know if you have any final updates.

**Comment by flomotlik** [comment]
To make the logical ids work well in the future we need to think about 2 things, binding and unique naming:

# Binding in logical ids:

Resources can be bound to either the service or a function. Binding to the service means that when you change the function name the resource logical id will not be changed and thus it will stay the same on the next deployment. Furthermore several functions can use that same resource for different setups, e.g.

* S3 Bucket: We want to be able to call several functions from the same S3 bucket event
* SNS Topic: We want to be able to call several functions from the same sns topic

Example name: S3BucketMyCustomBucket

It has the Name of the CF Resource (without the AWS prefix) to easily see what the resource is and then the name of the bucket (without the non-alphanumeric characters). When two functions now reference the same bucket they will both be triggered from that same bucket. Thus we can't and shouldn't add any numeric or random number to the end of the buckets logical id

# Unique Naming

Naming follow the following format:

{FUNCTION NAME}{CloudFormationResourceName}{ResourceName}{SequentialID or Random String}

* FunctionName: For resources that are function bound we should add the Function Name in the beginning, e.g. CloudWatch Event Schedules. This has the downside that those resources will be recreated when the function is renamed but we need some way to connect a function to a specific resource if its only used for that specific function, otherwise we can't recreate the CF template on the next deployment
* CloudFormationResourceName: To easily identify what type this is adding the CFResourceName makes sense.
* ResourceName: A name that is derived from the configuration of this resource. E.g. UserCreateGet for an API Gateway Method or MyBucket for an S3 Bucket. This doesn't have to be unique as we can achieve uniqueness with the sequential or RandomID. If the resource is Service bound we need to make sure they get merged together instead of overwritten so that multiple functions can point to the same resource
* SequentialID: When you have multiple function bound resources of the same type but different config we need a sequential number to identify them, e.g. if we have one function that should have two different schedule events attached to it. The Sequential number represents the index of the schedule event in this function, so it only increases for schedule events and not if you also have other events defined. Otherwise if you rearrange the events the number might change and it gets redeployed.
  * HelloEventsRuleSchedule1
  * HelloEventsRuleSchedule2
* Random String: Some resources need to have Random strings attached so they get redeployed every time, e.g. APIG Deployments.

**Comment by nicka** [comment]
@flomotlik All good with `{FUNCTION NAME}{CloudFormationResourceName}{ResourceName}{{SequentialID}`.

My only concern is the `{or Random String}`. Do we have a plan to apply custom configuration for these kind of resources through custom resources?

**Comment by flomotlik** [comment]
@nicka its only reserved for things where we absolutely need the random string, e.g. APIG Deployment (which is the only case at this point and I hope the last one). APIG Deployments don't need any custom config (or really can't get any custom config) as they are basically just a trigger to deploy. We need the random element there to trigger a redeployment when something changes until Cloudformation does this automatically themselves.

**Comment by flomotlik** [comment]
What we can do though is add the random variable to the Parameters or mappings section of the CF template file so users can actually access it in custom resources (though I'm not sure if they are able to access it in the logicalID. http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html

**Comment by nicka** [comment]
@flomotlik Thanks for the clarification on this!

**Comment by flomotlik** [comment]
This is fixed now with #1951
