### ISSUE TITLE
API Gateway error handling patterns

### ISSUE THREAD

**Issue by justinsoliz** [serverless/serverless#1939]
##### Serverless Framework Version: 1.0.0-beta.2

I'm not seeing anything in the docs that references error handling patterns (400s, 404s, 500s etc..) in regard to API gateway. Is there a page I may have missed or is this beyond the scope of functionality that serverless is supporting right now?

**Comment by pmuens** [comment]
Hey @justinsoliz thanks for bringing that up.

We're currently discussing this in https://github.com/serverless/serverless/issues/1593 as we're about to introduce the functionality to add own request / response templates which should cover that.

Feel free to chime in!

Closing this for now as the implementation of #1593 which is planned for the beta.3 milestone should solve this problem here.
