### ISSUE TITLE
Default authorization identitySource

### ISSUE THREAD

**Issue by nguyer** [serverless/serverless#1943]
Line 47 of `authorizers.js` sets the default identitySource to `method.request.header.Auth`:

    identitySource = authorizer.identitySource || 'method.request.header.Auth';

To me, it seems strange that the default is not `method.request.header.Auth`. Is there a reason why it is this way? Most APIs that I have used, the `Authorization` header is used.

Shouldn't the default be `Authorization`?

https://github.com/serverless/serverless/blob/85f4084e6b0fd4a6d763ace8cd0db82817bbc712/lib/plugins/aws/deploy/compile/events/apiGateway/lib/authorizers.js#L47

**Comment by nguyer** [comment]
Also line 30 of the same file.

**Comment by andymac4182** [comment]
It would be great if this could be overridden as a default. Since we are changing this on all of our functions.

@nguyer Auth is the default from AWS.

**Comment by andymac4182** [comment]
@flomotlik I am happy to implement the ability to set a provider default in `serverless.yml` similar to memorySize or should I wait till after the variables PR has been merged https://github.com/serverless/serverless/pull/1834?

**Comment by nguyer** [comment]
> Auth is the default from AWS.

Didn't realize that. The ability to set a provider default would be great!

**Comment by kennu** [comment]
It seems I reported the same issue in #1983.

Auth is not the default header in AWS. When you create a custom authorizer in API Gateway, the default identity token source is `method.request.header.Authorization`.

Also Authorization is handled by default in many situations like CORS headers, CloudFront whitelisting headers etc., since it is also the official HTTP header to use. I think Auth is something made-up for examples only and not a very good idea for default.

**Comment by andymac4182** [comment]
Ahh I must of miss read the UI. Authorization is what we are using for ours at the moment.

**Comment by kennu** [comment]
I submitted a PR to change Auth => Authorization and I believe #1983 now closed also this issue.

**Comment by flomotlik** [comment]
Yup as @kennu mentioned this is fixed now due to his PR. Thanks again!
