### ISSUE TITLE
serverless create error messages

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#1965]
##### Serverless Framework Version:

1.0.0-beta.2
##### Operating System:

Mac
##### Expected Behavior:

Serverless should throw a warning or tell me that I can't write in the directory.
##### Actual Behavior:

Serverless says the project is created when it actually is not.

`serverless create --template aws-nodejs` didn't create the project like the CLI says it did.

![image](https://cloud.githubusercontent.com/assets/532272/17991249/b925c364-6af1-11e6-942f-a75b1a0c90d0.png)

I believe this is an issue with the directory I am in not having write access, but we shouldn't tell people something is created when it's not. 

Instead we should show them a warning "Error unable to create a service in this directory. Please chmod the directory and change file permissions to enable service creation"

**Comment by flomotlik** [comment]
Yup! Added a help wanted easy label as its not super crucial for us, but should be resolved at some point

**Comment by gburch** [comment]
I have a fix for this but as of 1.1 it no longer silently fails. Instead it fails like so:

<img width="489" alt="screen shot 2016-11-04 at 3 24 16 pm" src="https://cloud.githubusercontent.com/assets/144618/20024527/77f4d688-a2a4-11e6-9628-dfe3c3f51630.png">

I will open a pull request for discussion since the code is written for a more user friendly message but not really sure if that is needed.
