### ISSUE TITLE
Add a package.json for the template : aws-nodejs

### ISSUE THREAD

**Issue by StefH** [serverless/serverless#1996]
# This is a Feature Proposal
## Description
- Creating a new **aws-nodejs** from template should also provide a default package.json

**Comment by andymac4182** [comment]
@StefH Is there anything in particular you are looking for in the package.json?

**Comment by StefH** [comment]
Something like this for a javascript project:
```js
{
  "name": "{insert name here}",
  "version": "0.0.1",
  "description": "{insert name here}",
  "scripts": {
    "deploy": "serverless deploy",
    "typings": "typings install"
  },
  "dependencies": {
    "aws-sdk": "^2.5.4"
  },
  "devDependencies": {
  }
}
```

**Comment by andymac4182** [comment]
Here is a diff. If the guys are happy I can submit a PR. https://github.com/serverless/serverless/compare/master...andymac4182:template_node_packagejson?expand=1

**Comment by rowanu** [comment]
Not a fan of this idea. Why can't people just run `npm init -f` in their service directory if they want it?

For my projects that have many functions, I might want to have a per-function `package.json` for dependency management (in a sub directory), and nothing at the top level.

I also don't want the AWS SDK installed automatically - the Lambda execution environment automatically includes it, so installing it locally just means I need to zip and push more data. Also, what if (in the future) I'm not using AWS as a provider?

**Comment by rowanu** [comment]
Wouldn't it be better to just implement #1938 so that people can install their own templates, and keep the bundled templates to a minimum to get started?

**Comment by eahefnawy** [comment]
💯 agreed with @rowanu ... I'd rather keep the `create` templates as thin as possible (I'm not even a big fan of the generated `event.json` file). Simplicity is best imo ☺️ ... an ideal service creation for me would be just `serverless.yml` & `handlers.js`

**Comment by dougmoscrop** [comment]
Could we maybe add like a .. `plugins` plugin that let users do things like `sls plugin add <name>` and then that manipulates the appropriate file? (i.e. it could understand -f as a function to install the plugin for, or for all functions if not present, and so on)

**Comment by dougmoscrop** [comment]
Building on my previous comment, I actually think this could help also make it so that you can remove all the aws specific 'core' plugins. Why? Well I feel like at some point you are going to want to be able to merge and release fixes to AWS related functionality without necessarily releasing Serverless Core functionality (and vice-versa).

Given that there's a PR to install from a repository, I feel like this makes sense and fits with various things I've seen in other tools:

- move the core aws plugins to e.g `serverless/aws`
- move the creation templates to separate github projects (e.g. `serverless/starter-awsnodejs`)
- change the example to like `serverless install github:serverless/starter-awsnodejs`)
- have that project have a `package.json`, which includes `serverless-aws` as a devDependency and make the `serverless install` do an `npm install`

**Comment by dougmoscrop** [comment]
@rowanu 
> For my projects that have many functions, I might want to have a per-function package.json for dependency management (in a sub directory), and nothing at the top level.

I think those are different things. The per-function package.json is an artifact of the fact you're using Node as your Serverless function. The "top level" package.json is an artifact of the fact serverless is a node.js tool. Even a Python application could have a package.json in the root.

I actually think that you should list the serverless plugins, as I said above, in a top-level package.json as devDependencies. The stuff you pull in to your Lambda function is entirely different. (I think having one package.json is still simpler and what you're describing is a more advanced use case anyway. Even with one package.json people can optimize via webpack, for example)

**Comment by rowanu** [comment]
I do list my serverless plugins in a top level `package.json` as `devDependencies`. The issue is I **don't** want them bundled up as part of my Lambda function package, which they would be by default. Suggesting users need to optimise their packaging with webpack sounds like the advanced use-case to me, not the default.

> * change the getting started example to like serverless install github:serverless/starter-awsnodejs)

If there's support for templates (as you mentioned in your previous comment) they why wouldn't you just put the `package.json` in the template you using? That way you can have whatever you want, and there's no need to put a file in the default service setup.

**Comment by dougmoscrop** [comment]
You're optimizing for the case where you don't use any (non-built-in) plugins (If you did, you already have a package.json...) and I'm suggesting a slight paradigm shift where people *always* use plugins could benefit release/code management.

Agreed that devDependencies should not be bundled as part of the package. But dependencies should be. The most obvious, straight-forward thing for someone using Node is to `npm install --save` and `require()` and omitting the devDependencies seems like something that serverless should understand (can serverless run `npm prune --production` or something? What about ignoring serverless-plugin-*?)

Otherwise, the workflow you suggest has the same problems as automatically doing it. User installs/creates a project. User does npm init. User has everything bundled up and has to research how to avoid it or has no idea it's happening.

**Comment by rowanu** [comment]
> I actually think that you should list the serverless plugins, as I said above, in a top-level package.json as devDependencies.

But if you install your plugins as `devDependencies` and then run `npm prune --production` and run Serverless, won't that break? This all seems to complicated, and not something we should be deciding for users.

**Comment by dougmoscrop** [comment]
It would have to be run in a staging dir or something if prune was used.

So, how do you do it? How do you ignore your package.json devDep?

**Comment by rowanu** [comment]
I have per-project `package.json` and package my functions individually. For my simple projects with no dependencies I don't have a `package.json` or `node_modules/` in the top-level service directory, which is why I'm against including it by default.

Just to be clear I am very for #1938 (aka. service templates) so that you can do exactly what you want with a dedicated template, I just don't think it should be the default.

**Comment by dougmoscrop** [comment]
I don't care so much about how it gets implemented, but I was in favour of this because it helps making serverless-aws things that are distributed separately. The use cases you are describing (which I consider to be two ends of spectrum: trivial and overly complicated i.e. multiple things in one repo) kind of prohibit this. 

Perhaps another way of approaching it would be to have serverless install plugins in to .serverless, so you would do `serverless plugins install` and this would 'npm install' them but without the package.json at all. Just what's referenced in serverless.yml.

Dunno.

**Comment by rowanu** [comment]
Those are the two types of cases I have personally used, so that's all I can speak to.

It sounds like you're taking about something much more complicated than what this issue was proposing: adding additional file(s) to the default service template that aren't strictly required.

You've  obviously thought a lot about this, so feel free to propose a new feature on a new issue.

**Comment by flomotlik** [comment]
At the moment I don't think we're going to introduce this, but we're going to make templates a little more real world with unit tests and all. Will move to a different issue for that in the future.
