### ISSUE TITLE
[Feature] compiling before upload

### ISSUE THREAD

**Issue by stoffern** [serverless/serverless#2005]
# This is a Feature Proposal

## Description
Add babel compiling before zipping and uploading (will suport all ES versions bu default)
Compile all node_modules that are required from package.json (including sub deps) into modules.js (minified and zipped)

**Comment by flomotlik** [comment]
Hi, thanks for sending this in, could you update the issue to follow our template: https://github.com/serverless/serverless/blob/master/.github/ISSUE_TEMPLATE.md

It helps us a lot to better understand the use case and prioritise then.

**Comment by andymac4182** [comment]
Personally I like this being a plugin. It works well since there is a few different systems to compile your code. It also works well since not everyone is using nodejs. The way you have implemented it in https://github.com/stoffern/serverless-es6-example is a great example of one way and https://github.com/elastic-coders/serverless-webpack is another.

**Comment by stoffern** [comment]
@andymac4182 yeah, probably plugin is the right way to go :smile:
