### ISSUE TITLE
serverless.yml should have a jsonschema and be validated

### ISSUE THREAD

**Issue by polvoazul** [serverless/serverless#2008]
It would be very nice to have an active documentation on what is a valid serverless.yml file.
Small typos, caps issues and sometimes just finding a good documentation on a feature would take MUCH LESS TIME if there was an authoritative source. 

I suggest writing a json-shema for serverless.yml and including a serverless.yml validation step on deploy.

**Comment by flomotlik** [comment]
Thanks for the feedback, the problem with a json schema is that users can extend serverless.yml individually through plugins, so we can't really fully validate it. We're going to work on other features like auto indent check or validating that events aren't configured in a wrong way.

**Comment by jurosh** [comment]
At least would be good to have some validation of known stuff - like resources, databases, policies etc - now deploy told me that I have syntax errors in policy but I have no clue what is wrong...

Also not sure if it's possible to use json as working with yaml is pain...

**Comment by saiaman** [comment]
+1 for "Syntax errors in policy"

**Comment by atz** [comment]
You should at least be able to formally model your own file, without any plugins.  It then becomes very easy for a plugin-developer to specify what additional expressivity they are adding, by extending your existing schema.  

I agree you cannot integrate validation at runtime with plugins, since the intersection of arbitrary plugins does not produce a foreknown document-space.  Or rather, you *could* validate, IF we quarantined all plugin namespace under a given property like `custom` or `plugin_config`.  

In the meantime, at least one person was taking a stab at this:
   https://github.com/softprops/serverless-yml-schema
