### ISSUE TITLE
Check if events is an array when loading the config

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2027]
# This is a Bug Report

## Description

When a user accidentally configures events to be an object instead of an array an exceptions gets thrown. Instead the user should be warned that the event has to be an array. Example:

```
events:
  http: get users
```

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by rowanu** [comment]
Hey @flomotlik I was just looking at the tests around this functionality and want to confirm with you: It looks like the tests for `getEventInFunction` [incorrectly configure `events` to be an object](/serverless/serverless/blob/master/tests/classes/Service.js#L416-L418). Is that worth fixing as part of this PR? It doesn't seem to be causing any issues, because I can't see `getEventInFunction` being used anywhere in the codebase.

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/2033
