### ISSUE TITLE
Add Documentation for IAM ARN feature

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2028]
# This is a Bug Report

## Description

Currently we don't have documentation for the recently merged PR #1975 about IAM Role ARN implementation.

Similar or dependent issues:
*

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by mpaf** [comment]
Hi, about this issue - how do we deal with different functions in the same service needing a different role? In version 0.5 it seemed to be more flexible, so that custom resources could be used as variables in the templates, so you could use any role with a function definition. Now it seems that by using the provider -> IamRoleARN we are limiting it to one ARN for all the functions within the same service stack.

**Comment by flomotlik** [comment]
There is an open issue for this feature with #1807 discussing this. Basically the same config as per service should be available per function as well so you can create individual roles for every function.

**Comment by mpaf** [comment]
Ok. What about getting the ARN from the Custom Resource you just created? If you deploy the function/service across accounts that ARN will be different, so it doesn't make sense to hard-code the ARN, a reference to the custom serverless resource would be better. I haven't seen any documentation to that purpose, if that's already a possibility - it was a possibility in 0.5 at least.

**Comment by flomotlik** [comment]
@mpaf definitely a possibility. As its all part of the same CloudFormation stack you can simply use the Ref syntax of Cloudformation. Some of this is also documented here in this PR: https://github.com/serverless/serverless/pull/2073

**Comment by horike37** [comment]
@flomotlik 
I implemented this. Cloud you review it?

**Comment by mthenw** [comment]
Fixed in https://github.com/serverless/serverless/pull/2309. Thanks @horike37!
