### ISSUE TITLE
remove leaves project in a unrecoverable state

### ISSUE THREAD

**Issue by aychedee** [serverless/serverless#2035]
# This is a Bug Report

## Description

For bug reports:
* Created a basic project with one GET endpoint on AWS, tried adding another POST endpoint, this failed. Tried `serverless remove`, then tried `serverless deploy`. Project now in a broken state due to missing s3 bucket. 
* I expected that the project would be removed cleanly and would be deployable again
* What was the config you used?

## Command output
```
┌[ jobs: 1 389 22:56 ] [ hansel@home ] [ ⎇  master ] [ ~/Projects/homer ]
└> serverless remove
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking stack removal progress...
........ 
  Serverless Error ---------------------------------------
 
     An error occurred while removing the stack
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 

┌[ jobs: 1 390 22:59 ] [ hansel@home ] [ ⎇  master ] [ ~/Projects/homer ]
└> serverless remove
Serverless: Getting all objects in S3 bucket...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 

┌[ jobs: 1 390 23:00 ] [ hansel@home ] [ ⎇  master ] [ ~/Projects/homer ]
└> serverless deploy
Serverless: Zipping service...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
```

## Additional Data

* ***Using latest version from github on master branch***:
* ***Linux/Ubuntu 16.04***:
* ***Stack Trace***:
* ***Status:
DELETE_FAILED
Status reason:
The following resource(s) failed to delete: [IamRoleLambda].***:

**Comment by aychedee** [comment]
I can see why the delete failed, because I attached a IAM policy to the Lambda role, so that it could have access to dynamodb... But I still think this is a bug. Would it have worked if I somehow added the IAM role in the resources part of my config? Not that I'm sure how I would even do that :)

**Comment by rowanu** [comment]
Yes, it probably would've worked if you added the policy as part of the config - then it would've been managed in the same CloudFormation template.

Because you attached the IAM policy outside of CloudFormation, it wasn't able to delete it when you ran `serverless remove`. This mean that you would've had a stack in a failed state (but not deleted), and when you tried to do `serverless deploy` after it failed because a stack with the same name already existed (and stack names must be unique).

You should be able to recover by going and deleting the offending stack through the AWS Console.
There isn't anything Serverless could've done to prevent/fix this.
