### ISSUE TITLE
API Gateway returns 200 when function times out

### ISSUE THREAD

**Issue by fruffin** [serverless/serverless#2049]
# This is a Bug Report

## Description
* What went wrong?
When a lambda function times out, API Gateway still returns a 200 OK status code

* What should have happened?
API Gateway should return a 500 or 504 status code when a lambda function times out

* What was the config you used?
Serverless 1.0 RC1

The code change for this is very simple. PR to follow shortly

**Comment by andymac4182** [comment]
Is this when the function timeout is shorter than the 30 second timeout from API Gateway?

**Comment by fruffin** [comment]
yes, it was with a 20s timeout on the function.

**Comment by adonisv79** [comment]
I am getting this issue wherein a timeout is code 200. I do not understand this thread where it does not speak of what is the workaround but claims the issue is fixed and closed. was serverless supposed to be handling these automatically (coz it did not for me), is there something I need to set in the yml file? the handler?

**Comment by pmuens** [comment]
@adonisv79 what integration type are you using?

Using the `lambda` integration type should fix the issue.
