### ISSUE TITLE
API Keys not working as expected

### ISSUE THREAD

**Issue by dwtalk** [serverless/serverless#2058]
# This is a Bug Report

## Description

API Keys specified in the serverless yaml file are not able to be leveraged

## Details

When an API key is specified in the serverless.yml file as such:

provider:
  name: aws
  runtime: java8
  apiKeys:
      - mytestapikey

The behavior is that an api key is created in AWS, however it is not usable.

1. The API key is created with the given value "mytestapikey" in yaml as the name of the key, where as the actual API key value (the data sent in header) is randomly generated. This needs to be changed to "Custom" and the data in the YAML file should be an array of key value pairs, the API key name and API key value.
2. Once an API key is successfully created, it is not usable without a usage plan. This seems like it could be accomplished in the cloudfront section, but the documentation does not make it clear that this needs to be in place to leverage an API key when for a given function "private: true" is set.

## Additional Data

* ***Serverless Framework Version you're using***:
1.0rc <- head as of 9/6/16
* ***Operating System***:
OSX
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
{403: Forbidden}

**Comment by eahefnawy** [comment]
Thanks for bringing this up @dwtalk ... I've also wondered about this when I started implementing this feature, but unfortunately [CF doesn't support setting custom API key values](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html#cfn-apigateway-apigateway-apikey-name).

Good news is that the value is returned from the resource and can be used as a CF output. So what we can do is list the values for you after deployment or using `serverless info` cc/ @flomotlik @pmuens

**Comment by eahefnawy** [comment]
@dwtalk FYI I just PRed an implementation to return the api key values after deployment and when running `serverless info`. This should make the process a bit easier 😊

**Comment by thehighlander** [comment]
I'd like to do another vote for adding the ability to provide custom API keys. I know you want to break out the apigw CLI!

In my case, if I have a client "crm" they would always use the "crm-api-key" value across any API mapped under an entire custom domain. With serverless, the client has to manage many keys to hit different areas in the custom domain API. Some of our client apps hit one a single "area" so far, but others would have multiple client keys to keep straight (and it feels like it breaks my ability to easily track my client).

Also, if I stand up a new stage for a new feature branch, it seems to break down as-is. If I run it side-by-side the "real dev" I have to change the key in the "client app" or redeploy it as well in order to test that integration.

**Comment by eahefnawy** [comment]
Thanks for sharing your thoughts @thehighlander .... maybe I wasn't super clear, but **it's not possible** for us to support custom API keys values, even though we want to. This is due to the fact that we create API Keys using CloudFormation, and CF doesn't support adding custom values. It always auto generates

**Comment by thehighlander** [comment]
Oh, I understood - that's why I quipped 'break out the cli' since you can do it using that instead. I know, I know... changing the state of a resource created by CF is a technical no-no....

**Comment by pmuens** [comment]
This is now implemented with #2079

**Comment by lewisdawson** [comment]
@eahefnawy I think it would be helpful to document this limitation. Would you be opposed to that? I spent quite some time trying to figure out why it wouldn't work when enabling the API key.

**Comment by davidduffett** [comment]
This issue was closed but as far as I can see API keys are still unusable as they are not associated with a usage plan in API gateway.  Any idea when adding the keys to a usage plan will be available?

**Comment by pmuens** [comment]
@davidduffett Thank you for your feedback! That's definitely a good addition. Could you open up a separate issue for that so that we can discuss this functionality there?

Thanks in advance!
