### ISSUE TITLE
API Gateway URLs change when removing and redeploying service

### ISSUE THREAD

**Issue by kennu** [serverless/serverless#2074]
I know this is a debatable issue, but I'd like to raise it anyway. Whenever the Serverless 1.0-style CloudFormation stack is removed and recreated, API endpoint URLs also change. This is very undesirable when those URLs have been configured e.g. into front-end web applications and other integration points who expect the URLs to remain constant.

This might (?) not be an issue when using API Gateway Custom Domains. However, API Gateway doesn't support ACM certificates, so in many cases it's necessary to use the "raw" API Gateway endpoint URLs. It's not really convenient to use Let's Encrypt certificates either. I also think that even with Custom Domains, an admin needs to remap everything manually.

I never include persistent resources in my own CloudFormation stacks for this reason. I exclude things like Route 53 configuration, DynamoDB tables, S3 buckets, etc. because removing and recreating them along with the stack always causes pain and problems in CloudFormation. I only include transient and easily recreatable things like SQS queues, SNS topics, IAM policies etc.

This is why I would also urge Serverless to exclude the API Gateway APIs from the CloudFormation stack and instead manage them manually, as was done in Serverless 0.5. This would let users keep their endpoint URLs forever.

(I have also 'complained' about a similar problem when deleting the Serverless 1.0-created CloudFormation stack from AWS Console. Manual delete fails because a non-empty S3 bucket is included in the stack, causing aforementioned pain and problems. This is why I would also exclude the S3 bucket from CloudFormation. It's anyway a bad idea to create dozens of buckets, when the default resource limit is 100 buckets per account.)

So what I'd like to communicate, with several years of AWS experience, is this: It's not a good idea to put everything in CloudFormation, even if it's technically possible.

**Comment by flomotlik** [comment]
Thanks @kennu for getting this discussion started. I think it highlights a few things we need to resolve in the future with Serverless.

I will talk about our reasons for Cloudformation at first and then go into more details one the specific issues that we need to solve to make the painpoints you mentioned (Endpoint URLs changing, ...) not an issue any more.

# Why Cloudformation

With regards to Cloudformation we definitely want to keep resources in CF, for various reasons:

1. Easier to deploy a completely new stack as all resources are handled as one and can be removed as one.
2. It is much easier to integrate any changes AWS is doing because the CF team takes care of maintaining that integration to the different other services.
3. Extending or overwriting resources is possible. If we start going through the API and setting up infrastructure it is much harder or nearly impossible for users to have very tight control through custom resources on how to set up their infrastructure. This would be an absolute no-go for many larger companies we're talking to. With CF templates they have complete insight what is going to be deployed, even before we actually deploy it.
4. It would make our Code much much more complicated. V0.5 went through the API to configure resources and it was a constant Pain. That was one of the main reasons why we decided to reimplement the whole tool with V1 when I came on. The old system of maintaining resources independently through the API was not maintainable. In contrast right now adding new features to Serverless that extend the infrastructure is relatively simple as you simply overwrite resources or add to the CF stack that will be deployed. A few unit tests and everything is covered as you don't have to deal with requests to AWS, have to hand over the final ARNs to other parts of the system or build systems to have some consistency over your infrastructure.

# Infrastructure challenges we need to solve

Building a Serverless architecture has a lot of challenges though. Basically its a micro-service architecture on Steroids. We introduced the service concept 

* Inter-service communication: When we start building lots of independent services one of the big questions is how do they communicate with each other and update the frontend of the application. This is the same problem you generally have in Micro-service infrastructure, with the added component that every function could essentially be seen as its own  service. Currently I think that we should go towards a setup where you can easily send sync or async messages to services (through SNS for example, or other similar services) and get a response. All that message passing is handled in an SDK that you include in your service and use. The endpoints can of course also talk through an API Gateway via HTTP in addition to more direct async message passing.

* Entry points to your services: API Gateway provides a very convenient way to set up publicly facing Endpoints, the downside though is that they are always public and can't be run inside a VPC (https://aws.amazon.com/api-gateway/faqs/). While you can verify that requests are coming from a specific source, this is still a massive issue and API Gateway should therefore only be used for actually public facing API's and everything behind the public API Gateway should be done with inter-service communication and through VPC's.

Currently I'm thinking about different ways we can potentially solve this, e.g. automatically setting up infrastructure like SNS topics you can communicate through to lambda functions, directly calling functions through the AWS API or other potential solutions.

On top of that we need to have good service discovery, so e.g. you have one service that is the public frontend of your application, but if you change the URL of a backend application that will be reflected quickly in the frontend part of the infrastructure as well. One idea there would be nested stacks, e.g. when deploying a stack you push the template to a specific bucket, but then instead of deploying there directly you also ping a parent stack with the updated template that will then redeploy the main stack with APIG and also the application you just deployed. Now this definitely starts to get complicated but we have to find good answers to this to make large and complex serverless services viable.

**Comment by kennu** [comment]
I think the basic challenge here is trying to support two approaches simultaneously:
- small services that mainly need convenience, agility and simplicity
- big services that need more control and security at cost of convenience, agility and simplicity

IMHO decisions like using CloudFormation for everything, adding SNS connections, requiring VPCs etc. will improve the latter at the cost of the former. This will work up to a point, but eventually the path leads to choosing simpler alternatives for small services and leaving Serverless as the solution for larger services. Perhaps this is in fact the goal and there's nothing wrong with that.

**Comment by kennu** [comment]
One more thought also came to mind. I think Amazon makes using CloudFormation in AWS optional exactly for the reason that they want to support a wide range of use cases. Developers can start by picking the simplest AWS building blocks and then expand as needed.

If AWS in general would require a CloudFormation template for every project (and force developers to interact through CF updates instead of AWS Console or CLI), it would make development very jarring, because CF is designed more for ops than dev.

This being said, I found the Serverless 0.x approach of storing basic resources (mainly IAM roles and policies) in CloudFormation quite convenient. The main difference was that you only had to update the CF stack very infrequently, when making changes to IAM policies or adding new resources. It was easy to re-create the whole stack if needed and it didn't hinder day-to-day development in any way. A kind of a best-of-both-worlds solution.

**Comment by flomotlik** [comment]
I agree that its a balance that we need to make happen to on the one side use good defaults so you can make implementing small services (although I think the better term would be smaller companies) use Serverless, but at the same time also make Serverless usable by large companies and enterprises that have very stringent security and control requirements.

But I do think Serverless should promote good defaults and best practices, e.g. not having too many API Gateways for every small service as it will make all of your services public to the world. While that might be convenient, its not something we should promote imho. 

>If AWS in general would require a CloudFormation template for every project (and force developers to interact through CF updates instead of AWS Console or CLI), it would make development very jarring, because CF is designed more for ops than dev.

This is true, but AWS is a multi-billion dollar company with thousands of developers maintaining all this. We can't replicate this easily and the former implementation of going through the API was a huge blocker for many features and for contributions.

We should absolutely keep the conversation on how best to use CF open, find different ways to make this better (e.g. nested stacks), but I just want to make it very clear (so there are no misunderstandings) that we have no intention of moving away from CF. I don't want this to be understood as killing the conversation about it, just want to make our point of view clear so there are no misunderstandings.

**Comment by kennu** [comment]
I have faced the same discussion/debate before in some other projects, and later on the proponents of "CloudFormation for everything" approach have faced the inconveniences that I have mentioned. :-) But they are of course not insurmountable and it's not a black and white thing, and also the AWS platform evolves. I am just a little pessimistic because CF hasn't evolved much into the more flexible dev direction in the past years.

Nested stacks certainly sounds like an opportunity to create one very permanent CloudFormation stack, and then keep the more dynamic stuff inside it as substacks. This could go hand-in-hand with some kind of Serverless versioning policy to support the outer CF stack layout "forever", so you'd never have to delete it.

You could safely keep your API Gateway endpoints (and perhaps even S3 buckets and DynamoDB tables) in the "permanent" stack when upgrading Serverless. Also during daily development you wouldn't have to update the "permanent" stack, with risk of it entering a failed state and requiring deletion. All resources of the "permanent" stack could then have a DeletionPolicy of Retain, so they'd never get deleted by accident.  Perhaps this has already been discussed under other issues.

Btw, in my view, one simple feature in AWS CloudFormation would make all this much easier. They should make it possible to attach and detach individual resources to and from CloudFormation stacks. You could then manually detach a resource, safely perform an upgrade without having to delete that resource, and afterwards reattach the resource. This would also make development so much easier and let dev+ops people work happily together.

**Comment by dougmoscrop** [comment]
https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/ might help

**Comment by chris-hailstorm** [comment]
Having the public URL of a service change after it's deployed is bad. There has to be a way to refer to the same service/stage (dev, test, prod) consistently over its lifecycle. There are cases where a developer may choose to abandon a URL, or have one URL for v1 and another for v2, but that's his choice -- should never be a side-effect of redeploying or rebuilding a service.

If it can happen, then it forces us to set up another level of API gateway (we use Kong) to patch over these changes on the AWS side, but that's clunky.  The URL needs to be a permanent ID.

**Comment by AndrewFarley** [comment]
I'm facing some issued related to this bug as well, and wanted to +1 on what @dougmoscrop said above.  I firmly believe the solution to this lies in using a decoupled cloudformation approach with cross-stack referencing.  This would effectively decouple the CloudFormation stacks and allow you to _never_ change certain stacks that need to always remain constant (like the API Gateway) and then simply refer to that stack in your other stack(s).  Now that Amazon has made this decoupling possible through cross-stack references, I've started migrating all my clients to this type of mechanism.  It makes updating complex environments much simpler since they are broken up into small stacks, not _one massive CF_ and it helps avoid the problem that is described in this bug.

**Comment by ryansb** [comment]
I'm of the opinion that this is not a bug: the stack (whole project) is *removed* so it wouldn't make sense to retain the API Gateway anyway. If you need a persistent URL, then don't delete your stack. The framework doesn't take any actions that cause a replacement of the API Gateway except for deleting it when the user deletes their stage.


Fortunately this is no longer an issue because API Gateway now supports ACM certs :tada: and custom domains can be created in API gateway, then connected to your service. Add this to your resource section, and you're good to go. Add this to `resources` to map your stage to a domain that's in a var called "devDomainName" or "prodDomainName", or whatever name the stage has.

```
resources:
  Resources:
    CustomDomainMap:
      Type: "AWS::ApiGateway::BasePathMapping"
      Properties:
        DomainName: ${self:custom.${opt:stage, self:provider.stage}DomainName}
        Stage:${opt:stage, self:provider.stage}
        RestApiId: {Ref: ApiGatewayRestApi}
```

So you do need to do the ACM/custom domain tangl outside CloudFormation in the API Gateway console (no CFN resource for it yet). 

I'd say it's ok to close this issue now, since external service discovery or custom domains solve this, depending on use case.

**Comment by kennu** [comment]
I have also switched to using the awesome new custom domains with ACM certs, so I'll close this.

**Comment by kennu** [comment]
Btw, to add to @ryansb's guide, if you have problems with dependencies, try adding at least one API key and a DependsOn like this to force the deployment order:

    BasePath:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn: ApiGatewayApiKey1
      Properties:
        DomainName: ${self:provider.environment.SERVICE_DOMAIN}
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${self:custom.stage}
 
(Re: https://github.com/serverless/serverless/issues/2233)

**Comment by pmuens** [comment]
Thanks for the in-depth response and guides @ryansb and @kennu 👍

**Comment by ryansb** [comment]
@kennu out of curiosity, what dependency/deploy order do you need? The `Ref: ApiGatewayRestApi` already introduces a dependency on the API Gateway itself, so you shouldn't need a dep on any API subresources.

**Comment by kennu** [comment]
@ryansb The problem happens to me when deploying a new service from scratch, where `sls deploy` shows this error, apparently because no `AWS::ApiGateway::Deployment` has yet been created:

    Serverless Error ---------------------------------------
 
       An error occurred while provisioning your stack: BasePath
       - Invalid stage identifier specified.

By adding the dummy API key and the dependency to it, the BasePathMapping is only created after the first deployment has been created.

This problem does not occur if you have already deployed the service/stage once, before adding the BasePathMapping resource.

**Comment by StevenACoffman** [comment]
Sorry to comment on old, closed issues. Is there a gist, or example repo where the  "ACM/custom domain tangle outside CloudFormation in the API Gateway console" is explained in more detail?

**Comment by kamilpp** [comment]
@StevenACoffman it is not what you are asking exactly but should help.

Steps to set up a custom domain for a serverless project. I assume using only AWS services and provide CloudFormation examples.

1. Setup a Hosted Zone in `Route53` and validate it:

```
  CustomDomainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: mydomain.com
```

2. Create certificate for the domain e.g. let's make it wildcard `*.mydomain.com` in `Certificate Manager`. **It has to be created in `us-east-1` region**, doesn't matter where you deploy other resources. For the validation you may need to configure `WorkMail` for the hosted zone.

```
  CustomDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: '*.mydomain.com'
```

3. Create custom domain name in `API Gateway`. Let's create a subdomain actually:

```
  CustomDomainGatewayEntry:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: arn:aws:acm:us-east-1:...  # here put your certificate ARN from step 2
      DomainName: sub.mydomain.com
```

4. Associate custom domain with `CloudFront` distribution:

```
 CustomDomainDnsCloudFrontDistributionRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: sub.mydomain.com.
      AliasTarget:
        DNSName: {Fn::GetAtt: [ CustomDomainGatewayEntry, DistributionDomainName ]}
        HostedZoneId: Z2FDTNDATAQYW2  # this is required and fixed, just paste it
      HostedZoneName: sub.mydomain.com
```

5. Finally set up custom domain mapping:

```
  CustomDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: CustomDomainGatewayEntry
    Properties:
      DomainName: sub.mydomain.com
      RestApiId: {Ref: ApiGatewayRestApi}
      Stage: ${self:provider.stage}
```

I did first 2 steps manually as they require some manual verification.
Steps 3-5 I have placed in my serverless resources config. In fact you could use them in many serverless projects if specifying another subdomains without the need to repeat steps 1-2. 

Now you can query your endpoints using: `https://sub.mydomain.com/myendpoint` instead of `https://sa92random13123.execute-api.eu-west-1.amazonaws.com/stage/myendpoint`.

**Comment by pmuens** [comment]
Thanks for this very helpful step-by-step guide @kamilpp! 🥇👍

**Comment by mayankiiitm** [comment]
Is there any way to automate it? @kamilpp

**Comment by liftyourgame** [comment]
I just got @kamilpp 's stuff working myself:

1. In step 4 HostedZoneId is hard coded because it is for the 'cloudfront.net' domain itself and not your own domain name.
2. Also step 4 HostedZoneName should not have 'sub', just mydomain.com. equivalent. Should also have a trailing dot.

Here is my resources section from serverless.yml:

resources:
  Resources:
    CustomDomainGatewayEntry:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn:         arn:aws:acm:us-east-1:XXXXXXXXXXX:certificate/YY
YYYYYYY
        DomainName: my-services.DOMAIN.com

    CustomDomainDnsCloudFrontDistributionRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Type: A
        Name: my-services.DOMAIN.com.
        AliasTarget:
          DNSName: {Fn::GetAtt: [ CustomDomainGatewayEntry, DistributionDomainName ]}
          HostedZoneId: Z2FDTNDATAQYW2

        HostedZoneName: DOMAIN.com.

    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn: CustomDomainGatewayEntry
      Properties:
        DomainName: my-services.DOMAIN.com
        RestApiId: {Ref: ApiGatewayRestApi}
        Stage: ${self:provider.stage}

**Comment by kamilpp** [comment]
@mayankiiitm I was working on this a year ago and finished with that project so I am not certain how it could be currently improved. Steps 1-2 were manual but steps 3-5 were enough "automated" as for my needs (perhaps a plugin would be more friendly but I don't know if such exists).
 
Good luck :)
