### ISSUE TITLE
Initial deployment only creates Stack and nothing else

### ISSUE THREAD

**Issue by pmuilu** [serverless/serverless#2114]
Version: 1.0rc1
	
	14:15:27 UTC+0300	CREATE_COMPLETE	AWS::CloudFormation::Stack	prod	
	14:15:20 UTC+0300	CREATE_COMPLETE	AWS::S3::Bucket	ServerlessDeploymentBucket	
	14:14:59 UTC+0300	CREATE_IN_PROGRESS	AWS::S3::Bucket	ServerlessDeploymentBucket	Resource creation Initiated
	14:14:59 UTC+0300	CREATE_IN_PROGRESS	AWS::S3::Bucket	ServerlessDeploymentBucket	
	14:14:55 UTC+0300	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	prod	User Initiated

Now, the next deploy will work as expected and update functions et al. 

I think this worked fine in beta2.

**Comment by flomotlik** [comment]
The deployment of Serverless is split into 2 steps, first create of the stack and then a separate update step that deploys the whole infrastructure.

I'm not sure what the issue here is specifically as the Issue doesn't have enough info. Could you please follow our Issue template to provide all the necessary data for us to really understand what the issue is. I'm going to close here until then, but please update again and ping so we can look into this if its an issue.

**Comment by marjanSterjev** [comment]
@pmuilu
Hi, please check your computer clock and adjust it if needed. I had a similar problem because my clock was ahead compared with AWS CF event timestamps.

**Comment by pmuilu** [comment]
Thanks! Ok if this is by design, then it's fine. I expected it to deploy everything at once.

**Comment by flomotlik** [comment]
@pmuilu we have to deploy in two steps as we have to create the S3 bucket first that we use for the later deployment stages, then upload the artifacts into the S3 bucket and then deploy a stack update so the CF template can reference files in that S3 bucket. Its a bit of a PITA, but no way around it at the moment.
