### ISSUE TITLE
Some tests return a reject but won't break the overall tests

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2115]
# This is a "Bug Report"
## Description

If one runs `npm test` all our unit tests are run. However if you look closely at the output you can 
see some rejection printings (See screenshot below).

<img width="597" alt="bildschirmfoto 2016-09-13 um 13 53 55" src="https://cloud.githubusercontent.com/assets/1606004/18472922/6d3dde78-79ba-11e6-992d-1fc1748e87c4.png">

/cc @flomotlik @eahefnawy

**Comment by eahefnawy** [comment]
@pmuens I noticed this before and I investigated, it's not really a failure from our core code base, it's actually a **mocked failure in the unit tests** due to `--noDeploy` tests.

**Comment by pmuens** [comment]
Interesting. Should we do anything about it soon?

BTW. Could you point me to the tests which are causing this mocked failure? Thanks!

**Comment by eahefnawy** [comment]
Something going on [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/tests/monitorStack.js#L235-L246) and [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/tests/monitorStack.js#L275-L279)

**Comment by rowanu** [comment]
Just to add to this issue since I've been looking at those tests (for PR #2125 to address #2087) - this functionality seems to assume that `sls` will see all the CFN events (specifically the failures) but depending on the polling interval some events may be missed, meaning `sls` doesn't actually know why a stack has failed.

I basically want to question the value of these tests, so if they're also causing other issues they might be eligible for removal (due to lack of ROI).

**Comment by flomotlik** [comment]
@pmuens whats the status of this?

**Comment by pmuens** [comment]
I talked with @eahefnawy about this and it's not a problem as far as I remember.

It's a Promise problem. Maybe @eahefnawy can explain why this happens.
