### ISSUE TITLE
Packaging Dependencies/Common Code

### ISSUE THREAD

**Issue by scott-wood-vgh** [serverless/serverless#2199]
# This is a Bug Report

## Description

I have several AWS Lambda functions in Serverless, and found I was writing the same sendEmail function over and over - just setting up the client and composing the SES response with a few minor tweaks. I decided it would be best to abstract this to a single function that is called by the others. My folder structure resembles:

Serverless
-----> Commons
-----------> sendEmail.py
-----> AlarmsManager
---------> Alarm1.py
---------> Alarm2.py 
---------> serverless.yml
-----> BackupManager
---------> Backup1.py
---------> Backup2.py 
---------> serverless.yml

My question is, how do I include this sendEmail function in other deployments? I've tried including a fully-qualified path to it in the calling function's serverless.yml file (which already has the proper SES IAM permissions), but the resulting CloudFormation template is built without it as if it never existed. I've also tried pasting the sendEmail.py file in the same deployment folder (not ideal obviously), but it is similarly ignored. It doesn't have a function nor a handler (nor should it). How do I include this and other dependencies in serverless.yml? RE: raising this as a bug, should the deployment not fail if it can't find a file I've specified to include?

For bug reports:
* What went wrong?

CloudFormation template built and did not include sendEmail.py

* What did you expect should have happened?

Failure should have been logged as an error if the file could not be found/added

* What was the config you used?

My serverless.yml
```
service: Ec2Monitor
provider:
  name: aws
  runtime: python2.7
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:DescribeInstanceStatus"
        - "ses:SendEmail"
      Resource: "*"

package:
  include:
    - Serverless/Ec2Monitor/monitorEc2Events.py
    - Serverless/Commons/sendEmail.py

functions:
  monitorEc2Events:
    handler: monitorEc2Events.monitorEc2Events
    description: "Monitors the status of EC2 Events daily."
    memorySize: 256
    timeout: 300
    events:
      - schedule: cron(0 12 * * ? *)```

* What stacktrace or error message from your provider did you see?

N/A

## Additional Data

* ***Serverless Framework Version you're using***:

1.0.0

* ***Operating System***:

Mac OS X

**Comment by rowanu** [comment]
How are you verifying the code is not being included? Individual code files will never appear in the CloudFormation template - they are packaged up in your function zip and uploaded to S3. You can verify the package deployment with the `serverless deploy --noDeploy` command and checking the package zip file in the `.serverless/` directory. Can you please check that?

If you don't see `sendEmail.py` in your package file, could you please format your snippets using the "code" formatting (by putting "```" around your YAML and code snippets - see the [formatting guide](https://guides.github.com/features/mastering-markdown/) for more info). Since whitespace is significant in YAML it may be the cause of your issue, but I can't tell at the moment.

For other/future readers, please log support requests/questions like this in [the Serverless Forum](http://forum.serverless.com/).

**Comment by RomeLeader** [comment]
@rowanu I was checking the code by downloading the .zip from S3 and extracting. Using noDeploy is a good idea to save me some time in testing, thanks for that. 

I'm fairly sure my whitespace is not the problem since the template/Lambda function is otherwise deployed fine, but I will make the appropriate edits to make it more clear.

My apologies for posting as an issue - I had also reached out to the forum for support but have not heard back in a couple of days. I do think it deserves some bug attention if a template can be created without error and miss including a file entirely - perhaps some logging could be added.

**Comment by rowanu** [comment]
Thanks for formatting that. No worries about opening the issue - just that the forum is more suited for this trouble-shooting back-and-forth.

Can you try referring to the files that are outside of the service directory using relative paths? It's not something I've tried but it might "just work" i.e. in your `serverless.yml`:

```yaml
package:
  include:
    - ../Ec2Monitor/monitorEc2Events.py
    - ../Commons/sendEmail.py
```

Including files from outside your service directory is not a common thing, and I'm not sure if it is - or should be - supported.

If you want to share code you should create a module and then list it as a dependency in your code so that it's clearly defined and can be detected if missing by your package/dependency management tool. In your current setup, if you `Commons` directory is deleted your services will stop working even though nothing has changed in them and all of their dependencies (as far as they are aware) are installed, which is not ideal.

**Comment by scott-wood-vgh** [comment]
@rowanu This didn't work for me. I tried a manual ZIP of these files and confirmed it worked, so my bottleneck is definitely with Serverless. I think you are right in that the main issue is that including files from outside the service directory is not supported, however the trail of deleted documentation regarding 'magic handlers' to fix this has not helped in trying to diagnose this issue and how I might work around it, if at all. Do you know what purpose magic handlers used to serve (as per the resolution here: https://github.com/serverless/serverless/issues/642) and whether this functionality is at all present in the current release?

**Comment by rowanu** [comment]
Serverless  v1.x is a complete rewrite, so docs and issues for v0.x are basically irrelevant. It seems like the functionality you want is just not available in v1.x.

I think your options are to do the packaging of shared code, or create a feature proposal; This isn't really a big as such.

**Comment by eL0ck** [comment]
Hi @scott-wood-vgh ,  I use serverless to deploy python functions also.  My service has simple functions which requires very few imports and other complex data processing functions which use many scientific python modules managed by [conda environments](http://conda.pydata.org/miniconda.html).  In some cases they include compiled shared object libraries too. 

The largest of the functions almost reach the lambda zip size limits so I need to be selective about what gets included and excluded for each function.

Serverless v0.5.x and v1.0 both meet my needs on this.  I'll write a more detailed description on your forum post.

P.S It may be worth clarifying what you mean by the word 'deployment'.  As far as I can tell you are using it to mean '[Service](https://serverless.com/framework/docs/#services)' as defined in the Serverless docs. Do I misunderstand?

**Comment by eL0ck** [comment]
Regarding 'magic handlers' references by @eahefnawy in #642:

The service design pattern has changed since v0.5.x  I'm not the right person to elaborate on it.  Nonetheless I did use 'magic handlers' to gain access to common code and shared objects with v0.5.x.  In the end I used symlinks instead.  Symlinks are clean and and clear.  They still work in v1.0.0

[Here is the forum response](http://forum.serverless.com/t/sharing-common-functions-in-deployment/345/2?u=el0ck)

**Comment by scott-wood-vgh** [comment]
@eL0ck Thanks for the follow-up and extra info! Your experience definitely sounds similar to mine - though I'm reluctant to use a single service for purposes of separating responsibilities. The symlink approach was a simplification I hadn't considered, I'll look further into doing that. When I said "deployment", I was indeed talking about a single service being deployed with Serverless.

I'll close this issue as I think I now have enough to go - I'll open a feature request should I be able to further characterize a need to support a more general feature for this, but I think I can now conceive a path of least resistance into coupling the code I want together with the service. Thanks again!
