### ISSUE TITLE
Use stdin for serverless invoke

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#2211]
# This is a Feature Proposal
### Problem

You can't currently create dynamic test data for testing your functions with.  Instead you have to keep updating `event.json`.  

For example, if you have a `usersCreate` function that has a unique email address rule, you will have to update `event.json` before every `sls invoke` to add in a new email address.  This is slow, tedious and makes automation difficult.
### Solution

Optionally support `event.js`.  The Framework should detect this and if it exists, pass in the function name, stage and region as params.  Then code can be written in `event.js` to return whatever dynamic data is necessary.

**Comment by eahefnawy** [comment]
I've faced a similar issue, and I thought maybe `event.json` should be an object in `serverless.yml` to make use of the variable system. Much easier to implement with less boilerplate (we can always use file references), but not sure it'd completely solve your issue since it's not super dynamic (you can only go as far as our variable system goes)

**Comment by eahefnawy** [comment]
Generally speaking though, what do you think about managing config in `.js` files? I just realized that if `serverless.yml` was `serverless.js`, we wouldn't need our variable system at all and we'd have much more flexibility/versatility 😜

**Comment by dougmoscrop** [comment]
What about being able to take event data from stdin instead?

I feel like rather than having serverless call external code you could make serverless [accessible programmatically](https://github.com/serverless/serverless/issues/1678) for advanced use cases that can't be covered by reading from stdin. Most CLI tools (mocha, for example) can be required() and called with arguments that basically match whatever the CLI gets.

`CLI > Parse > new Serverless()`
vs
`stress-test.js > new Serverless()`

This also keeps your core a bit smaller

**Comment by mthenw** [comment]
+1000 for supporting stdin

```
echo "{}" | serverless invoke
```

**Comment by flomotlik** [comment]
Yup I think STDIN is would be a good first option to implement this as its easy and it allows us to support any language. `events.js` would be very Node specific and I think we should build this in a way that is easy for any language (or any tool).

If that is not sufficient for users we can still think about more complex ways to allow people to have dynamic data imho. I'm currently not sure if we should read from STDIN by default if the `--path` option isn't set, or if users have to specifically configure that we should read from STDIN:

Configure to read from STDIN
```
echo "{}" | serverless invoke --path -
```

Without --path config we can read automatically from STDIN
```
echo "{}" | serverless invoke
```
