### ISSUE TITLE
 serverless v1,  how to send environment variable

### ISSUE THREAD

**Issue by josh9254** [serverless/serverless#2219]
I have a project with python & serverless v1,

I need to send environment variables from serverless.yml to somefile.py

how i can do this???

**Comment by rowanu** [comment]
Please follow #1455.

**Comment by colbywhite** [comment]
@josh9254 #1455 is the magic ticket for this stuff. 

Since I see this get asked a lot in the gitter, allow me to attempt to provide a TLDR.

- it's not possible directly in v1. I'm not sure what the plan is for #1455 
- many of the JS folks use webpack to get around this
- there is also the [](https://github.com/silvermine/serverless-plugin-write-env-vars) plugin which uses the npm [dotenv](https://github.com/motdotla/dotenv) module.
- for us python folks, i don't believe there is anything for us. I have been saying for a couple weeks that I want to make a plugin based around the python version of [dotenv](https://github.com/theskumar/python-dotenv), although I'm not sure how used that is. I hope to get around to it by November, but #1455 might have more light around it by then.

**Comment by colbywhite** [comment]
For future reference, after playing a bit with dotenv, the python version works the same way. so no need for a python-specific plugin. So @josh9254, take a look at the env-vars plugin linked above. It will work around this until a plan is thought of for #1455 .

**Comment by flomotlik** [comment]
Closing issue. We're also working on something new that will help here in the future.

**Comment by rboarman** [comment]
Can someone please confirm for me how to get the stage from within my python function? 

This used to work:

stage = os.getenv('SERVERLESS_STAGE')

Thanks!

**Comment by flomotlik** [comment]
@rboarman at the moment we don't automatically expose the stage as environment variables any more. This is a super important feature for us and we're working with AWS to bring this back in a great way at some point.
