### ISSUE TITLE
Investigate Test timeouts

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2225]
# This is a Bug Report
## Description

the following test failed with a timeout:

```
 1) createStack "before each" hook for "should resolve if stack already created":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

It simply shouldn't fail due to a timeout because it shouldn't really take that long. We need to investigate if we have timing issues in our tests.

Similar or dependent issues:
- 
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by dougmoscrop** [comment]
I'm not sure if [this bug](https://github.com/serverless/serverless/pull/2204) could have caused it -- the 'test code' for that would have run, but not as part of any test itself, and since it's an execSync it would have blocked the loop for ~2+ seconds (as you saw yesterday sometimes the integration tests were failing at a 2s timeout).

Of course if this happened after the merge then nevermind :D

**Comment by pmuens** [comment]
This was merged recently with a change which set the timeouts to 0.
