### ISSUE TITLE
Not possible to create resources that depend on the ApiGateway::Deployment

### ISSUE THREAD

**Issue by alexanderbh** [serverless/serverless#2233]
# This is a Bug Report
## Description

For bug reports:
- What went wrong?

I am creating a custom resource `AWS::ApiGateway::BasePathMapping` like this:

```
pathmapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
        BasePath: oauth2
        DomainName: ${self:custom.domainName}
        RestApiId: 
          Ref: ApiGatewayRestApi
        Stage: ${self:custom.stage}
```

But the Cloudformation stack fails. It fails because the BasePathMapping requires the API to be deployed but it does not depend on the `AWS::ApiGateway::Deployment`
- What did you expect should have happened?

The cloudformation stack should not fail. The BasePathMapping should be able to depend on the Deployment.
- What was the config you used?

Serverless RC2
- What stacktrace or error message from your provider did you see?

> Invalid stage identifier specified
## Additional Data
- **_Serverless Framework Version you're using**_: RC2
- **_Operating System**_: Mac OS X
- **_Stack Trace**_: None. The cloudformation stack is fine but fails to update.
- **_Provider Error messages**_:

This is the error from CloudFormation when creating the BasePathMapping

> Invalid stage identifier specified
## Workaround

It is not possible to DependsOn the deployment because the logical name of the deployment contains a random number (based on the time in ms).

I just tried to copy the entire cloudformation stack json and change the logical name of the deployment to ApiGatewayDeployment and then make my BasePathMapping DependsOn that and now it works.

This is not a good workaround because it defeats the purpose of sls.

The way I got around it to depend on an ApiKey since they are named with a sequental number.
So I create an ApiKey in the provider section:

```
provider:
    apiKeys:
        - workaroundkey
```

And then I can make my BasePathMapping depend on this:

```
pathmapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ApiGatewayApiKey1
    Properties:
        BasePath: oauth2
        DomainName: ${self:custom.domainName}
        RestApiId: 
          Ref: ApiGatewayRestApi
        Stage: ${self:custom.stage}
```
### Regression

The unique number was introduced in https://github.com/serverless/serverless/pull/1761

Before that it was possible to DependsOn the logical name of the Deployment.

**Comment by alexanderbh** [comment]
The unique number was introduced in https://github.com/serverless/serverless/pull/1761

Before that it was possible to DependsOn the logical name of the Deployment.

**Comment by flomotlik** [comment]
thanks @alexanderbh for reporting. The main problem is we need to append a random number to the deployment, otherwise on the next deployment nothing happens and the API updates don't get deployed (you can test that locally when removing the random part).

The only real way I see at the moment to do this would be using a Cloudformation Mapping and storing the random number in that Cloudformation Mapping: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html

This way you could depend on it because you get the value for the ref out of the mapping.

**Comment by alexanderbh** [comment]
Yeah that is what I got from the earlier talks relating to the random number.

I am gonna try to add the mapping to the stack and see how that works. If I get it to work I will make a pull request.

**Comment by alexanderbh** [comment]
It is not possible to use a function in DependsOn. DependsOn must be a string or a list of strings. I had made the mapping solution but it does not work when I try to use the Fn::FindInMap as DependsOn.

I am going to try to fix the force-redeploy instead. It would be more clean to remove the random number than working around it with maps.

**Comment by dougmoscrop** [comment]
Another workaround would be generating this 'random slug' at command invoke time, so it's available in serverless.yml for expansion. 

DependsOn: 'ApiGatewayDeployment${slug}'

**Comment by jacob-meacham** [comment]
I just published a serverless plugin that essentially allows what @dougmoscrop describes - it lets you bind the dynamic deployment id to your custom resources at runtime. You can find the plugin here: https://github.com/jacob-meacham/serverless-plugin-bind-deployment-id

**Comment by simoami** [comment]
@flomotlik @alexanderbh 
Because the random number is an internal workaround, potentially a just a temporary one, I doesn't make sense to expose it for us to use in serverless.yml to employ it as @dougmoscrop suggests. What I suggest instead is to scan through references of `ApiGatewayDeployment`, e.g. `DependsOn: ApiGatewayDeployment` inside yaml files and append the random number. This way it remains transparent to users and doesn't introduce breaking changes if the random number workaround is eliminated, in light of a better solution.

**Comment by jacob-meacham** [comment]
@simoami 
Indeed, that's what the plugin does, and if the workaround is removed, would continue to work, because it would pick up the new naming convention of the `ApiGatewayDeployment`. I did choose to look for a sentinel value (by default `__deployment__`) and replace it entirely with the deployment id, rather than only appending the random number onto `ApiGatewayDeployment`, since the name `ApiGatewayDeployment` could also potentially change in the future. Using a non-standard sentinel value also makes it clear that there is some magic going on. Of course, I added a hook to change the sentinel value, so you could very easily set it to `ApiGatewayDeployment` and everything would work as you describe. You can change the sentinel value with:

```yaml
custom:
  deploymentId:
    variableSyntax: ApiGatewayDeployment
 ```

**Comment by simoami** [comment]
@jacob-meacham Thanks for the plugin. I will be helpful in the short term. 

I wouldn't worry about hardcoding `ApiGatewayDeployment`. The plugin exists to address a very specific issue with serverless that affects a single template name. Because of the suggested sentinel value, the yaml file now has to include proprietary values to the resource definitions. Can it be optional as in only specifying the plugin name is enough by default?

**Comment by jacob-meacham** [comment]
Are you suggesting that I should change the sentinel value from `__deployment__` to `ApiGatewayDeployment`? I'd be open to doing so. 

You mentioned the pros of that approach: 
* the customResources in serverless.yml look like standard CloudFormation templates
* if/when this is no longer required in serverless, users can just remove the plugin and everything will continue to work. 

I think the cons are that it hides what's going on in a way I fear could bite people in a way similar to this issue. Using a clearly invalid key means that no one is fooled into thinking that `ApiGatewayDeployment` works on its own.

**Comment by polvoazul** [comment]
I like very much the idea of having an explicitly 'magical' sentinel value as a default. 
Jacob was kind enough to support changing it through configuration, so I don't see any problems with the current settings.

**Comment by simoami** [comment]
@jacob-meacham Now that I got some time to think about this, I have a suggestion for you. Your plugin could be made very useful if it supported a bunch of more magic values that are internal to serverless. including new ones that you generate, like uuid, random time number...etc. And so one can use: `${self:custom.magic.deploymentId}`, `${self:custom.magic.sequentialId` or `${self:custom.magic.uuid}`. In my opinion this would make the plugin extremely useful even outside of the current use case.

**Comment by FritzSG** [comment]
So I'm having a hell of a time with this issue. Has there been any progress on this front?

**Comment by lukeplausin** [comment]
Same here. +1 for @simoami's suggestion

**Comment by yvele** [comment]
Same problem here with `AWS::Serverless::Api` ([SAM](https://github.com/awslabs/serverless-application-model))

```yml
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Foo
  BasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      Stage: Foo
```

> **UPDATE_FAILED**	AWS::ApiGateway::BasePathMapping	BasePathMapping	Invalid stage identifier specified

**Comment by HyperBrain** [comment]
@yvele Do you have a AWS::ApiGateway::Stage resource in your stack that is named "Foo" ?
I'm quite sure that the BasePathMapping.Stage property can only reference a Stage resource, not a name. This is imo only possible with the Deployment resource.

**Comment by yvele** [comment]
@HyperBrain Isn't `AWS::Serverless::Api` supposed to **create** the `Foo` stage?

**Comment by HyperBrain** [comment]
As far as my experiments with that were, it does not (maybe implicitly within APIG, but not explicitly as AWS::ApiGateway::Stage resource in your stack).

**Comment by yvele** [comment]
@HyperBrain I just run the test an I confirm that `AWS::Serverless::Api` is successfully creating the the `Foo` stage.. But I'm not able to depend on it (neither implicitly nor explicitly via `depensOn`) .. 😭

**Comment by ajkerr** [comment]
Unfortunately, the handy plugin at https://github.com/jacob-meacham/serverless-plugin-bind-deployment-id is broken as of Serverless 1.12.

**Comment by HyperBrain** [comment]
@ajkerr Can you copy the actual error message here? It needs to be checked if the plugin tries to use or modify some internal state, or one of its hooks is wrong.

**Comment by ajkerr** [comment]
@HyperBrain Sure thing. Here's the error:
``` 
Serverless Error ---------------------------------------

Template format error: Unresolved resource dependencies
[__deployment__] in the Resources block of the template 
```

This error is actually coming from AWS, because the plugin didn't do what it intended to do, which was to replace __deployment__ with the actual generated deployment id.

The issue appears to be that the code is modifying internal state here: https://github.com/jacob-meacham/serverless-plugin-bind-deployment-id/blob/master/src/index.js#L28

This no longer seems to have any affect with the changes to the lifecycle hooks made in 1.12.

Perhaps there's another hook that can be plugged into earlier in the lifecycle, where modifying this value makes sense?

**Comment by HyperBrain** [comment]
I think the error is that the plugin operates on  `this.serverless.service.resources.Resources` instead of `this.serverless.service.provider.compiledCloudFormationTemplate`. Plugins should not modify the immutable service definition, but the mutable compiled template. I assume that at the time the plugin tries to modify the service definition, the compiled template already has been generated and serverless does continue with the compiled template for deployment.
See https://gist.github.com/HyperBrain/bba5c9698e92ac693bb461c99d6cfeec for the new events. I wonder that the plugin did not use one of the old deploy:XXX events to do the modifications, but just before:deploy:deploy.

**Comment by jacob-meacham** [comment]
@HyperBrain @ajkerr thanks for the feedback/suggestions - I'll take a look at this today and see if I can't get it working again.

**Comment by ajkerr** [comment]
@jacob-meacham I just updated the PR I submitted yesterday, and I think it's working properly now.

**Comment by schickling** [comment]
Any progress on this issue? My current workaround is commenting out the `AWS::ApiGateway::BasePathMapping` for the first deploy run and then commenting it in again.

**Comment by pmuens** [comment]
@schickling have you looked into https://github.com/jacob-meacham/serverless-plugin-bind-deployment-id which tackles this issue?

Unfortunately we had to do this "hack" so that API Gateway picks up the changes. Not sure if this quirk was fixed by AWS in the meantime 🤔

**Comment by Siyfion** [comment]
@pmuens I too am experiencing this issue for the "first" deployment, after that it's fine. But it's more than just a bit hacky and potentially very confusing to someone taking the project and trying to create their own deployment.

**Comment by flyinbutrs** [comment]
I set my basepathmappings dependent on CreateLambdaPermissionApiGateway, which seems to have worked, FWIW.

**Comment by talawahtech** [comment]
Is there any way to verify if this hack is still required or if it can be reversed now? Another side effect is that the Api Gateway Deployment is always updated every time the cloudformation stack is updated even if there are no api related changes

**Comment by pmuens** [comment]
@talawahtech thank for commenting 👍

Unfortunately this hack is still required. Have you tried the https://github.com/jacob-meacham/serverless-plugin-bind-deployment-id plugin to work around this?

**Comment by talawahtech** [comment]
@pmuens, thanks for you suggestion. I have been working around it by setting the DependsOn attribute to {FunctionName}LambdaPermissionApiGateway. I prefer this approach because I don't have to rely on a plug-in being kept up to date.

**Comment by pmuens** [comment]
> @pmuens, thanks for you suggestion. I have been working around it by setting the DependsOn attribute to {FunctionName}LambdaPermissionApiGateway. I prefer this approach because I don't have to rely on a plug-in being kept up to date.

Thanks for commenting a posting your solution @talawahtech 👍. Sounds like a good approach for now!

**Comment by stevenmwade** [comment]
@flyinbutrs Without some code, we don't know what `CreateLambdaPermissionApiGateway` refers to.

**Comment by stevenmwade** [comment]
@talawahtech That did not work for me.

**Comment by talawahtech** [comment]
@stevenmwade are you replacing {FunctionName} with normalized name of your function? You can confirm the actual name by searching for "LambdaPermissionApiGateway" in the auto-generated cloudformation template (cloudformation-template-update-stack.json) that serverless creates in the .serverless folder when you do a deploy.

**Comment by stevenmwade** [comment]
@talawahtech I did. Instead of failing at 25 seconds, it fails at 18 minutes and gives the same error.

**Comment by JBerges** [comment]
Just in case someone find some issues like me: I was not able to fix using @talawahtech solution but found something similar.
I finally added a DependsOn: [LambdaAPIDefinitionStage] in my 'AWS::ApiGateway::BasePathMapping' element. In my case, my 'AWS::Serverless::Api' element was called LambdaAPIDefinition.
Also, I was not able to locate the cloudformation-template-update-stack.json, but was able to find something that I understand is similar by going to AWS console > Cloudformation > (your stack) > other actions > view / edit template in Designer .
Thanks a lot @talawahtech, your comment allowed me to find a solution :)

**Comment by grvhi** [comment]
FWIW, another solution to this problem is to use the [additional stacks plugin](https://github.com/SC5/serverless-plugin-additional-stacks) and define your base path mappings (and route53 entries if necessary) as an additional stack, like this:

```
custom:
  additionalStacks:
    pathMappings:
      Deploy: After
      Resources:
          myDomainName:
              Type: AWS::ApiGateway::DomainName
              Properties:
                  DomainName: my-domain.com
          ssoDomainMapping:
              DependsOn: myDomainName
              Type: AWS::ApiGateway::BasePathMapping
              Properties:
                  DomainName: "Fn::GetAtt": "myDomainName.DomainName"
                  RestApiId:
                       "Fn::ImportValue": "api-gw-id-${self:provider.stage}"
                  Stage: ${self:provider.stage}
```
The `Deploy: After` line ensures that when calling `sls deploy`, this additional stack is deployed last, which means the API Gateway exists and can be referenced by the additional stack. Note that in my example, I've referenced an output from the main sls stack:
```
Outputs:
    APIGatewayID:
      Value:
        "Ref": ApiGatewayRestApi
      Export:
        Name: api-gw-id-${self:provider.stage}
```

**Comment by jplock** [comment]
Is the random number problem still an AWS issue?  Has anyone tried reverting that change to see if its easier to depend on the deployment?

**Comment by jplock** [comment]
I was able to make this work by adding:

```
DependsOn:
  - <LambdaNameGoesHere>LambdaPermissionApiGateway
```

to my `AWS::ApiGateway::BasePathMapping` resource creation

**Comment by Imran99** [comment]
The `xxxPermissionApiGateway` doesn't work reliably for me. The only way I was able to get this working reliably was by using the plugin.

**Comment by jaredkaczynski-agero** [comment]
You can use

DependsOn: 'ApiGatewayDeployment${sls:instanceId}'
