### ISSUE TITLE
Feature Proposal: CloudFormation file should be formatted as YAML instead of JSON

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2235]
# This is a Feature Proposal
## Description

Now that CloudFormation supports both JSON and YAML it would make sense for us to use YAML since it lines up better with the definitions in `serverless.yml`. To me the idea around this will help with debugging items like custom resources since you can use the examples from the CloudFormation documentation in `serverless.yml` and check them against the documentation once output. 

For feature proposals:
- What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
  Unify around one configuration language.
- If there is additional config how would it look

**Comment by screamish** [comment]
Would this mean that one could start using the new CFN Yaml functions such as

```!GetAtt logicalNameOfResource.attributeName```

when combining extra CFN resources in the `resources:` section of the serverless.yml?

**Comment by pmuens** [comment]
Hey @andymac4182 thanks for opening.

Right now we still stick to JSON since we'll parse it into a POJO anyway behind the scenes and JSON is more popular in AWS land (at least for now) than YAML.

@screamish unfortunately not still we're parsing the YAML into a POJO behind the scenes.

Closing this for now. Maybe we resurrect it once YAML in AWS land is more popular!
