### ISSUE TITLE
Fatal error on first setup and run, maybe root required to create tracking-id file

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#2248]
I successfully installed v1.0 on Ubuntu 15.50 with `sudo npm install -g serverless`, but when I run `serverless --version` I got:

    Error --------------------------------------------------
 
     EACCES: permission denied, open '/usr/lib/node_modules/serverless/lib/tracking-id'
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
    Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.

I though it may be Serverless trying to generate a `tracking-id` file in that position, so I tried `sudo serverless --version` instead, and it run fine. After that I can run it without root permissions, so I think my assumption was correct:

    $ sudo serverless --version
    1.0.0-rc.2
    $ serverless --version
    1.0.0-rc.2

**Comment by adimarco** [comment]
I experience the same problem with Ubuntu 14.04, also with `1.0.0-rc2` installed via the `npm install` method mentioned above.

Running `sudo serverless --version` fixes the problem.  After that I'm able to run `serverless create` as a non-root user.

**Comment by marcio0** [comment]
@adimarco solucion is weird but worked for me

**Comment by mthenw** [comment]
Hey, thanks for reporting. We changed the location of that file so it's no longer an issue. Please upgrade to v1.

**Comment by markvivanco** [comment]
I just installed v1.5 and I have to run servlerless as sudo otherwise I get permission denied on Ubuntu 16.04.  When I try to install serverless as a normal user I get the error below

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/serverless'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/serverless']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/serverless' }

/usr/local/lib is owned by root:staff

**Comment by pmuens** [comment]
Hey @markvivanco normally you shouldn't have to `sudo` to install and work with Serverless.

Have you updated from an older Serverless version or have you installed in the first time?

This might resolve your problem:
https://docs.npmjs.com/getting-started/fixing-npm-permissions
