### ISSUE TITLE
Error while deploying for the first time.

### ISSUE THREAD

**Issue by joshg111** [serverless/serverless#2284]
When I try to deploy for the first time I get the following error. 

This is on a windows 10 station. 
I'm using AWS. 
Everything I did I tried to follow the guide. 
I installed awscli for windows. 
Let me know if I'm missing something. 

 Error --------------------------------------------------

```
 ServerlessError: ServerlessError: Signature not yet
 current: 20161008T200637Z is still later than 20161008T195903Z
 (20161008T195403Z + 5 min.)

 For debugging logs, run again after setting SLS_DEBUG env var.
```

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

```
 Please report this error. We think it might be a bug.
```

**Comment by laardee** [comment]
I think that is an AWS error, check that the time is correct on your computer. https://forums.aws.amazon.com/thread.jspa?threadID=134543

**Comment by pouledodue** [comment]
what is the reasoning behind this requirement from aws?

**Comment by noogen** [comment]
This is not something unique to AWS.  Most modern auth system/platform does this, including Microsoft Azure.  

When accessing AWS, instead of sending your key and secret directly to the server, it use your key and secret  to sign an auth token that include timestamp and expiration.   This is why your local time must be in sync.  

This secure you from issue such as network sniffers, in a compromised network, to find your key and secret; instead, it will only find your token.  And even if it can find your token and log somewhere, the token has, hopefully, been expired by the time the hacker get to use it.

**Comment by mthenw** [comment]
Duplicate https://github.com/serverless/serverless/issues/2111.
