### ISSUE TITLE
feature request: add bucket triggers to info command

### ISSUE THREAD

**Issue by id0Sch** [serverless/serverless#2289]
# This is a Feature Proposal
## Description

For feature proposals:
- when showing the stack config, s3 triggers are missing.
  it would be nice to also should which buckets and events are being 'listened'

what do you think?

**Comment by pmuens** [comment]
Thanks for opening @id0Sch 

Closing this issue since we've pushed some changes to the `info` plugin which makes it easy to hook into them via external plugins. The core of the `info` plugin should be as slim as possible and only display the most relevant infos.

A separate `info` plugin which contains the logic for more event sources and other information could be a great extension here.
