### ISSUE TITLE
BREAKING - Unify API Gateway event object

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2298]
# This is a Feature Proposal
## Description

As @eahefnawy already mentioned: The API Gateway `event` property is slightly different when using the `lambda` integration in comparison to the `lambda-proxy` integration. It would be great if the event object of the `lambda` integration is exactly the same as the event object of the `lambda-proxy` integration so that people don't have to change code when they switch the integration types.

**Note:** This will introduce breaking changes for users.

/cc @flomotlik

**Comment by leonardoalifraco** [comment]
:+1:

Breaking changes are already there by having the lambda-proxy as default integration.

However, it's important to provide a prepared configuration or clear documentation to get the current lambda integration request template mapping.

**Comment by pmuens** [comment]
Closing this since it's quite stale and will result in a breaking change. Futhermore it's better to stick to the API contract AWS provides here to avoid confusion.

**Comment by VersBinarii** [comment]
Hello All,
Any chance you could reconsider this issue?

> Futhermore it's better to stick to the API contract AWS provides here to avoid confusion.

Please correct me if i'm wrong but it seems to me that the AWS documents the field as `queryStringParameters` in [here](https://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https.html)

'Serverless' is controlling the field by the default mapping templates [it provides](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js)

I understand breaking changes should be avoided as much as possible but not at the cost of correctness.
This issue is not too problematic when building stuff in Javascript however it becomes troublesome when Typescript is used as the types [defined](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/index.d.ts#L80) adhere to the AWS documentation.

**Comment by CoryKleiser** [comment]
@VersBinarii, thanks for the sanity check

The close reason is absurd. How about unify what AWS spits out and what we're receiving from serverless? I feel like disparate event types sow confusion rather than avoids it.
