### ISSUE TITLE
reduce S3 upload timeouts in uploadZipFile using a Stream

### ISSUE THREAD

**Issue by perl5punk** [serverless/serverless#2363]
# This is a Bug Report / Feature Proposal

This is actually a part bug and part feature proposal, on connections with slow upload speeds, a 17mb file regularly fails to upload to S3, in part this is due to the method in which the upload is being handled.

## Description

While this isn't a prominent issue at the moment, as file sizes increase it could become more problematic.

My suggestions is to change body to a stream (~line 34/41 in uploadArtifacts.js)
fs.createReadStream...  At the same time add options to adjust the partSize to stream smaller chucks so it's not choking bandwidth.

For bug reports:
* What went wrong?
Frequent deploy timeouts with large zip files on connections with slower upload speeds
* What did you expect should have happened?
Deploy should not timeout, and increasing the timeout is insufficient.  The upload works fine though the AWS console, the same result should be expected in the SLS CLI
* What was the config you used?
Normal
* What stacktrace or error message from your provider did you see?
N/A
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
Couldn't find any

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by doapp-ryanp** [comment]
@perl5punk why not submit a PR?

**Comment by rowanu** [comment]
Yeah, I don't think this is a framework problem; I have no timeouts uploading bigger files to S3.

Reducing chunk size is going to add more transmission overhead, so really this would just be optimising the transfer process for poor connections...

**Comment by andymac4182** [comment]
I have had this issue with high packet loss connections before or highly contended connections. It is rare for me though.

**Comment by pmuens** [comment]
That's an interesting one as we've switched form streams to plain zipped data for the reason to be multi provider support ready.

The main problem with streams is that currently only AWS supports the retrieval of streamed data. So in order to implement multi-provider support we need to stick to one way.

But this is still a bug which will remain if we stick to the current implementation...

/ccing @flomotlik and @eahefnawy here for other thoughts.

**Comment by flomotlik** [comment]
Thanks @perl5punk for bringing this up and laying out a potential solution. Definitely an issue, but imho one that would mean we have to introduce more complex code to fix it in situations that are rare and an issue in general anyway (slow, lossy connections).

Also reducing chunk size would be detrimental to fast connections and probably >95% of deployments happen with a fast enough connection (its probably >99%), so I don't think its something we can reasonably do.

With that in mind I'm going to close as I don't think we'll implement this. But if more reports come in definitely willing to take another look.

And just fyi to @doapp-ryanp question imho this is the exact way I would like issues to be raised before going into implementing the PR, because sometimes we get PRs without a prior Issue discussion and I sometimes have to say No or it has to be changed dramatically. So discussing the Issue first before working on PR is 👍  to me because I think its fundamentally faster over all opened issues.
