### ISSUE TITLE
Move Integration tests into Main repo and run on Master

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2377]
# This is a Feature Proposal
## Description

We recently worked on Integration tests in a separate repo: https://github.com/serverless/integration-test-suite

Those tests should be moved back into the main repository and run on every build on the master branch. This will allow us to detect issues with Serverless early and have an integration test suite that grows together with the codebase.

Without these integration tests in place the chances are that we will kill core features (e.g. #2359 )

Similar or dependent issues:
- 
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by pmuens** [comment]
Since we already have that in place in the separate repo why don't we keep it there and use https://docs.travis-ci.com/user/cron-jobs/ to trigger the build every night (or X times a day)?

This way we don't have to migrate everything and it's separated / reduces the code in the main repository.

**Comment by dougmoscrop** [comment]
You could also make the integration tests a *devDependency* of serverless and run them however often you want (`npm run integration-tests`) -- this makes me think of contract testing. It encourages not changing the contracts and the implementation at the same time by keeping them in separate locations.

FWIW you don't even have to publish them to npm, you can just add them as `github:serverless/integration-test-suite#some-tag`

**Comment by pmuens** [comment]
Thanks for your feedback @dougmoscrop!

@eahefnawy @flomotlik I've just updated the integration test repository so that the tests will pass again (except for the SNS tests). The API Gateway tests are now integration aware and nested into the corresponding directories. I've added a "Simple API Setup" test for the `lambda-proxy` integration.

@eahefnawy the SNS tests are failing. Don't know if it's the logging problem (where we had too many CloudWatch logs). Would be great if you could look into that.

This should make everything ready so that it can be moved into the main repo.

One other thought one can consider is to keep the integration tests in the dedicated repository and trigger them e.g. through the Travis CI API when the build in the main Serverless repo succeeds. This way the large integration test repo is only triggered when all of the unit tests and the small integration test in the main repo succeeds.

- https://hiddentao.com/archives/2016/08/29/triggering-travis-ci-build-from-another-projects-build/
- https://docs.travis-ci.com/user/triggering-builds

**Comment by flomotlik** [comment]
The main reason why I want to move them into the Main repository so there is no way we're starting to ignore it. I've seen this before where there was a different test repository and some tests start failing and because it isn't the main repository and isn't breaking the main build it starts getting ignored.

The build runs a few hours later maybe, but because everyone is busy it starts failing and getting ignored. This is an absolute no-go and I want to have the feedback loop between something getting merged to master and the tests telling us it failed to be smaller.

Moving integration tests can be something that we can do as an optimisation once the build takes too long or is otherwise a problem. But for now we should move

**Comment by dougmoscrop** [comment]
Yep! Just have to be diligent about not changing the tests while changing code :D

**Comment by flomotlik** [comment]
@dougmoscrop sure, but a change in an integration test will get a lot more scrutiny (or should at least) than other tests. But reviews in general have to be super strict.
