### ISSUE TITLE
Service Composition

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2481]
# This is a Discussion
## Description

Building a large event driven micro-service infrastructure with Serverless requires many decisions on how to compose your infrastructure. How do you want to split up services, do you deploy them individually or as one larger deployment, how should they talk to each other and ho are dependencies between them defined.
### Important questions to answer:
- What questions are there about Service composition we can answer through documentation
- Do users prefer docs, guides, blogposts, ebooks or a mix of all
- What are best practices users came across
- What features could we implement to support this
### Feature Ideas
- Define dependencies between services so a service can only be deployed if other services are deployed as well
- Dependency management so one service can set up others if necessary (which can be helpful for dev infrastructure
### Similar or dependent issues:
-

**Comment by chris-hailstorm** [comment]
A little philosophizing, since you said this issue is a discussion :)

I've been using Serverless for a short time and I'm impressed.  It's not quite mature enough yet, but it's already pretty useful.  The idea of specification-driven infrastructure (declarative instead of procedural steps) is powerful.  That's a lesson we learned originally from Hashicorp.

You're right to think about the micro-services endgame.  Composition --> Discovery --> Communication as the service environment gets more complex is where a lot of projects get lost.  But there's a danger in these topics for Serverless.  What you've done so far is simplify the act of deploying and running services on AWS -- valuable because (a) the native AWS approach is too complex, and (b) your users' goal is to create and exploit services, not master the arcana of 47 different AWS services.  Basically you removed a lot of negative-value technical friction.  But if you move into the big picture of what happens between micro-services, you'll be in a layer where people have many more opinions :).  Every team has its own ideas for notification vs. queues, naming conventions, how to do production upgrades and other things.  I don't think you can define a macro solution pattern that works broadly the way your micro solution does.

I'd encourage you to think in terms of two distinct problems -- (1) how to make development / testing / deployment / operation of individual services as awesome as possible -- solve that problem absolutely to death -- then later (2) how to address service discovery / composition / communication challenges.  You can't do (2) well without doing (1) exceedingly well first in any case, so you don't lose anything by maxing out (1).  And then those of us who don't really want a canned solution for (2) can continue to use the services framework with or without the macro.

Going back to Hashicorp.  They've done outstanding work, but in your area, like AWS, they're  too damn complicated.  I love the power and sheer intellectual brilliance of Atlas + Terraform but to use them effectively, you have to have a pretty strong understanding to start with.  In my opinion, the big strength of your approach is that a junior developer can install Serverless and start using it.  You can build up grass-roots style as a developer's knowledge expands, while the Hashicorp tools are only ever accessible to architect-level people. You can win a big chunk of the market by doing the micro-services layer very well. Plus, no one would take you seriously at the macro level if you didn't fully deliver on the original micro-services solution concept.

We love Serverless.  Please don't lose focus :)

**Comment by thenikso** [comment]
Every time I think of serverless/microservices in general I come back to this very question: *how do you compose?*

The problem has multiple sides:

- **service discovery/communication** with Serverless/API Gateway one already has a single http entry point to an automatically scaled function. I think it should then be all right to configure a function with endpoints to other functions' gateways. However one might want other interfaces to functions such as message queues. What to to then?

- **circuit breaking** make it so that a failing function gets cut out even before being called. This should also make an hard dependant function also fail early (however this should make you question your function design). Eventually the question to be answered here would be: how do you identify and take care of failing functions?

- **logging** should allow a dev to track a call tree of function by passing around some kind of request id. best practices on how/what/when to log and how to analyze those logs would go a great length in allowing microservices infrastructure to be adopted.

And the list goes on. My point is (I think) that, even if Serverless itself might focus on the function deployment alone; without a guide/best practice/library/whatever allowing users to quickly and reliably deploy and maintain a microservice architecture; I don't see Serverless being used for more than simple/independent functions only.

**Comment by DavidHooper** [comment]
I've recently started working with Serverless. I have a good idea of how I want our company's services to be split up and deployed independently. I've found managing many shared resources to be troubling. For example, I want all my services to use the one API gateway. If I decide to split them up, each Serverless configuration want's to create the gateway when it exists. 

Making management of existing and shared services easier should allow the flexibility of creating multiple services. Also, it could be that I'm missing documentation; so the answer could be to also update the documentation with some enterprise level examples.

**Comment by pmuens** [comment]
Closing this one for now to keep the issue count low.

Upcoming Serverless versions will provide ways to solve this problem.

**Comment by s1mrankaur** [comment]
@pmuens  Is there a way to resolve this yet? 

> Define dependencies between services so a service can only be deployed if other services are deployed as well
> Dependency management so one service can set up others if necessary (which can be helpful for dev infrastructure

**Comment by s1mrankaur** [comment]
@flomotlik  did you find a solution?
