### ISSUE TITLE
Serverless invoke local plugin

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2531]
# This is a Feature Proposal
## Description

We want users to be able to run functions locally and give parameters so they can test everything is working.

To that end we're introducing the `serverless invoke local` command

Options:
-  --function (-f): provide the function to run
- --path (-p): path to a file that has configuration for the function parameters

the `path` can point to a file with the following syntax where you can set all the parameter details:

```
event:
  ….
context:
  ...
```

This first implementation will only work for NodeJS. We'll look into other options in the future.

**Comment by gertjvr** [comment]
Curious have you looked at [docker-lambda](https://github.com/lambci/docker-lambda)? I have created a [serverless plugin](https://github.com/gertjvr/serverless-docker) that allows exactly this.

`sls simulate invoke -f functionName -i path to event` this will spin up a docker container and execute the lambda

one major plus for me is it supports all the aws lambda languages.

**Comment by eahefnawy** [comment]
@gertjvr does that impose a hard dependency on docker? So users have to install docker as a result?

We thought about the docker approach, but the dependency was a show stopper, and it seemed too simple for docker. But multiple language support is sure a big plus!

**Comment by eahefnawy** [comment]
@ac360 also suggested that we should emulate Lambda as closely as possible by having a default context with all the required methods so that users who use `context.done()` and similar methods would be able to run it locally as well.

Reflecting on the above proposal, we can have a default context that has those methods **but no data** (or default data?), we'll then merge whatever context data the user provided in `event.json` to overwrite those data.

@flomotlik @ac360 what you think?

**Comment by gertjvr** [comment]
@eahefnawy I agree that docker can be a show stopper, but since the release of docker for macOS and Windows, its install and forget very similar to any other application install, on windows or mac. and if your on linux I think you would be comfortable with maintaining docker installation.

In my opinion there are more issues with trying to control the developer host environment, ie what node version and what other dependencies that have installed globally.

The docker solution allows us not to worry about the host environment as the lambda would execute in isolation and the language it was written in, with the context already created by the container all the developer has to provide is the `event`.

The future of my [serverless-docker](https://github.com/gertjvr/serverless-docker) is to allow developers emulate more than just `API Gateway`, using [moto-server](https://github.com/spulec/moto) we would be able to simulate `s3`, `sns`, `sqs` and  `s*s` basically anything moto supports.

**Comment by flomotlik** [comment]
That context suggestion makes sense eslam. Will share my opinion on Docker based system later, need to think a little more about it

**Comment by QuantumInformation** [comment]
How do you get the console log? All I get is null:

trying to invoke:

![image](https://cloud.githubusercontent.com/assets/216566/22110080/57e49740-de52-11e6-8efd-c947cad35623.png)

with:
![image](https://cloud.githubusercontent.com/assets/216566/22110094/625ff598-de52-11e6-92cc-958aa2f4032d.png)

by:
`sif sendMail -p event.json
`

**Comment by pmuens** [comment]
@QuantumInformation could you share your functions code?

The signature is`module.exports.funcName = (event, context, callback) => ...` and the event data is accessible in `event`.
