### ISSUE TITLE
Allow plugins to be loaded from parent node_modules folder

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#2619]
# This is a Feature Proposal

## Description

V.1 conflates dev dependencies and regular dependencies but gives you no easy way to exclude the dev dependencies, causing Lambdas to be larger than necessary.  

V.0 resolved this issue by having dev dependencies installed in the parent folder (formerly known as the project folder).  

By allowing plugins to be loaded from a parent `node_modules` folder, not just the current service folder, we can easily solve this issue since the service folder is the deployment unit.

**Comment by andymac4182** [comment]
What folder layout are you expecting with this @ac360? Eg below.

- Root folder
  - Service Folder
    - serverless.yml
  - node_modules

**Comment by flomotlik** [comment]
@ac360 wouldn't this be a problem for loading devDependencies like mocha as npm expects them to be in a local node_modules folder? So when I want to execute the mocha binary will it be found?

Just tested it by installing mocha in a parent npm folder (and looked into the docs) and it seems like npm is then only loading dependencies in the node_modules folder in the same directory?

To optimise your dependencies and remove dev dependencies you can also use `npm prune --production` which will remove all dev dependencies from your node_modules folder.

Or is this only for additional plugins for users? Because I think the impact of only having support for plugins in other node_modules folders will be pretty minimal.

**Comment by ac360** [comment]
@flomotlik npm automatically searches several parent folders (I think it's ~10) when it can't find a module in the local `node_modules` folder.  But the Framework doesn't follow this pattern and only looks [locally](https://github.com/serverless/serverless/blob/master/lib/classes/PluginManager.js#L81).  This can be changed with a few trivial lines of code.

One of the largest problems of the Serverless Framework is slow development time.  Speeding this up is critical to its success.  The majority of the slowness clearly comes from the upload time of the Lambda zip.  Therefore, reducing the size of the zip is most obvious way to speed up development, and this is why combining dev dependencies with regular dependencies is hugely problematic.

Running `npm prune --production` is one way, but it doesn't fix the underlying problem of slowness since the user will have to run this before each deploy, then run `install`, when they continue to develop.

Keeping dev dependencies in a parent folder isn't perfect, since we'd optimally want to declare those in the `package.json` in the service folder, so that everything is defined together.  However, it offers the best solution to the problem at this time and does so as an option, not a forced way or recommended best practice, allowing us more time to figure that out.

**Comment by flomotlik** [comment]
Are you sure it goes up? I tried this recently and if there was a node_modules folder in the same folder it didn’t look into the parent anymore. The other thing is that this will definitely require users to split up their dev/production dependencies and install them in different places. How would they do this and how many would like to do this? From my experience splitting up dependencies into different files and folders gets very painful very quickly so I’m not sure how practical this is and how many users would actually go for it.

And even then wouldn’t this only touch plugins they install from us? This only covers a small part of dev dependencies as you have a ll the test tools, … in place as well, so it would only provide a minimal upside and require quite a bit of work from the users.


On 13 November 2016 at 21:43:28, Austen (notifications@github.com) wrote:

@flomotlik npm automatically searches several parent folders (I think it's ~10) when it can't find a module in the local node_modules folder. But the Framework doesn't follow this pattern and only looks locally. This can be changed with a few trivial lines of code.

One of the largest problems of the Serverless Framework is slow development time. Speeding this up is critical to its success. The majority of the slowness clearly comes from the upload time of the Lambda zip. Therefore, reducing the size of the zip is most obvious way to speed up development, and this is why combining dev dependencies with regular dependencies is hugely problematic.

Running npm prune --production is one way, but it doesn't fix the underlying problem of slowness since the user will have to run this before each deploy, then run install, when they continue to develop.

Keeping dev dependencies in a parent folder isn't perfect, since we'd optimally want to declare those in the package.json in the service folder, so that everything is defined together. However, it offers the best solution to the problem at this time and does so as an option, not a forced way or recommended best practice, allowing us more time to figure that out.
