### ISSUE TITLE
Internal server error after updating to 1.1.0

### ISSUE THREAD

**Issue by cristim** [serverless/serverless#2627]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  * After updating sls from 1.0.0-rc2 to 1.1.0 functions fail to run with "Internal server error", even though there were no other changes in the configuration or the lambda code.
* What did you expect should have happened?
  * Functions should keep running after the serverless version update
* What was the config you used?
  * nothing special, but I can't release it publicly due to company policies. It is a simple function listening on an HTTP event
* What stacktrace or error message from your provider did you see?
Function calls always return
``` 
{
message: "Internal server error"
}
```

I can provide more information upon request.

**Comment by pmuens** [comment]
Hey @cristim thanks for raising this issue!
Unfortunately It's hard to tell without some code / configuration.

What you might want to check is the used `integration` type for the `http` event.

We've changed the default integration type to `AWS-PROXY` / `LAMBDA-PROXY` once AWS launched this integration type. You need to specify the response explicitly in code rather than through API Gateway requests and response setups when using this.

You can read more about this in the docs: https://serverless.com/framework/docs/providers/aws/events/apigateway/#lambda-proxy-integration

Furthermore here's an example how this looks like in code (https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/aws-nodejs/handler.js).

Let me know if this solves your issue. Cheers 💃

**Comment by cristim** [comment]
@pmuens thanks, I'll give that a try.

But still, it would be nice not to break my existing function whenever updating sls.

**Comment by flomotlik** [comment]
@cristim between rc.2 and 1.1.0 we released a lot of changes, including breaking changes with 1.0. Going forward we're using Semantic Versioning and detailed in the Github releases tab so you can see exactly when breaking changes are occuring.
