### ISSUE TITLE
Simple Lambda function fails locally

### ISSUE THREAD

**Issue by izogain** [serverless/serverless#2646]
# This is a Bug Report 

## Description
i have this simple code, i couldn't figure out why its working when deployed and tested on aws but not locally. I used the default nodejs template, only changed the body and the nameservice/memory.

https://gist.github.com/izogain/3eee7ae8ef358cad7cfaae7bd047f2c5

## error message:

https://gist.github.com/izogain/80e26a27f0bd76452bf38f8fb2c40222

Any reason why ? thx.

**Comment by rowanu** [comment]
It is working.

Look at [the first line of the error message](https://gist.github.com/izogain/80e26a27f0bd76452bf38f8fb2c40222#file-gistfile1-txt-L10):

```
Error: some error type
```

That "some error type" is coming from the [argument you're passing to your `callback` function](https://gist.github.com/izogain/3eee7ae8ef358cad7cfaae7bd047f2c5#file-handler-js-L4) - it's treating the string as if it was an Error, but obviously there's no meaningful details because it's just a string.

**Comment by izogain** [comment]
Thank you very much, i was confused by the stack error.
