### ISSUE TITLE
configure log retention?

### ISSUE THREAD

**Issue by bdruth** [serverless/serverless#2653]
Cross-post from gitter.im/forum post question (not getting any responses on either):

Quick question re: the provider.cfLogs support in serverless
we should delete the existing log groups, then redeploy with provider.cfLogs: true, so the serverless-generated CF template creates the log groups
I'm following that
where do the logs actually get configured? I was hoping to be able to configure log retention once serverless was managing the log groups, but I don't see any addl configuration hooks
so, if I'm understanding correctly, the change to provider.cfLogs is just "step 1" ?

**Comment by flomotlik** [comment]
@bdruth at the moment we don't expose additional config (we will in the future) but because this is now a resource in your cloudformation template you can simply overwrite it. If you check the CF template in the `.serverless` folder you'll see the LogGroup in there. You can just add additional resources as custom resources that will extend that CF resource with additional parameters like log retention: https://serverless.com/framework/docs/providers/aws/guide/resources/

I'm going to close here as its not a direct issue that we're tackling right now, but if you have any further questions let me know.

**Comment by bdruth** [comment]
Excellent - that's what I needed, thanks @flomotlik.

**Comment by ctindel** [comment]
@flomotlik Trying to figure out how to get the log retention stuff working. Are we supposed to put the .serverless/cloudformation-template-create-stack.json under source control and add stuff to it to define the retention policy?  I figured this was something auto-generated so is there a good way to automate the retention policy setting as part of the CI workflow?

**Comment by pmuens** [comment]
Hey @ctindel 
You could use `cfLogs: true` in your provider section of your `serverless.yml` file:

```yml
provider:
  cfLogs: true
```

After that Serverless will generate the corresponding resources for you. Those CloudFormation files  live in the `.serverless` directory. The resources can be overwritten with the `resources` section in `serverless.yml` (https://serverless.com/framework/docs/providers/aws/guide/resources/). So you just need to define the exact same resource logical id there with additional config which will then be merged into the auto-generated one (and overwrite the settings Serverless will put in place).

Here's an example:

```yml
service: some-service

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true

functions:
  hello:
    handler: handler.handler
```

will generate the following LogGroup for you:

```json
"HelloLogGroup": {
  "Type": "AWS::Logs::LogGroup",
  "Properties": {
    "LogGroupName": "/aws/lambda/some-service-dev-hello"
  }
}
```

You can then overwrite / extend it like follows:

```yml
service: some-service

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true

functions:
  hello:
    handler: handler.handler

# THIS IS NEW
resources:
  Resources:
    HelloLogGroup:
      Properties:
        SomeNewProperty: SomeKey
```

**Comment by ctindel** [comment]
@pmuens thanks for the instructions.  I'm glad this was added recently, it makes things really customizable!  I'll post my instructions here for people who stumble upon the thread later.

It was confusing trying to figure out what property to put in the yaml, because if I did "aws logs describe-log-groups" I got back something like this:

```
{
    "logGroups": [
        {
            "retentionInDays": 30,
            "metricFilterCount": 0,
            "storedBytes": 9476075,
            "arn": "arn:aws:logs:us-east-2:773216979769:log-group:/aws/lambda/sa-demo-coordinator-curator-dev-cron:*",
            "logGroupName": "/aws/lambda/sa-demo-coordinator-curator-dev-cron",
            "creationTime": 1482878640409
        }
    ]
}
```

However, even though the property there is "retentionInDays", CloudFormation expects it to be capitalized.  So what worked for me was putting this in my serverless.yml:

```
resources:
  Resources:
    CronLogGroup:
      Properties:
        RetentionInDays: "30"
```

**Comment by pmuens** [comment]
@ctindel thanks for getting back and posting the instructions for others!

Glad to see that you got it working! 👍

**Comment by nick4eva** [comment]
@ctindel thanks for instructions how to change log group retention, but it doesn't work for me for some reason (I'm using Serverless v1.5.0).

I've added `cfLogs: true` to `serverless.yml` in `provider` section and redeployed function, but in `.serverless` folder generated json template doesn't contain resource `"AWS::Logs::LogGroup"`.

**Comment by ctindel** [comment]
I'm doing it on 1.4.0. Out of curiosity if you install that version instead do you see any difference?

**Comment by pmuens** [comment]
@nick4eva Adding `cfLogs: true` should usually do the trick.

Could you please provide your `serverless.yml` file so that we can look into it?
Could you maybe also run `serverless deploy --noDeploy` and look into the `cloudformation-template-update-stack.json` file for the `AWS::Logs::LogGroup` resource?

**Comment by brendanjerwin** [comment]
@nick4eva I just discovered that I don't get the LogGroups defined if I have a `role:` specified. Seems it only does the `cfLogs` magic if using the default role?

**Comment by nick4eva** [comment]
@ctindel no difference on version 1.4.0 (it also doesn't work), but now I know why.

I've played with freshly generated boilerplate the way @pmuens mentioned and it works. So the problem is our serverless configuration.

We have defined `role: defaultRole` but that `defaultRole` is custom one defined in `cloudformation.resources.yml`. So we have a situation which @brendanjerwin spotted: if `role:` specified, `cfLogs` doesn't work.

@pmuens so what we need to do? Add creating Log Group into our custom role, or serverless should handle this situation, so it's a bug?

**Comment by pmuens** [comment]
Thanks for investigating @brendanjerwin and @nick4eva.

I would suggest that you add the creating of the Log Group to your custom role for now.

Could you please open a new issue with the bug that using a custom role and `cfLogs` won't work so that we can discuss the problem there? Thanks in advance!

**Comment by AndrewFarley** [comment]
Hey guys, sorry to bring this up again, but did something change in the latest version of Serverless (v1.20.2)?  My previous deployments worked with the above example...
```
resources:
  Resources:
    CronLogGroup:
      Properties:
        RetentionInDays: "30"
```
But since updating now it says...

```
Serverless: Validating template...

The CloudFormation template is invalid: Template format error: [/Resources/CronLogGroup] Every Resources object must contain a Type member.
```

It seems to me someone added some client-side validation that appears to be functioning incorrectly?  Or is there perhaps a new way to define the log retention...?

**Comment by AndrewFarley** [comment]
Incase anyone else lands here, per my last comment I figured it out.  With new serverless you need to use the "type" apparently, as follows...

```
resources:
  Resources:
    CronLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
```

**Comment by pmuens** [comment]
Thanks for commenting @AndrewFarley 👍

And thanks for posting the solution for this problem 👍.

We've implemented template validation in Serverless in one of the last versions. This validation happens on AWS end (using an SDK call) so they basically define how a valid template looks like (and can change it as they please). The upside of this is that it enables way faster feedback loops (because an invalid template is detected before it gets deployed).

**Comment by bytekast** [comment]
is there a way to set this globally (for all functions) in a service rather than specifying the config per individual function?

**Comment by gcampionpae** [comment]
I agree with @bytekast, it would be really awesome if this could be set for all functions' logs for a service :)

**Comment by AndrewFarley** [comment]
@gcampionpae I agree it would be great for a native way to automatically do this within' the serverless framework.  However, if someone has some free time this wouldn't be too hard to implement this in a dynamic variable (javascript) script, which could read the serverless.yml file and automatically generate some items for `resources:`.  However, doing this would make you have to put any other custom resources inside your dynamic variable script, which could get rather annoying.  I'm already starting to use dynamic variables for a handful of similar (but less complex) uses.  If I did much more serverless work, I would probably implement this myself.

**Comment by theburningmonk** [comment]
@bytekast I implemented this (along with other platform level conventions like subscribing logs to a log-shipping functions) using CloudTrail + CloudWatch event pattern + Lambda, so that whenever a new log group was created in response to a new function, these conventions would be applied.

You can read about it in this [post](https://hackernoon.com/tips-and-tricks-for-logging-and-monitoring-aws-lambda-functions-885af6da29a5) there's even a repo with demo code you can use.

**Comment by bytekast** [comment]
thanks guys. it looks like there's a new `logRetentionInDays` config in the `serverless.yml` as described here https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

that may be what we're looking for

**Comment by mllanes** [comment]
`logRetentionInDays` doesn't appear to be actually setting the log group expiration in CloudWatch

**Comment by callum-p** [comment]
Would be good if you could use variables to define this, but it looks like serverless always casts variables to strings, when it needs to be an int.  To get around this I've had to override each log group individually and use define a CloudFormation parameter so it casts to an int correctly :(

`
custom:
  logRetentionInDays: ${env:LOG_RETENTION_IN_DAYS, '7'}

Parameters:
  logRetentionInDays:
      Type: String
      Default: ${self:custom.logRetentionInDays}

Resources:
  HealthcheckerLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays:
          Ref: logRetentionInDays
`

**Comment by joemendel77** [comment]
It seems this can now be set globally for all functions using the logRetentionInDays parameter.

https://github.com/serverless/serverless/pull/4591
https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

Generated CF template contains:

    "AutoApproverLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/autoApprover",
        "RetentionInDays": 30
      }
    }, ...

**Comment by zipper1972** [comment]
In your serverless.yml file add the following: 

(in the custom section) 
custom:
  logRetentionInDays:
    prod: 90
    dev: 30
    qa: 30

Then (in the provider section)
provider:
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}}

**Comment by workpush** [comment]
> In your serverless.yml file add the following:
> 
> (in the custom section)
> 
> ```
> custom:
>   logRetentionInDays:
>     prod: 90
>     dev: 30
>     qa: 30
> ```
> 
> Then (in the provider section)
> 
> ```
> provider:
>   logRetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}}
> ```

you can also just use ${self:custom.logRetentionInDays.${self:provider.stage}}
