### ISSUE TITLE
How to debug locally?

### ISSUE THREAD

**Issue by ra50** [serverless/serverless#281]
Hi, this isn't really a bug but more a general question about using Lambda and JAWS.  With a typical Node server I'm used to pointing my mobile app to the locally running server so I can debug in my IDE during development.  How can this be accomplished when using Lambda and JAWS?

As I understand it, there are two ways to call Lambda functions, either directly through the AWS SDK or via REST API calls.  It seems neither of these would be available on my local machine, as the SDK would be calling to Amazon, API Gateway also points to Amazon, and calling the REST API some other way wouldn't be possible without something like Express running as part of the app.  I'm very interested in trying JAWS but I just want to understand how I can run and debug locally like I do today before deploying my functions.

Thanks.

**Comment by eahefnawy** [comment]
JAWS works very differently than traditional frameworks like express. There's really no "local" server. There's even no production server! It's a **serverless** framework, remember! ;)

But to answer your question, to debug your app during development, you just create a stage called `dev` (it's the default anyway), where you'll deploy all your changes to, and test your mobile app on. When you're done building & testing, you can very easily deploy to another stage called `production` or something.

IMHO I find this to be much more efficient than using a local server, mainly because the dev/testing environment is an **exact match** of the production environment, allowing you to find production grade bugs and fix them during development. This is called "Dev/prod parity". It's factor/rule #10 in the [Twelve-Factor App](http://12factor.net) principles.

**Comment by Kenny-House** [comment]
Although dev / prod parity and deploying to stages for testing is certainly ideal, I think many developers are going to expect support for local development environments.

We've just started experimenting with JAWS in our dev team and are quite excited about it. One of the immediate questions from our developers, however, was "how do I run it locally".

We're interested in implementing a utility to read the API gateway config and emulate the routing to the appropriate lambda functions. We'll likely be looking at a docker-based solution so that everything is in a linux environment. Will certainly update the community if / when we begin work on it, although I don't anticipate any work on it soon.

**Comment by eahefnawy** [comment]
That's fascinating! It would be great! Keep us posted ;)

**Comment by ra50** [comment]
Thanks for the responses.  Dev/prod partiy does sound great and would ease transition to production.  I like the idea of the "serverless" setup and the dev stage sounds good.  But am I correct that that means step-by-step debugging is not possible?  If dev testing still involves uploading the functions to Lambda and invoking them there, it seems the only way to debug is to use console logging, which sounds like a big step backward for any non-trivial functions.  This is the main thing holding me back from trying Lambda and JAWS for a complete back-end right now.  What Kenny-House describes, where you have an Express server or something similar locally routing API calls to local lambda functions, is what I would anticipate something like JAWS eventually having.  It would fit in well with the idea of JAWS being all about making Lambda easy and painless to use.

**Comment by Kenny-House** [comment]
Not that the particulars of an implementation matter right now, but I was considering the docker approach so that API gateway config would be translated into an nginx configuration. This would allow requests to be routed to different containers with isolated execution environments per function. This would allow for node and java and python execution environments to be running locally.

Handling the template mapping in API gateway is something I haven't given much thought to yet, but should certainly be emulated locally as well.

**Comment by ra50** [comment]
That sounds like a really good way to make it mirror how Lambda actually functions as much as possible.  I'd be really excited to see something like this come with JAWS out of the box.

One thing that makes me less concerned about robust debugging capability is that since these are microfunctions, writing one bad function doesn't bring down whole server.  The rest of your app and functions can keep on going while you fix the problematic one.  This is making me considering trying it out and just getting used to console.log debugging, but I would love to hear how others are handling this.

**Comment by marklawlor** [comment]
Debugging JAWS has been pretty painless for myself and my team. Our philosophy is basically "Ignore JAWS. Write standalone well tested javascript services, then integrate them into JAWS."

JAWS works great with a Test Driven Development workflow, as each Lambda is designed to be simple and only have one purpose.  We use [Rewire to mock AWS services](https://www.npmjs.com/package/rewire) ( Some people use [Sinonjs ](http://sinonjs.org/)) and [DynamoDB Local](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html). Simply ignore the handle.js file and just work with index.js. At this stage ignore that this is a Lambda and just treat your code like a standalone normal Javascript micro-service. [Node Inspector](https://github.com/node-inspector/node-inspector) is amazing for debugging.

Once we are happy with our test coverage we rely on CloudWatch logs.  We use a [Winstonjs-like] (https://github.com/winstonjs/winston) custom logging library that uses an environmental variable to set the logging level. Following the TTD workflow, we write API integration tests to ensure everything is working.

Stages follow a git-flow approach. Feature stages during development before being merged into a integration/release/master stage.

If your plan your tests correctly your can iron out most of your debugging issues before you even uses the JAWS tools.

Not being able to delete stages though the CLI has been our biggest issue :(

**Comment by ra50** [comment]
Thanks marklawlor for that detailed info.  There is a lot of new tooling you mentioned there that I'll have to look into if I want to consider using Lambda effectively.  Essentially, are you only exercising your code locally via your tests?  I've been trying to wrap my head around how the code is executed locally without a "server" of any kind.  I guess if the testing service provides the runtime, then it can just load your modules and exercise them.  But does it still mean it's not possible to have my mobile app running in a simulator call my functions executing on my local PC?  Also good to see there is a local version of DynamoDB available.

What are your overall experiences with Lambda and DynamoDB so far?  I'm trying to evaluate if the advantages compared to a standard Node.js server on Beanstalk are worth it.  Are you concerned about the vendor lock-in by setting up your server app in this way and coding against DynamoDB?

**Comment by oravecz** [comment]
If you need to debug code right in your IDE as you are developing, here is the configuration you will use for IntelliJ IDEA. This is a technique for debugging one Lambda locally at a time. The directories shown are for OSX.

1. Run -> Edit Configurations
2. Plus Sign (New Configuration) -> Select Node.js
3. Name (provide the name of your lambda)
4. Node interpreter (mine defaults to `/usr/local/bin/node`)
5. Working Directory (point to the directory containing your lambda's `event.json` file)
6. Javascript file (`/usr/local/bin/jaws' if you installed on OSX with the -g option)
7. Application parameters (`run`)
8. Environment variables (these will vary based on what your lambda does)
    1. For AWS services you will have to specify `AWS_REGION=<region>` and `AWS_PROFILE=<profile>`. If you don't use profiles, you may have to specify the access key and secret key.
    2. Set `DEBUG=*` if you want to see JAWS debug messages. Or your own if you use the debug package.

And that's it. Save that configuration and either run it, or place breakpoints in your code and debug it.

**Comment by rkoberg** [comment]
These are all great suggestions, but they don't help when using the lambda functions to power a web site/app. Imagine a designer type person who checks a project out from a git repo. Their task is to run the web app and modify the templates (place data results where wanted) and SASS stylesheets to their hearts content. They need to see the result of the api calls to be able to do their job.

I am currently biting the bullet and wiring up swagger (I am assuming that is in future plans for JAWS) and then plan to use something like: https://github.com/BigstickCarpet/swagger-express-middleware to run locally to have the full web app experience.

**Comment by marklawlor** [comment]
JAWS is aimed more at the people who build APIs and/or work in dev-ops. I wouldn't expect a designer to be looking through JAWS code, especially if they just want to check what the API returns. Theres better tools for that job.

I started working on a (JAWS to Swagger plugin)[https://github.com/marklawlor/jaws-swagger]. The uses SwaggerUI to document all API endpoints ([example of SwaggerUI](http://petstore.swagger.io/)). The idea being that you provide this to your designers to interact with the API and get all the documentation they need, without sifting though the codebase.

If something like [jaws serve](https://github.com/jaws-framework/JAWS/pull/269) becomes available, you could use this to test your API locally as well.

**Comment by rkoberg** [comment]
"JAWS is aimed more at the people who build APIs and/or work in dev-ops."

Take this for what it is worth: That is fine, but I want it to back a web app were the focus is mainly on the front end and making it look pretty. It is currently inconvenient to do that now. The designer type or even other (perhaps front end) developers would not need to look through any of the JAWS code. But they do need to hit refresh a lot to layout/style a page. With a little glue code, it is easy enough to map a simple local api to the JAWS managed api. I am hoping to automate that in some way with swagger.

**Comment by ac360** [comment]
We are working on a local JAWS server so that you can run your lambdas locally.  But it will be hard to support multiple runtimes.

@Kenny-House Your approach sounds interesting.  I'd like to chat with you further about this.  Could you email me at austen@jawsframework.com?

**Comment by aletheia** [comment]
Maybe using docker containers could be a good way to support different
runtimes?

This could resolve any issue related to lambda execution. Regarding to
infrastructure provisioning there's not much we can do

Il giorno mar 3 nov 2015 alle 02:35 Austen <notifications@github.com> ha
scritto:

**Comment by justingreenberg** [comment]
@ac360 I think this conversation really captures the excitement driving JAWS: standardized, modular, declarative workflow for wiring AWS resources into serverless applications. This is cutting edge and best practices are emerging. Issues such as local development quickly enter a roadmap conversation. A community is already forming around these standards. 

I believe standards like this could have a huge impact on the way apps are developed—maintaining a focused, well documented API is the best way to build a healthy community. Projects that keep their communities engaged are laser focused on creating the best API, or really "developer experience" using their platform. It's not hard to imagine creating powerful development tooling around AWSM (such as the dockerized nginx config watcher mentioned above) and other integrations, ie simple CD for individual lamdas, staging and integration testing, and even full PAAS with WAF provisioning.

I'm looking forward to getting involved when things stabilize, maybe when v1 launches? Any idea when that will be? Anyway, just sharing thoughts—great job!

**Comment by aletheia** [comment]
Totally agree with you. In my company we're really excited about JAWS even
if a bit worried since it's a project in its early stage.
Some choiches did not come completely clear to us (i.e. choosing CF over
nodejs sdk and a build tool such as gulpjs to build infrastructure seemed a
bit overkilling) but decided to stick with the project since it's so
awesomely built.

Now we are willing to be as helpful as we could. Also providing support in
writing documentation or preparing examples would suit well for me, since I
have to drive backendless adoption to my dev team and JAWS is the choice
Il giorno mar 3 nov 2015 alle 08:26 Justin Greenberg <
notifications@github.com> ha scritto:

**Comment by ac360** [comment]
If anyone is interested in helping to solve this problem specifically, please email me: austen@jawsframework.com

**Comment by sebs** [comment]
I am still before my first live project, I just know my way around in node and testing. But I just set this up: 

A bunch of tests for that node functions: thats a module.export.run  ... what can be easier to test. Anyway, that would be my real local development need. As for the service, it just runs as a service. You can mock, fake or just pretend its there. It will be always two things: Not the real thing after all, and still integration testing. 

The setup I ended up with: 

1. Mocha unit tests, mostly in own npm repos. JAWS seems to like small things. This way I make sure they are. 

2. A bunch of ZombieJS tests and a Simple DSL made of Gherkin/CucucmberJS/Helpercode. I mean the APIs are pure HTTP

It clicked for me, when I understood JAWS as distributed software. Lets see where this leads

**Comment by flomotlik** [comment]
We're going to work on improving the ability to test your Serverless applications locally in the next version of Serverless. I will close this issue for now, but thanks for making all your suggestions, very helpful

**Comment by foobar8675** [comment]
Hi @flomotlik , do you know approximately when the next release will come out? Local debugging is something I am really looking forward to.

**Comment by flomotlik** [comment]
We're working on it in the V1.0 branch and going to release alpha versions throughout the summer. Our goal is to release 1.0 late summer, early fall. We want to make sure we really hit this one out of the park so take enough time to polish it.

**Comment by foobar8675** [comment]
@flomotlik awesome

**Comment by aheissenberger** [comment]
I use this to debug local:
`node-debug $(type -p serverless) function run XXX`

this should work with `serverless-offline` too but I have not tested it

**Comment by mrlamroger** [comment]
@flomotlik great to hear! Would it be helpful if I added an sentence or two to the README noting that it's a work in progress?

**Comment by QuantumInformation** [comment]
So is this the best way to debug sls invoke local in 2017? Modified to point to sls?

```
Run -> Edit Configurations
Plus Sign (New Configuration) -> Select Node.js
Name (provide the name of your lambda)
Node interpreter (mine defaults to /usr/local/bin/node)
Working Directory (point to the directory containing your lambda's event.json file)
Javascript file (`/usr/local/bin/jaws' if you installed on OSX with the -g option)
Application parameters (run)
Environment variables (these will vary based on what your lambda does)
For AWS services you will have to specify AWS_REGION=<region> and AWS_PROFILE=<profile>. If you don't use profiles, you may have to specify the access key and secret key.
Set DEBUG=* if you want to see JAWS debug messages. Or your own if you use the debug package.
```

**Comment by QuantumInformation** [comment]
I'm not sure what bin to use in that case:

![image](https://cloud.githubusercontent.com/assets/216566/22620999/e4ef3f62-eb10-11e6-8e6a-663b9af9e880.png)

**Comment by pmuens** [comment]
Hey @QuantumInformation thanks for getting back on this issue.

You can get the path to your Serverless executable by running `which serverless`.

**Comment by QuantumInformation** [comment]
Thanks, I done the following:

![image](https://cloud.githubusercontent.com/assets/216566/22640619/6855884e-ec4b-11e6-8ce6-258cafe57dc1.png)

but I get:
```
/Users/nikos/.nvm/versions/node/v6.9.1/bin/node --debug-brk=63417 --expose_debug_as=v8debug /Users/nikos/.nvm/versions/node/v6.9.1/bin/serverless invoke local -f createTodo
Debugger listening on [::]:63417

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

when I try just run it:

![image](https://cloud.githubusercontent.com/assets/216566/22640701/acf708d8-ec4b-11e6-86ab-ab072f765564.png)

**Comment by pmuens** [comment]
Hey @QuantumInformation filling out the forms in WebStorm and running it via the debug button in WebStorm should usually work.

Otherwise you might want to consult StackOverflow as well. You should find more help there since it's a Node.js related debugging question and not directly related to Serverless.

**Comment by QuantumInformation** [comment]
Roger that: http://stackoverflow.com/questions/42085694/debugging-serverless-framework-invoke-local-function

**Comment by QuantumInformation** [comment]
I think I'll ask the Json at pos 0 error too on SO.

**Comment by pmuens** [comment]
Great. Yes, that's a good idea 👍

**Comment by QuantumInformation** [comment]
there we go, took a while to write:
http://stackoverflow.com/questions/42089597/serverless-local-invoke-gives-unexpected-token-u-in-json-at-position-0

**Comment by QuantumInformation** [comment]
@pmuens having debugged this more its because the event.body wasn't valid JSON. I really hope more accurate error messages are output going forward in the absence of an easy way to debug local invokes.

**Comment by pmuens** [comment]
@QuantumInformation thanks for getting back and posting the solution for this problem. 👍 

Yes, we're going to constantly work on better error messaging...

**Comment by QuantumInformation** [comment]
great, this framework is the buzz in London!

**Comment by pmuens** [comment]
@QuantumInformation awesome! That's nice to hear 🎉

**Comment by panKt** [comment]
ok, so what is the solution for now? It still never runs for me in WebStorm

**Comment by pmuens** [comment]
@panKt not sure about WebStorm in general, but the `serverless-offline` plugin has some debug capabilities: https://github.com/dherault/serverless-offline#debug-process

Maybe @QuantumInformation can share his experience with debugging and WebStorm.

**Comment by QuantumInformation** [comment]
I haven't tried to debug in webstorm for a few months, I'll try that plugin and get back to you.

**Comment by pmuens** [comment]
Thanks @QuantumInformation 👍

**Comment by TheRoccoB** [comment]
OK, I've figured out how to do this with real chrome devtools with the excellent `node --inspect`. This is much better than node inspector because it uses the latest built in chrome devtools. [(more info on node inspect)](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27)

```node --debug-brk --inspect $(which serverless) invoke local -f myfunctionname```

I ran that but my function wasn't loaded yet (probably some lazy loading in the serverless code). So I added a `debugger` to the top line of my function and everything seems to be working great.

In my case I also needed some test data, so I passed that through like this.

```
node --debug-brk --inspect $(which serverless) invoke local -f postprocess -d '{"Records":[{"eventVersion":"2.0","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2017-06-17T05:08:29.598Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"ALS78N87ZDYNW"},"requestParameters":{"sourceIPAddress":"52.119.114.78"},"responseElements":{"x-amz-request-id":"2EB4FAD5892EC247","x-amz-id-2":"nVLasIYsWvWm7xwONiTB6z7L8oXKkvPOb9FntOYoG/kKS+PuWwbMJ1xM7n/C1X3NJh5FUCj4aEM="},"s3":{"s3SchemaVersion":"1.0","configurationId":"3c3b2a71-b639-4116-b246-08dcacd0c7d6","bucket":{"name":"simmer-uploads-test","ownerIdentity":{"principalId":"ALS78N87ZDYNW"},"arn":"arn:aws:s3:::simmer-uploads-test"},"object":{"key":"example+%285%29.zip","size":4757597,"eTag":"9aa90579ee4e8152e6dfa60258754a83","sequencer":"005944B94AD9307261"}}}]}'
```

I am working on a mac, and I heard there might be some problems with $(which serverless) on windows. But someone give it a shot and let me know.

**Comment by pmuens** [comment]
That's cool!

Thanks for sharing this tip @TheRoccoB 👍

**Comment by QuantumInformation** [comment]
@TheRoccoB hint, that would make a great you tube video.

Is https://github.com/dherault/serverless-offline an alternative that would offer better ease of debugging. Seems both that and `node --debug-brk --inspect ` both allow debugging.

**Comment by ra50** [comment]
In May last year @flomotlik said, "We're going to work on improving the ability to test your Serverless applications locally in the next version of Serverless."  Today the quick start docs say: "Write tests to run locally".  Were there improvements around local debugging planned for the 1.0 release that didn't make the cut?  What's the best practice for doing this today?

Having to deploy and use console logging to test your functions from your app seems a lot slower than hitting your function locally where you can step through execution.  Serverless could come with a minimal express server and CLI command to listen for requests locally to test against.  I guess this is what serverless-offline is trying to accomplish.

**Comment by HyperBrain** [comment]
@ra50 `serverless-offline` is a really good solution to test your functions locally. The plugin fully concentrates on the emulation of local endpoints and it is also possible to debug your code with `node --debugt-brk --inspect` and setting a breakpoint into your code after the initial break.

If you just want to debug a single Lambda invoke locally, you can use `--debug-brk --inspect` with `serverless invoke local`.

In general, I do not see the emulation as part of the framework because that would add a lot of technical debt to the core framework - a plugin can react much faster on changes to the AWS APIG behavior.

**Comment by pmuens** [comment]
Hey @ra50 thanks for commenting and @HyperBrain thanks for answering 👍

Yes, `serverless-offline` is a good way to develop your Serverless services locally.
Furthermore there's `serverless-localstack` (which uses `localstack`) and `serverless-plugin-simulate`.

Back in the time when this decision was made we've decided to focus more on the core parts for Serverless v1 rather than trying to emulate every cloud provider service (which is a really hard thing to do).
