### ISSUE TITLE
Add metrics to info plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2810]
# This is a Feature Proposal

## Description

Add `metrics` information to the `info` plugin.

**Comment by nikgraf** [comment]
Notes from analyzing the Info/Metrics plugin decision:

- On a first deploy the metrics are useless. The only exception is if I'm using Serverless for the first time as I see the output.
- Having two commands: `info` & `metrics` is confusing. Metrics is something different, but I'm not sure it needs an extra command.

## Option 1: extending the info plugin

- What's the overhead to fetch all that data? Could cause issues if you have multiple functions.
- How can we extend it to show timestamps or hide/enable certain metrics in the future? Most of these parameters could cause some confusion, because `serverless info` shows you the CURRENT state of your infrastructure. Metrics is a view into the past. If I would type in --startTime into info I'm would expect it shows me data from functions I have removed as well …

## Option 2: Create a separate metrics Plugin

- If now timestamp is provided it should mention that these are the last 24 hours.
- We focus on a service architecture not functions. If we do `serverless metrics`, by default it should show the whole service. We could to `serverless metrics function` for a specific function.

- There is a bug in the current implmentation with date parsing:

sldev metrics --function landingPage --startTime='2010-11-20'
 
  Serverless Error ---------------------------------------
 
     Expected params.StartTime to be a Date object, ISO-8601
     string, or a UNIX timestamp
 
  Get Support --------------------------------------------

## Conclusion

Right now I'm leaning more towards separate `metrics` and `metrics function` commands. Adding the feature sounds good to me, but I'm worried about adding more commands. The list already is long! I'm wondering if this has to ship in the core, but rather live as a separate plugin. We probably need to make the same decision for secrets management sometimes soon. Both are valuable in the core, but also adding more complexity and the list gets longer again. Tricky trade-offs and this is a good point in time to decide if we want a fat core or slim core with highly recommended plugins …

What are you thoughts? @pmuens @mthenw @eahefnawy @ac360

**Comment by mthenw** [comment]
@nikgraf i like that. +1 for that

**Comment by pmuens** [comment]
I'm also in favor of having a separate `metrics` plugin.

Including the metrics in the `info` plugin like it was planned before has may different drawbacks:
- Right now `info` does not take any options. How do I specify the `startTime` and `endTime` for the metrics?
- It only displays metrics for the last 24h (that's the default which was chosen because of the lack of specifying `startTime` and `endTime`  
- The info output gets very crowded
- For each function we need to make 4 requests via the SDK so if your service has e.g. 5 functions only the metrics retrieval will issue 20 requests to get the relevant data. This slows down the info plugin

I'd vote for the separate metrics plugin which is already in place.
Not sure if we need the `serverless metrics` and `serverless metrics function` commands. IMHO we can still use `serverless metrics` and if the user has not specified a function name then the plugin will return the metrics of all functions in the service. We can extend this easily later on.

**Just one note**: I had to refactor the `info` command so that I could implement the metrics fetching in a correct way. It would be great if we could get the refactoring in the codebase (it's in the "Add metrics to info plugin" PR) as it makes the codebase a lot cleaner (we can remove the metrics fetching from this PR).

**Comment by pmuens** [comment]
Closing this once since we have the `metrics` plugin in place and this won't be added to core.
