### ISSUE TITLE
api keys are lost forever when not included in deploy

### ISSUE THREAD

**Issue by orasis** [serverless/serverless#2822]
api keys are generally designed to be long lived.  Assuming we store the serverless.yml under revision control, there is a flaw in the design of apiKeys.

1) add an new apiKey to serverless.yml
2) deploy
3) send that api key to a customer
4) revert serverless.yml to fix a configuration issue
5) deploy

The original key is deleted from api gateway lost for ever.  the customers requests are now forbidden.

This would be greatly exacerbated if the api keys are stored in ${env:MY_API_KEY} as is described in the docs.  If that environment variable didn't exist on the shell being deployed from, all previous api keys would be lost.  This would be a catastrophic problem for a B2B api.

**Comment by orasis** [comment]
I guess this isn't as doom & gloom as I made it out to be if the customer can resend you the API key that isn't working you could re-add it manually through the API gateway console.

**Comment by medikoo** [comment]
Closing as it's a old, stale issue, and it's not clear to me exactly what are the expectations.

Yes it's true, that if API key is removed from configuration it'll be then removed on AWS side, I believe that's expected behavior by most of users (we should be able to deactivate keys, and removing them signals such intent)

@orasis if you believe I misunderstood this issue, and feel it's still important to address, please elaborate so I have good reasoning.
