### ISSUE TITLE
Setting API key in serverless.yml needs further configuration

### ISSUE THREAD

**Issue by bassbump** [serverless/serverless#2840]
For it to work you also have to define a Usage Plan and manually add the API key to the Usage Plan in your AWS console.

Maybe this should be documented as well here https://serverless.com/framework/docs/providers/aws/events/apigateway/#setting-api-keys-for-your-rest-api

**Comment by ngocketit** [comment]
Absolutely agree! I took me almost 1 hour just to find out that the call fails because I haven't created and associated an usage plan for the api key. Does the framework support doing all that automatically when deploying?

**Comment by pmuens** [comment]
Hey @ngocketit thanks for your feedback! 👍 
Unfortunately, the attachment of Usage Plans to API Keys is not supported via CloudFormation so far.

Additionally it depends on the state your account is in (if you've enabled usage plans for your account) if the current Serverless implementation lets you use API keys out of the box (if you've opted in for usage plans you need to wire them up manually).

I'll submit a PR with a doc update so that other users are aware of this.
