### ISSUE TITLE
AWS service proxy integration for API gateway without Lambda

### ISSUE THREAD

**Issue by jong-eatsa** [serverless/serverless#2841]
# This is a Feature Proposal

## Description
AWS service proxy integration for API gateway with other services (e.g. Kinesis or S3) _without_ going through a middleman lambda function.

Currently I can either
* Use middleman lambda as a proxy to call ```putRecord``` into Kinesis Stream/Firehose (or S3 equivalent) using the AWS client as showcased [here](https://github.com/pmuens/serverless-kinesis-streams).
* Use AWS console to create an ```AWS service proxy``` integration type for API Gateway as described in the official AWS documentation for [kinesis](http://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-kinesis.html) and [S3](http://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-s3.html)

To implement this I could see the AWS service proxy being just another resource to configure in ```serverless.yml```

A typical use case would be a real-time data collector / buffer. A client-side webhook would push data to the API Gateway endpoint, and it would eventually make its way to S3 or Redshift (via Kinesis Firehose) directly without incurring lambda calls.

Similar or dependent issues:
* #2488

**Comment by dt4k** [comment]
+1 for this

**Comment by cdichiara** [comment]
+1

**Comment by emotazedi** [comment]
Big +1

**Comment by timothyBRZ** [comment]
Would be great to pass data between API Gateway to DynamoDB without having a Lambda function in the middle.

**Comment by Agent-Smith200** [comment]
+1 This would be great.

**Comment by cdichiara** [comment]
BTW, I've done a bypass in serverless v1.6 to make a DynamoDb proxy call work within the framework ... I didn't put it up before because I assumed other folks were doing the same thing and it might send the signal that this feature isn't so greatly needed ... but now I think it might be helpful to post. I'm sure you could change this up for other types of proxy calls, I just haven't done them yet.

Thank goodness for resources:Resources: being loaded after all of the serverless code runs ... otherwise we'd be dead in the water with so many tweaks we have to do to serverless to make it work with IAM, etc.

[apigProxyConfig.yml.txt](https://github.com/serverless/serverless/files/758516/apigProxyConfig.yml.txt)

**Comment by softe1988** [comment]
+1 would be super helpful

**Comment by pmuens** [comment]
@jong-eatsa thanks for opening this.

Right now the Framework is a deployment tool which helps developers deploy their Functions to different FaaS providers so the unit of deployment is the function.

We see the value in this addition but don't want to introduce it to the Framework core.

However this feature could be a great Serverless plugin (https://github.com/serverless/plugins) users can add to have support for something like this.

**Comment by AndrewSwerlick** [comment]
@pmuens even if the unit of deployment is a function, there might still be a reason for this, at least in a really specific scenario. As far as I can tell at this point, using a service proxy is the only way to have the API gateway invoke your lambda function asynchronously. This is helpful for chat platforms like slack, which expect a response quickly, to acknowledge you received the event, but expect that you'll continue processing and post something back via their own api when you're done.

**Comment by gligorkot** [comment]
Having this functionality would be really beneficial for us too. I hope you reconsider, or someone provides a plugin for this.

**Comment by RhysC** [comment]
While i think this would be great i think @pmuens response is pretty sensible. This should be a plugin and not dilute the core focus of this project which is FaaS

**Comment by orasis** [comment]
+1.  I'd like to see a model where api gateway goes directly to kinesis which *then* executes a lambda so everything can be fast and async with minimal lambda time.

**Comment by digitalray** [comment]
Anyone know if there is a plugin for this?

**Comment by horike37** [comment]
I just published the plugin. Let me know if you have any feedback or opinion 👍 
https://github.com/horike37/serverless-apigateway-service-proxy

**Comment by thorbenheins** [comment]
Hi @horike37,

thanks for the plugin. I tried it and it basically works. For our use-case we need a lot more features we want to configure of ApiGateway, so it does not suffice our needs unluckily. As i have 0 node.js experience (and no time to dive into it right now) i won't be able to support you create the needed features. 

Thanks anyhow!

**Comment by horike37** [comment]
Hey @thorbenheins, thank you for the feedback 😄 
Would be great to leave a comment the detail of your use-case on an issue of the plugin repo if you would like. The plugin still BETA so would like to keep improving based on users feedbacks.

**Comment by ed-sparkes** [comment]
Hi, this is  a great idea and thanks to @horike37 for initial plugin work. I have been looking into this and was in the process of  extending @horike37 plugin to support S3 and custom authorizer functions when i realized i would end up copying a lot of the boilerplate for api gateway integration from the core lib and the only bit that really needs to be different to support these extra services is the Method Integration Request and Response.

Is there any chance the core lib could updated to allow the Method Integration to be passed through to the core API Gateway compilation, and then the libs exposed so that a plugin could make use of the core api gateway code and simply concern iteself with the missing Method Integration types e.g. SQS, S3 etc. 

Just seems completely wrong to replicate all this behavior from a maintenance perspective. 

The benefit of this approach would be that any changes to AWS platform with regard to the parts of the API Gateway config that arent Method Integration would be updated in the core lib and the plugin would benefit. 

Interested in peoples thoughts and happy to contribute where I can. 

Thanks, Ed

**Comment by otehrani1** [comment]
i have installed the plugin and when trying to do serverless deploy 
i get 
 Type Error ---------------------------------------------
 
  this.provider.getApiGatewayDescription is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 

here's my serverless.yml

custom:
  region: us-west-2
  accountID: 11111111
  stage: dev
  apiGatewayServiceProxies:
    - kinesis:
        path: /kinesis
        method: post
        streamName: { Ref: 'YourStream' }
        cors: true

resources:
  Resources:
    YourStream:
      Type: AWS::Kinesis::Stream
      Properties:
        ShardCount: 1
functions:
  :
    handler: do-something.handler
    events:
      - s3:
          bucket: ${file(./config.yml):${self:provider.stage}.my-s3-bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: location/in/bucket/
            - suffix: .csv
provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  timeout: 30
  memorySize: 128

plugins:
  - serverless-apigateway-service-proxy


and here's what i have in my serverless folder

ls
node_modules				package.json				serverless.yml
package-lock.json			serverless-apigateway-service-proxy

and the string only exist in here 
grep -lr getApiGatewayDescription *
node_modules/serverless/lib/plugins/aws/provider/awsProvider.js
node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js

what am i missing ?
