### ISSUE TITLE
Invoke Local: Java Support

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#2864]
We'd love to add support for Java in invoke local. The way this would work is to spawn a child process that runs a java binary `bin/invoke-local-java` that would handle this local invocation.

We're not great in the Java world, we'd really appreciate it if someone with good Java experience could jump on this so we can include it in the next release. 😊 

Related: #2700, #2862

cc/ @serverless/vip

**Comment by volphy** [comment]
Can we leverage SAM Local (CLI):
https://github.com/awslabs/aws-sam-local#invoke-functions-locally
?

SAM Local is currently in beta but it already looks promising.

**Comment by RafalWilinski** [comment]
FYI: I've started working on it [here](https://github.com/RafalWilinski/serverless/pull/2/files)

I've managed to run Java artifact from `invoke local` command but passing event is a whole different story due to lack of JSON parsing functionality built-in to Java. This requires adding dependency & dependency manager which in my opinion might be _too big_. Any ideas?

**Comment by andrew-templeton** [comment]
Lazy load / install the dependency on first attempted java invocation? Seen that pattern before.

**Comment by RafalWilinski** [comment]
As @andrew-templeton suggested, I've proceeded with that approach - https://github.com/RafalWilinski/serverless/pull/3/files. Passing event data works but I've decided to not implement *custom* context yet and focus on core functionality. 

1. User fires cmd `serverless/bin/serverless invoke local -f hello -d '{"key":"value"}'`
2. Serverless checks if JS <-> Java bridge is already built
a. If it's not, then it's running `mvn package` to download all the dependencies and build executable JAR.
3. Once bridge is built, Serverless runs it with all the necessary parameters. Event is passed via STDIN just like in Python.
4. Bridge parses the event, loads selected function artifact dynamically using reflection and invokes  function locally. 

Remarks/todo:
1. Passing custom context might be even trickier if not impossible.
2. [Default context methods are not yet implemented](https://github.com/RafalWilinski/serverless/pull/3/files#diff-76cd81d4c50a24bed746e089b8e0b5d8R9), I wanted to focus on the core.
3. In order to get correct output, developer will have to implement `toString` method of `ApiGatewayResponse` class. If it's not there, output looks like this: `com.serverless.ApiGatewayResponse@42e26948`

Let me know if that solution is acceptable for you so I could continue working on that or if it's too complicated. 
I'm also wondering, if this command (`invoke local`) would be still needed when https://github.com/serverless/emulator will be 100% operational.

**Comment by cagataygurturk** [comment]
@RafalWilinski you should also add Gradle support. Or better ask the build command from the user so the project can be used by any JVM language that can have different build systems.

**Comment by RafalWilinski** [comment]
@cagataygurturk Maven builds only the JS-Java bridge that ideally would be able to invoke any JVM-based artifact.

**Comment by pmuens** [comment]
Great!!! Thanks for starting this @RafalWilinski 👍 🎉

An MVP implementation sounds good! We'll look into your branch the upcoming days 💪.

**Comment by volphy** [comment]
If Maven is needed anyway, would it not be easier to use lightweight JSON (i.e. no transitive dependencies needed) Java library such as gson::
https://github.com/google/gson

?

**Comment by fr3dm4n** [comment]
I have to questions:
1. Can we update the [documentation](https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/). Adding something like: "If you want to run Java, you need to install maven"
2. If I do:
```
sls create --template aws-java-gradle --name test --path test
cd test
./gradlew build
sls invoke local -f hello
```
I see:
```
Serverless: Building Java bridge, first invocation might take a bit longer.
```
... and nothing happens. The process runs for all eternity.
Shouldn't I see any Logs/Outputs?

Serverless version is 1.26.1

**Comment by javahaxxor** [comment]
same here unfortunately ..
