### ISSUE TITLE
body object appears normal when invoked locally, but errors when deployed

### ISSUE THREAD

**Issue by samcorcos** [serverless/serverless#2914]
# This is a (Bug Report / Feature Proposal)

Bug report

## Description

For bug reports:
* What went wrong?

`body` object appears normal when invoked locally, but errors when deployed. It failed silently and did not log anything in cloudwatch and responded with a `500` error.

It also works on Lambda when the function is tested in the AWS console, but appears to break when it hits API gateway.

* What did you expect should have happened?

I would expect the function to either pass in both environments or fail in both environments—not pass tests, then fail after deployment.

* What was the config you used?

This version worked locally but failed in deployment:

```js
  return callback(null, {
    statusCode: 200,
    body: {
      message: ‘works locally and passes tests, but breaks when deployed’,
    },
  })
```

This version works in both:

```js
  return callback(null, {
    statusCode: 200,
    body: JSON.stringify({
      message: ‘works locally and deployed’,
    }),
  })
```

* What stacktrace or error message from your provider did you see?

None

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

If a response body is not stringified, it should fail locally.

* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: OSX
* ***Stack Trace***: none
* ***Provider Error messages***: none

**Comment by eahefnawy** [comment]
@samcorcos yeaaah we've been discussing this internally. The thing is `invoke local` tests the **lambda** function not APIG. And per your confirmation, it works locally and remotely when invoked directly (without APIG).

I think what you're looking for is local emulation of APIG, which is really hard to do (emulating an entire AWS service locally?!). However, the [serverless-offline](https://github.com/dherault/serverless-offline) plugin might be of help here.

Anyway, I'm closing this because it's not really a bug, since invoke local was not meant to emulate APIG. 

Thanks for opening up! 🙌
