### ISSUE TITLE
Environment Variables for Lambda wiped out if set from a different part then serverless CF

### ISSUE THREAD

**Issue by riccardo-89** [serverless/serverless#2955]
# Feature Proposal

Possibility to update Lambda Configuration Environment Variables from a different context and not only from serverless without having them wiped out randomly on deployments.

## Description

For feature proposals:

* What went wrong?

I do prefer to not send any environment variable to the client project and avoid that the project itself set the env variables because I think is more secure to set those directly from my infrastructure stack by updating the LATEST lambda configuration. 

Sometimes it happens (not really sure when because it does not happen always) that configuration variables are wiped out after serverless deployments.

* What did you expect should have happened?

I do expect that environment variables for the lambda configuration are ignored if the "environment" prop is not setup on the serverless.yml

Thanks a lot! :D 

* ***Serverless Framework Version you're using***: 1.3
* ***Operating System***: MacOS

**Comment by mthenw** [comment]
It would cause the deployments completely unpredictable because there would be no single source of truth. 

Regarding securing env vars please check existing example for that https://github.com/serverless/examples/tree/master/aws-node-env-variables-encrypted-in-a-file and also consider using KMS for that.
