### ISSUE TITLE
No updates are to be performed - exit code 1

### ISSUE THREAD

**Issue by nicka** [serverless/serverless#2981]
# This is a Feature Proposal

## Description

```
Serverless: Updating Stack...
 
  Serverless Error ---------------------------------------
 
     No updates are to be performed.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.2.1
     Serverless Version: 1.4.0
 
error Command failed with exit code 1.
```

I'm not sure how the rest of us feel about this, but I did not expect the `exit code 1`. Do we want to change this? In our case it failed our CI deployment.

**Comment by paulSambolin** [comment]
Same here, an error code 1 in codebuild returns build failed in our code pipeline.  I don't think it should be an error that the stack already exists. Maybe a warning

**Comment by paulSambolin** [comment]
@nicka I was unable to issue a pull request (permissions?) but I have a fork that quietly kills the exception at https://github.com/paulSambolin/serverless

**Comment by nicka** [comment]
@paulSambolin Sorry I'm not member of the core team ;) but in any case you should be able to create a new PR.

**Comment by pmuens** [comment]
@paulSambolin thanks for jumping in! 👍 

You can always PR via your fork. Let us know if you need any help!

**Comment by paulSambolin** [comment]
![screen shot 2016-12-21 at 10 34 16 am](https://cloud.githubusercontent.com/assets/14282579/21395061/0ec0239a-c769-11e6-87cc-447f4033a06e.png)
@pmuens When I go to create one my pull request button is greyed out.  My first real attempt at an OS project so if I am missing a step or something else please let me know

**Comment by pmuens** [comment]
@paulSambolin hmm that's strange. Have you committed your work on a separate branch? 

According to the screenshot you want to merge `master` from your fork into `master` from Serverless which might be not possible because there's nothing changes yet.

Here's a step by step guide how you can submit a PRs from your fork:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

The steps are basically the following:
1. Fork the Serverless repo
2. Create a new branch in your fork and work on it (commit the changes to your branch)
3. Open up a PR and say that you want to merge `your-branch` with the changes into `master` of Serverless

Let us know if this resolves your problem or if you need any further help! 👍

**Comment by nicka** [comment]
@paulSambolin Fill in the PR title 🎉

**Comment by pmuens** [comment]
Woops I missed that 😬 ! Nice catch @nicka !

**Comment by paulSambolin** [comment]
Haha fail

**Comment by mthenw** [comment]
@nicka could you provide repro steps for that issue?

**Comment by nicka** [comment]
@mthenw That's a though one since it happened within our CI setup 🙈  But the moment the framework allows for resource only updates (read that somewhere) we will definitely see this issue more often.
