### ISSUE TITLE
Reduce memory consumption when zipping service / individual functions

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3054]
# This is a Feature Proposal

## Description

The current zip implementation eats lots of memory e.g. when functions are zipped individually. We should come up with a way to reduce the zipping memory footprint so that e.g. CI / CD systems won't fail.

Here's an example service which can be used for benchmarking / testing the zipping functionality:

https://github.com/pmuens/serverless-service-zip-testing

Furthermore @dougmoscrop created a first draft to improve the zipping:
https://github.com/serverless/serverless/pull/3006

/cc @dougmoscrop @ryansb

**Comment by vladgolubev** [comment]
What about taking same approach as @meteor ? They use native `tar`, native `7zip` and only then fallback to javascript zip implementation. Here is their PR: https://github.com/meteor/meteor/pull/7457

**Comment by pmuens** [comment]
@vladgolubev thanks for the suggestion! That sounds indeed interesting!

Seems like it has reduced the zipping time a lot. Do you know anything about memory consumption since this is the bottleneck right now?

**Comment by vladgolubev** [comment]
@pmuens huge thanks for the example repo! It helped a lot to perform these tests. Here are the results:

<details>
<summary>for i in {1..10}; do zip -r "native-${i%/}.zip" . -x *.serverless* -x *native* --quiet; done</summary>

```bash
$ /usr/bin/time -v ./native-zip.sh 
	Command being timed: "./native-zip.sh"
	User time (seconds): 30.12
	System time (seconds): 0.93
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:31.14
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 3244
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2416
	Voluntary context switches: 27
	Involuntary context switches: 719
	Swaps: 0
	File system inputs: 0
	File system outputs: 1953600
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

</details>


<details>
<summary>serverless deploy --noDeploy</summary>

```bash
$ /usr/bin/time -v ./serverless-zip.sh 
Serverless: Packaging service...
Serverless: Did not deploy due to --noDeploy
	Command being timed: "./serverless-zip.sh"
	User time (seconds): 62.70
	System time (seconds): 4.09
	Percent of CPU this job got: 225%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:29.56
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1184404
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 107
	Minor (reclaiming a frame) page faults: 393244
	Voluntary context switches: 104943
	Involuntary context switches: 118153
	Swaps: 0
	File system inputs: 266984
	File system outputs: 1954040
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

</details>



<details>
<summary>for i in {1..10}; do 7z a -r ../"severn-zip-${i%/}.zip" . 2&>/dev/null; done</summary>

```bash
$ /usr/bin/time -v ./seven-zip.sh 
	Command being timed: "./seven-zip.sh"
	User time (seconds): 70.72
	System time (seconds): 1.80
	Percent of CPU this job got: 328%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:22.10
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 149200
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 32048
	Voluntary context switches: 989
	Involuntary context switches: 27528
	Swaps: 0
	File system inputs: 0
	File system outputs: 2740968
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

```

</details>


| **Command** | **Time** (m) | **RAM** (max rss) | **CPU** |
|-------------|----------|------------|---------|
| sls         | 0:29     | 1156MB     | 225%    |
| 7z          | 0:22     | 145MB      | 328%    |
| zip         | 0:31     | 3.16MB     | 99%     |

So we have a chance to reduce memory consumption at least in 10 times!

But ok, measuring pure `zip` without node.js overhead is a bit unfair.

So I modified `/lib/plugins/package/lib/zipService.js` to spawn a `zip` command instead of using `archiver`:

| **Command** | **Time** (m) | **RAM** (max rss) | **RAM (avg)**| **CPU** |
|-------------|----------|------------|----------|---------|
| sls (arhiver)         | 0:27     | ~1165MB     | ~900MB | 236%     |
| sls (7z)          | 0:28     | ~720MB      | ~88MB  | 318%    |
| sls (zip)         | 0:17     | ~700MB     | ~89MB  | 304%    |

Note: 704MB with `zip` was only during last split seconds, probably because of writing file buffer to disc or sort of.

Also `zip` is 10 seconds faster now because functions are packed in parallel, unlike to my example above.

The only concern left is Windows users. Should we fallback to archiver or include 7zip binary to npm package?

**Comment by dougmoscrop** [comment]
Is it too ambitious to suggest that archiver be a good place to introduce
this native-or-fallback logic rather than having "everyone else" have to go
down this separate discovery? Or has this already been discussed and
rejected? Sorry if so.

**Comment by pmuens** [comment]
@vladgolubev awesome! Thank you very much for benchmarking! Impressive results!

@dougmoscrop I agree. That is a really good idea. I can imagine that other users might have also faced the issue and will benefit from it. 👍

**Comment by ryansb** [comment]
The way I've gotten around this thus far has been to use the `zip` command and set the `artifact` parameter manually, so that the `sls` command doesn't try to zip files up at all.

**Comment by vladgolubev** [comment]
I'll submit a PR on this soon. The trickiest part was include/exclude... Although `zip` has `--include` and `--exclude` arguments, they don't work in the way serverless expect, like `!` or overrides, or I did something completely wrong.

**Comment by ryansb** [comment]
Yeah, the ! overrides aren't the same. I used the `--exclude @exludes.lst` feature to keep excludes in their own file so they don't have to be escaped (lest the shell interpret them as wildcards). Feel free to @ me on that pull request and I can test it out.

**Comment by pmuens** [comment]
@vladgolubev thank you very much for the PR and the work you've done here!

I've added it to the 1.7 milestone since this needs more thoroughly testing. Have you opened up an issue in the archiver `npm` package to discuss whether this can be added to the package (like @dougmoscrop proposed)? Could be interesting as other project might face the same problems.
