### ISSUE TITLE
wish: document whether .serverless should be checked into Git

### ISSUE THREAD

**Issue by markstos** [serverless/serverless#3137]
# This is a Feature Proposal

## Description

`serverless deploy` creates a `.serverless` directory with files in it. It's not initially clear whether these need to be kept, are safe to delete, or should be checked into .git.  (From further review and testing, it appears that the directory can be safely deleted). 

There is a bit of documentation about this directory already, but it's hard to find the docs until you realize that the directory is related to the "deploy" command or that the files in it are called "Artifacts". 

What would be helpful is a simple "README.md" that gets created in the directory at explains what the files in are for, whether they can be safely deleted and whether the directory should be checked into it. People curious about the directory would naturally find that file without wading through all the online docs trying to figure out the details of the directory. 

## Additional Data

* ***Serverless Framework Version you're using***:

serverless 1.5.1

* ***Operating System***:

Ubuntu 16.04

* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for the feedback on the docs and the idea to add a paragraph about this @markstos 👍 

**For everyone curious:**

The `.serverless` directory is used to store the deployment assets. The files you can find in there are always re-generated when running `serverless deploy` or `serverless deploy --noDeploy`. It's recommended to .gitignore it since it'll change quite frequently.

**Comment by pmuens** [comment]
Closing this since it's quite stale and all our templates now have a `.gitignore` which adds a statement to igonre `.serverless`.
