### ISSUE TITLE
DX: Add ability to preview populated serverless.yml

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3224]
The variable system is ultra powerful and amazing!

However it is super confusing to people unfamiliar with a given project and the [variable syntax](https://serverless.com/framework/docs/providers/aws/guide/variables/)

![image](https://cloud.githubusercontent.com/assets/532272/22808793/afa31204-eee2-11e6-82f1-ae13371be091.png)

Additionally working with nested variables is really cool but hard to get right.

**It would be a huge UX/DX win if you could preview the output of the `serverless.yml` file populated with it's final variables before deploying.**

Something like `serverless deploy --dry-run` or `serverless info variables`

Then you could preview what exactly your config files (or CLI options) are actually resolving to in the final `serverless.yml`

---

I felt this first hand with creating https://github.com/serverless/scope/blob/master/backend/serverless.yml and would have freaking loved a preview option to see what was going with the final serverless.yml that was being deployed.

**Comment by pmuens** [comment]
Big 👍 for this one!

Related issue is: https://github.com/serverless/serverless/issues/2366

**Comment by DavidWells** [comment]
I figured out how to implement this.

What should the command be to run this?

`serverless deploy --dry-run` or something else?

cc @pmuens @eahefnawy

**Comment by pmuens** [comment]
@DavidWells nice!

Will this create a file or just show the whole `serverless.yml` on the console?

If it creates a file we could maybe re-use / add it to the `serverless package` command or create an `inspect` / `debug` command or smth. like that.

Doing this in `deploy` might be cumbersome since then we have to interrupt / stop the lifecycle events and therefore re-introduce the `--noDeploy` `if` checks we've recently tried to remove.

**Comment by mthenw** [comment]
This issue could be partially (if not completely) solved by introducing change sets with nice diff feature.

**Comment by pmuens** [comment]
@mthenw are you sure that this solves the issue?

AFAIK the idea here is to show the `serverless.yml` file with all the populated variables and stuff like that. The `serverless.yml` file is used to deploy the service, but I think it would be easier if I can take a look at the `.yml` rather than the CloudFormation changeset.

**Comment by DavidWells** [comment]
Changesets would be freakin' awesome and I'm for it! @mthenw any thoughts on how that can be achieved?

I think as a first (easier) step is simply showing how the `serverless.yml` variables are resolving.

The idea is fast feedback on what is actually happening with the variables being used for debugging etc before deploys

**Comment by mthenw** [comment]
@pmuens @DavidWells 

Hmm, running `serverless deploy --dry-run` should show something similar to `git diff` (where `+` and `-` indicates what's been added/changed/removed):
```
functions:
  helloworld:
-   memory: 1024
+   memory: 512

resources
  UsersDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
-          ReadCapacityUnits: 1
+          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
```

**Comment by mthenw** [comment]
So effectively just diff on `serverless.yaml`

**Comment by eahefnawy** [comment]
@DavidWells super nice idea 👍 ... but always keep in mind that many of the variables values are sensitive, specially if you're gonna output the populated config file (should be .gitignored...etc)

**Comment by eahefnawy** [comment]
@DavidWells here's another idea, what if the info plugin would list the referenced variables and their populated values?

```
Variables:
  ${opt:stage} => production
  ${self:provider.name} => aws
  ... and so on ...
```

I believe this would be better experience because it allows the user to focus on the variables only, rather than trying to decrypt what was populated where in the populated `serverelss.yml`.

**Comment by DavidWells** [comment]
@eahefnawy I like the idea of simply adding `Variables` to `sls info` output.

Using this approach how would the `opt:stage` fields be populated? `sls info --stage dev` ? 

Also I agree with you on not writing these to a file b/c the reasons you mention (ie sensitive keys)

**Comment by eahefnawy** [comment]
Whenever someone hits `sls deploy` or `sls info`, they'll see exactly the above screen based on the params they passed, so if they run `sls deploy -s production` they will see `${opt:stage} => production`, if they run `sls deploy -s qa` they'll see `${opt:stage} => qa`. You can think of it as a key/value pair of the variable and it's value as detected/populated by the framework.

Is that what you're asking?

**Comment by DavidWells** [comment]
I thought you were proposing:

When a user runs the `sls info` command, they would see the variables populated like:

```yml
Service Information
service: serverless-hello-world
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  GET - https://efi4rjb098.execute-api.us-east-1.amazonaws.com/dev/hello-world
functions:
  helloWorld: serverless-hello-world-dev-helloWorld
Variables:
  ${opt:stage} => production
  ${self:provider.name} => aws
  ... and so on ...
```
However, just running `sls info` will not know what `opt:stage` is referring to because that flag is not provided by just running `sls info`.

So perhaps this would need to be part of the `sls deploy` command as a `--dry-run` flag?

**Comment by pmuens** [comment]
I'm not sure if we should extend the `info` / `deploy` command here.

Imagine that you want to see your variables without having anything deplotyed beforehand. This way the `info` command will break since it relies on a stack to be deployed.

Furthermore we need to extend `info` / `deploy` in such a way that it displays the variables only when using a flag like `--dry-run` etc. which will result in messy code and tech debt.

I'm more in favor to introduce a new command like `preview` or whatever which will just show the variables and their replacements like this:

```yml
serverless.yml variables:
  ${opt:stage} => production
  ${self:provider.name} => aws
  ... and so on ...
```

This way we also reduce the usage of screen real estate.

**Comment by eahefnawy** [comment]
> Imagine that you want to see your variables without having anything deplotyed beforehand. This way the info command will break since it relies on a stack to be deployed.

I'm not sure I'm following. Listing vars/values in info command doesn't depend on the stack at all, unless of course the user chooses to ref outputs in other stacks, but he's responsible for those stacks he's referencing.

> I'm more in favor to introduce a new command like preview or whatever which will just show the variables and their replacements.

Imo creating a new command is a lot higher in technical debt! Not to mention that we have to document that new command and make sure people can find it. I think we should try to keep our list of commands minimal.

**Comment by eahefnawy** [comment]
@DavidWells thats exactly what I'm proposing, and no matter what users have to provide the referenced option regardless if it's `info` or `deploy`. Keep in mind that whatever we update in the info plugin would update the deploy plugin too because info runs right after deployment.

**Comment by pmuens** [comment]
> I'm not sure I'm following. Listing vars/values in info command doesn't depend on the stack at all, unless of course the user chooses to ref outputs in other stacks, but he's responsible for those stacks he's referencing.

Running `serverless info` without having the service deployed yields to the following error message when run in `master`:

```
root@739863a1d627:/app/service# ./bin/serverless info
 
  Serverless Error ---------------------------------------
 
     Stack with id complex-service-dev does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.9.0
     Serverless Version: 1.13.1
```

IMHO `serverless info` is about the info of the deployed service and has little to do with `serverless.yml` and the populated variables.

> Imo creating a new command is a lot higher in technical debt!

Yes, that's more like a personal preference. I just revisited the hustle we went through removing `--noDeploy`. It was spread all over the codebase and was written in places you wouldn't necessarily expect it to be.

IMHO providing this functionality as a separate plugin is way easier to remove / refactor later on since it's a unit of its on. If you don't want it anymore, then just remove it from `Plugins.json`.

I agree that we should keep the list of commands minimal, but IMHO that shouldn't be the show-stopper here. There should be ways in the future to hide commands from the list though (AFAIK @HyperBrain already implemented smth. like that in the `PluginManager`).

Just my 2 cents here...

**Comment by pmuens** [comment]
Cross-linking the most recent issue about this (#4215) and https://github.com/serverless/serverless/issues/4125#issuecomment-323476189 here.
