### ISSUE TITLE
Increase log lines limit

### ISSUE THREAD

**Issue by aletheia** [serverless/serverless#3226]
I've experienced a strange behavior, that think is related to 
https://github.com/serverless/serverless/blob/3733f49d3d9c419543051fbbb4dffa93ce916706/lib/plugins/aws/logs/index.js#L38
that limits returned logs to 50 lines (probably not always ordered by Cloudwatch)
It should be increased or multiple fetch taken into account

Could that be possible?

**Comment by RafalWilinski** [comment]
@aletheia Thanks for reporting feature request.

Judging from the docs, it seems that `50` is the [upper limit for a single `describeLogStreams` call](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogStreams.html#API_DescribeLogStreams_RequestSyntax). 

In order to exceed that limit we'd need to recursively call that API until we reach the end (nextToken is undefined) or desired number of entries, specified by e.g. `--limit` flag. 

Is adding `--limit` flag ok for you?

cc @pmuens

**Comment by RafalWilinski** [comment]
Btw, I think this feature is not so needed because there's [a `startTime` flag](https://github.com/serverless/serverless/blob/3733f49d3d9c419543051fbbb4dffa93ce916706/lib/plugins/logs/logs.js#L31).  You can just put 1.1.2001 here and whole history will be pulled from the API.

**Comment by pmuens** [comment]
Thanks for opening and thanks for replying @RafalWilinski 👍

Yes, we could use `nextToken` to fetch more logs, but IMHO the best approach would be to use the `startTime` flag as @RafalWilinski mentioned above 🔝.

**Comment by pmuens** [comment]
Closing this issue for now since the approach @RafalWilinski showed should be a viable solution.
