### ISSUE TITLE
self signed certificate issue

### ISSUE THREAD

**Issue by MichaelBowers** [serverless/serverless#3230]
I've tried running the samples as follows:

1. serverless create --template aws-nodejs --path myService
2. serverless deploy

I get the following error message:

  Error --------------------------------------------------
 
     ServerlessError: ServerlessError: self signed certificate
     in certificate chain
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.0.0
     Serverless Version: 1.6.1

I've searched documentation in vain for information on either configuring serverless to allow self signed certificates, and am not sure if this is something that should be configured in AWS itself somewhere?  Documentation in this area would be helpful!

**Comment by pmuens** [comment]
Thanks for opening @MichaelBowers 👍 

Closing this one since the issues is stale and we've pushed a bunch of fixes in the meantime. Feel free to re-open if you still face this bug!

**Comment by beb-bang** [comment]
Hi - I've just run into this today. I'm using the latest version of Serverless, 1.17.0, and I know exactly what the issue is just not how to correct it. 

I've recently begun testing deep packet inspection in my network. The firewall is decrypting, inspecting, and reencrypting my SSL traffic for malware and such. There is a firewall generated, self-signed certificate deployed to the local CA trust store, and for other applications that don't use the OS's trust store I've had to add the self-signed cert somewhere/somehow.

For example, git requires:
`git config --global http.sslCAInfo <path to cert.pem>`

npm has a similar functionality for adding a reference to the cert or strict checking can be disabled with:
`npm config set strict-ssl false` 

So... question is: how might I add or reference the self-signed cert in serverless? 

```
Serverless: Packaging service...
  Serverless Error ---------------------------------------
  ServerlessError: self signed certificate in certificate chain
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.10.3
     Serverless Version:     1.17.0

```
In the serverless documentation for OpenWhisk, there is a reference to a property of the provider called "ignore_certs" that can be set to true. I'm using AWS, but tried this anyway and it did not change the result. 
![image](https://user-images.githubusercontent.com/19676403/28395436-e1c06996-6ca8-11e7-9074-b748f9b29b2b.png)
https://serverless.com/framework/docs/providers/openwhisk/guide/credentials/#register-with-openwhisk-platform-self-hosted

Any suggestions would be greatly appreciated. 

Cheers!
Bryan

**Comment by yowainwright** [comment]
This issue still exists.

**Comment by RichardSilveira** [comment]
I'm solved by setting up a environment variable "ca" with pem string content from the certificate.

For **windows user**, you may search for a openssl command that read your certifcate path file and returns to you the cert "pem" content, something like this:
```
-----BEGIN CERTIFICATE-----\n
MIIDqjCCApKgAwIBAgIQYgDGmc0IY5xP+L5uIpWpWTANBgkqhkiG9w0BAQUFADBH\n
XXXXX/IsZAEZFgRwam10MRgw\n
FgRwam10MRgwFgYDVQQDEw9wamA10LUFEVEotMDEtQ0EwggEiMA0GCSqGSIb3DQEB\n
AQUAA4XXXXXXXBE\n
bEVl+3Mp0JblcM5SJy+/A83fN3jf1dOP34MW/bwtnZSdyQiaaC3jEEAweBFWrGZd\n
oNcmSzJOWcuD+AABO946BP9X0/S1wbDn42nKGblZ\n
-----END CERTIFICATE-----
```
**And set it up as a single line string.**

**Note**: The _\n_ should be inserted manually, if doesn't have!


The serverless version 1.26.0 at some place has a code that read this env var (i don't tested new version).

**Comment by corydorning** [comment]
@RichardSilveira thanks! your suggestion worked!
