### ISSUE TITLE
Broken Link to Azure NodeJS Example

### ISSUE THREAD

**Issue by murraybauer** [serverless/serverless#3296]
The link on this page to 'Azure Node Simple' example code is broken. I can't find the example anywhere.

https://serverless.com/framework/docs/providers/azure/examples/

**Comment by pmuens** [comment]
Nice catch! Thanks for reporting @murraybauer 👍 

The PR https://github.com/serverless/examples/pull/98 is not merged yet because it needs some updates. The link should be fine once this PR is merged.

In the meantime you can explore the service here: https://github.com/christopheranderson/examples/tree/9e25f7ca9d5b2b81793ea60dbbd2c266af2d45d4/azure-node-simple-http-endpoint

**Comment by DavidWells** [comment]
@pmuens merged  serverless/examples#98

**Comment by pmuens** [comment]
Great. Thanks for merging @DavidWells 👍
