### ISSUE TITLE
Allow multiple API Gateways in a single project

### ISSUE THREAD

**Issue by jaikdean** [serverless/serverless#3340]
# This is a Feature Proposal

## Description

I have a project which provides two separate APIs, at different endpoints, for different audiences. As these interact with the same data and share some business logic, it makes sense to consider them a single project at keep deployments synchronised.

As such, I would like to have Serverless create more than one API Gateway in AWS, and specify which to use in the `http` event on my functions. Since this is likely a relatively uncommon use-case, a somewhat manual process involving defining a second API Gateway in `resources:` in `serverless.yml` would be totally reasonable.

Having looked at the code, it appears everything is hardcoded to use a single API Gateway at the moment.

Similar or dependent issues:
* #435 discussed this a while ago but was closed while it was considered

## Additional Data

None

**Comment by HyperBrain** [comment]
Allowing multiple APIs in one service, in my opinion, would make things very complicated (on a configuration side and on the implementation side).

For that scenario, you could create multiple services (one for each API) in the same repository like this:
```
   + myProject
   |
   + lib (for common components)
   |
   + service1 (for API 1)
      + serverless.yml
   |  + src (sources for service 1)
   + service2 (for API 2)
      + serverless.yml
```

You even can create deployment time dependencies between the services by using CF Output exports and import them into the other stack with Fn::ImportValue (Of course only one way, as otherwise you would have circular references)

**Comment by pmuens** [comment]
Closing since this issue is quite stale and @HyperBrain made a good point about additional complexity.

**Comment by lahdo** [comment]
+1
