### ISSUE TITLE
feature request: fast re-deploy all defined lambda functions

### ISSUE THREAD

**Issue by Kosta-Github** [serverless/serverless#3364]
Since it takes time to deploy the whole CF stack, there is this feature to fast re-deploy a single function via `sls deploy function -f <my_func_name>`.

I would like to propose to add an `-a` or `--all` option to `sls deploy function` to fast re-deploy all defined lambda functions.

**Comment by rowanu** [comment]
CloudFormation will only update resources that have changed. Since SLS re-packages the function code, it counts as a change every time.

The behaviour you've proposed is exactly what happens every time you do `sls deploy` _after_ the initial deploy of your service (as the first deploy creates dependent resources like buckets, API GW stages, etc).

**Comment by rowanu** [comment]
Oops, I stand corrected - I see a bunch of resources now get "random" strings attached, and are therefore re-deployed. My bad.

**Comment by Kosta-Github** [comment]
what I forgot to mention: I also manage the creation of additional resources via `serverless.yml` (e.g., `SQS`, `SNS`, ...), which probably leads to even longer deployment running times when done via `sls deploy`...

**Comment by RafalWilinski** [comment]
I think something like this _could_ work: https://github.com/RafalWilinski/serverless/commit/ddb63c13d83310614def1dcad382a486ebf42ef7

Can you tell me if I'm going in right direction?

**Comment by RafalWilinski** [comment]
cc @rowanu ☝️ ?

**Comment by rowanu** [comment]
@Kosta-Github resources created in the `Resources` section of the `serverless.yml` file will behave as I first explained - they will not be updated unless they _need_ to be updated (because CloudFormation).

@RafalWilinski yeah, that might work. I'm assuming the code version of the function is a parameter, so re-using the template is a good start (but I haven't checked in a long time).

**Comment by Kosta-Github** [comment]
@rowanu I know that the resources dont get recreated, but still running through the full CF procedure takes a consierable amount of time, which can be omitted in case you just want to update the lambda sources...

**Comment by rowanu** [comment]
@Kosta-Github the problem with that is that your changes now exist outside of CFN, which means you've effectively got configuration drift. While that might be OK in the development stage or with a toy project, it's just not good enough in the real world. It's hard for the framework to know which case it is so it does the safest thing, and that probably shouldn't change.

**Comment by andymac4182** [comment]
I am curious as to what is your requirement for it to be so fast @Kosta-Github? 

We develop locally which removes most of the need for this. We use `serverless-offline` or `serverless-plugin-simulate` https://github.com/serverless-community-labs/serverless-plugin-simulate

**Comment by AndrewFarley** [comment]
@RafalWilinski Can we get that "deploy-only" feature implemented/merged?  :P  This feature would help for CI/CD pipelines to allow for much quicker deployment times when only the code is updated, instead of having to script iterating through every function name and running `serverless deploy -f funcname`

**Comment by HyperBrain** [comment]
@AndrewFarley You have to be aware that all of this, also `deploy function` is not really usable for production services as it creates lambda versions that are not controlled by CF and any CF stack rollback will revert anything deployed with that. For dev where it does not need to be stable it is ok.
Also any function configuration that contain CF references will not be pushed again.

**Comment by AndrewFarley** [comment]
@HyperBrain Ouch... I didn't realize that.  That makes things a lot... more complicated, and I see now why this feature isn't implemented yet and/or is probably not even possible.  Thanks.

**Comment by HyperBrain** [comment]
The only real solution for all these kind of problems would be to add a differential deployment, i.e. SLS would retrieve the currently deployed CF template and just add stuff that changed. Then the CF deployment would be very fast and - deploy function could just use the same functionality.

**Comment by AndrewFarley** [comment]
@HyperBrain I'm just learning/realizing this now from you, after implementing a few CI/CD pipelines for clients who heavily leverage function deployments to speed up deployments.  Shouldn't we have more/better documentation and/or info in --help that contains this information?  This seems quite severe to know and understand before leveraging heavily (like I've done)

**Comment by HyperBrain** [comment]
Fully agree. This should be documented and mentioned properly.

**Comment by pmuens** [comment]
Closing this for now since this issue got quite stale. We've added support for accelerated S3 deployments which should address this problem.
