### ISSUE TITLE
Invoke local should support context.callbackWaitsForEmptyEventLoop

### ISSUE THREAD

**Issue by leeeomaaax** [serverless/serverless#3456]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Invoke local doesn't check the event loop before "executing" the handler callback.
* What did you expect should have happened?
Invoke local should replicate lambda behavior of waiting event loop to be empty before executing the handler callback, unless context.callbackWaitsForEmptyEventLoop is set to false.
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Even though this is a lambda specific behavior, I think this event loop flag could be added to the documentation. My suggestion is in the invoke sessions.

* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.9.0
* ***Operating System***:  macOS
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by mattmeye** [comment]
+1

**Comment by simonbuchan** [comment]
In the case when it is false, it should probably also immediately process.exit() as well?

**Comment by HyperBrain** [comment]
After a few thoughts, I think this is not as trivial as it seems. Taking the Node event loop into account when invoking functions locally, also would mean, that any external influences should be eliminated and only the code under test (the user's lambda code) should be counted for the event loop to qualify as empty.

In Serverless there are a lot of things running in the event loop (especially, if you're using plugins that offer a watch mode for the invoke).
A proper solution here might be, to change the invocation semantics in a way, so that instead of directly invoking the user's code, Serverless will create a [Node VM sandbox](https://nodejs.org/dist/latest-v8.x/docs/api/vm.html) and let the user function run in there. This guarantees that there are no external influences and we can really simulate a separated Lambda environment.

**Comment by dschep** [comment]
Hey folks, I've created a [PR](https://github.com/serverless/serverless/pull/5863) that uses the [`lambci/lambda`](https://github.com/lambci/docker-lambda) docker images, to more accurately replicate the lambda runtime environment and more runtimes. An initial search indicates that it does something with the `callbackWaitsForEmptyEventLoop` option, so, please check it out and test it by installing serverlesss like this:
```
npm i -g serverless/serverless#invoke-local-docker
```

**Comment by pmuens** [comment]
As @dschep described above 🔝 this will be resolved via #5863.

I just tested it today and it works great 👍
