### ISSUE TITLE
Add more documentation about --verbose mode for info plugin

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3485]
# This is a Feature Proposal

## Description

The `--verbose` option makes it possible to print out all the `Outputs` in the CloudFormation template when using e.g. the `info` command.

However this option is currently a little bit hidden so users might have a hard time to figure out that something like this exists.

In #2788 and we've discussed to print the `Outputs` by default. @tobyhede was kind enough to PR #3416 which adds this feature. However after some time thinking through this we might be better off to just add a little bit more documentation around this feature rather than displaying all the information about the CloudFormation template on every deploy / info command use.

/cc @brianneisler @eahefnawy

**Comment by tobyhede** [comment]
Just following up on this, happy to enhance the docs. 

Quick note on my PR - I made it so that only *custom* outputs that the user has added are displayed under info. The current verbose behaviour stays the same. 

So if you add a CFN output to your resource declaration, that will be displayed under info (which is quite handy if you want to grab things like ARNs). 

```
Outputs:
  DynamoDBReadName:
    Description: DynamoDBRead arn
    Value:
      Ref: DynamoDBRead

```
info:
<img width="354" alt="screenshot 2017-05-02 10 54 57" src="https://cloud.githubusercontent.com/assets/28390/25600250/2524af1e-2f26-11e7-8b38-bc960232edbb.png">

Verbose then stays the same and displays all of the resources. 

info verbose:
<img width="422" alt="screenshot 2017-05-02 10 57 07" src="https://cloud.githubusercontent.com/assets/28390/25600254/2b27bc62-2f26-11e7-851c-e8c53a96ac04.png">

**Comment by tobyhede** [comment]
This idea was based on the comment in the original thread here: https://github.com/serverless/serverless/issues/2788

**Comment by pmuens** [comment]
@tobyhede thank you every much for the in-depth explanation! 👍 

The main reason for sticking to the `--verbose` way was that adding the implementation to always display the `Outputs` might add too much technical debt for a feature which can be turned on by passing a flag. Furthermore stacks with a large amount of `Outputs` might "pollute" the console. Most of the time you just need a rought summary about your deployment and if you need additional information you could use the `--verbose` flag.

But thanks again for taking the time to provide a PR for the initial idea to always display the outputs.

We would really appreciate a PR to update the docs so that this feature with the `--verbose` flag gets more exposure and can be found more easily!

**Comment by pmuens** [comment]
Closing since this issue is quite stale and lots of updates have been shipped in the meantime.
