### ISSUE TITLE
Is it OK to take the cloudformation-update*.json and deploy it using CFN directly?

### ISSUE THREAD

**Issue by srikanna** [serverless/serverless#3556]
question:

With sls package features we can create the templates for various stages and store them in custom path! Which is great!
Now for deployment, do we have to use serverless deploy -p ... or Can i take the *update*.json template and update the stack using Cloudformation directly?

use case here is to use AWS codepipeline deploy stage [ with cloudformation ]... keep the build output for various stages very minimal and clean!

**Comment by pmuens** [comment]
Hey @srikanna thanks for asking!

Technically you could take your CloudFormation files and deploy them through CFN directly. But keep in mind that Serverless might manage other resources (such as the deployment bucket) for you so you need to ensure that e.g. your functions code is uploaded since the path to that is reflected in the CloudFormation file.

**Comment by pmuens** [comment]
Closing this one since the answer 🔝 should answer the question.

Feel free to re-open / write another comment if there's still something unclear.
