### ISSUE TITLE
Serverless can't deploy when using a linked profile with mfa_serial

### ISSUE THREAD

**Issue by lukeplausin** [serverless/serverless#3570]
Hi all,

I'm having an issue where I can't deploy to AWS with serverless when using linked profiles. My config and credentials files look like this:

(deploying to the *application* account)

config
```
[profile master]
output = json
region = eu-central-1

[profile application]
output = json
region = eu-central-1
source_profile = master
```

credentials
```
[master]
aws_access_key_id = AAAA12345678...
aws_secret_access_key = abcd12345...
mfa_serial = arn:aws:iam::123456789012:mfa/a.guy.called.luke

[application]
role_arn = arn:aws:iam::098765432109:role/Deployment
source_profile = master
mfa_serial = arn:aws:iam::123456789012:mfa/a.guy.called.luke
```

It seems like this issue is caused by the way that serverless parses the config file. It doesn't handle the case where there is an `mfa_serial` entry in the credentials file.

Might I suggest using the credentials resolver that comes built into the AWS SDK? It handles all this kind of stuff automatically.

Thanks :)

**Comment by Artur-A** [comment]
Hi,
I faced some related issue where `region` section is not loaded from `~/.aws/config`.

Having in config:
```
  [default]
  region = us-west-2

  [profile some-service-name-dev]
  region = eu-west-1

  [profile some-service-name-qa]
  region = eu-west-1
```
related `credentials`:
```
[some-service-name-dev]
aws_access_key_id = XXXXX...
aws_secret_access_key = XXXX...
```

and in serverless.yml put link to profile:

```
service: some-service-name
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:stage}
  profile: some-service-name-${env:stage}
```
Then run `stage=dev serverless deploy` or `package`.
Expected result in Cloud Formation file is to have `region: eu-west-1` (loaded from dev stage).
However it is set to `us-east-1`, which is default in serverless. AWS keys are loaded  without a problem with same profile sections from `~/.aws/credentials`, but not `region` from `config` file. OS: Mac Sierra.

Is it a bug or is it made on purpose, or am I doing something wrong?

**Comment by pmuens** [comment]
Thanks for opening @lukeplausin and thanks for commenting @Artur-A 

AFAIK we load the profile information first (in [AwsProvider]( https://github.com/serverless/serverless/blob/2f658ed9721501747da3f3ef8e5f87e9e15add44/lib/plugins/aws/provider/awsProvider.js)) but then overwrite it [here](https://github.com/serverless/serverless/blob/2f658ed9721501747da3f3ef8e5f87e9e15add44/lib/plugins/aws/provider/awsProvider.js#L193-L200) and finally [here](https://github.com/serverless/serverless/blob/2f658ed9721501747da3f3ef8e5f87e9e15add44/lib/plugins/aws/lib/validate.js#L15-L17).

For me this seems to be a bug since the region shouldn't be overwritten several times (especially the `validate.js` seems suspicious).

/cc @eahefnawy

**Comment by HyperBrain** [comment]
@pmuens @eahefnawy I think the real problem here is, that only the credentials are loaded from the profile if present, but not the region [see here](https://github.com/serverless/serverless/blob/2f658ed9721501747da3f3ef8e5f87e9e15add44/lib/plugins/aws/provider/awsProvider.js#L183-L200). The correct fix should be, that the `getRegion()` method would query the profile (if present) and use the region from that too in its evaluation (using the `impl` class).

Nevertheless the region overwrite in validate should be changed to use `getRegion()` to set the options property. It ensures that options is set correctly. With that change the system would be consistent and support for profile regions would be implicit.

**Comment by pmuens** [comment]
@HyperBrain yes, that sounds reasonable 👍 

I agree with the `validate` part. AFAIK the `getRegion()` was added later on, but we should definitely change the behavior in `validate`. Furthermore I would move that out of validate to another function called `setDefaults` or smth. else. Setting the region in `validate` feels wrong to me.

**Comment by pmuens** [comment]
Closing since this issue is quite stale and we've published newer versions with fixes for this in the past. Feel free to re-open if this is still an issue.
