### ISSUE TITLE
Use Yarn lockfile

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#3686]
# This is a Feature Proposal

## Description

Use Yarn instead of npm. We won't have to manually `npm shrinkwrap` any more since Yarn takes care of generating the lockfile. It would also be one less step on the release checklist.

**Comment by pmuens** [comment]
Hey @hassankhan thanks for opening 👍 

We've discussed Yarn usage in https://github.com/serverless/serverless/pull/2371 the outcome was that Yarn is a great addition, but not yet too mainstream so that we consider it in the Framework.

Furthermore the next versions of `npm` are looking quite promising.
