### ISSUE TITLE
Serverless and Imagemin

### ISSUE THREAD

**Issue by tgensol** [serverless/serverless#3720]
# This is a Bug Report

## Description

Hi there,

I am trying to use imagemin in a function (Nodejs). It is working fine on local, but once it is deployed, I am getting this error if I try it, and the lambda function crash.

```
"code": 126,
    "killed": false,
    "stdout": "",
    "stderr": "/var/task/node_modules/guetzli/vendor/guetzli: /var/task/node_modules/guetzli/vendor/guetzli: cannot execute binary file\n",
    "failed": true,
    "signal": null,
    "cmd": "/var/task/node_modules/guetzli/vendor/guetzli --quality 90 /tmp/f67f3a83-0132-4320-a56b-f03cbdd87edc /tmp/3a639aee-827c-45f1-b407-83ce15ce5632",
    "timedOut": false
```

(It happens with every plugins, mozjpeg, png...)

Maybe I am missing something, a file to deploy, or a configuration ? I didnot know if it was a issue of imagemin or serverless (or both)

Thanking you in advance

**Comment by pmuens** [comment]
Hey @tgensol thanks for opening. Seems like smth. is wrong with the binaries. Do you know what permissions they have when they are uploaded?

This issue might be related: https://github.com/serverless/serverless/issues/3557

**Comment by HyperBrain** [comment]
@pmuens I remember there is (or was) another issue that the executable flags are not honored with the ZIP used by Serverless. I assume that the permissions are not stored correctly.

**Comment by tgensol** [comment]
Are you looking for this ? 

```
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-gifsicle
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-guetzli
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-mozjpeg
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-pngquant
```

I tried lots of things but I did not find a solution yet.
Thanks !

**Comment by HyperBrain** [comment]
This is the related bug https://github.com/serverless/serverless/issues/3557.
The only difference is, that @mattisdada tried to include a separate executable whereas your's is included within the dependencies in node_modules.
@tgensol Can you check the exact contents of the created zip file (especially if the execution permissions are pertained)? You can create the zip without deploying by using `serverless package --package=<some directory>`. The zip file should be in `<some directory>` afterwards.

**Comment by tgensol** [comment]
I put these a few minutes ago : 

```
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-gifsicle
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-guetzli
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-mozjpeg
drwxr-xr-x    6 thibaut  staff    204  1 jui 16:46 imagemin-pngquant
```

Which are the permission of the node_modules inside the serverless-XXXX.zip. Is it what you are looking for ? Or what do you want ? 

Thanks

**Comment by HyperBrain** [comment]
Yes. Sorry did not see that these were the permissions inside the zip file.
But they are definitively wrong (`drwxr-xr-x`). They are tagged as directory (!). The correct permissions should be `-rwxr-xr-x`.
Also user/group information should not be set (although I do not know if that can cause any issues on AWS side as it is world-executable).
@pmuens Any suggestion or info here?

**Comment by tgensol** [comment]
@HyperBrain Actually, I do not really know... I only wanted to use the imagemin node module and mozjpeg/pngquant or any plugin of it, and I got this issue, but your asking is by far too much for my knowledge I am sorry

**Comment by HyperBrain** [comment]
@tgensol No problem. You're here to get helped 😄 - I'll check tomorrow if I have some time to have a look at the package and check it out with a test project of mine.

**Comment by pmuens** [comment]
Thanks for jumping in @HyperBrain 👍 

> Also user/group information should not be set (although I do not know if that can cause any issues on AWS side as it is world-executable). @pmuens Any suggestion or info here?

Yes, we should definitely try to keep the permissions as fine-grained as possible.

Just for the context: @tgensol you're using a UNIX based OS for packaging / development, right?

We should definitely try to fix this bug since including executables is a really powerful feature.

**Comment by tgensol** [comment]
Hi,

@pmuens I am using Mac Os (10.12)

**Comment by HyperBrain** [comment]
Just started looking into it - OMG: the imagemin module has 211 (!!) dependencies.

**Comment by HyperBrain** [comment]
Regardless of the error, the system requirements for the `guetzli` plugin are harsh and might not fit into a lambda runtime environment 😕

> Guetzli uses a large amount of memory. You should provide 300MB of memory per 1MPix of the input image.
> Guetzli uses a significant amount of CPU time. You should count on using about 1 minute of CPU per 1MPix of input image.

Remember that you have max. 1536 MB RAM and 300s max. CPU time available. This means the images that can be handled here are at max 5MPix (for RAM and CPU).

Nevertheless I will check the binaries now.

**Comment by tgensol** [comment]
@HyperBrain Thanks ! I see, I was thinking guetzli was not a good idea for lambda function, but I wanted also to use less consuming libraries like https://github.com/imagemin/imagemin-mozjpeg

**Comment by HyperBrain** [comment]
Ok. what I've found out:
If you do a `npm install imagemin` the imagemin wrapper is installed. Then you do a `npm install imagemin-mozjpeg`. This will install the mozjpeg wrapper **and** the mozjpeg package which contains the binary that will be executed by the wrapper.
The problem here is, that the platform specific binary is selected on install time (e.g. in Serverless terms on the computer where you deploy or package your project, or just do the npm install). This binary is then uploaded to AWS.
I tested this on my Windows PC, and the mozjpeg package installed the Windows executable which will then be deployed to AWS - for your MacOS the same will happen, i.e. you upload the MacOS executable to AWS. But the AWS Lambda environment runs on Linux. Your deployed Lambda now tries to execute the executable, but cannot do that - because the executable is no Linux ELF executable but something else (a MacOS executable or Windows executable in my case).
That's exactly the error message you receive.

The only way to get this working on AWS is, if you have a build server on EC2 that runs Aamazon Linux (with high certainty I can say that this matches the AWS Lambda environment) and do the npm install and serverless deploy from there. Ubuntu as build/deployment server might also work, but I did not check if the binaries are linked statically completely, without any loader or ldd dependencies.

**Comment by pmuens** [comment]
Closing, since this issue got quite stale and it looks like it has smth. to do with the used module.

Additionally I'm not sure if the Framework can do smth. about that.

**Comment by Dudeful** [comment]
I just had this issue yesterday. In case someone is also facing it, **and** the development environment is Windows, then I believe this is the solution for you.
I tried a few different solutions, but the easiest and fastest solution was to install the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and run Serverless Deploy from the Ubuntu terminal on windows.

As pointed in-depth above by @HyperBrain the issue is that some packages are OS-dependent, meaning that the same package installed on different OSs are going to produce different installations. So your best shot is to just install the packages, build and deploy your project from a Linux environment _(not sure if all Linux distros fit in this statement, but Ubuntu certainly does)_. 

**Here's the timeline for what I did:**

> 1. Install and enable the WSL with Ubuntu _(no big deal at all, 10min top, just follow [Microsofts doc](https://docs.microsoft.com/en-us/windows/wsl/install-win10))_
> 2. Open the Ubuntu terminal **as an administrator** _(if you don't run as administrator it won't allow you to properly run "npm install" in the next steps)_
> 3. Make sure everything is updated, just run _"apt install upgrade"_
> 4. Create a folder by running "mkdir _your-folder-name_" _(or just cd directly into your project's original folder, you can do it by Shift+RightClick on the given folder and choosing "Open Linux Shell Here". I preferred to separate it to avoid messing with my original stuff)_
> 5. Get into the newly created folder by running "cd _your-folder-name_"
> 6. Clone your repository into that folder **or** just copy/paste it manually _(to open your current folder from Ubuntu terminal on Windows just run "explorer.exe .")_
> 7. Run the good and old _"npm install"_ from the Ubuntu terminal
> 8. Now here's a pitfall, if you have your AWS KEYS/SECRETS on your **.env** file, and you set your serverless.yml file to use the environment variables from the .env file, the next step will fail if you don't have the .env file in place _(and you will only see the real error on CloudWatch because the console logged error in the browser will be a CORS error)_
> 9. Run _"Serverless Deploy"_ to deploy your project

That's it. 
Took me around 20min to perform this solution while the others, even though some being effective _(like CodeBuild)_, were more confusing therefore more time-consuming.

I'm pretty new to Serverless, therefore not aware if it exists, but it would be very convenient to have on Serverless an option to build my project directly on AWS environment (Amazon Linux) by just inserting a command on serverless.yml _(pretty much like you do on buildspecs.yml)._ Some sort of integration with CodeBuild perhaps?
