### ISSUE TITLE
DX: Add additional context for `sls deploy list` command

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3756]
`sls deploy list` pulls back a list of deployments, which is great. 

It would be even more useful, especially on a team setting, if you could get additional context about who deployed which one.

```bash
Serverless: Listing deployments:
Serverless: -------------
Serverless: Timestamp: 1494896076414
Serverless: Datetime: 2017-05-16T00:54:36.414Z
Serverless: Who: david-wells
Serverless: Files:
Serverless: - compiled-cloudformation-template.json
Serverless: - service-xyz-processing.zip
Serverless: -------------
Serverless: Timestamp: 1496860835240
Serverless: Datetime: 2017-06-07T18:40:35.240Z
Serverless: Who: phillip-muens
Serverless: Files:
Serverless: - compiled-cloudformation-template.json
Serverless: - service-xyz-processing.zip
```

Good idea from http://forum.serverless.com/t/policy-for-travis-ci-deployments/2021

It looks like we are pulling back s3 objects for this and don't have the information on who

```
{ 
  Key: 'serverless/test-service/dev/443213232-2017-06-05T16:59:52.882Z/test-service.zip',
  LastModified: 2017-06-05T16:59:56.000Z,
  ETag: '"xxxxxxxxxxxxxxxxxxxxxxxxxx"',
  Size: 409,
  StorageClass: 'STANDARD' 
}
```

Is it possible to attach additional meta data to the deployment artifact? (or solving another way)

This might be easier once platform is out of beta =)

**Comment by pmuens** [comment]
Agreed 👍 

Related to https://github.com/serverless/serverless/issues/2517

**Comment by RafalWilinski** [comment]
How you'd identify users? By aws-profile, `whoami`, IP or something else?

**Comment by HyperBrain** [comment]
Imo this is not trivial, as soon as you think about a CI/CD system. The effective user doing the deploy most likely will be a `deploy` user and not the user who actually triggered the deploy (either manually or through a build/commit via CD).

Quickly evaluating I see 2 ways to achieve this:
(1) Within a separate plugin that enriches the functionality, so that the correct user is sent as metadata to the deployment artifacts and that the `deploy list` command is extended to show this information.
As a consequence of having a whole bunch of sources of user detection (may it be the GIT commit author that led to the deployment, may it be the user who clicked on the deploy button, or anyone else). Only a plugin (or even more than one) can implement the correct semantics that is needed to fetch the user name or id.

(2) Supporting a command line option for the `deploy` command like `--deploy-user` which will receive a user identifier that is attached to the deployment metadata on S3. Then the deployment system (whatever that is) can set it according to its context.

Any thoughts?

**Comment by pmuens** [comment]
Closing since this issue is quite stale and there are no plans to work on this in the foreseeable future.
