### ISSUE TITLE
nested serverless.yml

### ISSUE THREAD

**Issue by arunsubbanna** [serverless/serverless#3801]
Is it possible to have a nested serverless.yml?  Also, can we specify any conditions ?

**Comment by pmuens** [comment]
@arunsubbanna thanks for the question 👍 

What do you exactly mean by "nested"?

Do you mean putting a `serverless.yml` inside of a `serverless.yml`? That's not possible since a `serverless.yml` file descries one "microservice".

You could Use [Serverless Variables](https://serverless.com/framework/docs/providers/aws/guide/variables/) to make the `serverless.yml` more flexible and e.g. require external `yml` and `json` files.

**Comment by justinmchase** [comment]
I have a monorepo with multiple serverless.yml files, then just use gulp to deploy them all with a single command. Serverless does support importing other files but each one is a single service.

**Comment by arunsubbanna** [comment]
thanks, this works.
