### ISSUE TITLE
Stack with id <STACK_NAME> does not exist

### ISSUE THREAD

**Issue by sbkn** [serverless/serverless#3805]
# This is a Bug Report

## Description

Using AWS, recently I've started getting the error: `Stack with id <STACK_NAME> does not exist`. I am not sure why exactly it's happening, but it might be triggered by deleting the stack in the AWS console. I think I have completely purged any reference to the stack from AWS.

The only way I found to recover from that is manually creating a stack with Cloudformation using the same name and redeploying on top of that using Serverless. How can we fix that more elegantly?

## Additional Data

Serverless Framework Version: 1.15.0
I am using the serverless-aws-alias plugin, version 1.2.1

**Comment by pmuens** [comment]
@sbkn thanks for opening.

The best way would be to solely use the Serverless Framework to manage stacks which are based on `serverless.yml` files (so basically Serverless Framework stacks).

One of our goal is to keep the developer logged out of his provider console as much as possible since any manual changes could result into an inconsistent stack / service states.

**Comment by sbkn** [comment]
Thanks for the quick answer @pmuens !

Removing the stack with `serverless remove --stage foo` didn't work for me, IIRC it had to do with the alias stack generated by serverless-aws-alias plugin.

Can you shed some light on why this error is thrown? Naively I'd expect that any non-existent stack name would be just created by serverless when deploying, so I guess serverless saves the currently deployed stacks somewhere locally?

**Comment by HyperBrain** [comment]
If you use the alias plugin, you have to remove the deployed aliases before removing the sls stack with `sls alias remove --alias=XXXX`. This removes any dependencies of the alias stacks to the sls base stack.

Currently the `sls remove` command is not hooked completely in the plugin. I will add that feature in the near future to the plugin, so that you can just do a `sls remove` and the plugin will remove its own resources automatically.

@pmuens For this to be done the `sls remove` command lifecycle has to be implemented with a detailed sublifecycle (as in package or deploy), so that the plugin (or any plugins) can hook the subfunctionality of the remove command.

**Comment by sbkn** [comment]
@HyperBrain How exactly do you remove the alias stack when using a CLI option to determine the stage (e.g. `sls deploy --stage foo` and using `"stage": "${opt:stage}"` in serverless.json)?

`sls alias remove --alias foo --stage foo` gives me:

> Error: Cannot delete the stage alias. Did you intend to remove the service instead?

**Comment by HyperBrain** [comment]
Your case is to delete the master (stage) alias from the stage (alias name === stage name). The "alias remove" command can only be used to remove all other aliases.

Instead of supporting "sls remove" I also could add a possibility to remove the master alias, which would remove the service. Then your problem should be solved.

**Comment by sbkn** [comment]
I'm sorry for asking that much, but I just don't seem to find sufficient information on removing serverless stacks ..

Removing the stack with `sls remove --stage foo` seems to run through successfully, but cloudformation events say:

> Export <STACK_NAME>-foo-<EXPORT_NAME> cannot be deleted as it is in use by <STACK_NAME>-foo-foo

So now I have 2 stacks: `<STACK_NAME>-foo` and `<STACK_NAME>-foo-foo` and neither `sls remove --stage foo` nor `sls alias remove --alias foo` can remove anything?

**Comment by HyperBrain** [comment]
Indeed. What you can do as a quick fix is, to delete the alias stack (the foo-foo stack) in the AWS CF console.
Then sls remove should work. I'll give the alias removal feature very high priority now.

**Comment by sbkn** [comment]
@pmuens So, I still keep having the same error even with a service which has never been successfully deployed yet. I do not understand how and why that keeps happening and what the suggested solution might be .. Any hints?

**Comment by pmuens** [comment]
Thanks for jumping in @HyperBrain 👍 

Yes, so this seems to be related to the `serverless-alias` plugin. Nice to hear that you were able to resolve the problem.

**Comment by duc-anh-tran** [comment]
In my case, I went into S3 and delete the related bucket for cloudformation, then rerun the deployment.

**Comment by dm-grinko** [comment]
Hello from 2019. `sls remove` is working as expected. Thank you

**Comment by sinkng** [comment]
Experiencing this error during the deployment. I finally find why (at least on my side) that CloudFormation removes error stack before Serverless can get a hold of it to extract error reasons. So I went into AWS CloudFormation console and watch for error reason of the stack before it disappears.

**Comment by LyndonZhao** [comment]
I fix the problem by reduce the length of stackName.
As AWS required,  as statckName will be used as a part of 'roleName' , and the role anme must have length less than or equal to 64

**Comment by serverlessguru** [comment]
I'm seeing this as well, but I'm hitting too many buckets error on AWS. The terminal doesn't send this information back.

![Screen Shot 2020-05-05 at 3 40 39 PM](https://user-images.githubusercontent.com/39802277/81123009-f444e700-8ee6-11ea-8c49-57cabad8f4ad.png)

<img width="1099" alt="Screen Shot 2020-05-05 at 3 40 30 PM" src="https://user-images.githubusercontent.com/39802277/81123002-f27b2380-8ee6-11ea-8691-bec069302db6.png">

**Comment by joekendal** [comment]
in my case, i just needed to specify the region as well
```shell
$ serverless remove --stage $STAGE --region $REGION
```
