### ISSUE TITLE
DX: Improve invalid aws credentials message

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3862]
After running `serverless invoke -f hello` with invalid creds on my machine (for testing). I see this:

![image](https://user-images.githubusercontent.com/532272/27565838-99522520-5a95-11e7-91b6-027b1e35fefe.png)

The current error message "The security token included in the request is invalid." is super vague and doesn't say how to fix the error.

Instead, lets say something like: 

```
The AWS security token included in the request is invalid.
Please check your ~./aws/credentials file and verify your keys are correct
```

@eahefnawy do you know where this error throws? I couldn't track it down.

**Comment by pmuens** [comment]
This is super annoying. I always face this because of MFA.

Re-authenticating via `assume-role` fixes the problem for me.

**Comment by rdugue** [comment]
Hello,

I wanted to update the error message, but also could not find it in the project's code. Has this already been resolved?

**Comment by pmuens** [comment]
Hey @rdugue thanks for your comment! 👍 

This issue was not resolved yet. The error should be thrown somewhere here: https://github.com/serverless/serverless/blob/bf1d07663e6963ed36b346915bcf79078fa4e223/lib/plugins/aws/provider/awsProvider.js#L153.

You could catch the error message, compare it to the one provided in the issue description and then throw a new one with more, detailed information.

We do smth. similar here: https://github.com/serverless/serverless/blob/bf1d07663e6963ed36b346915bcf79078fa4e223/lib/plugins/aws/lib/monitorStack.js#L115-L122

Let us know if you need any help here and thanks again for jumping in! 💯

**Comment by DavidWells** [comment]
Another example in wild http://forum.serverless.com/t/serverless-error-the-security-token-included-in-the-request-is-invalid/2219/2

This needs to get fixed to alleviate much user pain

**Comment by rdugue** [comment]
I made a pull request :). I can add a test case to it as well once I get a handle on how they're written.

**Comment by pmuens** [comment]
Thanks for the PR @rdugue 👍 We'll review it ASAP!
