### ISSUE TITLE
Feature Proposal: `sls deploy` should only deploy functions that changed

### ISSUE THREAD

**Issue by rupakg** [serverless/serverless#3932]
# This is a Feature Proposal

## Description

I don't want to have the responsibility on the user to determine what to deploy, or track what functions changed. The Framework should 'detect' what changed, and as a user, I should always be calling `sls deploy`.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us. - **It makes the CLI UI cleaner and simple. It also takes away the responsibility of tracking what changed from the user to the framework.**
* If there is additional config how would it look - **N/A**

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
@rupakg 
For eamaple, We assume there are the following projects
--------------------
- serverless.yml
- function-a.js
- function-b.js
- function-c.js
--------------------

if we change only finction-c.js and run sls deploy, Serverless core detect what changed and automatically deploy only function-c.js.

Dose this sounds good what you state?

**Comment by pmuens** [comment]
Thanks for opening @rupakg and thanks @horike37 for jumping in!

Serverless `v1.17` just introduced a way to diff the whole stack (including functions) and will only re-deploy if something has changed.

Does this functionality solve the problem you're describing here?

**Comment by eahefnawy** [comment]
@pmuens I think @rupakg wants to make the redeploy changes you've implemented smarter, so that not only it would redeploy if something changes, but only deploy the minimum artifacts that needs to be deployed, similar to what @horike37 described.

So if function A didn't change but function B did change, only function B would be deployed, and I'm guessing the stack doesn't need change either?! although we do manage versions via CF 🤔

**Comment by HyperBrain** [comment]
@eahefnawy @pmuens In you example (function A and B) this would mean that Serverless should create a new function version resource for function B (which leads to a redeploy of B through CF automatically) and keep the existing function version resource for A (it will not be updated by CF). This would reduce the deplyoment time.

But there's a big **but**:
Function version resources are currently created by the naming module and have a random identifier attached to their end. So it is not possible to know the old function version without querying the existing stack template from CF. That's the only way to achieve that only the changed functions are deployed by CF. This will add additional deployment time, that imo only would improve things for large stacks where only a few functions are changed.
From my experience with real-life services this is an edge case. If a new version of a service is deployed in most cases a lot of functions changed (due to the microservice concept).

**Comment by eahefnawy** [comment]
hmmm great points @HyperBrain 🙌 

> This will add additional deployment time, that imo only would improve things for large stacks where only a few functions are changed.
From my experience with real-life services this is an edge case. If a new version of a service is deployed in most cases a lot of functions changed (due to the microservice concept).

So in your opinion, are you saying that this feature is not as practical/useful as we think?

**Comment by HyperBrain** [comment]
Not necessarily. I use the `getTemplate` call throughout the alias plugin. If you do only one central call to retrieve the deployed original template it only adds one call (I think it's even faster than to fetch it from S3).
The feature itself **is** valuable and persisting the old version resources instead of creating new ones will do the job just fine.

**Comment by brettneese** [comment]
This should definitely be a thing, or perhaps a "--function" option could be added to "sls deploy." 

We have a larger Serverlesss service whereby each function is an API endpoint. It's a monorepo, and essentially each endpoint is it's own little express server node nodule with it's own package.json and the like. We do individual packaging, and I have scripts in each of them that zip them up, then they get handed to Serverless using the:

`package:
        artifact:`

syntax.

When we do CI, we do a diff between the last released version of each endpoint, and only want to test and deploy the ones that have changed. And if something 

This gives us an operational guarantee whereby the most you could ever possibly break is the endpoint you're working on (and even then, we do staging.) 

We'd use `sls function deploy -f` -- and I've actually written a script that generates those deployment commands for only the changed repos, but that won't manage function-level resources, and it doesn't appear to use s3 deployment buckets, which is problematic because a few of our functions are just over the 50mb limit (they rely on a couple ~10ish MB native binaries for file conversion that `npm installed` into the repo.) Also, it's nice to be able to pull down the zip of what actually got deployed and is running. 

I've thought about abstracting each part of the serverless.yml into each module as well, but then you gotta combine them into one file to get a local API up and running using `sls offline,` and you have no central source that defines routes, and can't share AWS resources between endpoints, and that sounds like a great way to spend a long time jankily patching together files and losing a central source of truth.

I might be willing to help on this, but I don't know where I'd begin.

**Comment by pmuens** [comment]
Thanks for the really in-depth feedback on this feature @brettneese 👍

Those writeups really help understanding the different use-cases / problems and solutions for features like this.

> I might be willing to help on this, but I don't know where I'd begin.

That would be great 👍

I think the first step could be to do a quick implementation proposal we can discuss here. Nothing too technical. Just a quick summary how the features works from a high-level and lower level (e.g. a rough overview of what Serverless does behind the scenes).

Let us know if you need any help here / have any questions.

**Comment by brettneese** [comment]
@pmuens I will do that. The biggest challenge is not quite understanding how cloudformation is working underneath/what it's challenges or limitations are (specifically what @HyperBrain is talking about.)

**Comment by pmuens** [comment]
> @pmuens I will do that.

Great! Thanks for jumping in on this one @brettneese 👍.

> The biggest challenge is not quite understanding how cloudformation is working underneath/what it's challenges or limitations are (specifically what @HyperBrain is talking about.)

Yes, that's a really though one. Feel free to show smith. early on, even if it's not 100% polished yet!

**Comment by brettneese** [comment]
Alright, sorry for lagging on this a bit. Wanted to make sure I took the time to thoroughly think this through.

I hope it's okay that I took the liberty to create a new issue with my proposals: https://github.com/serverless/serverless/issues/4071

**Comment by pmuens** [comment]
>Alright, sorry for lagging on this a bit. Wanted to make sure I took the time to thoroughly think this through.

Thanks for getting back @brettneese 👍 No worries! IMHO planning things thoroughly is super important (and oftentimes the more important part).

> I hope it's okay that I took the liberty to create a new issue with my proposals: #4071

Just saw that this morning! This is super nice 🎉 💯 super detailed and exactly what we need to start a discussion!

Thanks for taking the time to create that 🥇

**Comment by pmuens** [comment]
Closing this issue since it's quite old and `serverless deploy` will always leverage CloudFormation ehind the scenes. We need to go through a full deployment to ensure a consistent state afterwards.

One can use `serverless deploy function` to deploy a single function.
