### ISSUE TITLE
Updating to latest version ...

### ISSUE THREAD

**Issue by jamesladd** [serverless/serverless#3943]
This may be a lame issue but how do I update to the latest version of Serverless?
I can't find the command line instructions anywhere.

**Comment by horike37** [comment]
@jamesladd 
AFAIK, the way is to run `npm install -g serverless` again.
Please try it.

**Comment by jamesladd** [comment]
Will try

**Comment by pmuens** [comment]
Thanks for opening @jamesladd and thanks for providing help @horike37 👍 

Yes, `npm install -g serverless` should do the trick. You could also run `npm install -g serverless@latest` to get the latest version.

I'll close this issue for now since this should solve the problem. Let us know if you need anything else!

**Comment by jamesladd** [comment]
Will this be added to a document somewhere?

**Comment by pmuens** [comment]
> Will this be added to a document somewhere?

Good idea. Do you think you can PR the change to the docs? Otherwise we can do it as well! 👍

**Comment by jamesladd** [comment]
I'd love to contribute so let me have a go ;)

**Comment by pmuens** [comment]
> I'd love to contribute so let me have a go ;)

Nice that sounds great! 💪 

You could add the section about updating here --> https://github.com/serverless/serverless/blob/master/docs/getting-started.md

Let us know if you need any help with that 👍
