### ISSUE TITLE
sls deploy removes earlier resources

### ISSUE THREAD

**Issue by mgurnani** [serverless/serverless#3961]
Hello,

Thanks for a nice framework !! I am developing a full website to be backed by AWS and would really like to use serverless in my project.

I am trying to use it to deploy many of my lambda functions. I have kept my resources in a separate serverless.yml file. My resources yml has DynamoDB tables definitions. 
The other yml (for Lambda Function) has the function details and API GW events.
I can deploy resources as well as my function individually by executing 'sls deploy' in respective directory.
However, when I deploy the function, it removes the DynamoDB tables and vice versa (resources yml removes the Function and API GW endpoints). I can see on AWS Console that Cloudformation is removing the resources. 
Is it because, CloudFormation stack name is same in both ymls? Can I deploy without removing the existing resources?

**Comment by horike37** [comment]
@mgurnani 
Does you use the same service name in two serverless.yml files?
If so, the first deployed service would be overrided by the other service, since
the stack name follows the scheme which is `{servicename}-{stagename}`.

**Comment by pmuens** [comment]
Hey @mgurnani thanks for opening and thanks for the kind words!

Thanks @horike37 for jumping in!

Generally speaking Serverless creates a separate stack for each service you have where one `serverless.yml` file corresponds to one service.

The solution here would be to combine both `serverless.yml` files into one larger `serverless.yml` file so that they won't overwrite each other.

You can still keep your resources in a separate `.yml` file and include it in your `serverless.yml` file with the help of the [Serverless Variables system](https://serverless.com/framework/docs/providers/aws/guide/variables/).

For your DynamoDB table you could use the deletion policy to control what AWS should do when you attempt to remove the table: https://github.com/pmuens/serverless-crud/blob/8096b8282b22886c323bef6bc11b77b258551fc9/serverless.yml#L61

I'll close this issue for now since it's more like a question rather than a problem with the Framework. However feel free to continue the discussion here. We're happy to help you 👍

**Comment by mgurnani** [comment]
Thanks for the prompt response !!
Yes I have the same service name. 
I am using Java Maven projects for my Lambda functions. I plan to have a serverless.yml in each project directory as there will be different package:artifact corresponding to each output jar.
I have different lambda functions under the same service (eg; "user" service with functions UserRole, UserAuth etc) - these functions will be in their own Maven project with a corresponding yml. The service name will be same in some of these hence.

Is this not an appropriate structure? What would be a best practice for such projects?

**Comment by mgurnani** [comment]
My apologies for raising this as an issue-  did not realize I could post it like a question. I will take care of that in future. 
And Thanks again  @horike37 @pmuens for responding lightening fast !!
I love this framework and would really be interested in a way to get it to work for functions distributed across Maven projects. 
I will go through the links you folks have shared (Serverless Variables and Dynamo Deletion policy) and update here..

**Comment by pmuens** [comment]
Hey @mgurnani thanks for getting back :+1:

> Yes I have the same service name.

You can think of one service as a microservice. So e.g. a "users" microservice. This service should contain all the logic necessary to make the service functional. So in your case it should contain the Database, the functions and any other, additional resources related to it.

You can read more about different architectural patterns in our corresponding [blog post](https://serverless.com/blog/serverless-architecture-code-patterns/).

Additionally we have a Java Maven example you can find here: https://github.com/serverless/examples/tree/master/aws-java-simple-http-endpoint

> My apologies for raising this as an issue- did not realize I could post it like a question. I will take care of that in future.

No worries! GitHub is mainly a place to coordinate the work on the Framework codebase. However we also have a our [Serverless Forum](https://forum.serverless.com) which provides a place for questions like this!

> And Thanks again @horike37 @pmuens for responding lightening fast !!
> I love this framework and would really be interested in a way to get it to work for functions distributed across Maven projects.

Thanks for the kind words! Really appreciate it! Let us know if you have any additional questions!
