### ISSUE TITLE
Question: CRUD Best practices

### ISSUE THREAD

**Issue by visualasparagus** [serverless/serverless#398]
Are the any best practices for doing basic CRUD with serverless?

Is it?
**1-** let module be the resource and then create different functions for each HTTP method?
**2-** let function be the resource and then map all HTTP methods to separate endpoints? You could then capture `$context.httpMethod` in the request template to determine the desired action.

I suppose with **1** you could have functions with a smaller code footprint.

**Comment by eahefnawy** [comment]
We'd recommend putting all related CRUD operation in a single `s-function.json`. We think this would make the module more organized since modules could grow large over time.

**Comment by contractorwolf** [comment]
@eahefnawy could you elaborate a little further maybe with an example?  I am trying to move something I did in JAWS the other day to Serverless and am not quite getting how to handle the CRUD actions with the single index.js file.  In JAWS I had an index.js in each function I created in my users aws_module so my code was nicely segmented there.  I am loving JAWS/Serverless but cant really find many examples to work with other than this one:
https://aws.amazon.com/blogs/compute/getting-started-with-jaws-on-amazon-web-services/

Thanks in advance!
-James

**Comment by eahefnawy** [comment]
@contractorwolf here's a real world module that illustrate using multiple functions inside a single `s-function.json`:
https://github.com/serverless/serverless-slackbot

**Comment by visualasparagus** [comment]
@eahefnawy - can you clarify a few things?

1- the project example slack-bot doesn't follow the standard Serverless project structure. Is there a reason for this?
2- isn't putting multiple functionality in one function counter to keeping the code lean and mean for fast loading/execution?

**Comment by contractorwolf** [comment]
It took me a while to figure out how to do what I was doing in JAWS and convert it to work in Serverless, but I thought I would add a suggestion here that might make it easier for others to make the jump.  What confused me coming from JAWS was the usage of one index.js (in Serverless) for the multiple endpoints (functions) I was putting onto a module.  I could make it work several ways but I didnt get what the expectation was.  Was I supposed to make multiple .js files and rewrite the lib call to point to each one?  I finally figured out that the single index.js file in the module was supposed to have multiple exported methods, one for each of the functions you were trying to implement.

My suggestion is this:  When you are using Serverless to create a new module, instead of naming the modules code file "index.js" and referencing it like this: "var lib = require('../lib');" in the handler, it would make more sense (to me) to name the main code file after the module, and then referencing it directly, like this:
/lib/users.js (the newly created file when creating a module, instead of index.js)

and the handlers in the module would look like this:
```javascript
// Require Logic
var lib = require('../lib/users.js');

// Lambda Handler
module.exports.handler = function(event, context) {
  lib.respond(event, function(error, response) {
    return context.done(error, response);
  });
};
```

This way when you are testing you are testing against a file that is named after what you are doing.  The users object could have exported methods like create(), retrieve(), update(), and delete().  It is really just a naming difference, I know, but it may help other to understand where they need to be writing their code, and it would encapsulate the logic in a file that was named after the functionality it performed.

Just my 2 cents, I love the project so far and will be demoing how easy it is to use when I get back to work.

**Comment by contractorwolf** [comment]
@eahefnawy I took a look at doing all of my CRUD functions in the s-functions.json file but that would mean that they would all be able to only use the one events.json  file for testing which doesn't work for me since my users(module)/retrieve(function) wouldn't be able to use the same events.json file to test the show-all-users(endpoint) and the show-one-user(endpoint), since they need different data passed in.  I am not sure if that will make sense to you or if there is something else I am not understanding there.  Let me know. Thanks!

**Comment by ac360** [comment]
@contractorwolf In Serverless `v0.0` you can have a property for each function in the folder's `event.json`, to support multiple events for multiple functions in a function folder. 

However, after lots of thought, we've decided to remove the ability to put multiple functions in the function folder.  It presents a lot of difficulties that we did not anticipate.  In Serverless `v0.1.0` you will no longer be able to do this.  On the other hand, this opens us up to many new features coming in `v0.1.0`.  Please stay tuned, we will release it shortly.  

After this release, we will be making more modules that contain examples of CRUD.  That will be our main focus for a while :)

**Comment by contractorwolf** [comment]
@ac360 Nice, Looking forward to v 0.1.
