### ISSUE TITLE
Development of Local Plugins No Longer Works

### ISSUE THREAD

**Issue by kornatzky** [serverless/serverless#4090]
# This is a Bug Report 

Can no longer test a serverless plugin. 

## Description

Put the plugin test-plugin in folder .serverless_plugins/test-plugin

and included it in plugins section of serverless.yml

Yet it is not recognized by serverless, says 

Serverless plugin "test-plugin" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

This was also tested with this example repo, [sls-plugins-example](https://github.com/lithin/sls-plugins-example) by Anna Doubkova.

Where that example, just puts a file plugin.js inside the serverless_plugins folder

## Additional Data

MacOSX
Node 8.2.1
NPM 5.3.0
Serverless Version:     1.19.0

**Comment by guyklainer** [comment]
Hey @kornatzky ,
I had the same issue yesterday.
I guess that you have some error in your test-plugin. npm install maybe?

If the plugin throws an exception when "required", the framework will print the "not found" error.

**Comment by guyklainer** [comment]
@pmuens as I said in the previous comment,
If the plugin throws an exception when "required", the framework will print the "not found" error.

You should distinguish between really not found to an internal error of the plugin startup.

**Comment by HyperBrain** [comment]
Fully agree. It is annoying for plugin development to have no accurate callstack on crashes.
The reason is, that Serverless' `pluginManager` encloses the plugin require with a try/catch and does not forward the original exception but creates a new one. That hides the original callstack.

I also agree that for the user using Serverless a plugin callstack would only pollute the output and be of no value for the user himself.

My suggestion here would be, that we rethrow the original exception/rejection **BUT ONLY**, if `SLS_DEBUG` is set. That has the advantage, that plugin developers can debug their plugins and find the reason of the crash, but without giving the user useless information. This should be an easy-pick and can be implemented without adding tech debt and risk.

@pmuens What do you think?

**Comment by HyperBrain** [comment]
Attached a PR that fixes the issue.

**Comment by pmuens** [comment]
@kornatzky @guyklainer yes, absolutely agree. That should be fixed.

Also ran into this bug a couple of time the last couple of days.

Thanks for the implementation proposal and the PR @HyperBrain 👍
