### ISSUE TITLE
Feature Request: Custom Template

### ISSUE THREAD

**Issue by stefanthorpe** [serverless/serverless#4099]
# This is a Feature Proposal

## Description

The standard templates are great generic boilerplates. However, I have to make the same modifications everytime I start a new project. I think it would be great to be able to create and specify my own custom template for use with the service create command.

**Comment by pmuens** [comment]
Thanks for opening @stefanthorpe 👍

This issue is related to https://github.com/serverless/serverless/issues/2498.

**Comment by alexdebrie** [comment]
@stefanthorpe Is your custom template available on GitHub? You can use the [`sls install`](https://serverless.com/framework/docs/providers/aws/cli-reference/install/) command. It's basically like `sls create`, but it works with a zip file from a GitHub repo.

**Comment by pmuens** [comment]
> @stefanthorpe Is your custom template available on GitHub? You can use the sls install command. It's basically like sls create, but it works with a zip file from a GitHub repo.

That's a good point! Thanks for pointing that out @alexdebrie 👍

It would be nice if this is integrated in the `create` command. So if you specify an URL (no matter if it's GitHub, GitLab or smth. else) it will download the template / service 🤔

**Comment by kbariotis** [comment]
@pmuens I would like to get my hands on this one! :) So, I will move the code responsible for downloading a GitHub repo from the `install` plugin over to the `create` plugin and make it accept either a template name either a template URL and then decide what it should do. I will make it also accept not only GitHub URLs but whatever.

Should I abstract the code in order to be used by both commands? Will the `install` plugin still be useful after this gets implemented?

**Comment by pmuens** [comment]
Great @kbariotis 👍. Really nice that you want to tacke this one!

> So, I will move the code responsible for downloading a GitHub repo from the install plugin over to the create plugin and make it accept either a template name either a template URL and then decide what it should do. I will make it also accept not only GitHub URLs but whatever.

Sounds like a good plan!

> Should I abstract the code in order to be used by both commands? Will the install plugin still be useful after this gets implemented?

Yes, we should definitely keep the `install` plugin to be backwards compatible. Yes, the best way to solve this is to abstract this so that it can be shared by the `create` and `install` plugin (as you already described). This way it's DRY and can be easily extended.

Thanks again for taking the initiative 💯. Let us know if you need any help with that!
