### ISSUE TITLE
Add a `serverelss function <action>` command

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#4135]
# This is a Feature Proposal

## Description

To help keep parity with the new `serverless plugin <action>` command we should introduce a `serverless function <action>` command. There was consensus that the grouping of actions under a specific `<object>` makes more sense and is easier to understand. https://github.com/serverless/serverless/pull/4046

The first commands that would be available are the ones that already exist.
```
serverless function deploy
serverless function rollback
```
However, this will leave room for adding such commands as...
```
serverless function install
serverless function publish
...
```

**Comment by HyperBrain** [comment]
How will that fit into the current lifecycle events? To be non-breaking the new "function" commands would have to spawn the existing "deploy function" commands exactly as is - the lifecycle events are bound to the invoked Serverless functions. For the sake of all existing Serverless plugins you have to make sure that all existing hooks are triggered in the same order and with the same configuration as they are triggered now with "deploy function".

My personal opinion is, that you open a can of worms if you meddle with the lifecycles. Only if you see the "new" commands as aliases to the old ones, the approach could work, i.e. the new commands MUST NOT implement any functionality and the SHALL only call pluginManager.spawn() to invoke the original commands. This should be properly documented and monitored. Any change there would easily break lots of plugins.

**Comment by HyperBrain** [comment]
I rethought a bit over this again. Now I'm pretty sure that these kind of command changes can indeed be done in a non-breaking way. The key is to introduce command aliases, i.e. existing commands could define aliases which just invoke the existing commands without the need to implement the alias command at all.
This would be the most compatible and non-breaking approach and will allow to make commands available under different paths and commands,

The definition of such an alias would be quite simple:
```js
// lib/deploy/deploy.js
...
this.commands = {
  deploy: {
    ...
    commands: {
      function: {
        usage: 'Deploy a single function from the service',
        lifecycleEvents: [ ... ],
        aliases: [
          'function:deploy'
        ]
      }
    }
  }
}
...
```

The alias command implementation is quite easy and local to `pluginManager`, i.e. when loading plugins and their commands, the pluginManager would also parse the aliases array and setup the alias commands in the commands collection with their hooks just being duplicates of the original command's hook. This would be stable and non-breaking - and best of all, also plugins can integrate with this mechanism. The need to discuss risky command movements or changes will be eliminated completely then and all command changes will be non-breaking in nature.

@pmuens @eahefnawy What do you think about this approach? I think I can get a PR up and running in just a few days (hours?) as it is really easy.

**Comment by pmuens** [comment]
Thanks for the feedback, the in-depth analysis and the proposal @HyperBrain 👍 💯

I agree that aliases are a good extension and can be the solution for the problem here (Aliases for plugin commands is a feature which was already asked for a long time ago).

Only downside could be that it could be harder to reason about the code execution flow.

Furthermore what about aliases which might overlap / end in an infinite loop (or smth. along those lines)? Is the alias always `command:lifecycleEvent`? What about entrypoints?

**Comment by HyperBrain** [comment]
> Furthermore what about aliases which might overlap / end in an infinite loop (or smth. along those lines)? Is the alias always command:lifecycleEvent? What about entrypoints?

There can be multiple cases for that - here with some solutions:
* An alias has already been registered by a previous plugin (2 plugins register the same alias)
  ⇨ The second registration should fail to tell the plugin author that the alias is already in use. This will automatically prioritize core plugins because they are loaded first. So 3rd party plugins cannot use any alias used by the core.
* Multiple plugins add an alias that share common paths (like function:deploy and function:rollback)
  ⇨ The common path would be a shared alias command (here: function) and the subcommands are aliases to the resp. original commands. This allows to create "bucket" functions that are only virtual hosts for aliases.
  ⇨ It is a design decision if the core defines virtual buckets upfront or lets the system dynamically compose them when aliases are created.
  ⇨ 3rd party plugins must not alias a common path. This should lead to en error (e.g. plugin X registers "function" as alias). Can be checked during plugin loading. However, aliasing beneath an existing alias is allowed (e.g. to extend a command or alias with subcommands).
* Circular aliases/commands
  ⇨ I believe that this can be catched in pluginManager in a deterministic way. PluginManager has to check for circular aliases and bail out. As aliases are a static command definition this will definitly eliminate any risk of circular aliases.
* Entrypoints
  ⇨ I'm not sure if aliases can be non-visible entrypoints at all. Everything aliased should be public, so it is also callable from within another plugin via spawn() or run(). So aliases are public commands in any case, and can themselves never be entrypoints.
  ⇨ Entrypoints can be used as a "move" of an command. E.g. to expose `deploy:function` only as `function:deploy` (a move!) entrypoints can help. You just have to declare the old `deploy:function` as entrypoint, so that it is not accessible from the CLI anymore, but declare an alias for it `function:deploy`. This will automatically make the old command hidden, but the new command public.
* Lifecycle events
  ⇨ The triggered lifecycle events are always the events from the original command.
  ⇨ Aliases only start the original commands internally

> Only downside could be that it could be harder to reason about the code execution flow.

Slightly disagree here, as aliases do not invent/implement their own lifecycles but start the original command's lifecycles. To have a clear overview of aliases I can extend my lifecycle cheat sheet to show the aliases too. So any plugin author has all information at hand. Also documenting the behavior should not be very complex.

**Comment by pmuens** [comment]
Great! Thanks for taking time to make an in-depth analysis (with solutions) about the concerns @HyperBrain 👍.

That's really helpful!

**Comment by medikoo** [comment]
I'm going to close it, as we do not envision larger shifts to Framework CLI API (focus is now put more onto Components) and while there are valid points behind proposal that are worth discussing, it doesn't bring anything new, while cost of the change would be significant. I believe community got used to and is happy with `sls deploy function`.

Great thanks for all the insight!
