### ISSUE TITLE
Cannot reference existing Cognito User Pool resource in configuration

### ISSUE THREAD

**Issue by tcchau** [serverless/serverless#4207]
# This is a Bug Report 
(but could be a Feature Proposal if desired behaviour wasn't supposed to be supported)

## Description
I'm using serverless to manage my backend services on AWS.

I’ve divided my project into two stacks: one that defines all the lambdas, and another that defines only resources, such as DynamoDB tables, and User Pools.

I’m now stuck not knowing how to define my PreSignUp trigger in the service stack, so that it will reference a User Pool that’s already been created. I can always manually go into the User Pool console and select the correct lambda, but that just seems wrong…

I’ve tried using an ARN where pool is specified, but I get a validation error (no colons accepted for example):
```
- cognitoUserPool:
    pool: "arn:aws:cognito-idp:us-east-1:XXXX:userpool/us-east-1_XXXXX"
    trigger: PreSignUp
```

The above does not work, so I’d like to know how to do this correctly. It seems that this is designed to only work with logical names.

## Additional Data

Using Serverless Framework 1.19.0
Mac OS X 10.12.6
No stack trace
No error messages

**Comment by pmuens** [comment]
Thanks for opening @tcchau 👍

Related to https://github.com/serverless/serverless/issues/3773 and https://github.com/serverless/serverless/pull/3799

**Comment by cazzer** [comment]
It seems the [PR](https://github.com/serverless/serverless/pull/3799#pullrequestreview-46536671) has gone a bit stale so I wanted to throw out a use case:
CloudFormation does not support all Cognito features, such as the ability to use email/phone number instead of a username; however, this is possible through the console.

I would like to create a Cognitor User Pool through the console with features which are not supported by CloudFormation, and associate that Pool with cognitoUserPool function event triggers.

**Comment by kevboutin** [comment]
Definitely want this to automate user pool creation and usage with lambdas via triggers.

**Comment by ldgarcia** [comment]
Any update on this issue?

Currently I have to manually configure the triggers in the Cognito console.

I cannot use CloudFormation to create the user pool yet, because the CF support [is not feature complete](https://forums.aws.amazon.com/message.jspa?messageID=838927#838927).

**Comment by Necromancerx** [comment]
Any news about this? Thanks :)

**Comment by kcijezie-wedge** [comment]
Any updates yet?

**Comment by cazzer** [comment]
#3799 was closed, so this issue can probably be closed now too.

**Comment by GreenVine** [comment]
What is the correct configuration if we need to reference an existing user pool here? I do not want Serverless to create one for me.

**Comment by atwoodjw** [comment]
@GreenVine, It should look like this.

```
functions:
  handler:
    handler: hello.default
    events:
    - http:
        authorizer:
          arn: arn:aws:cognito-idp:us-east-1:XXXXXXXXXXXX:userpool/us-east-1_XXXXXXXXX
        path: hello
```

**Comment by GreenVine** [comment]
@atwoodjw, thanks, however, I don't want to use this as an authorizer in API Gateway. Instead, I am trying to use these Lambda functions as [User Pool Triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) (e.g. `PreSignUp`, `PostAuthorization`).

I want to reference Cognito's ARN rather than let Serverless create a Cognito user pool for me.

**Comment by atwoodjw** [comment]
Ah, got it. I wasn't able to get that working either. In my case, I create a Lambda for the customMessage hook and configure manually via web console. 🤷‍♂️ 

```
functions:
  customMessage:
    handler: src/cognito.customMessage
```

**Comment by phillipsnick** [comment]
Just spent an hour trying to work out how to do this with little success.

@atwoodjw what did you specify in the web console?

**Comment by tcchau** [comment]
@phillipsnick You should be able to do that manually by using the Cognito Console, opening up the Triggers page from the side menu, and then manually selecting the lambda you want invoked for each of the triggers. If you have automatically created the user pool from your serverless.yml, you will have to unset, save, then set it again.

The reason is that (for me anyway) there's no way to specify in serverless.yml that your user pool is permitted to invoke the trigger lambda functions; the serverless.yml IAMRoles only define which resources your functions can access, but not the other way around.

Setting the lambda manually from the Cognito Console seems to implicitly set the appropriate permissions.

It would be great if someone could figure out how to do this through serverless.yml, but I haven't figured out how to yet. C.f. https://forums.aws.amazon.com/thread.jspa?messageID=748566#748566

**Comment by tcchau** [comment]
@cazzer or anyone else: can you verify that the problem I originally posed has indeed been fixed by #3799 ? I personally can't verify it at this this time because I've moved on to other projects, but maybe able to do so at some future date.

**Comment by phillipsnick** [comment]
@tcchau found it thanks! I have a separate CF stack for Cognito so it's all created prior to the serverless deploy.

I was unable to specify a ARN for the pool with version 1.28.0

```
  Serverless Error ---------------------------------------

  An error occurred: CognitoUserPoolArnawscognitoidpeuwestuserpooleuwestXXXXXX - 1 validation error detected: Value 'arn:aws:cognito-idp:eu-west-2:XXXXXX:userpool/eu-west-2_XXXXXX' at 'poolName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w\s+=,.@-]+ (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: X).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.4
     Serverless Version:     1.28.0
```

Using the following config.

```
cognito:
  handler: functions/cognito.main
  events
    - cognitoUserPool:
        pool: arn:aws:cognito-idp:eu-west-2:XXXXXX:userpool/eu-west-2_XXXXXX
        trigger: PreSignUp
```

**Comment by tcchau** [comment]
@cazzer I just reviewed #3799 and it does not fix #4207 (this issue). @phillipsnick Yes, you're just running into the same issue that this current issue reports on. 

This current issue differs from #3773 in that I'm trying to reference a User Pool resource that's already been created, either using AWS CLI scripts or through another serverless.yml.

**Comment by cazzer** [comment]
Thanks for checking it out for us, @tcchau. My use case was the same as yours: create a UserPool in the Console with passwordless login, (because that isn't supported by CloudFormation and thus Serverless), and refer to it via the ARN in my Serverless templates. According to your testing, #3799 will not resolve my issue either.

**Comment by et304383** [comment]
Can we please get this fixed?  CloudFormation support for Cognito sucks so we need to create externally.

**Comment by tcchau** [comment]
> Ignoring that, it's not proper design to couple stateful resources with your stateless resources. 
> Even if CFN support was complete for Cognito we wouldn't combine it with the stateless API
> resources.

Hi @et304383, not sure what you mean by the above comment. How would you go about designing the serverless specification for the AWS lambda functions and the resources that they work with/upon?

**Comment by et304383** [comment]
> How would you go about designing the serverless specification for the AWS lambda functions and the resources that they work with/upon?

Ideally, stateful resources (user pools, dynamo tables, S3 buckets) are declared separately either via API calls, CloudFormation, Terraform, whatever.

The reason for this is to reduce blast radius.  I should be able to update my API code with 100% certainty that my stateful resources (the important stuff) isn't going to be affected.  I should also be able to tear down and recreate my API stack without affecting stateful resources.

Unfortunately, it appears we cannot do this in serverless if we want to use Lambda triggers on Cognito events.  I realize this is because serverless is adding the LambdaConfig property to the user pool declaration.  So obviously this issue isn't easily fixed.

**Comment by tcchau** [comment]
@et304383 I see what you mean. I had hoped to be able to separate the two, but by using serverless only, and hence, the separate stacks, i.e. serverless.yml files. Since I haven't been able to do that, my approach is a combination of serverless and AWS CLI scripting. It's more messy because we're now using two different technologies, but it's serviceable in the interim, FWIW.

**Comment by DMor1** [comment]
From what I can tell this is not a limitation of the Serverless Framework itself, but a limitation in AWS CloudFormation support for Cognito which prevents Serverless from implementing this feature - correct me if i'm wrong.

I put in a feature request with aws to add a "AWS::Cognito::Trigger" which would allow the linkage between an existing lambda and existing user pool. This would be similar to various VPC CloudFormation resources which allow separate creation such as "AWS::EC2::SecurityGroup"

**Comment by DanielBoa** [comment]
I've managed to set up a lambda triggered by the CustomMessage event without touching the AWS console or CLI.

The steps I followed:
- Define your lambda in your `serverless.yml` as you would normally
  - [see here more information on the structure of the lambda itself](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html)
- On your UserPool definition underneath "Resources" add the property `LambdaConfig`, which itself has a property called `CustomMessage`. This must be set to the ARN of the above lambda, this can be achieved using the Cloudformation `Fn::GetAtt` function
  - Something of note here is that when referencing the lambda function you must use the normalised name which will be generated by serverless -  [see here](https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference)
- You now need to create a resource of type `AWS::Lambda::Permission` which will allow Cognito to invoke the CustomMessage lambda.

I know this is just one stack, but you should be able to achieve the same with multiple stacks by using exports and `Fn::ImportValue:` to retrieve the lambda Arn.

So the relevant parts of the `serverless.yml`:

```yaml
functions:
  authCustomMessage:
    handler: path/to/authCustomMessage.handler

resources:
  Resources: 
    UserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        # ... other properties
        LambdaConfig:
          CustomMessage: { "Fn::GetAtt": ["AuthCustomMessageLambdaFunction", "Arn"] }

    AuthCustomMessageLambdaFunctionInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::GetAtt:
            - AuthCustomMessageLambdaFunction
            - Arn
        Principal: cognito-idp.amazonaws.com
        SourceArn:
          Fn::GetAtt:
            - UserPool
            - Arn
```

_Note: I have other Cognito resources linked to the UserPool but I've left them out because they're not relevant to the solution._

Something else I ran into when doing this is a circular dependency, this was because I was referencing the UserPool as an environment variable on the top `provider:` level of the yml, which was applying it to the custom message lambda. The solution here was to move that environment variable to the specific lambda it was being used in.

**Comment by janoist1** [comment]
@DanielBoa Unfortunately it doesn't work for me. I did everything the same way your config says only difference is that I'm trying to setup a trigger for `PostConfirmation`. I had to manually go and set it in the console. Have you got any idea? Thanks

**Comment by DanielBoa** [comment]
@janoist1 Looking at the Cloudformation docs I see no reason that `PostConfirmation` shouldn't work in the same way. Where does it fail exactly and what is the error message?

**Comment by janoist1** [comment]
Thanks for the quick reply. There is no error message during deploy. It only seems to ignore setting the trigger. It sets up the lambda permissions part from `ConfirmUserLambdaFunctionInvokePermission` though.

**Comment by DanielBoa** [comment]
@janoist1  Hmm, that's very odd if it doesn't error. I don't have time to try this out myself at the moment so the best I can advise would be to look over the cloudformation logs to look for any clues.

I will likely be setting up a PostConfirmation hook in the near future though, when I do I'll be sure to get back to you with any findings.

**Comment by jorgedavila25** [comment]
@DanielBoa Curious to know if you set up the PostConfirmation hook. Seems like I am on the same boat as most people in this thread.. Thanks!

**Comment by aldarund** [comment]
Hm, i cant even attach function to user pool that is created through serverless. When i define a trigger it endsup serverless create second pool with same name

**Comment by pointtoken** [comment]
> Hm, i cant even attach function to user pool that is created through serverless. When i define a trigger it endsup serverless create second pool with same name
You can override it with the following syntax so it doesn't create two:
https://serverless.com/framework/docs/providers/aws/events/cognito-user-pool/

**Comment by tonyxiao** [comment]
@pointtoken using that workaround does that mean this issue can be closed?

**Comment by pointtoken** [comment]
@tonyxiao  in my opinion, yes.

**Comment by pmuens** [comment]
Closing this issue since there's a documented workaround.

**Comment by pmuens** [comment]
Re-opening as we're looking into ways to support this via native CloudFormation.
