### ISSUE TITLE
Adding new providers

### ISSUE THREAD

**Issue by rylandg** [serverless/serverless#4232]
Hey I was hoping you guys could give me some insight into an issue I've been struggling with. My company is currently developing our own FaaS platform and since we love SLS it made sense to make it our first point of integration. Although we have a working node-sls plugin for our backend, it appears that for a provider to work with SLS(out of the box) changes need to be made in the core SLS code itself. From my understanding both templates and the list of providers would need to be updated for a custom provider to work with a non-forked SLS.

So now for my question(s). Have I missed something? I tried to do my research before coming here but there is definitely a chance I missed a feature/piece of code that would solve my issue. Alternatively, if my hypothesis is indeed correct what steps can we take to be recognized officially by the SLS framework?

Thank you for any insight you guys can provide.

**Comment by pmuens** [comment]
Hey @rylandg thanks for opening 👍

Great to hear that you're working on an integration for your company 💪!

We've updated the Framework recently so that there's no need to make changes to core if other providers want to integrate with the Framework.

You could use the `serverless install` command to install your template from a remote GitHub URL (we're currently working on `serverless create` so that it's also able to download services via URLs) and then you can use your provider plugin with that template as if you've created an "official" service template.

I'll close this issue for now, but feel free to continue the discussion. Let us know if you have any additional questions!
