### ISSUE TITLE
Introduce a functionality which attach events to an existing resource

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4241]
# This is a Feature Proposal

## Description
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

  `S3` and `cognitoUserPool` events can't attach an existing resource. I think the main reason is that those can't specify an external resource within CF generated by Serverless.

However, I think many users hope that. 
I think there are many cases that data sources like S3, DynamoDB or  Cognito userpool are preferred to separate a stack from a one which includes Lambda.
 If those are built in a same service, you can't remove and recreate anytime since data sources have a state.

* If there is additional config how would it look

Similar or dependent issues:
* #4237, #4207, #2154

**Comment by a-suenami** [comment]
I have the same idea. I want this feature.
What status is it?

**Comment by horike37** [comment]
Thank you for pinging @a-suenami :+1: 
To implement this feature, we need to decide how to parse CloudFormation template(in generally speaking, the Serverless Framework convert serverless.yml setting to CF template.), because it would break the consistency of deployment if we choose a way without CF.

However, TBH, I don't have the best way.
Do you have any ideas? 
cc: @serverless/framework-maintainers

**Comment by a-suenami** [comment]
Ah, I see...
I'm sorry but I have no ideas because I'm not familiar with CloudFormation. 🙇 
So I'll see the current implementation and consider how to realize it.

**Comment by HyperBrain** [comment]
I'm quite sure that this is possible with a proper `${cf:...}` variable reference. You can address any output variable from the other stack. So the only thing you have to make sure is, to have the other stack export the arn of the target correctly.

You also can use the cf variable references within your resources part of the serverless.yml and define the trigger by yourself.

However, we have to check if the current implementation of the S3 and User Pool events handle the subscriptions, in case one would just specify an arn instead of something else. This has nothing to do with Serverless' generated CF template, but more the internal creation and handling of the events.

**Comment by a-suenami** [comment]
@HyperBrain Thank you for your answer, but I can't clearly know what you mean.

For example, my `serverless.yml` is here.

```s
  cognito-user-pool-custom-message-trigger:
    handler: index.handler
    events:
      - cognitoUserPool:
          pool: MyPool
          trigger: CustomMessage
```

Then, generated `.serverless/cloudformation-template-update-stack.json` is as blow.

```json
"CognitoUserPoolMyPool": {
  "Type": "AWS::Cognito::UserPool",
  "Properties": {
    "UserPoolName": "MyPool",
    "LambdaConfig": {
      "CustomMessage": {
        "Fn::GetAtt": [
          "CognitoDashuserDashpoolDashcustomDashmessageDashtriggerLambdaFunction",
          "Arn"
        ]
      }
    }
  },
  "DependsOn": [
    "CognitoDashuserDashpoolDashcustomDashmessageDashtriggerLambdaFunction"
  ]
},
```

Because of `DependsOn` attribute, each lambda functions are created first, and Cognito User Pool is created next. Is it right?

I'd like to:

1. create a resource of Cognito User Pool in some way (AWS Console, another CF stack, terraform, and so on)
2. attach the Lambda Functions (defined by serverless framework) to the created User Pool

Can I do that? If yes, how can I do?

**Comment by a-suenami** [comment]
I want to ONLY attach triggers to existing User Pool.

**Comment by ldgarcia** [comment]
Any update on this issue?

Currently, I have to manually configure the triggers in the Cognito console.

I cannot use CloudFormation to create the user pool yet, because [it is not feature complete](https://forums.aws.amazon.com/message.jspa?messageID=838927#838927).

**Comment by exoego** [comment]
What if serverless add capability to specify existing resources in a form of `existingXXXX` ?
If the syntax is acceptable for this new feature, I will open my PR to implement this.

Examples for Cognito User Pool

```yaml
- cognitoUserPool:
    pool: new-pool
    trigger: PostConfirmation
- cognitoUserPool:
    existingPool: old-pool
    trigger: PostConfirmation
- cognitoUserPool: # INVALID: Do not specify 'pool' and 'existingPool' on same event
    pool: new-pool
    existingPool: old-pool
    trigger: PostConfirmation
```

Examples for S3

```yaml
- s3:
    bucket: new-bucket
- s3:
    existingBucket: old-bucket
- s3: # INVALID: Do not specify 'bucket' and 'existingBucket' on same event
    bucket: new-bucket
    existingBucket: old-bucket
```

**Comment by exoego** [comment]
Or, adding `existing: true` field to `s3` event and `cognitoUserPool` event.
This may be more easy to understand for users and to implement than `existingXXX`.

**Comment by dschep** [comment]
I like the 2nd option @exoego 👍  And make it `preExisting: true` rather than `existing`.

**Comment by exoego** [comment]
@dschep @horike37 
I need a design decision by core devs regarding Cognito user pool.

S3 is fine. `s3` event requires `bucket` name which is unique in AWS globally,  so the plugin can find the existing S3 bucket by the name.

However, IIUC, `cognitoUserPool` requires `pool` name which is NOT unique. In other words, there may be multiple user pools with same name, since user pools are distiguished by its pool id, which is like `ap-northeast-1_AbCdeFgHi`.
New feature should consider the case when there are user pools with same name.

I came up with 3 design:
1. `preExisting: true`+`pool`: Attach Lambda to all matched user pools.
1. `preExisting: true`+`pool`: Abort and warn users to delete user pools same name.
1. `poolId` for exsting pool, instead of `preExisting`+`pool` : No need to worry about multiple same name and faster to find existing by the ARN (No AWS-SDK execution required).

I think 1st and 2nd choice is not good, since 1st and 2nd support different use cases.
3rd is my recommendation, however it mismatches `s3` with `preExisting`.

**Comment by dschep** [comment]
What about the following:

If `preExisting: false`(default) then `pool` is a pool name.
If `preExisting: true` then `pool` is expected to be a pool Id

I think that should be acceptable if it's well documented. And if there's a way to check that a string is a valid ID, then it could also check that it maches that when preExisting is true.

**Comment by exoego** [comment]
Please forget the above issue reference which is created accidentally.
![image](https://user-images.githubusercontent.com/127635/50625618-9c9e1080-0f6c-11e9-9d30-c294b743c902.png)

**Comment by exoego** [comment]
Please forget the above issue reference which is created accidentally.
![image](https://user-images.githubusercontent.com/127635/50625618-9c9e1080-0f6c-11e9-9d30-c294b743c902.png)

**Comment by dschep** [comment]
Hmm. Yeah, I don't really like the idea of adding more non-cf stuff 😕

**Comment by pmuens** [comment]
This has been recently done via https://github.com/serverless/serverless/pull/6290 and https://github.com/serverless/serverless/pull/6362. We're planning to add more custom resources in the future, so stay tuned.

Given that we have the main building blocks in place I'll close this issue for now. Feel free to continue the discussion about other event sources which could be added to the aforementioned list.

**Comment by DemonGyro** [comment]
I am running against 1.58.0 and this feature doesn't appear to be working. Here is my events for the lambda:
```
    events:
      - s3:
        bucket: ${self:custom.fileBucket}
        event: s3:ObjectCreated:*
        rules:
          - prefix: ${self:custom.filePrefix.${self:provider.stage}}/
        existing: true

**Comment by lhyleo** [comment]
I am running against 1.58.0 as well and I am having an error of 
`An error occurred: S3Bucket - The event is not supported for notifications (Service: Amazon S3; Status Code: 400;)`

Here is my events:
```
events: 
    - s3:
      bucket: some-bucket
      event: s3.ObjectCreated:*
      rules:
        - prefix: prefix/
        - suffix: .json
      existing: true
```
