### ISSUE TITLE
function "..." you want to update is not yet deployed

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#4246]
# This is a Bug Report

## Description
Saw `function "loadGenerator" you want to update is not yet deployed...` when trying to deploy previously working service.

I have been able to reproduce this using the latest in NPM (v1.21.1) but not with a branch off of master (`circular-vars`).  Still investigating cause and will try to update if I discover anything.

For bug reports:
* What went wrong?
'ServerlessError: The function "loadGenerator" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.'
* What did you expect should have happened?
Successful deployment, as usual
* What was the config you used?
see https://github.com/Nordstrom/serverless-artillery/blob/master/lib/lambda/serverless.yml
* What stacktrace or error message from your provider did you see?
See stack trace at tail.

Similar or dependent issues:
* https://github.com/Nordstrom/serverless-artillery/issues/76 (original report of issue, investigating...)

## Additional Data

* ***Serverless Framework Version you're using***: 1.21.1
* ***Operating System***: OSx
* ***Stack Trace***:
```
$ npm i -g serverless serverless-artillery
$ serverless-artillery deploy

        Deploying Lambda to AWS...

{ ServerlessError: The function "loadGenerator" you want to update is not yet deployed. Please run "serverless deploy" to deploy your service. After that you can redeploy your services functions with the "serverless deploy function" command.
    at provider.request.then.catch (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:65:13)
    at tryCatcher (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (~/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) name: 'ServerlessError', statusCode: undefined }

        Deploy complete.
```
* ***Provider Error messages***: N/A

**Comment by erikerikson** [comment]
note that this blow up is in the first of the following rather than the second:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deployFunction/index.js
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/index.js

`'deployFunction' !=== 'deploy'`

**Comment by erikerikson** [comment]
note that `serverless-artillery deploy` results in the command to serverless:
`sls deploy -f [func]` using (`process.argv = [null, null, 'deploy', '-f', constants.TestFunctionName];`)

it seems https://github.com/serverless/serverless/pull/4192 (correctly or not) may be the root cause of this.

**Comment by erikerikson** [comment]
guess this is an example of the SLS choice to say "f-u" to semver violations impacting users.  (we check compatibility here: https://github.com/Nordstrom/serverless-artillery/blob/master/lib/index.js#L177)

**Comment by erikerikson** [comment]
I can confirm that downgrading from `v1.21.1` to `v1.21.0` resolves this issue.

**Comment by pmuens** [comment]
**First of all:** Thanks for opening @erikerikson and sorry for the inconveniences 😞

I was able to reproduce this issue with Serverless `v1.21.1`. I tried to reproduce this with a usual template in `master` but was not able to do that.

It would be interesting to know how `serverless-artillery` works behind the scenes (haven't look that much into the code yet). It looks like it deploys single Lambdas with the help of `serverless deploy function` without deploying through `serverless deploy` beforehand (but I can be wrong here). If that's the case then my assumption is that this shouldn't be possible (since you need to have a Lambda in place to update it through `serverless deploy function`).

Is there a way to create a service setup which isolates the parts where it breaks? (Or provide some steps how this can be reproduce with a Serverless service template?)

Looks like you're correct that #4192 introduces this inconsistency. ccing @HyperBrain here. Maybe he knows more 🤔

**Comment by HyperBrain** [comment]
@pmuens @erikerikson The command delegate `deploy --function` is non-destructive in any way. It just invokes the function deploy in case you add the (**previously unsupported**) `--function` argument to the `deploy` command.
If `serverless-artillery` did set the function option on `deploy`, it used an unsupported switch (relying on unspecified behavior), which now leads to the changed behavior. Imo the change is non-breaking and also does not violate semver in any way, because it **adds** a new switch which wasn't there before for the `deploy` command.

**Comment by pmuens** [comment]
Thanks for the in-depth explanation here @HyperBrain 👍

Yes, I agree. It's an additive feature and therefore non-breaking (if we've followed `semver` correctly).

@erikerikson is correct that it's a breaking change in this specific case because we shipped it with a patch release. We definitely need to revisit our release process here (shipping minor features in a patch release is a no-go).

/cc @brianneisler @eahefnawy 🔝

**Comment by HyperBrain** [comment]
@pmuens In my opinion that would also mean to follow semver **completely** and not half-way. The rediculous major version number **1** should be dropped for the package versions, which are definitely not product versions. So breaking changes must lead to an increase of the major version (for the package, not the product), features must affect the minor version and bugfixes that do not introduce anything but the fix might increase the revision part.

**Comment by erikerikson** [comment]
@pmuens slsart does as little work as possible.  in the deploy case, we do deploy a single lambda from a simple serverless.yml.  To do this, we use the `serverless` available in the local `node_modules` falling back to the global installation.  We change the argv so that when we `init` and `run` serverless (we're using it programmatically) it behaves as though it was executed on the CLI.  However, as Frank notes, we were depending on the command being interpreted as being `sls deploy ...` as I will discuss...

@pmuens @HyperBrain you guys are right...  I looked back in the docs and it has been clear that the `-f` flag is not to be used with the standard `sls deploy` (sans `function`) command (
https://github.com/serverless/serverless/blob/v1.0.2/docs/03-cli-reference/03-deploy.md).  I guess we got away with it because it was previously ignored.  I have a foggy recollection that we added that because of validation that was rejecting our command or something...

[digging...]

Hrmm...  This seems relevant:
https://github.com/Nordstrom/serverless-artillery/issues/30 // "remove unintended `-f` option"
Unfortunately, the PR that closed it didn't actually resolve the matter:
https://github.com/Nordstrom/serverless-artillery/pull/38

Looks like I foresaw this but...  /sigh  Oh well.

I think @HyperBrain is correct that the previous "use" of the flag and our reliance on the tool ignoring it is on us.  As in, this is not a `serverless` bug but a `serverless-artillery` bug.  Very sorry for the noise!

**Comment by HyperBrain** [comment]
@erikerikson Hi Erik. I do not think is was noise - at least it brought up the old issue about semver versioning again 😄 which in my personal opinion should be implemented strictly.

Nevertheless you might make use of the new flag for deploy and just use `serverless deploy` with and without the flag to simplify and streamline the implementation.

**Comment by erikerikson** [comment]
@pmuens Regarding Frank's missive on strong semver, I couldn't be more supportive.  This is a challenge for us and it leads to negative experiences for our workshops, engineers, and public parties.  This reduces adoption and "those magic moments"

A quick way to accomplish this (and another goal) would be to make serverless programmatically usable and then have a thin shim that manages/contains/maintains the product version while allowing the implementation module to iterate on the major version for reliable usage.

Personally, so I'm perfectly happy to have to update versions and keep up so long as previously working and reliable setups aren't being broken without notice.  Maybe we need to cron our builds to detect this stuff.  That's the alternative before us given the behavior and choices so far with serverless.

**Comment by erikerikson** [comment]
Yes, that's the exact resolution path I plan to take!  😄 
Always glad to talk about why semver provides value.

**Comment by erikerikson** [comment]
Oh yeah.  @pmuens I also noted that this wasn't an issue on master.  That was odd to me.  This could indicate that @HyperBrain 's changes have been excluded from master somehow.  Probably worth a quick check to see why the extra `-f <name>` would be ignored.

**Comment by pmuens** [comment]
Thanks for the discussion and the analysis on the `serverless-artillery` project @erikerikson and @HyperBrain 👍

We're very sorry for this bug to pop up (and opening this was definitely not noise, so keep it coming 😃).

We've completely abandoned planned breaking changes a long time ago and started to follow server again (we've created the [`VERSIONING.md`](https://github.com/serverless/serverless/blob/master/VERSIONING.md) file to have a provide a contract on that with our community). However as @HyperBrain mentioned we're not following it strictly here.

The root cause for this is our release process right now. As soon as we've released a new version we start to review and merge new PRs. However if there's a bug which should be fixed ASAP (in the case for this release it was the bug that binary data is not packaged correctly) we simply publish a patch release which might include recent merges as well. IMHTO we should cherry-pick the bug fix and only publish that, but that's something we need to discuss (maybe in a separate issue).

Again. Thanks for bringing this up and thanks for the in-depth discussion on that 👍

**Comment by erikerikson** [comment]
I'm really happy to read this @pmuens, thanks for the update!

**Comment by pmuens** [comment]
> I'm really happy to read this @pmuens, thanks for the update!

Good to hear that @erikerikson 👍 🙌! We're really sorry for the inconveniences and struggles the old versioning approach with breaking changes introduced.

Maybe we should've announced our decision to go back to strict semver more publicly (more than just adding a `VERSIONING.md` file). However we try to stick to it as much as possible and will always refine our processes around that to ensure a straightforward update story.
