### ISSUE TITLE
Serverless should NOT fail if provided profile is not valid

### ISSUE THREAD

**Issue by kevindiamond** [serverless/serverless#4264]
This is to alter the breaking change made in #4245 

Profiles are not always required. Things like IAM roles and policies can be used instead and typically are used in CI/CD pipelines, rather than sharing credentials. 

I see a couple ways to handle this:

- There is @simonbuchan's idea of using a WARN instead of ERROR.
  - If you don't have a profile loaded or another way for it to have access (like IAM) that is needed, you get the warning and it will fail anyways because it can't access the resources. So you accomplish knowing why it failed and it fails quickly anyways.
  - If you don't have the profile loaded, but you do have another way to access (IAM), you see the warning but it accomplishes its task and all is good.
- Another option is a flag at time of deployment, something like --no-profile, that simply doesn't provide the error.
  - I like this less as it requires a change to the flow on how people would deploy locally versus in automation
- A final option would be a configuration of serverless itself, something like a serverless config no-credentials or something like that...

Definitely open to other suggestions? Maybe we just make the WARN change for now and explore other options for the near future as maybe the SLS team has better ideas of the future and where this might fit in (such as today we build the CICD pipeline using Resources that directly are built into CloudFormation, so not cross cloud compatible, where as maybe in the future they are planning to add things like this and it would be handled in there? No idea).

[Added for visibility of the new ticket: @pmuens @RafalWilinski]

**Comment by simonbuchan** [comment]
Just a note, warning is not my suggestion, and in fact would un-fix the problem I hit if it were the only change. Details are in #4242 and comments on #4245 already.

**Comment by kevindiamond** [comment]
Sorry @simonbuchan, my mistake! Didn't mean to put words in your mouth.

**Comment by kevindiamond** [comment]
So I guess the issue that #4242 covers would not be fixed by WARN, but also is likely how IAM roles essentially work since Serverless just relies on the device having some way to do its thing... So I guess it would need to be more explicit... hmmm.... ideas?

**Comment by simonbuchan** [comment]
Keep in mind also that profiles are not the only credentials source, the CLI allows, in priority order:

- explicit key id and secret parameters
- explicit profile parameter
- AWS_* environment variables for the above
- default profile
- *then* instance roles

Serverless is supporting most if the above, slotting in the provider.profile value somewhere in the middle there (presumably above default profile)

I'm off the opinion serverless shouldn't default too far away from that.

If the use case is CI should look the same as dev, but still allow a missing profile, I would suggest adding the equivalent to provider.profileIsOptional:  true, but that this shouldn't apply to --aws-profile

As a note, you definitely don't want to try instance profile first, since that's a http request that will timeout fail outside of an instance

**Comment by RafalWilinski** [comment]
@pmuens What's the decision here? I think we might proceed with replacing Error introduced in https://github.com/serverless/serverless/pull/4245 with a very prominent warning. 

This wouldn't require any changes from developer side, like adding flags or changing config (suggested here https://github.com/serverless/serverless/issues/4264#issue-257804697) and everything will be working the same as in 1.21.

**Comment by simonbuchan** [comment]
Is it possible to prompt if `istty`? Or to cancel the deploy? It is pretty normal for CI to invoke differently, so unless this is a compatibility fix only and you are pushing the breaking change to a major version just warning doesn't fix my original issue

**Comment by pmuens** [comment]
> @pmuens What's the decision here? I think we might proceed with replacing Error introduced in #4245 with a very prominent warning.

Thanks for pinging @RafalWilinski and thanks for the discussion everyone 👍

Generally speaking I'm more a fan of an error rather than a warning. Simply because deploying with a wrong profile is unintended behavior and should error out. However since this is a breaking change I'd suggest that we implement the **super prominent** warning. We can re-introduce the error-out functionality in `v2`.

**Comment by haines** [comment]
We ran into the same problem. I'd agree with @simonbuchan that the `provider.profile` should fit in to the list of credentials sources just above the default profile.

We use the `provider.profile` parameter to set the name in our dev environments, while CI uses `AWS_*` environment variables to override this setting.

We'd only expect an error that the profile is missing if the `AWS_*` variables are also absent (in which case the error would be useful, because it would indicate misconfiguration of a dev machine).

**Comment by simonbuchan** [comment]
To be clear, that was just a description of the AWS CLI behavior and a guess as to what serverless is doing, but if it works?

**Comment by haines** [comment]
Yep, it worked in 1.21.1

**Comment by jmaleonard** [comment]
I have the same problem. 
The below snippet used to work. 
`provider:
    name: aws
    stage: ${opt:stage, self:custom.defaultStage}
    profile: ${self:custom.profiles.${self:provider.stage}.AWS_PROFILE}
`

But now had to change it to 

`provider:
    name: aws
    stage: ${opt:stage}
    profile: ${opt:profile}
`

**Comment by medikoo** [comment]
On my side we also upgraded to latests SLS, and CI started to crash due to #4245.

I think feature implemented with #4245 is not fully compatible with AWS, for reasons mentioned here https://github.com/serverless/serverless/issues/4264#issuecomment-329581813

It'll be better to never crash, than crash in case of false positives due to incomplete detection means

**Comment by pmuens** [comment]
Closing since this issue is quite stale and we've published newer versions with some fixes in the past.

Furthermore changing this behavior could also lead to unexpected / breaking changes.
