### ISSUE TITLE
  An error occurred: CreateLambdaFunction - Function not found: arn:aws:lambda:us-east-1:525021290452:function:serverless-landingpage-dev-create.

### ISSUE THREAD

**Issue by codeforgeek** [serverless/serverless#4276]
Deployed this code yesterday.

https://github.com/pmuens/serverless-landingpage-backend

And deleted the function from the AWS console. Now when i am trying to deploy this code again. Getting the following error.

  An error occurred: CreateLambdaFunction - Function not found: arn:aws:lambda:us-east-1:525021290452:function:serverless-landingpage-dev-create.

**Comment by pmuens** [comment]
Hey @codeforgeek thanks for opening 👍

The problem you're running into has smith. todo with state and the way the Serverless Framework / CloudFormation works (The Serverless Framework uses CloudFormation behind the scenes).

Generally speaking you should never manually remove update or add any resources. Everything should be managed with the help of the Serverless Framework.

The Serverless Framework generates a CloudFormation file which is then uploaded to AWS. Once uploaded CloudFormation checks what needs to be changed and thinks that the Lambda function is still around since it has no knowledge that you've removed it manually.

The solution / recommendation here would be to remove and re-deploy the stack and manage everything with the help of the Serverless Framework.

**Comment by chandrajayam** [comment]
thanks for this answer, i was in same situation. I removed one lambda function manually. later tried to update my cftemplate. now i deleted my old cftemplate and re-deployed

**Comment by adir1661** [comment]
in my case i terminated the batch job before it finishes, 
this caused unusual behavior ...

**Comment by pcguru** [comment]
One way to get around this is to:
1) Create a new empty lambda with the same name in the AWS console.
2) Comment out the function in serverless.yml (use #)
3) Deploy (this function will be removed on AWS
4) Remove comments in serverless.yml
5) Deploy again (the function will now be properly created with all permissions, env vars etc
