### ISSUE TITLE
How to deploy new Lambda functions only,without effecting the existing functions in the AWS Lambda

### ISSUE THREAD

**Issue by Erandakuruneru** [serverless/serverless#4291]
How to deploy new Lambda functions only, without effecting the existing functions in the API Gateway,

If we add the new Lambda functions to existing service, once we deploy the service using sls deploy command.all the existing functions in the yml file also deployed, is there a way we can deploy only latest functions to API gateway?

Your Environment Information -----------------------------
OS: win32
Node Version: 8.4.0
Serverless Version: 1.22.0

**Comment by RafalWilinski** [comment]
Hi @Erandakuruneru 

If you'd like to update your existing functions code, you can use `serverless deploy function -f your_function_name` which only deploys selected function's code and updates its configuration.

If you'd like to add new functions or change e.g. events, I'm afraid that there's no other option than full deploy.

**Comment by Erandakuruneru** [comment]
HI @RafalWilinski 
We can not do that for production and serverless deploy function -f your_function_name only can use after deployed the all full deployment.

**Comment by HyperBrain** [comment]
@Erandakuruneru You also SHOULD NOT use the single function deploy on production services, because it bypasses CloudFormation's integrity and just pushes the new code and configuration by using AWS Lambda's REST API. So after a `deploy function` CF does not know that there has been a new version deployed and in case of a rollback, stack update or other CF event you'll end up with something unexpected.

**Comment by Erandakuruneru** [comment]
HI HyperBrain
yes, I'm aware of that deploy function command, so any solution for the only deploy new Lambda functions?

**Comment by HyperBrain** [comment]
I think that would first need a rewrite of the `deploy function` command so that it uses CloudFormation in the background and updates the stack without changing any of the existing resources.
The second problem in the current implementation is, that the CF function version resources are recreated on every deploy, what leads to a full CF reployment of all functions instead of only changed ones (even if there's now an algorithm in place that will only upload the function code if it has changed).

I'm afraid that in the current implementation there's no real way to achieve the deployment of a single new function.

I'll check if there are already feature requests for this, but I'll have to look it up.
