### ISSUE TITLE
AWS Stage not work with Serverless

### ISSUE THREAD

**Issue by pralivera** [serverless/serverless#4295]
I want to manage two separate stages for DEV and QA within one API gateway. According to the documentation, this feature already supported by the AWS. But when I tried to create AWS stage using serverless, it creates new API Gateway for each stage. 

1). Why this stage feature not supported by serverless?
3). Did we have any other method to handle stage in serverless?
2). Did we have any workaround to handle this?

Thank you,

**Comment by HyperBrain** [comment]
You can try the [`serverless-aws-alias`](https://github.com/HyperBrain/serverless-aws-alias) plugin which does exactly that. You can deploy aliases within SLS stages, which means that (1) APIG stages in the same APIG API are used and (2) Aliases are also applied to functions, so that it makes use of AWS Lambda function aliased versions.

Then you have SLS stages as coarse separation (into multiple physical CF stacks) and aliases as fine separation within one SLS stage. That let's you separate production/QA from dev/DevQA physically, but with the possibility to have both QA testing on the same SLS stage.
Another use case is for developer branches that can just be deployed in parallel while developing.

**Comment by pralivera** [comment]
@HyperBrain 
I tried serverless-aws-alias plugin. But when I changed stage property to QA in yml file and then run following commands, it creates new api gateway for QA.

sls deploy
sls deploy --alias=QA

Did I follow any thing wrong ?

**Comment by HyperBrain** [comment]
If you changed the stage, that means that you changed the SLS stage -> so SLS will create a new API.

You should deploy the QA alias to an existing stage like this:
`sls deploy --stage=dev`
  => this will deploy the dev stage including a *dev* APIG stage (default alias: dev)

`sls deploy --stage=dev --alias=qa` 
  => this will deploy the qa alias to the dev stage including a *qa* APIG stage

**Comment by HyperBrain** [comment]
![image](https://user-images.githubusercontent.com/5524702/30693196-c52cc97a-9ece-11e7-8e37-059d221664c8.png)

As seen here, aliases can even contain different versions of an API or different sets of functions. This is especiually the case for feature development, where new features can deployed to aliases, to be able to test them without breaking the existing stable deployments. The function configurations can also be different in each alias.
In your case you would e.g. deploy a stable dev deployment to a qa stage, to be able to deploy unstable stuff to dev again. The qa will still test the stable version as it is deployed into their alias.

**Comment by pmuens** [comment]
Thanks for opening @pralivera and thanks for jumping in @HyperBrain 👍

Yes, the [serverless-aws-alias](https://github.com/HyperBrain/serverless-aws-alias) plugin is the most flexible way to implement this right now.

I'll close this issue for now. Feel free to continue the discussion here.

**Comment by pralivera** [comment]
Thank you ..
