### ISSUE TITLE
Purpose of the `back` directory

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#430]
Just a minor one... The `back` directory was gone in JAWS but got reintroduced in Serverless. What is the exact purpose of this? Is this is meant to create space for a frontend application in the future? Not sure of that's the cleanest approach, but I'm curious about the thoughts on this.

**Comment by visualasparagus** [comment]
Related to #396

**Comment by ac360** [comment]
Thanks for the input @joostfarla.  We have lots of plans to make this Framework versatile, and having this extra level is important to that versatility.  In Serverless `v0.1.0`, projects will be shareable, as well as the modules.  Who knows how the community will hack/evolve Serverless Projects.  But we want to encourage them to do so.  Hopefully, the existence of the `back` folder will spark some creativity...

**Comment by joostfarla** [comment]
@ac360 Thanks four your explanation!

Still feel like it's unnecessary, because modules are already a way of grouping your functions. The `back` dir just makes it overcomplex (also for the framework itself). With our most recent discussions (about project vars & templates), I feel like we will reach the same goals without the need for this extra level.

It might probably be worth reconsidering, lots of similar feedback @ Gitter at the moment.

**Comment by Nopik** [comment]
I've been stating my position few times already, this is just a repetition from gitter (with some additional explaination):

I'm having my front code, and it is located elsewhere, in the same repo, as sibling of serverless project
and it is pretty complex, I'm using bower, gulp, with some dist/prod custom folders to precompile assets, digest them, having several build steps, etc. I dont believe that adding `front/` folder will be good enough for everybody. Certainly it is bad for me. SL is not good enough to properly handle all my UI tasks, and cd-ing to some `front/` folder in order to be able to `gulp` something isn't good idea for me. Also, I dont want SL to be the 'master' of my repo, especially that SL is so backend-oriented anyway. I'm preferring SL to stay away from frontend and not enforcing the structure. It is doing more bad than good imho. It gives you promise that it will good for you, but generally I'm better having my UI outside of SL.

**Comment by visualasparagus** [comment]
What if serverless was rendering react on the backend for initial pageload/seo?

**Comment by Nopik** [comment]
That doesnt change much. I'm already having serverless to render some html to bootstrap my application. That is like 1 lambda only, out of 50+ in my project. Not good enough to justify drowning everything in useless `back/` folder with empty `front/` folder sibling.

**Comment by joostfarla** [comment]
Concerning frontend code, I totally agree that Serverless does not have to provide anything for that. If people want to add frontend code in the same repo (which is not always the case), they could easily achieve that by adding a custom dir structure, depending on their taste and needs.

**Comment by visualasparagus** [comment]
+1 

I vote to drop the back folder.

**Comment by obie** [comment]
+1
