### ISSUE TITLE
custom restApiId?

### ISSUE THREAD

**Issue by alexklibisz** [serverless/serverless#433]
I see in the top-level s-project.json file that there is a property under each stage called ```restApiId```. It appears that this is being generated by something like shortId. I would like to have this be a custom string. But when I change it and redeploy my functions and endpoints, I get the error:

```
Serverless: / { [NotFoundException: Invalid REST API identifier specified]
  cause: 
   { [NotFoundException: Invalid REST API identifier specified]
     message: 'Invalid REST API identifier specified',
     code: 'NotFoundException',
     time: Sat Dec 26 2015 14:21:06 GMT-0500 (EST),
     requestId: 'cf9217ef-ac05-11e5-bc9c-5df0c5d063d7',
     statusCode: 404,
     retryable: false,
     retryDelay: 30 },
  isOperational: true,
  code: 'NotFoundException',
  time: Sat Dec 26 2015 14:21:06 GMT-0500 (EST),
  requestId: 'cf9217ef-ac05-11e5-bc9c-5df0c5d063d7',
  statusCode: 404,
  retryable: false,
  retryDelay: 30 }
```

This isn't a major deal, rather a convenient thing to have if possible.

Awesome tool you've built here. Really really really helpful for quick development on Lambda.

**Comment by joostfarla** [comment]
The `restApiId` is the unique identifier of the API generated by AWS API Gateway on creation. When hosting your different stages within the same region, this will have the same value for each stage.

Since the identifier is used by Serverless to determine which API to deploy to, you don't want to change this value by hand, otherwise Serverless will be unable to deploy the API endpoints. It's not generated by the framework, so there is no way of customizing the generation of it.

**Comment by shadiakiki1986** [comment]
> It's not generated by the framework, so there is no way of customizing the generation of it.

Just came here to say that [serverless.yml docs](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) says `REST API resource ID. Default is generated by the framework`. This is a bit misleading and possibly needs to be re-worded in the docs.
