### ISSUE TITLE
Stack with id XX does not exist

### ISSUE THREAD

**Issue by jswift** [serverless/serverless#4341]
# This is a Bug Report 

## Description
I had an issue with my AWS serverless stack and I ended up deleting the CloudFormation stack. When I went to redeploy, I assumed it would just recreate the stack if it didn't exist, but it died. I then removed the project from the serverless platform too.

I cannot deploy it now at all, even if I rename it, use a different AWS profile, use a different region or a different stage.

## Additional Data

> Serverless Error ---------------------------------------
>  
>   Stack with id job-advertiser-dev does not exist
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Forums:        forum.serverless.com
>      Chat:          gitter.im/serverless/serverless
>  
>   Your Environment Information -----------------------------
>      OS:                     darwin
>      Node Version:           8.6.0
>      Serverless Version:     1.23.0

**Comment by horike37** [comment]
Thank you for reporting @jswift 👍 

>I ended up deleting the CloudFormation stack. 

Did you delete the stack directly on AWS management console?
If so, You can't control your service via `serverless deploy` since the S3 bucket for the deployment has been left(Your service was broken). You needed to delete the service via `serverless remove`.

You might want to look for the deployment bucket,  which name would include `-serverlessdeploymentbucket-`. You could deploy again if you remove it once manually.

P.S
One of the concepts of Serverless Framework is that it makes it possible to control any serverless services via only command line 👍

**Comment by jswift** [comment]
Thanks for that, yeh I broke it. I removed the stack via the console, but with the aws tools.

**Comment by horike37** [comment]
@jswift 
Glad to hear that your problem has been resolved 🎉
