### ISSUE TITLE
Redeploying Lambda in VPC Temporarily Fails

### ISSUE THREAD

**Issue by BrandonEvansAsurion** [serverless/serverless#4347]
After deploying a Lambda in a VPC with serverless, if we attempt to redeploy the same lambda again, we get the following error:

`Stack:arn:aws:cloudformation:us-east-1:ACCOUNT_NUMBER:stack/SERVICE_NAME/d5b6df90-97eb-11e7-8abc-500c21998436 is in UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state and can not be updated.`

This will continue for roughly 40 minutes, after which, we can deploy again.

All research so far points to ENIs being orphaned. [This StackOverflow thread](https://stackoverflow.com/questions/41299662/aws-lambda-created-eni-not-deleting-while-deletion-of-stack) implies that this is an AWS bug, but that competing frameworks like [Terraform](https://www.terraform.io/) have a workaround to resolve this.

A similar workaround in Serverless would be greatly appreciated.

**Comment by HyperBrain** [comment]
We ran into this issue already multiple times. The reason seems to be that sometimes the ENI associated with a lambda are still marked active and can only be deleted as soon as the traffic ceases. From my experience this happens after 40 - 120 minutes, the latter if you have a lambda that is triggered by CW events. This might happen on a stack update (where a function is deleted, or with a complete stack removal).

These are the 2 relevant threads on AWS Forum:
https://forums.aws.amazon.com/thread.jspa?threadID=229266
https://forums.aws.amazon.com/thread.jspa?messageID=730634&#730634

Regarding Terraform's workaround:
> Until AWS addresses this issue further, you can workaround the issue by detaching and deleting the leftover ENIs in between deleting the Lambda function and deleting the associated Security Group(s) and Subnet(s). This is how Terraform currently handles this issue in its framework.

I think the workaround would need some discussion as it uses the EC2 REST API to find and delete the ENI's. With Serverless everything is handled via CF (so there had to be an additional implementation in deploy, that triggers the ENI delete lambda, that should be auto-deployed as in the stackoverflow article)
