### ISSUE TITLE
Add nVidia cloud?

### ISSUE THREAD

**Issue by tycho01** [serverless/serverless#4394]
A while back nVidia announced they'd start their own [GPU cloud](https://www.nvidia.com/en-us/gpu-cloud/).
If this gets serverless functionality as well, it might end up getting worth adding here.

I'm fairly clueless as to its current state though, as it still seems to be in beta.
Feel free to close until relevant; just wanted to put the idea out there fwiw.

**Comment by horike37** [comment]
Thank you for giving us the information @tycho01 :+1: 
It would be great if the provider is added in the future :100: 

If you want to add a new provider, you need to implement the plugin and make the document for that. We are always welcome to introduce a new one:+1: 

Closing this issue since It would be still a long way off.
Feel free to re-open if you want to discuss anymore!
