### ISSUE TITLE
Deploy serverless package without installing plugins

### ISSUE THREAD

**Issue by Mortinke** [serverless/serverless#4439]
# This is a (Feature Proposal)

## Description

My aim:
Create a jenkins pipeline which download a serverless package (use the serverless-python-requirements plugin) from the central artifact repository(S3) and deploy this on several AWS accounts.

I created a deployment package with “serverless package” and store this on AWS S3 (central artifact repository).

The pipeline job should download the created package and try to deploy the package with “serverless deploy --package <package_path>”.

In this step I get the error:
```
  Serverless Error ---------------------------------------

  Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.5
     Serverless Version:     1.24.0
```

I’m wondering that I need all the plugins to deploy the packages! Is there a way to deploy the package without install all used plugins?

[Forum Link](https://forum.serverless.com/t/deploy-serverless-package-without-installing-plugins/3014)

**Comment by HyperBrain** [comment]
Hi @Mortinke , thanks for asking.

Unfortunately, you have to have all needed plugins installed and available. Every plugin listed in the service's plugins section is declared as needed and mandatory for the project.
Because plugins are free where to integrate into the framework, you cannot predict if a listed plugin is needed during the package phase or the deployment phase. There are lots of plugins out there that are invoked during package, deploy or even both. If a plugin that does something during the deployment phase is missing, you'd end up with a broken deployment.

If you do the deploy on a different system than your package/compile, you have to do a `npm install` on the deployment system to make sure that the integrity of the service is guaranteed. It might be possible, that you install the plugins globally on your deployment system, so that they are found, but I'm not really sure if that's currently possible.

**Comment by Mortinke** [comment]
Hi @HyperBrain, thanks for the clarification.

One way to make the deployment process leaner and faster is to add another property that lets you specify that the plugin is needed during deployment.
