### ISSUE TITLE
Feature Request: CLI command to check that all SSM params are present

### ISSUE THREAD

**Issue by GeneralistDev** [serverless/serverless#4447]
# This is a Feature Proposal

## Description

For feature proposals:
For the purposes of CI/CD it would be good to have a CLI command to fetch all the EC2 parameter store parameters via SSM and list those that cannot be resolved. In theory this should allow a user to check all serverless framework projects for missing environment variables prior to any deployment.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.0
* ***Operating System***: OSX 10.13.1
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Thank you for the proposal @rlgod :+1: 

It would be good to introduce the functionality as an optional parameter of `sls print` command.
something like this:

```
$ sls print --ssm
```

**Comment by alexdebrie** [comment]
@rlgod @horike37 The `sls print` command displays an error for me with this.

Using an example `serverless.yml`:

```yml
service: ssm-check

provider:
  name: aws
  runtime: python3.6
  environment:
    variable1: ${ssm:/notarealpath}

functions:
  hello:
    handler: handler.hello
```

And then running `sls print`:

```bash
$ sls print

 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/notarealpath' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/notarealpath' could not be found.

service: ssm-check
provider:
  name: aws
  runtime: python3.6
  environment:
    variable1: !<tag:yaml.org,2002:js/undefined> ''
functions:
  hello:
    handler: handler.hello
```

It's not the most clear though -- double prints, and then still prints the 'resolved' yml.

**Comment by rlgod** [comment]
Thanks for your feedback @horike37 @alexdebrie. @horike37 I think that would suffice. The key part is that the command needs to return 1 if there are parameters missing or 0 if they are all present. 

@alexdebrie I checked that command and got the same result as you (ie. double print) but the main issue was that I still got a 0 return code from the sls process even if ssm params or other environment variables were missing which makes it difficult to use in automated processes where we depend on that exit code.

I'm happy to work on implementing this if it's a desirable feature for the project by the way.

**Comment by alexdebrie** [comment]
That makes a lot of sense, @rlgod, and I think would be a good addition.

The big problem here is that we current [_only warn_](https://github.com/serverless/serverless/blob/16810823fb37bbb0989fa73bc2c7744b700b2cf5/lib/classes/Variables.js#L408) if a variable can't be resolved, rather than throwing a hard error. This feels like the wrong approach to me. It may have been because we didn't introduce default variables until quite recently.

My guess is that it would be considered a breaking change to start throwing a hard error if a variable was missing, though I wouldn't want to rely on that behavior. If that's the case, we'd probably have to introduce a flag via the command line or in `serverless.yml` (`strict: true`), which makes me sad. 😞 

The maintainers are much smarter than me so might know of a better way to handle this 😄

**Comment by rlgod** [comment]
I think that in the meant-time I'm going to begin working on a PR for this that adds a `sls check-env` command which hard fails if it can't resolve an environment variable. I don't want to hang off the `sls print` command since its functionality is to not fail on missing variables. Hopefully having a PR will mean I get some meaningful feedback from the maintainers as to the direction they want this in.

**Comment by jliebrand** [comment]
Hi @rlgod , just wondering if this ever got done?  I'd love to ensure my CI fails if there are missing vars

**Comment by jliebrand** [comment]
For anyone else coming across this, I found this workaround to help:
https://forum.serverless.com/t/possible-to-error-if-variable-declaration-cannot-be-resolved/2454/2

**Comment by medikoo** [comment]
I'm closing this as I believe this use case is best addressed with following approach:

1. Have a command that confirms the configuration (without taking any action) - That's already served by `sls print`
2. We should throw when variable resolution crashes - There's other dedicated issue for that: https://github.com/serverless/serverless/issues/5757
