### ISSUE TITLE
Differential Deployment

### ISSUE THREAD

**Issue by weaversam8** [serverless/serverless#4454]
# This is a Question / Feature Proposal

## Description

* Is it currently possible when running a `serverless deploy` to deploy only the code that changed (through autodetection of what edits you made?) I don't think it's currently possible, but it would likely simplify the deployment process and speed things up.
* If this was a feature I imagine it'd be enabled by default and then you'd do something like `serverless deploy --force` to force the deployment of all functions, even if they didn't change.

Similar or dependent issues:
* None Known

## Additional Data

* ***Serverless Framework Version you're using***: 1.14.0
* ***Operating System***: Windows 10 Pro
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by horike37** [comment]
Thank you for asking @weaversam8 :+1: 

>Is it currently possible when running a serverless deploy to deploy only the code that changed (through autodetection of what edits you made?) I don't think it's currently possible, but it would >likely simplify the deployment process and speed things up.

Currently, the framework doesn't have such a feature. Instead, you can use `serverless deploy function`, which allows you to deploy only a function you specify. And as a similar option, you can use `--update-config` option with `serverless deploy function`, which allows you to deploy only function configuration you edit.

https://serverless.com/framework/docs/providers/aws/cli-reference/deploy-function

`serverless deploy` is CloudFormation run behind the scene, so it would be hard to add the functionality what you want unless a feature which deploy a part of a code you change is supported by CF :cry: 

>If this was a feature I imagine it'd be enabled by default and then you'd do something like serverless deploy --force to force the deployment of all functions, even if they didn't change.

The force option is already supported, but it would be different a little bit from your image though.

https://serverless.com/framework/docs/providers/aws/guide/deploying/

**Comment by weaversam8** [comment]
Does CloudFormation not have the ability to update just the function that was changed, or does the whole stack have to be rebuilt?

**Comment by HyperBrain** [comment]
It generally only updates resources that are changed in the CF template (for functions if the hash changed specifically). It is not a problem of CF not supporting that, it is more a problem of the current SLS architecture and behavior.

Right now, most of the resources you have in your service (functions, endpoints) are just freshly recreated in the CF template, because there is no mechanism to first retrieve the currently deployed CF template from AWS and add/change only what has changed based on that.

This would be a feature that has to be implemented, but this implementation will be somehow deep into the framework's core and ist in that respect not easily done within a few days.

As far as I remember there is already a similar feature request open (already for a longer time).

**Comment by weaversam8** [comment]
I know Serverless adds a "version" to each function/deployment that is a string of random letters and numbers... (or maybe a hash... I digress)

If we knew which functions were changed, it would only be a matter of updating only the versions of those functions and their dependencies in the CF template, right? Is it true that the others would remain unchanged if their versions remained static?

**Comment by HyperBrain** [comment]
Yes. That's why the deployed CF template (fetched from CF REST) must be used to provide a viable solution.
The generation of the unique names (hashes) is very important to make sure _that_ everything we want is _really_ deployed, so that cannot be dropped. But the currently deployed ones are present in the online CF template.

**Comment by HyperBrain** [comment]
BTW: I'll take care of this and provide something soon.

**Comment by RyanMcDonald** [comment]
Has there been any progress on this?

**Comment by pmuens** [comment]
Closing since this was is already in core. Using `serverless deploy` will check if there are changes and skip the deployment if nothing was changed. `serverless deploy --force` will force a deployment.

**Comment by weaversam8** [comment]
@pmuens I don't think that's the purpose of this Issue. I opened this specifically with a focus on _differential_ deployment. Just checking for changes and deciding whether to deploy is only part of that. If the deploy still deploys the entire project, even functions which haven't changed, that's not differential.
