### ISSUE TITLE
match the lambda execution environment

### ISSUE THREAD

**Issue by alexklibisz** [serverless/serverless#446]
I've had several instances over the past week of using lambda where a function will run via ```sls function run``` without any errors locally, but then the function fails due to syntax error when deployed.

I looked up the lambda execution version for node, and it's currently 0.10.36 (source: http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

However, when I used nvm to set my local node version to match (nvm install v0.10.36), I can't even run sls:

```
$ sls

/usr/local/lib/node_modules/serverless/bin/serverless:5
let argv = require('minimist')(process.argv.slice(2));
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Is there currently any way to either a) patch AWS to use the node version that we are running/testing on locally or b) force sls to use the same node version locally as AWS lambda is using?

**Comment by joostfarla** [comment]
@alexklibisz good question!

Serverless is built on Node 4.x using ES2015 syntax. Hence, that is the minimal version for running the CLI commands.

Unfortunately, at the moment there is no standard way of testing your scripts locally in the exact same runtime environment as AWS does. One of the ideas is to provide a standard integration of the `run` command with Docker containers in the future.

Furthermore, the https://github.com/serverless/serverless-optimizer-plugin provides a way to *transpile*  your ES2015 code (using [Babel](https://babeljs.io/)) to ES5 code, which is supported by Node 0.10.x. This plugin is work-in-progress, but will be usable soon!

Let's hope AWS will provide support for Node 4.x soon!

**Comment by visualasparagus** [comment]
Doesn't this seem a bit backwards? Shouldn't Serverless support as a default the current AWS versions? Why not transpile Serverless to run on the existing AWS version instead of the other way around? Including a Docker dependency seems a waste when the great thing about Lambda is you don't have to deal with containers at all. Otherwise is there a way to hook the optimizer plugin in before the `sls function run` command so you can transpile for testing if that seems the better route?

**Comment by visualasparagus** [comment]
What if Serverless included it's own node executable that matched the AWS version and targeted this directly when doing `slss function run`. This could then also be used for the other supported languages as well to keep the testing functionality in line with the reality of AWS.

**Comment by joostfarla** [comment]
@visualasparagus Thanks for your thoughts! 

Letting the optimize plugin transpile on the `run` action sounds like an excellent option! :+1: 

About shipping binaries:
1) AWS supports multiple runtimes (Python, Java) already and it's very likely they will add a Node v4 runtime soon. So if we would do this, binaries should be offered and maintained for all runtimes.
2) Binaries are compiled differently, dependent on the host OS. That might make things pretty complex. This is were Docker might come in handy.

**Comment by visualasparagus** [comment]
@joostfarla just trying to think along. hopefully some of it is helpful.

Good points on the binaries. I'm still not a fan of the docker dependency though. Although I understand it's benefits. 

Perhaps another option to forcing a transpile to effectively to a test run — which will only apply to node anyway — is to allow the option to point the command line to an executable. It can use the system path by default, but otherwise allows for an override. This will also allow people to maintain legacy projects where necessary if that's applicable. It just seems strange to couple Serverless to the AWS versions.

Ideally the system would allow for a cascading preference. So first system wide, then s-project.json, then look at the s-module.json file. This will allow for fine grained version control that is maintained by the person/team who needs it and not by the serverless team. This also would mean that the runtime specification might need a version attribute depending if AWS will support different versions in lambda.

**Comment by MrRio** [comment]
Shipping the same version of Amazon Linux with the node version used for the 'sls serve' command will be absolutely invaluable to quick development cycles.

**Comment by MrRio** [comment]
You'd want it to undergo the same transformation it does when going live, i.e. get zipped up and minified and shipped into the docker container.

**Comment by visualasparagus** [comment]
@MrRio - Just trying to think of a simple way to support different languages and versions of the lambda environment without putting too much burden on serverless. I agree that you want to match the production environment as closely as possible. How is Python currently, or in the future Java, dealt with for `slss function run`? Can you point serverless to a particular binary? It just seems simplest to allow for overrides of the default binary path for whatever language/version you are using. If AWS eventually supports both older and new versions, serverless will need to be flexible enough for it.

**Comment by alexklibisz** [comment]
@MrRio I agree. I think the primary problem I would love to see solved is: you can run your code locally and it works, but then it fails in lambda. To me that breaks the entire value proposition of SLS as a tool. 

@visualasparagus I agree that having docker as a necessity for testing lambda functions locally is a heavy dependency. I develop on ubuntu linux but if I'm not mistaken, don't Windows and Mac require spinning up a complete virtual machine for every ```docker run```?

@joostfarla Is there any chance that something more lightweight like nvm (https://github.com/creationix/nvm) could be used to swap out node versions on the fly within the ```sls function run``` command? I know this isn't a solution that fits for python and java, but maybe a start?

**Comment by MrRio** [comment]
@visualasparagus Overrides for the binary path sound sensible and being able to configure how heavy a dependency you want to take on for emulation would be useful. This could be the job of plugins. Create different sls-docker-run / sls-native-run plugins for example.

> @MrRio I agree. I think the primary problem I would love to see solved is: you can run your code locally and it works, but then it fails in lambda. To me that breaks the entire value proposition of SLS as a tool.

Absolutely, I think that's at the core of what SLS must solve. Though the technical implementation itself is not clear to me yet.

> @visualasparagus I agree that having docker as a necessity for testing lambda functions locally is a heavy dependency. I develop on ubuntu linux but if I'm not mistaken, don't Windows and Mac require spinning up a complete virtual machine for every docker run?

It is heavy and gets even heavier for Mac (my platform) and Windows. You can run just one VM for all your dockers however. I know Docker are looking at having containers running on top of Mac directly somehow.

> @joostfarla, @visualasparagus Is there any chance that something more lightweight like nvm (https://github.com/creationix/nvm) could be used to swap out node versions on the fly within the sls function run command? I know this isn't a solution that fits for python and java, but maybe a start?

The project is currently recommend 'n' to do this switching, which is what we use at our company after some developers trying nvm and switching.

**Comment by joostfarla** [comment]
Good thinking! Using `n` (or similar) should definitely be easier to use. But, besides versioning, is this approach also capable of supporting other important aspects, like:

* Support non-UNIX operation systems (Windows)
* Availability of `ImageMagick` native binary with default settings
* Clean Node installation with only `aws-swk` and `imagemagick` as globally installed dependency
* Emulate working directory in the same way Lambda executes the script

Are there other aspects to incorporate?

**Comment by eggyal** [comment]
> AWS supports multiple runtimes (Python, Java) already and it's very likely they will add a Node v4 runtime soon.

There's a thread or two on AWS Forums discussing this issue, with some (indicative) official viewpoints [here](https://forums.aws.amazon.com/message.jspa?messageID=664872#664872) and [here](https://forums.aws.amazon.com/message.jspa?messageID=692719#692719).  Note that v4.3.0 has [just](https://bugzilla.redhat.com/show_bug.cgi?id=1192647#c16) made it into Fedora, which it's reasonable to suspect is upstream of Amazon Linux, so I'm optimistic it won't be too much longer.

> It is heavy and gets even heavier for Mac (my platform) and Windows. You can run just one VM for all your dockers however. I know Docker are looking at having containers running on top of Mac directly somehow.

For the highest dev/prod parity, one would ideally want to run the relevant AMI itself—but the kernels depend on a Xen hypervisor (to launch one on OSX/Windows would itself require a suitable host OS running in a VM), and even then other customisations made by Amazon may ultimately require replacing the kernel entirely (the most similar readily-available build probably being [this one of 4.1.13 for Fedora 21](http://koji.fedoraproject.org/koji/buildinfo?buildID=697373)).

Given that level of parity is probably overkill, I find Docker to be an acceptable compromise (especially since I use boot2docker, which is currently based off a 4.1.17 kernel—pretty darn close).  Yes, it requires a VM on non-Linux platforms—but personally I find boot2docker in VirtualBox to be practically unnoticeable (provided one avoids vboxsf).  Indeed, it's so lightweight that even on my teensy laptop I can easily launch multiple simultaneous containers to simulate the entire production infrastructure (S3, Dynamo, IoT, etc). Even if running Docker natively on OSX ever becomes possible, I'd still prefer to use a Linux VM since Docker containers utilise the host's kernel and Darwin isn't exactly similar to Linux.

So, I've built a Docker image to match the AWS Lambda runtime environment as closely as possible.  It was created on the exact same EC2 AMI as Lambda, with ImageMagick/Python27/java-1.8.0 installed from Amazon repos, nodejs-0.10.36/npm from EPEL, imagemagick/aws-sdk@2.2.32 from npm and boto3==1.2.3 from pip.  I'm tempted to use [lambdash](https://alestic.com/2014/11/aws-lambda-environment/) to explore/match further aspects of the runtime environment, including environment variables, working directory, other installed software... but I haven't got round to that yet.

Anyway, to simulate API Gateway within this environment I initially turned to [Nopik/serverless-serve](https://github.com/Nopik/serverless-serve)—but that immediately led to this very issue, as I reported under [Parity with AWS runtime](https://github.com/Nopik/serverless-serve/issues/21).  My solution was to use Babel to transpile & polyfill serverless and serverless-serve in order that it can run within the container—but since `sls serve start` reads the same `s-project.json` as used for deployment, it attempts to load every serverless plugin... so they _all_ need to be transpiled!  This is definitely a bit of a headache.

Of course, this won't be necessary once Node v4 lands in AWS—but there's no guarantee of when that will be.  It could also have been avoided if serverless and its plugins were shipped compatible with v0.10 (you could have performed transpilation before packaging/testing), but I guess that's unlikely to happen.

Meanwhile, I'm having to implement some nasty hacks.  The situation would be slightly improved if one could specify which plugins to load/ignore at the command line, or even nominate an alternative `s-project.json`—any chance of something like that?

**Comment by lpanebr** [comment]
It seems a similar approach [using docker containers to run lambda and dinamodb locally](https://aws.amazon.com/blogs/compute/cloudmicro-for-aws-speeding-up-serverless-development-at-the-coca-cola-company/) is in development. The downside is it's for python lambda...

**Comment by eggyal** [comment]
@flomotlik: Is this resolved?
