### ISSUE TITLE
enable/disable optimization

### ISSUE THREAD

**Issue by alexklibisz** [serverless/serverless#447]
In the JAWS demo at AWS re:invent 2015, at about 32:00 (https://youtu.be/D_U6luQ6I90?t=1920), the presenters show how you can enable/disable optimization.

Since then, the Jaws changed to serverless, and it seems that the configuration files have also changed significantly. 

Is there any way to "flip this switch" like in the presentation? 

I'm currently uploading a lambda function that is ~30 lines and requires three libs: Bluebird, lodash, and Firebase, and it's coming in at ~2.5 mb. Does this sound reasonable? Or do I somehow have this optimization feature turned off and I need to enable it?

**Comment by erikerikson** [comment]
Check out your local node_modules directory.

bluebird is 512 KB on disk
lodash is 2.2 MB on disk
I don't have Firebase

Since those will have been pre-reduced... yes, it does sound reasonable.

Look here for further optimization: https://github.com/serverless/serverless-optimizer-plugin

**Comment by joostfarla** [comment]
@alexklibisz the size of the script package affects the performance of the Lambda containers, so it might be worth making your codebase as small as possible.

As @erikerikson mentioned, you might want to have a look at the https://github.com/serverless/serverless-optimizer-plugin. It's actually the same thing as shown in the JAWS demo, it just has been extracted to a separate plugin for Serverless. This plugin enables you to `browserify` the code, which means that it extracts and bundles only the needed code into one single file. It can also compress (minify) the code, so that definitely saves a lot.
