### ISSUE TITLE
Feature Request: Access Serverless Functionality from Code

### ISSUE THREAD

**Issue by simlu** [serverless/serverless#4482]
I.e. we currently have

```shell
$ sls deploy
```

but I would like to access via code as

```javascript
const sls = require('serverless');
sls.deploy();
```

Or does something like this already exist? I couldn't find it in the readme. Cheers

**Comment by horike37** [comment]
Thank you for opening up @simlu :smile: 
Currently, the framework doesn't be officially supported as using a library.
it would be done on v2.0 if we would decide to support for that since the many parts of framework codebase will be changed(would be breaking changes)

We have been discussing that on the #1678 issue, so you can see that :+1:
closing this issue due to duplicating the previous one.
