### ISSUE TITLE
Question on resilience: Handling module retries when resources temporarily unavailable

### ISSUE THREAD

**Issue by rarkins** [serverless/serverless#449]
Is there any recommended way for handling temporary outages of third party components and the associated queueing and retry logic? The simplest example would be sending a transactional email notification, using a serverless module for sending. Let's say the transactional email provider is temporarily unresponsive, or rate limiting us. Let's also assume there's no upstream endpoint expecting a REST response or anything like that (the email is generated internally). In the serverless architecture, what would be the way to queue and retry such a task so that the email is eventually delivered?

**Comment by joostfarla** [comment]
Most ideal solution would be to use SQS as a task queue, since SQS allows you to delay delivery messages in the queue for up to 15 minutes. Unfortunately, Lambda does not support SQS events at this time, so you would need to have an intermediate EC2 instance listening to the queue and firing Lambdas (which makes the solution not 100% serverless).

Alternatively, you might want to check out SNS or Kinesis to republish messages after failure (but without delaying). You could also invoke a Lambda directly from another Lambda.

**Comment by rarkins** [comment]
What about this approach?

- Modules that may suffer from such "temporary" failures and should retry have an SQS queue each
- If a module fails its task with a non-final type of error, it puts its inputs into its queue
- Scheduled lambdas can be used to service the queues ever *x* minutes, depending on the urgency of those events/modules (e.g. for email I'd probably make the checks every 5 minutes)

And if something like this is plausible, could that sort of capability be built into serverless itself, or would it work as a serverless module somehow? i.e. to save every other module having to reimplement the same functionalities over and over. Until the point that AWS supports this concept natively, it would be nice if a serverless module can just declare itself as "resilient",with  a retry-every value (e.g 5 minutes) and then be able to support a self.queueforretry() function whenever applicable.

**Comment by joostfarla** [comment]
@rarkins Sounds like a good approach! You must be aware though that you will introduce the risk of piling up messages in the queue, which can cause unforeseen delays. Maybe the scheduled Lambda should just serve as orchestrator, firing multiple Lambda's for each task, depending on the number of items in the queue.

This sort of capability should typically be built in a separate plugin, so that this behavior can be enabled and configured per function or module.

**Comment by rarkins** [comment]
@joostfarla yes, my idea was as you suggest - that this "orchestrator" just empties the queue by invoking the lambda function in parallel for every message there, i.e. every event in the queue is processed in parallel (thanks to lambda) every x minutes.

And thanks for the advice regarding the plugin approach.

I will close this now, as it was just a question and has been answered. Good to know that it's theoretically possible, and hoping AWS themselves will develop this somehow in future!

**Comment by simple10** [comment]
Found this thread while searching for answers to the same problem.

The queue per rate limited module approach seems to be a common way to solve this problem. Then use an orchestrator lambda function mentioned by @rarkins that runs every X minutes, pulls tasks from the queue, and farms them out to other lambdas. The orchestrator contains the logic to back off (i.e. not pull from the queue) if API rate limiting is in effect.

Here's a good blog post that explains the details:
https://cloudonaut.io/integrate-sqs-and-lambda-serverless-architecture-for-asynchronous-workloads/
