### ISSUE TITLE
Packing external modules: stderr maxBuffer exceeded 

### ISSUE THREAD

**Issue by klimentLambevski** [serverless/serverless#4496]
I am using gitlab ci for building and deploy with serverless and i am getting this error.

```
Serverless: WARNING: Could not determine version of module nodes2ts
Serverless: Adding explicit peers for dependency graphql-tools
Serverless: WARNING: Could not determine version of module long
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: ramda@^0.24.1, nodes2ts, aws-sdk@^2.122.0, graphql-tools@^1.2.3, graphql@^0.11.3, jsonwebtoken@^8.1.0, apollo-server-lambda@^1.1.2, handlebars@^4.0.11, long
 
  Error --------------------------------------------------
 
  stderr maxBuffer exceeded
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.10.3
     Serverless Version:     1.24.0
```

**Comment by HyperBrain** [comment]
@klimentLambevski Hi, thanks for reporting.

I think you have hit the buffer limitation of the NPM execute in the webpack plugin. By default the buffers are 200K for stdout and stderr on Node. The webpack plugin has an option to increase the buffers for such cases. Can you try to set the flag to a higher value?

This would set the buffer to 400K
```yaml
custom:
  packExternalModulesMaxBuffer: 409600
```

**Comment by klimentLambevski** [comment]
@HyperBrain Hi, thank for the quick reply, i added `packExternalModulesMaxBuffer` in the config and it worked. 
The thing that i don't get is that the build passes locally but not on docker when the buffers are 200K

**Comment by HyperBrain** [comment]
It might be that NPM produces more output (or warnings) on Docker. Maybe the configuration is different than on your local machine.

**Comment by klimentLambevski** [comment]
Probably it is because i use npm 5 on local machine and npm 3 on docker.

**Comment by tommedema** [comment]
@HyperBrain in his output there are also lines like:

```
Serverless: WARNING: Could not determine version of module nodes2ts
```

I am also seeing this but for `aws-sdk`:

```
Serverless: Package took [1365 ms]
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: WARNING: Could not determine version of module aws-sdk
```

`aws-sdk` has a normal package.json with a `"version": "2.170.0"` entry. However, I put it into a parent directory because I put all my dev dependencies there as described here: http://www.goingserverless.com/blog/keeping-dev-dependencies-out-of-your-serverless-package

Is this serious enough to create an issue for or is this expected behavior?

**Comment by HyperBrain** [comment]
@tommedema This is expected in case a 2nd level dependency becomes a 1st level dependency, but the version cannot be determined from the package.json.

With serverless-webpack you should not need to separate dev and prod dependencies. It will only install prod dependencies in the packages. In your case it warns about aws-sdk, because webpack tells, it's a needed dependency, but in your service package.json it is missing. So no version can be determined.

You have 2 options here: (1) put aws-sdk into the dev dependencies - then webpack does not warn and does not install it. (2) add forceExclude: - aws-sdk to make sure that it does not try to install it into the packages.

At work, we do not remove the dev dependencies from our projects, because webpack will take care of that and everything works fine. Only if you use pure serverless without the webpack plugin you have to take care.

**Comment by tommedema** [comment]
@HyperBrain in my case I use a lerna repo. And some of the packages use serverless-webpack, while others do not (they don't even have functions often; but they have plugins). So I still benefit from having one root / project level package.json with all dev dependencies.

For now I will just use `forceExclude`; it's only been a problem with aws-sdk. Still, I think this is a fair case, it would be better if it would include Nth level dependencies.
