### ISSUE TITLE
Getting around API gateways 30 second timeout restrictions

### ISSUE THREAD

**Issue by achadee** [serverless/serverless#4500]
We have lambda functions that query slow customer wordpress instances causing API gateway to timeout.

This is an inevitable part of our business. is there a way that the lambda function can still execute over http without using api gateway?

Api gate has a hard 30 second restriction on http requests

**Comment by HyperBrain** [comment]
Hi @achadee ,

You could decouple the processing from the frontend, i.e. the lambda attached to the endpoint just retrieves a command and invokes a lambda that does the processing asynchronously (using lambda invoke with the invocation type `event` instead of `RequestResponse`). The processing lambda then has time until the full lambda timeout hits.

Of course you cannot deliver any immediate results with the response, maybe only a "continue" or something similar. How to get the deferred results is a different design question then. You even could use SNS to send something to the client if the client architecture supports it, or do a poll based retrieval.

Unfortunately the 30 second APIG timeout cannot be increased.

**Comment by dougmoscrop** [comment]
+1 on separation - you generally want your API Lambdas to be 1GB of memory or more for consistent performance, but your 'slow' detectors probably can run at 128 because they're just waiting.

**Comment by achadee** [comment]
So I ended up doing that, which I'm strongly against because I want to keep the request/response thing still going. I guess my question was if we could leverage cloudfront in serverless to bypass APIGW's hardcoded distribution?

**Comment by RafalWilinski** [comment]
APIGW uses CloudFront internally. I think it's not possible to bypass that using AWS services. You might consider provisioning your own, hosted on ec2 gateway/reverse proxy e.g. https://github.com/serverless/event-gateway to bypass this issue.

**Comment by celicoo** [comment]
I'm moving all my infrastructure to Azure Functions because of that :/

**Comment by achadee** [comment]
Hey guys, for anyone still stuck in the end I wrote up a super simple express proxy server to serve my http requests, and I set the timeout to 2 minutes:

```javascript

router.post('/', function(req, res, next) {

  lambda.invoke({
    FunctionName: req.query.function_name,
    Payload: JSON.stringify(
    {
      "body": req.body
    }
    )
  }, function(error, response) {
    console.log(error)

    var r = JSON.parse(response.Payload)

    console.log(r)
    res.status(response.StatusCode).json(JSON.parse(r.body));
  });
});

```

**Comment by praveenprabharavindran** [comment]
Thank @achadee  for sharing your findings.
