### ISSUE TITLE
Use CloudFormation Change Sets

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#4562]
# This is a Feature Proposal

## Description

CloudFormation supports sending a whole new template, then getting a Change Set and choosing to apply it or not. This is really useful, because CloudFormation still does have a ton of bugs with regards to failures and `DeletionPolicy` clauses.

Similar or dependent issues:
* #4179

**Comment by HyperBrain** [comment]
Hi @hassankhan , good thoughts 👍 

I would see this feature rather as an extension of the plan command and not as general for the framework. The plan command seems the right place for me to optionally have a CF changeset emitted.
Imo this should be kept separate, because if added to the standard deployment procedure, it will be a breaking change.

**Comment by alexdebrie** [comment]
@hassankhan You're in luck! @shortjared and his friends at Trek10 created a plugin to create changesets with Serverless -- [serverless-cloudformation-changesets](https://github.com/trek10inc/serverless-cloudformation-changesets). I haven't used it personally, but it may solve your problems.

**Comment by kbariotis** [comment]
@HyperBrain 

> I would see this feature rather as an extension of the plan command and not as general for the framework. 
IMHO, this should be a general feature, in order to avoid unneeded deployments. Right now, we always deploy new version even if no changes have happened. This is a real pain since we already have a dozen of serverless projects and new are added every day.

> Imo this should be kept separate, because if added to the standard deployment procedure, it will be a breaking change.
That's not a reason to keep it separate, breaking changes can happen with major releases.

**Comment by alexcasalboni** [comment]
Side note: if we find a way to use change sets we would also enable the SAM special resources (by applying the [`AWS::Serverless` transform](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html)).

**Comment by encee** [comment]
> @hassankhan You're in luck! @shortjared and his friends at Trek10 created a plugin to create changesets with Serverless -- serverless-cloudformation-changesets. I haven't used it personally, but it may solve your problems.

I am not sure if anyone else has gotten this to work but i can't seem to get any deployments to upgrade with it, doesnt seem to introduce a new deployment file in s3. Initial creates are fine.

The ability to see what changes before running these is huge and seems like a lacking feature, i understand it could be breaking to continuous delivery but recovering from some of the mistakes in cloudformation can be quite time consuming.
