### ISSUE TITLE
cloudFormation Template is invalid ::  instance of Fn::GetAtt references undefined resource ContactUSLambdaFunction

### ISSUE THREAD

**Issue by balakrishna222111** [serverless/serverless#4567]
`service: contactUS

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  apiGateway: contactUSAPI

custom:
  region: ${self:provider.region}
  apiGateway: ${self:provider.apiGateway}

functions:
  contactSendEmail:
    Type: 'AWS::Lambda::Function'
    timeout: 10
    handler: handler.contactSendEmail

resources:
  Resources:
    contactUSAPI:
     Type: AWS::ApiGateway::RestAPi
     Properties:
      Description: "A contactUS API"
      Name: ${self:custom.apiGateway}

    contactUSAPIResource:
       Type: 'AWS::ApiGateway::Resource'
       Properties:
         RestApiId:
           Ref: ${self:custom.apiGateway}
         ParentId: 
            Fn::GetAtt:
               - ${self:custom.apiGateway}
               - "RootResourceId"
         PathPart: "contactSendEmail"

    LambdaInvokePermission:
       Type: 'AWS::Lambda::Permission'
       Properties:
         Action: lambda:invokeFunction
         FunctionName:
            Fn::GetAtt:
              - ContactUSLambdaFunction
              - Arn
         Principal: apigateway.amazonaws.com
         SourceArn: 
           Fn::Join:
            - ''
            - - 'arn:aws:execute-api:'
              - Ref: AWS::Region
              - ":"
              - Ref: AWS::AccountId
              - ":"
              - Ref: ${self:custom.apiGateway}
              - "/*"

    ContactUSDeployment:
       Type: 'AWS::ApiGateway::Deployment'
       DependsOn: 
         - contactUSRequest
       Properties:
         RestApiId: 
           Ref: ${self:custom.apiGateway}
         Description: "My deployment"
         StageName: "DummyStage"

    ContactUSRequest:
      Type: AWS::ApiGateway::Method
      Properties:
         RestApiId:
           Ref: ${self:custom.apiGateway}
         ResourceId:
           Ref: contactUSAPIResource
         HttpMethod: POST
         AuthorizationType: NONE"
         Integration:
           Type: AWS
           IntegrationHttpMethod: POST
           Uri:
             Fn::Join:
             - ''
             - - 'arn:aws:apigateway:'
               - Ref: AWS::Region
               - ":lambda:path/2015-03-31/functions/"
               - Fn::GetAtt:
                 - ContactUSLambdaFunction
                 - Arn
               - "/invocations"
         RequestParameters:
           "method.request.querystring.fromEmail": true
           "method.request.querystring.toEmail": true
           "method.request.querystring.subject": true
           "method.request.querystring.data": true
         MethodResponses:
           - StatusCode: 200`

**Comment by HyperBrain** [comment]
@balakrishna222111 Thanks for posting the information 👍 

I'm trying to understand, what you try to achieve with this serverless.yml. Am I right that you try to encode a complete API structure with your resources section?
Is there any specific reason why you do not use the `event / http` section of your functions to define the endpoints and let serverless create the API, so that it is linked completely to your lambda functions?

This manual approach for a complete API will get you into trouble (especially as the name of your AWS::ApiGateway::Deployment resource is fixed). It would never redeploy the API after the first deploy.

Can you check https://serverless.com/framework/docs/providers/aws/guide/events/ on how to add an API definition to your functions.

In the case I'm comletely wrong with my assumptions above, please add a more descriptive explanation on what you want to achieve (using our issue template) in the issue description above. Thank you.

**Comment by balakrishna222111** [comment]
@HyperBrain Thanks for giving reply back..,
i have one contactSendEmail Lambda Function i want to upload this lambda function in apigateway

**Comment by balakrishna222111** [comment]
@HyperBrain  withouts events also we can add our lambda func to api ryt?

**Comment by HyperBrain** [comment]
@balakrishna222111 You should use the "events" definition as mentioned in the docs. Events of type "http" will just create the proper endpoints for your function and deploy them to the API Gateway automatically.

```yaml
# serverless.yml
functions:
  contactSendEmail:
    timeout: 10
    handler: handler.contactSendEmail
    events: # All events associated with this function
      - http:
          path: contact/send
          method: post
```

This will e.g. make your function available as `POST contact/send` in the API, i.e. your lambda is called when you post to this endpoint.

You do not need to declare the API in the resources section.

**Comment by balakrishna222111** [comment]
@HyperBrain  after adding events in my serverless.yml file also its throwing an error like this
 [contactUSRequest] in the Resources block of the template

**Comment by HyperBrain** [comment]
You should remove all manual resources for the API from the serverless.yml. Serverless will create them for you.

**Comment by balakrishna222111** [comment]
@HyperBrain  it's working fine..! i dont want to use events in my serverless yml which means without events i want to create everything in my serverlss .yml file using cloud function template is it possible

**Comment by HyperBrain** [comment]
Great to hear that!

Unfortunately the framework is designed to keep control over the API generation and makes sure that all necessary CF resources are created properly. Defining everything manually is not really possible nor recommended, because you will run into all issues (side-effects) that the framework already solves (a sample is, that you have to create the AWS::ApiGateway::Deployment resource with a random name to have it be deployed as updating with the same name does not work and won't deploy again), or that it automatically creates a correct APIG stage, and much more.

**Comment by balakrishna222111** [comment]
@HyperBrain do u have any sample like that for reference if yes share it

**Comment by HyperBrain** [comment]
Here at the very end is an example that overrides the logRetention of a lambda function resource:
https://serverless.com/framework/docs/providers/aws/guide/resources/#aws-cloudformation-resource-reference

You can also find there, how the resource logical CF id is generated to know what resource to override.
Another way to find out how the resources generated by Serverless are named is, to run `serverless package` and open the CF template json in the `.serverless` folder.

It works similar for others (only for a few ones not that have auto-generated names).

**Comment by balakrishna222111** [comment]
@HyperBrain could u pls help me out i want to enable cors in the serverless yml file but not in the events section which means i want to add it in cloud Formation template

**Comment by balakrishna222111** [comment]
thanks for the help @HyperBrain

**Comment by HyperBrain** [comment]
Hi @balakrishna222111 ,
Regarding the CORS question, you might ask that in the Serverless gitter channel https://gitter.im/serverless/serverless. There are always people from around the world in there who probably know the answers and can immediately answer.
