### ISSUE TITLE
serverless deploy function doesn't deploy triggers

### ISSUE THREAD

**Issue by dbachko** [serverless/serverless#4578]
## Description
**serverless deploy function** should deploy triggers for this function, but it never happens

Log: 
**Serverless: Bundling with Webpack...
Serverless: Packaging function: binance...
Serverless: Excluding development dependencies...
Serverless: Deploying function: binance...
Serverless: Successfully deployed function: binance .** 

Vs when you do full deploy( **serverless deploy** ):
**Serverless: Bundling with Webpack...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling Functions...
Serverless: Compiled Function (main): { ... }
...
Serverless: Compiling API Gateway definitions...
Serverless: Compiling Rules...
Serverless: Compiled Rule (main): [{ ... }]
...
Serverless: Compiling Triggers & Feeds...
Serverless: Compiled Trigger (NAME_schedule_trigger): { ... }
...
Serverless: Deploying Functions...
Serverless: Deploying Function: FUNCTIONNAME
...**

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Provider***: openwhisk

**Comment by HyperBrain** [comment]
Hi @dbachko , thanks for asking.

`deploy functions` is not comparable to a full deployment (you're speaking of AWS here?), because it is completely decoupled from CloudFormation and will _not_ update anything but the function's code and pure configuration.
In that respect, function deploy should only be used for debug deployments that just upload a new function version, but do not change any related things that are controlled by CloudFormation.

In fact a function deployed by `deploy function` isn't even tracked by CloudFormation and any rollback of the stack would just ignore the manually deployed stuff and restore to the last fully deployed service.

**Comment by pmuens** [comment]
Closing this since `deploy` should be used for fully-fledegd deployments. `deploy function` only updates the the functions configuration / code.
