### ISSUE TITLE
Feature Request: Support payload compression configuration for Amazon API Gateway

### ISSUE THREAD

**Issue by jaikdean** [serverless/serverless#4593]
# This is a Feature Proposal

## Description

Amazon's API Gateway has recently added [gzip compression of responses](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html). It would be useful to be able to configure this in `serverless.yml`.

Similar or dependent issues:
None found

## Additional Data

n/a

**Comment by tspecht** [comment]
Any status on this? Would love to have the response sent GZIPped, have all my express setup already configured to do so but the client is not able to decode the body properly since API gateway is messing with it!

**Comment by JimmyCheng** [comment]
Looking forward to the update on this feature.

**Comment by rebolyte** [comment]
Also looking for updates on this. I believe this is the limitation that's currently causing content encoding issues when trying to deploy a package that uses [aws-serverless-express](https://github.com/awslabs/aws-serverless-express).

**Comment by simlu** [comment]
Also looking forward to having this in the core. Meanwhile there is a plugin available:

>[serverless-content-encoding](https://github.com/xeno-dohai/serverless-content-encoding)

**Comment by joeyvandijk** [comment]
@horike37 @HyperBrain Cloudformation support is available: could you update the labels and determine priority? See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html for the reference.

**Comment by HyperBrain** [comment]
@joeyvandijk Thanks for the info 👍

**Comment by simlu** [comment]
**Important note for serving big files** _(should be added to the readme once this is implemented)_

If you are serving large files and want to compress them it might be desirable to do so in the lambda function instead of using api gateway. The reason is that lambda has a [maximum output size](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) of 6 MB. This means you'll get a 500 from api gateway if lambda returns anything bigger than that. Using gzip compression inside the lambda instead of API can increase this significantly.

So consider carefully if this setting / plugin is really what you want!

**Comment by daniel-cottone** [comment]
I've raised a PR which should add this feature. https://github.com/serverless/serverless/pull/5529
