### ISSUE TITLE
URL showing in terminal when no credentials are found is broken

### ISSUE THREAD

**Issue by nmarcora** [serverless/serverless#4674]
OS: darwin
Node Version: 8.7.0
Serverless Version: 1.25.0

My AWS credentials were not properly configured on this machine, and when I tried to deploy my Serverless application, I got the message:

```
Serverless Error ---------------------------------------

  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: http://bit.ly/aws-creds-setup.
```

However, when clicking on the URL provided, the URL that opens up carries the dot from the above text and bitly just gives presents me with a 404 message. Removing the dot from the URL takes me to the right page.

This is happening in my VS Code integrated terminal. I've tested this on the normal Mac OS terminal and clicking on the link here is not a problem. I will also be submitting an issue to VS Code, as it is likely that in the future, they can skip the dot at the end of URLs when parsing. But in the meantime, adding an extra space between the URL and the dot should fix this and allow this convenient feature to be used in all terminals that support hyperlinks, instead of having to copy-paste or edit the url.

**Comment by HyperBrain** [comment]
Hi @nmarcora , that's really interesting. In this case the URL is the last "word" in the sentence, so from grammar, it it written correctly. Imo, this is a parsing issue in VSCode, as parsed URLs should be stripped of the trailing dot for them to work.
However, in our case here, the dot can be omitted in the message, so that failures in case of invalid parsing are less likely, so I tagged it as enhancement.
