### ISSUE TITLE
Module not found after upgrading from 1.25.0 - 1.26.0

### ISSUE THREAD

**Issue by andrewspinks** [serverless/serverless#4693]
# This is a Bug Report

## Description
My serverless definition uses a module called `serverless` as in the following configuration.

```
functions:
  myFunction:
    handler: serverless.handler
```
After upgrading to 1.26.0 I kept getting the error ```Unable to import module 'serverless': Error    at require (internal/module.js:20:19)```.
After looking at the deployed code it looks like my serverless.js module is no longer being included in the source uploaded to lambda. I assume this is due to this change: https://github.com/serverless/serverless/pull/4590. Renaming our entry module to a name other than serverless.js fixes the problem.

If `serverless.js` is now a reserved name used for configuration files, it would be good to have some sort of warning when using it like this!

## Additional Data

* ***Serverless Framework Version you're using***:
1.26.0
* ***Operating System***:
macOS / alpine linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @andrewspinks , thanks for reporting this. Imo it is a bug, because the `serverless.js` must only be evaluated and handled, if there is no `serverless.yml` nor a `serverless.json` available for the service configuration.
Otherwise it has to be treated as user code. We should not restrict users with their names of their handler files.

**Comment by pmuens** [comment]
Closing this issue since it's quite stale and we've published a couple of versions in the meantime. Feel free to re-open if this is still an issue.
