### ISSUE TITLE
Go function is not supporting local invoke 

### ISSUE THREAD

**Issue by sandeep1512** [serverless/serverless#4746]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Mac
* ***Stack Trace***: 
* ***Provider Error messages***:  Serverless Error --------------------------------------- You can only invoke Node.js, Python & Java functions locally

**Comment by HyperBrain** [comment]
@sandeep1512 Good catch. As the Go runtime has been just supported recently, the local invoke support is still missing for it. I'll tag this report as a feature request then.

**Comment by napalm684** [comment]
New to serverless, I know this will give us the ability to run locally for go, but any idea if debug support via delve will be possible as a result?

**Comment by AyushG3112** [comment]
@HyperBrain any update on this please? I think this should be have a higher priority and this is very important for devs, especially during initial development.

**Comment by tylermauthe** [comment]
Hello! I needed this, so I built it:
https://github.com/tylermauthe/serverless/tree/go-local-invoke

I've still gotta write some tests for it - I tried to follow the same format as #4199, with some go flavouring on top.

There's a few weird things:
- You have to [compile special non-linux binaries](https://github.com/tylermauthe/serverless/tree/go-local-invoke/docs/providers/aws/examples/hello-world/go#2-invoke-function-locally) for your platform (unless you dev on linux)
- I've updated the Makefile templates to have a `build-local` target which outputs to `bin-local`
- I added an (undocumented) environment var that can override the `bin-local` path: `SLS_GO_BIN_LOCAL` -- I figured it shouldn't be documented because you probably know what you're doing if you mess with your Makefile
- Probably a few more things, I built this in a morning...

**Comment by AyushG3112** [comment]
@tylermauthe Nice, and I found another approach which could be used, though it adds technical debt on the dev side.


1. I installed the `serverless-sam` plugin, using `serverless plugin install --name serverless-sam`
2. Then I installed the AWS SAM CLI using `pip install --user --upgrade aws-sam-cli`(and docker if needed)

After this, I can use the AWS SAM(Serverless Application Model) to locally invoke my applications.
Infact, here's a `make` target to spin up your APIs locally

``` make
start-local:
	serverless sam export --output ./template.yml
	sudo sam local start-api
```

**Comment by tylermauthe** [comment]
Cool @AyushG3112! Personally I prefer my solution since you aren't required to use `pip` or `sam` - adding both of those to your toolchain seems like a lot of dependency.

Thinking about this more, I can probably add some smarts to the make target so that it rebuilds if the binary is not executable on the target platform. Target being either your local laptop or the Lambda environment...

I hope to find some time this week to get around to opening the PR -- unless there's some feedback from @HyperBrain or another Serverless maintainer! Thanks!

**Comment by AyushG3112** [comment]
Another potential small problem I see with your implementation is that if some developer changes the production build path from `/bin/*` to something else, like `/serverless_builds/*`, that will fail.

I have no issue with the implementation as such,  but it would be important to make a note of this condition.

**Comment by tylermauthe** [comment]
Thanks for your feedback @AyushG3112!

For the issue of moving the binary path - I had already added an environment variable `SLS_GO_BIN_LOCAL` that changes the path it looks for the binaries for local invoke within. However, since you asked about it - it would probably be a good idea to document it. The way I am finding local invoke binaries is really inelegant and I'd love a better solution...

AFAIK, you're required to re-run `make build` whenever you invoke against a remote target as well. I think that abstracting the build logic into invoke as you suggest would require a deeper change to the way `sls invoke` works. It's a really great idea for DX, but it seems like the existing choice to separate build and deploy of compiled languages was done intentionally - it works the same for Java (maven) and Go (make). Input from some Serverless maintainers would be appreciated on this suggestion also!

Take for example, this blog post on Golang Lambda support:
> Recompile & deploy again
https://serverless.com/blog/framework-example-golang-lambda-support/

If `sls invoke` did run the build, it might fix the unenforceable coupling between the build and the deploy/invoke modules. Deploy/invoke depends on build, but there's no communication between build and deploy - so the coupling must be hardcoded as an assumption. My current solution is to make both components optionally depend on an environment variable. If instead the dependency were inverted, then the build module could receive parameters from the invoke module in local invoke mode - totally solving the issue (since invoke would also have access to it's own data). I can even imagine taking this a step further and giving the build module more features - perhaps even generating the `Makfile` or `pom.xml`!

However, I still think that it should be possible to overload the make target to force a rebuild of binaries specific for your platform. This seems like a reasonable compromise for now, perhaps a larger initiative could be taken to integrate native build processes into the invoke pipeline though!

**Comment by estahn** [comment]
@tylermauthe Thanks for that. I tried to get it working but it doesn't seem to work well with `vendor`...

```sls invoke local -f hello                                                                                                                                                                       ✔  luke-admin/default ⎈  10200  17:06:04
Serverless: Building Go bridge, first invocation might take a bit longer.
make - main.go:14:2: cannot find package "github.com/aws/aws-lambda-go/lambdacontext" in any of:
	/usr/local/Cellar/go/1.11/libexec/src/github.com/aws/aws-lambda-go/lambdacontext (from $GOROOT)
	/Users/estahn/go/src/cloudfront-log-indexer/vendor/src/github.com/aws/aws-lambda-go/lambdacontext (from $GOPATH)
main.go:15:2: cannot find package "github.com/djhworld/go-lambda-invoke/golambdainvoke" in any of:
	/usr/local/Cellar/go/1.11/libexec/src/github.com/djhworld/go-lambda-invoke/golambdainvoke (from $GOROOT)
	/Users/estahn/go/src/cloudfront-log-indexer/vendor/src/github.com/djhworld/go-lambda-invoke/golambdainvoke (from $GOPATH)

make - make: *** [build-bridge] Error 1

/bin/sh: /usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/go/bridge: No such file or directory```

**Comment by tylermauthe** [comment]
Good catch @estahn, I forgot to put `dep` into the bridge package! That should be an easy fix, though.

Thinking more about the local binary path, maybe just calling the `build-local` target after and change the `deploy` to call `build` and just have all the binaries go in the usual binary path. Also adding some testing/error messaging around deploying non-linux binaries and/or locally executing non-platform specific binaries would probably very helpful for anyone debugging this.

Ultimately, I really need some feedback from @HyperBrain or another Serverless contributor on the way forward before I want to do any more work on this - so this work isn't a waste. Perhaps I could make it a plugin instead, I'll have to investigate if that's possible (and probably won't find time to do that).

**Comment by ngmaloney** [comment]
@tylermauthe's solution seems like a good path to move forward with fully supporting Golang in Serverless. Are there any plans to integrate it into the mainline repo? I would categorize the ability to run functions locally a requirement when claiming to support a language.

**Comment by dschep** [comment]
Hey folks, I've created a PR that adds support for golang & other runtimes by utilizing the [`lambci/lambda`](https://github.com/lambci/docker-lambda) docker images. Pleas check it out and test it like this:
```
npm i -g serverless/serverless#invoke-local-docker
```

**Comment by tiny-dancer** [comment]
catching up on this thread, based on @dschep's PR is this issue actually implemented & closed?

**Comment by tylermauthe** [comment]
@dschep's approach is much better than mine - as you are executing in an execution context much closer to a real lambda. Looks like this is part of #5848.

I'm going to unfollow this issue now as I do not use Serverless any more. 👋

**Comment by IvoPereira** [comment]
Is this in the roadmap at all? Some solutions have been already presented here and some official follow-up would be really nice to have.

**Comment by dschep** [comment]
oh. yes, This can be closed. It's supported now, via docker.

**Comment by bwpedro** [comment]
Hi, I'm using docker to test it **locally** and it works! but it takes forever in "Excluding development dependencies" step.

```
AppSync Plugin: GraphQl schema valid
Serverless: [serverless-jetpack] Skipping individual packaging for 1 functions
Serverless: [serverless-jetpack] Packaging 0 functions, 0 services, and 0 layers with concurrency 3
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...

```

It seems like it needs to deploy all functions before executing the **local** test.

In my case I have 3 functions in serveless.yml, one "Excluding development dependencies" for each function.

I was trying in a different project which I have more than 30 functions and it just took forever to test and I just had to gave up using go and use node.js instead.

If I deploy the function and test the **remote** function (just invoke, without local) it works but if I make a change I have to deploy the whole function to test.

Is anyone getting the same problem? What am I doing wrong?

My packages and plugins are:
```
"serverless": "^2.9.0",
"serverless-appsync-plugin": "^1.4.0",
"serverless-go-plugin": "^2.0.1",
"serverless-jetpack": "^0.10.7"
```
