### ISSUE TITLE
Improving the plugin architecture

### ISSUE THREAD

**Issue by joostfarla** [serverless/serverless#475]
This proposal document describes an approach for an improved plugin architecture, which should provide maximum flexibility for extending the default behavior of the framework.

The current actions can be classified into four types:

### Tasks

* Create folders
* Create files
* Apply templates
* Trigger deploy actions (?)

### Actions

* ComponentCreate
* FunctionCreate
* ModuleCreate
* ModuleInstall
* ProjectCreate

### Example use cases

* Generate CRUD module including multiple methods/functions
* Generate / synchronize full component based on Swagger / RAML / API Blueprint spec
* Change folder structure to meet custom requirements
* Change name generation (e.g. apply prefix)
* Change module configuration (e.g. setting restApiId per module)

### Tasks

* Gather and prepare files
* Perform transformations
* Compress result

### Actions

* CodePackageLambdaNodejs

### Example use cases

* Include / exclude files or directories
* Bundle (Node.js) and transform code with Browserify:
  * Transpile (Node.js only) code: ES6/7, Typescript, Coffeescript etc.
  * Minify
* Compile native modules
* Compilation (non-Node.js)
* Lint

### Actions

* FunctionRun
* FunctionRunLambdaNodeJs

### Example use cases

* Run functions / unit tests locally
* Mock AWS services

### Tasks

* Upload packages
* Perform AWS API calls

### Actions

* CodeDeployLambdaNodejs
* CodeEventDeployLambda
* DashDeploy
* EndpointBuildApiGateway
* EndpointDeploy
* EndpointDeployApiGateway
* EnvGet
* EnvList
* EnvSet
* EnvUnset
* FunctionDeploy
* RegionCreate
* ResourcesDeploy
* StageCreate

### Example use cases

* Add custom headers (CORS example)
* Add endpoints dynamically
  * Add preflight endpoints (CORS example)
  * Point multiple endpoints to 1 generic function
* Deploy other AWS services (with/without CF?)

# Solution

Some ideas to achieve all of the above:

* Generate/build actions should create a virtual representation of the initial folder/file structure that will be persisted or deployed eventually. A writeable stream object can be passed through the chain of `pre` hooks to allow for cascading modification of the streamed files. Files could be represented by [`vinyl`](https://github.com/gulpjs/vinyl) objects and the loading/persisting could be handled by [`vinyl-fs`](https://github.com/gulpjs/vinyl-fs). The `evt` object should contain a writable stream object, so that plugins can add custom pipes.

* All `pre` hooks should receive the prepared Meta objects in the `evt` object, so that these can be modified between the `configure` and `execute` steps.

* Actions should be able to trigger other actions programmatically. For example, a `project crud create` command could create a full module including all methods/functions by delegating the creation itself to the existing actions, which trigger their native hooks.

* Plugins should be able to add or modify the action's options (including the CLI prompt).

* The order of the hook execution should be modifiable from the outside.

## Hooks

* action.configure (this is where you can add/remove options)
* action.preExecute (this is where you implement custom preparation logic)
* action.postExecute (this is what has to be done afterwards)

These could be the 3 standard hooks, registered and triggered automatically by the framework.
Each action can add custom hooks to create custom extension points. All hooks could be handled by the native Node.js EventEmitter, so that custom events can be emitted from the plugin/action code.

**Comment by ac360** [comment]
@joostfarla Thanks for coming up with this great proposal.  Here are my thoughts on how this could work:

The biggest problem I see at the moment, and hope to solve in `v0.1.0` is giving Actions and Hooks a virtual project state which they can do operations off of, instead of persisting and reading from the file system.  This allows Actions and Hooks to manipulations during runtime to project data, which they may not want to persist to the file system.

To make this, I propose making a state variable on the main Serverless instance, which does an initial read of data from the file system on initialization (before Hooks or Actions are run), and stores the project data as well as provides useful methods for getting and setting that data.
```
Serverless.state
Serverless.state.get(); // Get State: { project: {}, meta: {} }
Serverless.state.set(); // Update state
```
Right now, the `Project` class features lots of useful utility methods.  I think those should be moved to `Serverless.state`. 
```
Serverless.state.getFunctions()
Serverless.state.getResources()
```

I'd like to investigate Immutable.js, to add in later.  I'm not a big fan of its API and data structures, however we can always mask those in our own methods.

**Comment by ac360** [comment]
I think we got this right in `v0.1`.  Looking forward to your feedback @joostfarla!
