### ISSUE TITLE
"serverless resources deploy" doesn't handle errors regarding resources-cf.json or stack update failures

### ISSUE THREAD

**Issue by hypexr** [serverless/serverless#479]
v0.0.15

If there are errors in the resources-cf.json or if a rollback occurs success is reported immediately

$ serverless resources deploy
Serverless: Which region are you deploying to:
  > us-east-1
Serverless: Deploying resources to stage  "development" and region "us-east-1" via Cloudformation.  This could take a while depending on how many resources you are updating...
Serverless: Resource Deployer:  Successfully deployed development resources to us-east-1

**Comment by tmilewski** [comment]
I had this same issue and due to that, as well as some other separate issues, I wrote the following plugin:

https://github.com/tmilewski/serverless-resources-validation-plugin

While it won't exactly fix this particular issue, it might help to identify what's causing the errors with regards resources-cf.json.

**Comment by edclement** [comment]
I posted a similar issue: https://github.com/serverless/serverless/issues/474

@tmilewski thanks for the response in both these posts!
