### ISSUE TITLE
sls invoke local should prefer local environment variables.

### ISSUE THREAD

**Issue by herebebogans** [serverless/serverless#4842]
# This is a Feature Proposal

## Description

`sls invoke local` should prefer local environment variables when set.

## Details
A common local dev pattern is that "local environment variables always win" in various helper frameworks eg ruby dotenv and nodejs dotenv.  It would be useful if sls invoke local worked like this to aid with CI.

Interestingly `sls offline` does honor the local environment from our experiences.

The specific usage case is functions needing the resolved value of cloudformation references from resources in the same template when deployed but the ability to override these for local development.

* See #2817 - currently sls invoke local will not resolve cloudformation references

Similar or dependent issues:
* #2817

**Comment by HyperBrain** [comment]
Hi @herebebogans ,

> The specific usage case is functions needing the resolved value of cloudformation references from resources in the same template when deployed but the ability to override these for local development.

CF variables in the local template can only be resolved when the template has been deployed at least once (as randomly created identifiers are created by CF). But there is a plugin that we use that resolves all function environment variables from the deployed stack (per stage), so that the function environment configuration matches the current definition and resource references are resolved correctly locally. It is [serverless-export-env](https://www.npmjs.com/package/serverless-export-env) which hooks into `incoke local` and automatically sets the variables properly. The only thing is, that the stack has to be deployed once, but that is necessary, regardless if you do it manually or not (e.g. a Dynamo table with a dynamic name _HAS_ to be deployed before you can ref it and get the name).

**Comment by herebebogans** [comment]
@HyperBrain thanks .. that plugin looks like a solution though it doesn't provide support for Fn:Gett which is a pretty common CF resource reference.

I *think* it would be a useful option for `sls invoke` to either inherit environment variables for pass them on the command line ..

**Comment by HyperBrain** [comment]
> I think it would be a useful option for sls invoke to either inherit environment variables for pass them on the command line ..

Agree. That would allow local overrides if needed.

Regarding the plugin, you should open a feature request there for any missing functionality. I'm sure that this can be added (the plugin is from a friend of mine). @arabold Would it be a problem to add support for `Fn:GetAtt` there?

**Comment by herebebogans** [comment]
Theres an existing issue open

https://github.com/arabold/serverless-export-env/issues/8

I'll raise it there - might even try my hand at adding it 😄
