### ISSUE TITLE
Support for temporary credentials set as ENV variables rather than access keys

### ISSUE THREAD

**Issue by flyinbutrs** [serverless/serverless#488]
I don't create IAM users or groups, and never use static keys. The company I work for has a token vending machine that gives devs temporary creds to use the AWS account, which are exported as env vars. I'd like serverless to accept those credentials rather than insisting on a hardcoded token in ~/.aws/credentials.

I don't know node very well, but if you point me in the right direction (IE where would I even look?), I can try to put together an MR.

**Comment by cosmin-dumitrache** [comment]
I'm in a similar situation. To get aws CLI to work, I configure the following environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN. They are temporary though, and I regenerate them every hour.

I've tried what you suggested and put those in ~./aws/credentials but it doesn't work for me. I get this error `ServerlessError: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.` - which is strange because AWS CLI is happy with that.

Is there any known workaround until this gets fixed?

**Comment by flomotlik** [comment]
Have you tried expriting those into environment variables as described here: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html
