### ISSUE TITLE
Enable / Disable uploading function

### ISSUE THREAD

**Issue by kkesley** [serverless/serverless#4915]
hello, I'm starting using serverless but then I notice when there are lots of functions, it's getting slower to build + upload to the lambda.

My use case is:

- I'm using Golang and each function needs to be built
- every time I run sls deploy, all functions need to be built and then get uploaded to the s3 + lambda
- I'm building with code deploy currently and it can takes up to 5 minutes for 3 functions currently

Can I pick functions that I want to re-upload to lambda? some kind of flag could be nice in the cli options. And --function option is not ideal as it doesn't deal with new functions

**Comment by HyperBrain** [comment]
Hi @kendrickkesley , thanks for the question.

Serverless treats your service as integral unit and uses CloudFormation under the hood to update the service. That means that CloudFormation has to have access to all function executables (code) and thus they have been accessible on S3. However, there are some major improvements in the current master branch regarding uploading changed or identical zip files that should improve the general behavior. They will be part of the next release.

Regarding the `--function` option: This is only meant to be used for debugging (i.e. exchanging a single function for testing). It bypasses all of CloudFormation's integrity validations and should not be used in production environments.

**Comment by kendrickkesley** [comment]
Hi @HyperBrain ! Thanks for getting back so quick! But with that major improvement, can it prevent me from building the function in the first place? Because building binaries is expensive and I'd like to not to build functions that I don't want to update.

**Comment by HyperBrain** [comment]
That's a valid point. Currently Serverless is only able to determine changes in the artifacts that will be uploaded _if they are available_, i.e. if they have been built.
As Go support in AWS is relatively new, this specific problem now becomes obvious with Serverless itself. But, honestly, I'm not sure right now, how this can be solved within the framework, because the compile itself is semantically not part of the deployment - from the framework's side. You can see that e.g. if you use Node as AWS runtime, but use the `serverless-webpack` plugin which does the webpack (or TypeScript) compile and provides the artifacts.
Right now, the build mechanism has no way to retrieve information about the last deployed or built artifacts, because this access is encapsulated in the deploy phase of the framework and not available in the build phase. This isolation makes sure that on CI/CD systems where the build server will work if it does not have any access to external resources, but the deployment server does, the framework works properly. Introducing such a functionality might break the needed isolation.

**Comment by kendrickkesley** [comment]
Hmm.. I may not the best person to give a solution on this one. But I was thinking that it's nice if the framework has the ability to ignore functions that we don't want to build. Which means the users can choose functions he/she wants to build / not.
Codebase and architecture can be separated. So, any changes in architecture (e.g. events or security groups) which are reflected in serverless.yml should be reflected in the cloudformation.
However, I think uploading the codebase of the function is optional as we can create a lambda function without any code in it, can't we?
And we don't need to think about the building process as it's completely controlled by the users. But the framework can just ignore the functions that the users don't want to change (that means even if the codebase of the function has changed). That way it can be flexible.

However, is it possible? Or even, should we do it? What's your opinion on this?
Thanks a lot!

**Comment by pmuens** [comment]
Hey @kkesley thanks for opening and @HyperBrain thanks for providing guidance here 👍

I'll close the issue since it's quite stale, however feel free to continue the discussion...
