### ISSUE TITLE
Local environment variables in `.env` not set during local testing

### ISSUE THREAD

**Issue by lorenzos** [serverless/serverless#493]
Variables in the `.env` file in the project's root folder are correctly written with `env set ... -s local` but not loaded in `process.env` when testing functions with `function run`. Additionally I can't understand why we need to manually create the file (both `project create` and `env set` do not create it).

When executed within the remote AWS Lambda environment, [it works (fixed in c854fbf9)](https://github.com/serverless/serverless/commit/c854fbf9fbdef7d95b96ed22b32284d0aea0c091).

Here are the steps to reproduce in 0.1.1:

```sh
cd /tmp
slss project create
cd serverless*
slss component create -c default -m default -f default
vim default/lib/index.js
```

```js
module.exports.respond = function(event, cb) {
  return cb(null, process.env.FOO);
};
```

```sh
touch .env # Why it is not automatically created?!?
slss env set -k FOO -v BAR -s local
cat .env # Ok!
slss function run default/default/default
```

```
Serverless: Running default/default/default...  
Serverless: -----------------  
Serverless: Success! - This Response Was Returned:  
Serverless: undefined <--- EXPECTED: BAR
```

*(I've already reported this issue in chat, I'm rewriting here for tracking purposes, I hope it's ok)*

**Comment by ac360** [comment]
Thanks we'll get on this right away :)

**Comment by eahefnawy** [comment]
Thanks for reporting @lorenzos ... we've accidentally been writing the `.env` file in the component root instead of the project root like you'd expect. We've updated the code. What you can do now for your project is just move the `.env` from the component root to the project root so that you only have one `.env` file in your whole project (ignoring `admin.env` of course) ... this way the env vars should be loaded and ready to go!

Thanks again, and please let us know if you have any more issues! :blush:
