### ISSUE TITLE
Upgrading from 1.24 to 1.26 serverless, AWS signature validation fails when invoking lamda function

### ISSUE THREAD

**Issue by malikadit** [serverless/serverless#4939]
https://forum.serverless.com/t/upgrading-from-1-24-to-1-26-serverless-aws-signature-validation-fails-when-invoking-lamda-function/4352

From 1.26 onward in case of Lambda integrations (Legacy) calls are failing.
I looked at the code 
line: 91 in $/serverless-master\lib\plugins\aws\package\compile\events\apiGateway\lib\method\integration.js
request parameters are again added in the integration section of cloud formation template.
Which enable integration request to specify request parameter, this is not in the case of previous versions of plugin.

Anyupdates if this could be an optional or any workarounds

**Comment by ozbillwang** [comment]
Some details can be found here: https://forum.serverless.com/t/upgrading-from-1-24-to-1-26-serverless-aws-signature-validation-fails-when-invoking-lamda-function/4352/8

**Comment by vasudevan-palani** [comment]
I raised an issue with AWS and they answered as below, " The internal server error" was raised because of “Signature mimatch” between API Gateway and Lambda. As API Gateway too uses “Authorization” header , the header gets corrupted if users too use it. AWS advised me not to use this header and use a different name.

I changed my header from “Authorization” to “AuthToken” and it worked in 1.26.1 serverless. Posting this is it can help anyone.

I believe this is just a work around and sls needs to fix this.

Thanks.
-Vasu

**Comment by vasudevan-palani** [comment]
I have a written a serverless plugin for workaround while the team fixes it permanently.

https://github.com/vasudevan-palani/serverless-fix-apigw-int

You can do 

1. npm install serverless-fix-apigw-int
2. Add this plugin to serverless.yml file.
3. deploy

Thanks

**Comment by pmuens** [comment]
Closing since this is a rather old issue. In the meantime we've published many different releases which should address this issue.

Feel free to re-open if this is still a problem.
