### ISSUE TITLE
TypeError: AWS.getAccountId is not a function

### ISSUE THREAD

**Issue by HoneyryderChuck** [serverless/serverless#4952]
# This is a Bug Report

## Description

On our CI builds, we've been getting the message:

```
TypeError: AWS.getAccountId is not a function
```

when performing resolving of refs, like:

```
- Ref: AWS::AccountId
``` 

what is weird is that, up until yesterday, these were working, and we didn't change anything relevant in our build set up for this error to show. Which leads me to believe that something at the serverless or AWS level changed. Is that so?

**Comment by HyperBrain** [comment]
@HoneyryderChuck I had the same with one of our projects that uses the AWS SDK yesterday (unrelated to Serverless) when accidentally removing the package-lock.json file -> npm install did an uncontrolled update.
It seems that the `AWS.getAccountId` function in the SDK vanished into nirvana. I tink this is a common problem that is located in the AWS SDK, not only in Serverless. The problem is, that Serverless does IMO not deliver a shrinkwrap to fix it's dependent AWS SDK version within the module deployed to NPMJS. So any `npm i serverless` would grab the broken (?) latest AWS-SDK 2.x.x.

@pmuens @horike37 Any chance that we publish with a shrinkwrap to restrict the used AWS SDK to a known working version?

**Comment by arabold** [comment]
It seems this is a bug (?) in `serverless`, not in the AWS SDK. Downgrading to a previous version of serverless fixes it. 

Here's the relevant PR which renamed `getAccountId` to `getAccountInfo`: https://github.com/serverless/serverless/commit/b921d2656e8a77a2e3ed6686bbe112a9d3acc021

**Comment by horike37** [comment]
Oh, it is accidentally breaking change...
I will take care of it.
