### ISSUE TITLE
Reduce Scope of IAM User policy during Installation

### ISSUE THREAD

**Issue by ashack293** [serverless/serverless#50]
AWS best practices dictates that IAM Users and Roles should have the most restrictive policies possible for their function. The installation guide recommends creating a user with Administrator access to the AWS account. The scope of the IAM User *jaws_user* should be revised.

**Comment by ac360** [comment]
I understand the security concern here.  This will be difficult since we are moving to make the CLI tool automate more of the user's workflow, sparing them from the AWS Web Console, and we need lots of permissions to perform all of the tasks we have in mind.

Also, if we limit the scope of *jaws_user* then as we introduce new features/automations in the CLI, the user will run into errors (if they do not update their User policies), which may result in bad ux.

**Comment by ashack293** [comment]
Your concern makes sense, and I agree with the notion of minimizing work in the AWS console. But I have a few counter-arguments:

1. If a developer were working on a company AWS account and had to request users and policies from the sysadmins, they'll never be able to get that level of access. I'm trying to look down the road at using JAWS in a production environment.

2. Wouldn't this be a big security flaw when installing / using third-party JAWS applications or modules? Maybe I'm being paranoid, but I would be reluctant to run any code on my AWS account that has complete control. 

Here's what I propose:
1. Making the Installation-level policy permissions as narrow as possible. 

2. At runtime (or via test command), using the AWS SDK to evaluate the permissions that the user has against a list of permissions that it needs. This list would be updated with each new release that introduces a change in the policy requirements. 

3. Throwing errors on the command-line when the policy needs to be adjusted. 

4. For users that are comfortable giving the IAM User permission to manage policies on its own, make the application automatically generate new permissions.

This would cover both use-cases - where the developer is sandboxing in a free account, or where the developer is working in a production environment.

If this seems reasonable, I'd be happy to work on this.

**Comment by ac360** [comment]
+1000  This is a great solution with great user experience.

I just added it as a comment to the [JAWS V1 Specifications](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit?usp=sharing)

I'll get it in the spec tomorrow.  I would really appreciate your help on this :)

**Comment by ashack293** [comment]
:+1:  Looking forward to seeing it in the spec so I can get started!

**Comment by ac360** [comment]
@ashack293 I'll write it in there today and start a JAWS V1 branch tomorrow.  Thanks again :beers:

**Comment by ac360** [comment]
@ashack293 In the V1 spec, on the **jaws new** command, the jaws-cli automatically creates AWS IAM Roles for each **stage** the user specifies in a prompt.

Excuse my ignorance about IAM here, but if the jaws-cli has a permission to create an IAM Role, then isn't there no point in limiting the permissions scope of the jaws-cli IAM User because it could potentially create and utilize an IAM Role that could access any resource?

**Comment by ashack293** [comment]
@ac360 Yeah, that basically moves the problem partially to Roles. The User is still too powerful because they can create roles and adjust the policies for them, and the Role is too powerful because we're letting the software dictate what its constraints are. You also need the User to have the same level of permissions, or else it's going to make local development more of a nuisance. I think there are two ways we could go with this, and maybe we do both:

A. Allow the developer to give JAWS extensive powers and automatically create the roles and policies. At least this will be a better security practice by provisioning with more granularity. **jaws new** would just report in the console as it configures the IAM User and Role for use in the application. 

B. Evaluate the policies assigned to the User and Role, and generate errors accordingly. This will prompt the developer to modify their IAM policies as needed to run the application. In this scenario, the application does not have the power to assign any IAM Policies, it can only read them. 

I think we definitely need **B**, and we might want **A**. Something to consider in either case: it's relatively simple to copy a policy template into IAM. So we could either provide the template with instructions, or upload it to AWS programmatically when the application is created. Either way, it removes the need for giving full admin access. We could make things easier by including sample policies in the project, or generating them on the command-line.

At some point, we're going to need to go a step further and support even more granular permissions, so the application can only read/write one specific database or S3 bucket, etc. The spec mentions generating roles for different environments. The question is, why would any of them be any different from each other? The main reason would be if you were configuring the roles with maximum granularity: *the Dev Role has write permission in S3Bucket 1, Staging Role has write permission in S3Bucket 2, etc*. 

To add this sort of granularity, we may want to use prompts on the command-line to accept ARNs as inputs and generate policies programmatically.

Lastly, since we're taking a more modular approach, it raises the question of whether we should require that you actively provide AWS credentials to each module instead of making them globally accessible. I do not think this is necessary, but I thought I would mention it for the sake of discussion.

</walloftext>

**Comment by ac360** [comment]
@ashack293 Sorry for the slow response.  I've been deferring digging into this issue because JAWS V1 is changing rapidly.  All of JAWS V1's details haven't been figured out yet.  Without those details, I feel I'm lacking the necessary information needed to best solve this issue.  Your suggestions are great as always.  I am going to keep this issue open, as a reminder and reference.  Right now, I'm focused exclusively on making the server-less workflow easy.  If we can make that, then it will be worth making secure.

**Comment by flomotlik** [comment]
We're currently working on the next iteration of Serveless that will deploy all resources through Cloudformation. We're thinking of ways to make it possible to use existing roles and users so we don't have to create them and user/role management can be handled externally from the serverless service.
