### ISSUE TITLE
"EACCESS: Permission denied" for a file that has permissions to read and write

### ISSUE THREAD

**Issue by xyproto** [serverless/serverless#5006]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

`serverless invoke -f hello -l` fails to run, and gives an EACCESS error.

I have given full access to `/var/task/handler.js` as a user:

    ~% echo 'test' > /var/task/handler.js
    ~% cat /var/task/handler.js
    test
    ~% :> /var/task/handler.js
    ~% cat /var/task/handler.js
    ~%
    ~% ls -al /var/task/handler.js
    -rwxrwxrwx 1 afr users 0 May 28 11:51 /var/task/handler.js

I'm not comfortable with giving full access to files in `/var`, but I gave full permissions `/var/task` for the sake of this bug report.

The error message is:

EACCES: permission denied, open '/var/task/handler.js'.

* What did you expect should have happened?

`serverless invoke -f hello -l` should succeed, with no permission denied error.

* What was the config you used?

I'm following the tutorial, using AWS Lambda, using as little custom config as humanly possible. I don't know which config is referred to at this point in the template. I have exported environment variables for accessing AWS, and deploing the service works fine.

`serverless.yml` is generated automatically and not touched by me.

* What stacktrace or error message from your provider did you see?

I'm not sure what you are referring to here. I got no error message from AWS, only through the serverless CLI interface. A full output is posted below.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Just trying to deploy and invoke a simple "hello" function, by following the tutorial for the first time.

* If there is additional config how would it look

Similar or dependent issues:

Could not find similar issues. I searched the issue tracker on GitHub for "EACCESS".

## Additional Data

* ***Serverless Framework Version you're using***:

    serverless version
    1.27.3

* ***Operating System***:

64-bit Arch Linux.

* ***Stack Trace***:

Here's the full error message, with logging enabled:

```
serverless invoke -f hello -l
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create/var/task/handler.js
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats/var/task/handler.js
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke invoke
{
    "errorMessage": "EACCES: permission denied, open '/var/task/handler.js'",
    "errorType": "Error",
    "stackTrace": [
        "Object.fs.openSync (fs.js:641:18)",
        "Object.fs.readFileSync (fs.js:509:33)",
        "Object.Module._extensions..js (module.js:578:20)",
        "Module.load (module.js:487:32)",
        "tryModuleLoad (module.js:446:12)",
        "Function.Module._load (module.js:438:3)",
        "Module.require (module.js:497:17)",
        "require (internal/module.js:20:19)"
    ]
}
--------------------------------------------------------------------
START RequestId: 82918c74-625c-11e8-a4f0-515e6163ec6e Version: $LATEST
module initialization error: Error
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 82918c74-625c-11e8-a4f0-515e6163ec6e
REPORT RequestId: 82918c74-625c-11e8-a4f0-515e6163ec6e  Duration: 53.35 ms      Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 19 MB

module initialization error
Error


  Error --------------------------------------------------

  Invoked function failed

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Invoked function failed
    at AwsInvoke.log (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/plugins/aws/invoke/index.js:102:31)
From previous event:
    at Object.invoke:invoke [as hook] (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/plugins/aws/invoke/index.js:22:10)
    at BbPromise.reduce (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/home/afr/webprojects/serverless/my-service/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/home/afr/webprojects/serverless/my-service/node_modules/serverless/bin/serverless:42:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.2.1
     Serverless Version:     1.27.3
```

* ***Provider Error messages***:

What does "provider error messages" mean?

**Comment by HyperBrain** [comment]
@xyproto Thanks for asking.

There is one thing I did not get completely: Do you want to invoke your function locally, or do you want to invoke a deployed lambda?
For local invocations, you should use `serverless invoke local ...` as "invoke" tries to invoke the "real", deployed function at AWS.

**Comment by xyproto** [comment]
@HyperBrain

My main goal is to follow the tutorial successfully, and to run the "hello" function remotely.

When using `serverless invoke local` instead of `serverless invoke`, there is no error message, nor output here.

In either case, I found it curious that the command line utility complains about missing access to `/var/task/handler.js`.

**Comment by rodel-talampas** [comment]
Hi, hope this helps.   

After doing some investigation, it seems a PERMISSION issue. When serverless packages your code into zip, it will take whatever FILE ACCESS you have granted to the files to be deployed. So I reckon look into File/Folder Permission.

Mine was an issue on the mounted drive where my code lie. It is only accepting group permission where my user is part of the group. You are not able to change USER +xrw hence the file uploaded to lambda doesn;t have execute user access.

**Comment by zenlor** [comment]
this line is the culprit

https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/zipService.js#L87

Whatever is the reason is breaking stuff for normal setups with the commonly used strict `umask 027` (translated as `u=rwx,g=rx,o=`)

**Comment by wcmjunior** [comment]
I got similar permission issue today running the `aws-python` and `aws-python3` templates. I was running on Ubuntu `18.04` and Serverless `1.38.0`. The reason was that I was creating those examples using a FAT32 device (don't ask me why), thus I realized file permissions were not properly set during upload by Serverless. Recreating the templates in a ext64 device got the template running fine due to proper file permissions.

It seems that @zenlor comment above applies to this issue.

I used the following commands in both file systems:

```
$ serverless create --template aws-python3 --path my-service
$ cd my-service
$ serverless deploy -v
$ serverless invoke -f hello
```

**Comment by Sphinxs** [comment]
Is there a way to just ignore the file?

I'm using:

```yml
package:
      exclude:
        - "./data"
        - "./collection"
```

But I still receiving the error, I can't remove the folder or change the permissions

**Comment by koitsu** [comment]
This bug is completely and entirely massive, on a scale that is almost unprecidented.  I have no idea how in over 2 years nobody from Serverless has done something about it.  Equally terrifying is the fact that AWS has also done nothing about it.

I cannot stress this enough: this is literally deal-breaking and cannot be solved through `umask`.  It has to be solved at the core: during the ZIP archival process.   When I encountered this bug, my first reaction was: "How is this possible?  ZIP files do not store anything about UNIX file permissions, nor ownership/group.  This shouldn't be possible."  I'm "old" and thus think of ZIP files as original PKZIP.

### History

It turns out that in the very late 90s, the Info-ZIP group -- the open-source folks who maintain ZIP archiver-related programs for UNIX/Linux machines -- [decided to extend the ZIP format to include file permissions on UNIX/Linux](https://en.wikipedia.org/wiki/Zip_(file_format)#Implementation).  They can even store user/group or UID/GID much like tar archives.  So these are actually Info-ZIP files, which means they contain extra capability.  I would say the vast majority of the world does not know this (myself included).  [Here is additional information](http://infozip.sourceforge.net/FAQ.html#corruption).

Windows machines (more accurately: NTFS) have file permissions as well; the beast there is very different.  I am focused purely on UNIX/Linux.

### Serverless

This means Serverless is using something that is generating Info-ZIP-compliant ZIP files and including permissions.  Period.  [The source code as of this writing](https://github.com/serverless/serverless/blob/4c33476210d355b9b822909685a951a4d970f467/lib/plugins/package/lib/zipService.js#L73) shows that the module "archiver" is used to generate the ZIP files.  I do not know what that god-awful block of code in lines 84 onward is actually trying to do for sure, but gut feeling tells me it tries to store **in the ZIP archive** modified file permissions (so that on extraction, you won't run into this problem).  But it's obvious that something in that code, or in "archiver", is not working.

You can verify this on a UNIX machine by using `unzip -Z` on the ZIP file that Serverless generates during its `sls package` phase, ex. `unzip -Z .serverless/myservice.zip`.

### AWS Lambda

The other half of the picture: AWS Lambda is not only extracting these ZIPs using an Info-ZIP-compliant tool, but they are extracting them with file permissions retained (or maybe that's the default, I don't know).  Thus, AWS is also not helping the situation any.  (They might argue the issue should be fixed at the core, and while I agree, I'm still a bit surprised that they do this.)

Lambda, if I remember correctly, needs global read access on files.

### Why this is a huge problem

A terrible rebuttal is the following: "just `chmod` your files to 644 or 755, and your directories to 755, and that'll work!"  While this is a convenient answer, it is not even remotely acceptable.  Honest.

For example, at one of my jobs, we rely heavily on Linux and proper group permissions: `umask 0002` (not a typo) thus files being 0664 (`-rw-rw-r--`) and directories being 2775 (`drwxrwsr-x`). Note the setgid bit on directories and group write permission.  We actually go to great lengths to ensure these are retained even during things like (non-Lambda) deployments through a whole series of `find | xargs chmod` commands, along with `git init --shared=world`, to ensure our developers can all modify the code on a shared box.  This is not an uncommon situation.  Really.  Let's also not forget that `git` too actually stores file permissions (really.  It's often overlooked though).

### Working around the problem

I can't think of a single way to work around this, other than for someone at Serverless greatly familiar with this block of code step in and figure out what's not working and why.  Maybe "archiver" changed some defaults, maybe someone broke part of it.  I don't know (I don't actually know JavaScript, just things like assembly, C, Perl, Python).

The last person I see to be poking at this code in question, relating to permissions, is @medikoo .  Can we please hammer this bug out already?

**Comment by medikoo** [comment]
@koitsu thanks for comment.

I imagine that fix could be to mostly ignore the permissions of files that we're package, and in zip archive store them with settings as follows
- Setup (archiver default) `644` mode for all non executable files
- Setup `755` mode for executable files
- Setup (archiver default) mode `755` for all folders

PR with a fix is welcome!

**Comment by koitsu** [comment]
> @koitsu thanks for comment.

You're welcome.  I concur that 644 for non-executables, 755 for executables, and 755 for directories would be enough. :+1: 

Sadly, as I said, JS/Node is not a language I know, otherwise I'd be doing a PR already.  I also have major difficulty understanding what all is going on in lines 84-121.
