### ISSUE TITLE
Nested variable expansion failure in 1.27.1

### ISSUE THREAD

**Issue by byarr** [serverless/serverless#5027]
# This is a Bug Report

## Description

In serverless 1.27.1 a nested variable expansion (e.g. `${file(serverless/default-vars.yml):greetings.${self:provider.awsProfile}}` ) that worked fine in 1.27.0 throws an error:

```
Serverless Warning --------------------------------------
 
  A valid file to satisfy the declaration 'file(serverless/default-vars.yml):greetings.self:provider.awsProfile' could not be found.
 
 
  Serverless Error ---------------------------------------
 
  Trying to populate non string value into a string for variable ${file(serverless/default-vars.yml):greetings.self:provider.awsProfile}. Please make sure the value of the property is a string.
```

I've reproduced an example that I can share:
[sls-error.zip](https://github.com/serverless/serverless/files/2076151/sls-error.zip)

Running `npm install` to install sls 1.27.1 and then `node_modules/.bin/sls package --stage live --profile qa --version 2 --region eu-west-1`.

**Comment by goncaloneves** [comment]
Having the same issue. This is related:
https://github.com/serverless/serverless/issues/4953

**Comment by GuruRAM** [comment]
Hi @byarr. I can't reproduce the problem using the latest master https://github.com/serverless/serverless/commit/47816be84ae736f4827b860baa9689890d9bc133.
If the problem is fixed I think these issues can be closed:
https://github.com/serverless/serverless/issues/4953, https://github.com/serverless/serverless/issues/5044

**Comment by dougmoscrop** [comment]
I think the basic case is fixed, but not a slightly more complex but common one:

```yml
service: broken

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    FOO: ${self:custom.config.test, self:provider.stage}

custom:
  config: ${file(./${opt:cfg}.yml)}

functions:
  hello:
    handler: handler.hello
```

We do this all the time where we have two configs, say `foo` and `bar`, and they may specify 'test' but we use some default 'test' as well, such as the stage name.

e.g.

foo.yml
```yml
test: 'override'
other: ignore
```
bar.yml
```yml
other: ignore
```

> sls package --cfg=foo

works

> sls package --cfg=bar

```bash
Serverless Warning --------------------------------------

  A valid undefined to satisfy the declaration 'deep:1.test' could not be found.

Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  Environment variable FOO must contain string

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.27.0
```

It seems to stat with 1.27.0 and  it has completely broken our ability to upgrade serverless.

It looks like deep-variable messed up overwrite logic, because here:

https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L456


`values` will be something like: `[ '${deep:0.test}', 'dev' ]`

and so "${deep:0.test}" satisfies the `validValue` logic. It's perhaps that the deep variable expansion isn't returning a promise that waits for the variable to be satisfied?

**Comment by erikerikson** [comment]
Thanks for doing the analysis of materials to reproduce this @dougmoscrop.  Looking into it.

**Comment by erikerikson** [comment]
@dougmoscrop if you could try out the branch on my PR above, I'm fairly confident in the fix but I'd appreciate you helping make sure that I haven't missed a more involved scenario.

**Comment by dougmoscrop** [comment]
@erikerikson Thank you! Yes, it appears to work!

**Comment by erikerikson** [comment]
Very glad to hear.  So sorry for the oversight!

**Comment by onebytegone** [comment]
Sorry for dredging up an old issue, but thought this might be the best place to raise the question. I recently upgraded from v1.26.1 and have a use case similar to what is documented by @dougmoscrop [above](https://github.com/serverless/serverless/issues/5027#issuecomment-402871790). The variable overwriting _does_ work as expected. However the following warning still gets logged:

```
$ sls package --cfg=bar

 Serverless Warning --------------------------------------

  A valid undefined to satisfy the declaration 'deep:2.test' could not be found.
```

Just wanted to confirm, when a deep variable within a fallback is not found, is the intended behavior to log the above warning? 

When I first ran across this behavior, it seemed a little funky because the developer could be providing a fallback as they know the variable may not exist. However, I can also see there being a case for logging the warning. Before I went about digging into this further or opening a new issue, wanted to get your-all's thoughts on the matter.

**Comment by erikerikson** [comment]
@onebytegone Very glad the final result was as expected, even though as you bring up the messaging may not be perfect in all circumstances from all perspectives.

It seems valid to go either way on writing a warning message or not when a non-default fallback is not populated with a valid value.  If you're expecting an earlier value to be taken but the default is being taken, it might be harder to notice or debug what is going on without this message.  Treating that case differently would require adding more code and I haven't tried to differentiate the cases in my PRs.  I wouldn't oppose the addition of that logic (and don't have the rights but have implemented a lot of it) but I don't think it is very high value.  Regardless, if the community wanted to have it and an implementer self-identified, I could commit to offering implementation support in slack and review here, I don't have the time to take it on myself.

I would suggest a separate issue for discussion and to support of any implementation.

**Comment by onebytegone** [comment]
Thanks for the feedback @erikerikson! I've created #5353 to follow up on this.
