### ISSUE TITLE
Serverless Dashboard V0.1

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#5058]
Hi all,

We're ramping up investment in the **Serverless Framework** to solve _design_ and _deployment_ problems in serverless application development.  At the same time, we're launching a new effort called the **Serverless Dashboard** which intends to solve _operations_, _monitoring_ & _collaboration_ problems.

We're launching the **Serverless Dashboard** within a few weeks and we'll be updating it daily with features and improvements.  We can't do this without the community, so we're going to share Dashboard features in advance with you for feedback.  Updates will be posted regularly in this thread (unless we find a better way to do this).

**Comment by horike37** [comment]
@ac360 
That sounds interesting!
I would love to know the Dashboard features more details.

**Comment by ac360** [comment]
# Serverless Dashboard Beta V0.1

_This is the initial version of the Serverless Dashboard and these are the features we are planning for this upcoming release.  Please let us know what you think by leaving a comment in this thread!_

## Serverless Applications & Services

The Serverless Framework has a concept of "Services".  Services are intended to be a unit of organization bigger than a Function, but smaller than an Application.  Their purpose is to create smaller stacks of cloud infrastructure that teams can own and work on autonomously, without affecting the system as a whole.  

Thus far, the "Services" concept has been successful (though we have a lot of planned improvements).  However, we believe an Application concept can help with development and operations tasks (though we must preserve the ability to work on Services autonomously) and the Serverless Dashboard introduces an Application concept.  In this release, an Application is akin to a folder, which helps organize Services within a single (larger) Application.

_The serverless "Applications" you currently own._

![serverless-dashboard-v01-applications](https://user-images.githubusercontent.com/2752551/41624384-5d9d407e-73ca-11e8-8bb6-26569dfd5ae1.png)

_The serverless "Services" within a specific "Application".  Each one can be worked on autonomously by a developer or team, or altogether._

![serverless-dashboard-v01-services](https://user-images.githubusercontent.com/2752551/41624392-627fb04a-73ca-11e8-9700-229a026f8d79.png)

## Visualizing Your Serverless Applications

Developers, teams & orgs continue to request great application-level tools for building, operating and collaborating on serverless applications.  Currently, most tools and dashboards are focused on pieces of individual serverless infrastructure (e.g. AWS Lambda, AWS API Gateway, etc.).  This offers a disjointed experience and makes it hard to get a holistic view of your serverless application.

**Providing great application-level tooling is what we are all about!**  This philosophy is behind the success of the Serverless Framework and naturally we're extending this approach to our Serverless Dashboard.

The first step is to simply show users all of the functions and function+event subscriptions within their serverless application, which is what we're offering in this upcoming release.

![serverless-dashboard-v01-service-overview](https://user-images.githubusercontent.com/2752551/41625049-52e7ef74-73cc-11e8-9775-afe43d7dcb7e.png)

## Collaborating On Serverless Applications

Collaborating on serverless applications is a large problem domain... and we'd like to solve it.   The first step we are taking is to enable developers to invite others to view and work on their serverless applications.

Every user in the Serverless Dashboard has a concept called a Tenant.  A Tenant is workspace that can hold many Applications.  The conceptual hierarchy goes like this...

```
Users
   Tenants
      Applications
          Services
```

You can invite a collaborator to your Tenant via an easy invite flow...

![serverless-dashboard-v01-collaborate-invite](https://user-images.githubusercontent.com/2752551/41628711-a8654ee8-73da-11e8-9f45-3989c61ac9a6.png)

Once they are added, they can see all of your Applications and their respective Services.

They can even create an Access Key in your Tenant and then can perform deployments to your Services, which you can visualize.

![serverless-dashboard-v01-collaborators](https://user-images.githubusercontent.com/2752551/41628875-6247a45a-73db-11e8-899e-ab0c783c3473.png)

**Comment by garethmcc** [comment]
**Applications**
This is a difficult one. I have worked in an environment where the concept of "Applications" applied to Serverless would make no sense. The services built using Serverless were consumed across multiple applications within a single organisation. On the other hand, I have also worked on projects where there is a distinct application. Its a tough one. Not sure how you can accommodate the former. Perhaps a more nebulous collection of services such as that can still logically be added to an "Application" which is just a catch all for the organisation as a whole and where the global services end up going; i.e. "Company A Global Services".

**Visualizing**
One visualisation which I feel could add a lot is a dependency graph that shows the links between components, such as functions and vendor services such as APIGW, SNS, SQS, etc graphically. This may end up being tricky where the association is within code; i.e. my function is not linked to an SNS event in serverless.yml but it does post a message to a topic. Perhaps using the IAM permissions setup within the serverless.yml

Another one is to more clearly show the exposed interfaces of functions, especially the http events where the request can be defined explicitly. In other words input requirements and outputs produced. Added onto that the ability to edit some details around the service or function manually so that the platform can also become a documentation platform for new developers joining. I might want to annotate why a certain topic is being published to, etc.

**Collaboration**
The only real addition I think that could be considered here is the addition of links to a repo for the service, and not just for Github though. This can make it easier for a new collaborator added to the platform to grab a services codebase to get contributing.

If deployments are planned from the application there needs to be some way to customise that pipeline as currently, and I am sure I am not alone in this, we run multiple automated checks such as linting and unit tests before the deployment occurs.

Hope that contribution helps. If I think of anything else I'll be sure to add my 2c

**Comment by ac360** [comment]
Hi @garethmcc,

This was super helpful feedback for us.  Thank you.  Our entire engineering team has been discussing it since you first posted.

> Applications
This is a difficult one. I have worked in an environment where the concept of "Applications" applied to Serverless would make no sense. The services built using Serverless were consumed across multiple applications within a single organisation. On the other hand, I have also worked on projects where there is a distinct application. Its a tough one. Not sure how you can accommodate the former. Perhaps a more nebulous collection of services such as that can still logically be added to an "Application" which is just a catch all for the organisation as a whole and where the global services end up going; i.e. "Company A Global Services".

Great feedback!  We're familiar with this situation and in no way does an Application concept preclude the former scenario.  There are a few ways we're going to address this, as it is a big problem surface area which we'll need to tackle via multiple methods.  Some examples include: Making Services easy to discover and consume outside of the Application, offering communication infrastructure to help facilitate service communication in event-driven and request/response flows (via the [Event Gateway](https://github.com/serverless/event-gateway), enabling Services to be added to other Applications and more.

> Visualizing
One visualisation which I feel could add a lot is a dependency graph that shows the links between components, such as functions and vendor services such as APIGW, SNS, SQS, etc graphically. This may end up being tricky where the association is within code; i.e. my function is not linked to an SNS event in serverless.yml but it does post a message to a topic. Perhaps using the IAM permissions setup within the serverless.yml

> Another one is to more clearly show the exposed interfaces of functions, especially the http events where the request can be defined explicitly. In other words input requirements and outputs produced. Added onto that the ability to edit some details around the service or function manually so that the platform can also become a documentation platform for new developers joining. I might want to annotate why a certain topic is being published to, etc.

> Collaboration
The only real addition I think that could be considered here is the addition of links to a repo for the service, and not just for Github though. This can make it easier for a new collaborator added to the platform to grab a services codebase to get contributing.

> If deployments are planned from the application there needs to be some way to customise that pipeline as currently, and I am sure I am not alone in this, we run multiple automated checks such as linting and unit tests before the deployment occurs.

>Monitoring
One addition that would be most helpful is general monitoring of service health and functions. There is a lot to say here so I will leave the bulk of it for when you are looking for that feedback but the basics I can mention are:

> Service summary: # successfully called functions, # errored functions, # retried functions
Function detail: List of function calls for a specific service.
Function call detail: The logs associated around one specific function call
Transaction tracing: Linking the interaction of functions and services; for example an http event triggers APIGW, which triggers a lambda, which publishes to a topic in SNS, which is consumed by another function that writes to DynamoDB.

More great feedback!  We agree with all of this.  In fact, most of these requests are already being added to upcoming versions.  Instead of talking about it, let's discuss once we ship (which will be soon).

Will you email me so we can send you some swag for being so helpful?  My email is austen AT serverless.com

**Comment by garethmcc** [comment]
Thanks for the kind words. Just pointing out where an app like the dashboard would help with some of the paint points I've had building serverless apps.
