### ISSUE TITLE
serverless login doesn't work from remote ssh

### ISSUE THREAD

**Issue by danucalovj** [serverless/serverless#5121]
I do a lot of my programming on a remote server hosted on Digital Ocean, not locally on my machine.

From the install:

serverless login

Output: Serverless: The Serverless login will open in your default browser...

I can't seem to find a way to login unless I'm using a local machine.

Is there something missing on the docs or some type of token-based authentication hasn't been developed yet?

**Comment by rupakg** [comment]
@danucalovj Would love to resolve this issue for you. What version of the framework are you using? We have folks who use docker and had resolved the issue. Would like to get some more info. from you to see what is still missing. Let me know.

**Comment by rupakg** [comment]
@danucalovj we use Auth0 to authenticate and since it uses OAuth, it needs user interaction and redirection flow. But the fix we put in place should print off an url that you could manually access and complete the auth flow. I have tested the fix with the latest Framework release 1.28.0. Let me know.

**Comment by pmuens** [comment]
Closing this for now since it's a stale issue and we have some resolutions here. Feel free to continue the discussion if this is still a problem.
