### ISSUE TITLE
Logging under Serverless 1.28.0 w/ Java using "invoke local"

### ISSUE THREAD

**Issue by steveardis** [serverless/serverless#5155]
It looks like the migration to log4j2 under Serverless 1.28.0 has caused logging when executing "invoke local" to fail with a "java.lang.NoSuchMethodError: com.amazonaws.services.lambda.runtime.LambdaLogger.log([B)V" error.

To recreate what I am seeing, run the following steps:

- sls create --template aws-java-maven --path test-serverless-1.28.0
- cd test-serverless-1.28.0/
- mvn package
- sls invoke local -f hello --log

**Comment by kekbur** [comment]
I was able to work around this problem by modifying the dependencies section of `node_modules/serverless/lib/plugins/aws/invokeLocal/java/pom.xml` as follows:

```xml
  <dependencies>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-log4j2</artifactId>
      <version>1.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.8.5</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.8.5</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.8.5</version>
    </dependency>
  </dependencies>
```

After making the modifications I ran `mvn package` in that directory to rebuild the file `target/invoke-bridge-1.0.jar`.

**Comment by piokania** [comment]
I've got the same issue when trying to use aws-lambda-java-log4j2

Exception:
```
java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.serverless.InvokeBridge.invoke(InvokeBridge.java:82)
        at com.serverless.InvokeBridge.<init>(InvokeBridge.java:36)
        at com.serverless.InvokeBridge.main(InvokeBridge.java:133)
Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.lambda.runtime.LambdaLogger.log([B)V
        at com.amazonaws.services.lambda.runtime.log4j2.LambdaAppender.append(LambdaAppender.java:74)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
```

**Comment by rogelio-ramirez** [comment]
Hi, I have reviewed the AWS documentation in https://docs.aws.amazon.com/es_es/lambda/latest/dg/java-logging.html?shortFooter=true#logging-java-examples and if You change only the version of
```xml
<dependency>
  <groupId>com.amazonaws</groupId>
  <artifactId>aws-lambda-java-log4j2</artifactId>
  <version>1.1.0</version>
</dependency>
```
to
```xml
<version>1.0.0</version>
```
You will be able to invoke your function locally while the root problem is solved.
Greetings!

**Comment by wasserholz** [comment]
@rogelio-ramirez Thanks for the solution. It worked perfectly!

**Comment by neshanjo** [comment]
Hi, I also ran into this issue. Permanently downgrading to version 1.0.0 is not an option since it does not handle java stacktraces correctly. Will this be fixed? Can this be fixed in serverless? Or is it a problem with the AWS lib? If you provide more information (link to docs or code that handles the java invocation), then maybe I can have a closer look.

**Comment by implsoftware** [comment]
Just experienced this issue as well. Seems like an issue with `aws-java-maven` ?

**Comment by yyamano** [comment]
Here is my analysis.

aws-lambda-java-log4j2 1.10 requires aws-lambda-java-core 1.2.0 because of an incompatible change, but our invoke-bridge uses aws-lambda-java-core 1.1.0. So upgrading aws-lambda-java-core is the way to go, but I have no idea how the change affect other parts of sls. I'm newbie of both both sls and aws-lambda-java.

LambdaAppender uses LambdaLogger.log(byte[] message) in https://github.com/aws/aws-lambda-java-libs/commit/b9abd1ba88bed9b7000a6d1f8a920cf17f70dd86#diff-f7be8dfac044436f53a04abd153f1d7a

The method is added in aws-lambda-java-core 1.2.0. See the change at https://github.com/aws/aws-lambda-java-libs/commit/36747fc8f24e257c31fc722a0ab5c698aa15553d#diff-6177ecfdeeafb7048b390dddea491f16
