### ISSUE TITLE
Attempting to login into platform on headless fails with no errors

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#5182]
# This is a Bug Report

## Description
After following instructions from @alexdebrie on the Serverless forum at https://forum.serverless.com/t/log-into-serverless-platform-on-a-headless-system/5215/3 I attempted to add the environment variable SERVERLESS_ACCESS_KEY to the CI platform and the `app` and `tenant` properties to the service's `serverless.yml` configuration. Subsequent deployments do not result in the service being deployed being added to the Serverless platform and are not visible on the serverless dashboard on the tenant account from which the key was generated.
For bug reports:
* What went wrong?
Service was not registered under the application within the Serverless platform
* What did you expect should have happened?
The the service would be listed under the application on serverless platform.
* What was the config you used?
`serverless.yml` configuration used
```
app: goingout-staging
tenant: garethmcc
```
Added a SERVERLESS_ACCESS_KEY to the deployment environment. Will not share that here for security purposes.

* What stacktrace or error message from your provider did you see?
There were no error messages at all.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.29.2
* ***Operating System***: A linux environment of some kind.
* ***Stack Trace***: NA
* ***Provider Error messages***: NA

**Comment by alexdebrie** [comment]
Thanks for raising this, @garethmcc.

@eahefnawy I believe the issue is [here](https://github.com/serverless/serverless/blob/49c1f29581180a0a006eea3a7bdbf79da8b6380c/lib/Serverless.js#L117-L118). Basically, we check early for whether there's a user from the `.serverlessrc` file and will bail on all Platform actions if it's not there.

Is the [`SERVERLESS_ACCESS_KEY`](https://github.com/serverless/serverless/blob/49c1f29581180a0a006eea3a7bdbf79da8b6380c/lib/utils/getAccessKey.js#L8-L9) environment variable designed for CI/CD usage or other situations where `sls login` is unfeasible / undesirable? If so, we'll need to update `getUser()` to allow for these situations.

**Comment by garethmcc** [comment]
It looks like its related to `lib/utils/isLoggedIn.js` checking for the serverlessrc to have user details and then returning false if it's not there. I am guessing an `else if` of some kind is to follow except I just don't have the time to go further down that rabbit hole and find where to validate the SERVERLESS_ACCESS_KEY env variable. Apologies for not going all the way to a PR here. Hope that little bit helps

**Comment by garethmcc** [comment]
I saw some activity related to dashboard and access keys. Was wondering if that had any impact on this issue?

**Comment by eahefnawy** [comment]
@garethmcc Thanks for reporting this. This is fixed in [this PR](https://github.com/serverless/serverless/pull/5219).

We've also released this as a v1.30.1 patch. Could you update and let us know if you're still facing this issue? You can now just set `SERVERLESS_ACCESS_KEY` env var in your CI setup.

**Comment by garethmcc** [comment]
Thanks so much. Its actually pretty exciting because I have a project going live over the next few days and I can incorporate integration into the dashboard which will be a killer feature for my killer I feel. Will be back in a day or two with feedback or sooner if there's an issue.

**Comment by garethmcc** [comment]
@eahefnawy I can confirm its working as intended now. Thanks for that. :)
