### ISSUE TITLE
sls deploy: Function not found

### ISSUE THREAD

**Issue by kogden** [serverless/serverless#5185]
So everything was working fine until I tried to shrink the size of my functions (they were all around 8MB because of the node_modules package). I manually deleted them from the AWS Lambda terminal and now I can't seem to deploy any more. 

Nothing has changed in the code itself I just get the error:
Serverless: Checking Stack update progress...
...............
Serverless: Operation failed!

An error occurred: UpdateLambdaFunction - Function not found: arn:aws:lambda:us-east-1:728832281197:function:serverless-nodejs-app-dev-update (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 1a23ce10-9689-11e8-ab22-418992b94479).

**Comment by kogden** [comment]
So I didn't really fix this but I was able to generate another set of lambda functions by renaming the service. I think going in and manually deleting them confused Serverless or AWS and they were searching for that service name in AWS. Changing the name of the service fixed the issue but I'm sure there's some garbage floating around somewhere.

**Comment by pramttl** [comment]
Facing the same issue. I think the issue should be reopened and it seems important to address this. The expected behavior as a user is -

Function should be created if it does not exist.

(Renaming the service is not a proper solution. Also, in my case I cannot rename the service because other functions under the project would also fall under a new namespace and we are using some of these lambda functions across other services. Renaming/changing the service namespace would be quite a hassle).

**Comment by exoego** [comment]
@pramttl 
Could you open a new issue since this issue had been quite stale and lacks details to reproduce.
Thanks in advance.

**Comment by pramttl** [comment]
@exoego Created. https://github.com/serverless/serverless/issues/5996
