### ISSUE TITLE
Documentation for serverless.yaml file is missing tenant and app

### ISSUE THREAD

**Issue by mrcoles** [serverless/serverless#5372]
# This is a Documentation Bug Report

### What went wrong?

Received this message during `sls deploy`:

> Serverless: WARNING: Missing "tenant" and "app" properties in serverless.yml. Without these properties, you can not publish the service to the Serverless Platform.

I checked the documentation for info on it and got nothing.

### What did you expect should have happened?

The [documentation page](https://serverless.com/framework/docs/providers/spotinst/guide/serverless.yml/#serverlessyml-reference) should have some info on this.

I finally found an example on a dashboard.serverless.com page:

> In your serverless.yml file, be sure to add your Serverless Platform Application and Tenant, like this:
> 
> ```yaml
> service: my-service
> app: MY_SPECIFIC_APP_NAME
> tenant: MY_SERVERLESS_ACCOUNT_NAME
> provider:
>   name: aws
>   runtime: nodejs4.3
> functions:
>   hello:
>     handler: handler.hello
> ```

Edit: found this in the serverless/platform docs: https://github.com/serverless/platform/blob/master/docs/getting-started.md#specify-the-tenant-and-application

**Comment by enBonnet** [comment]
Thanks works to me

**Comment by pmuens** [comment]
Thanks for opening @mrcoles and providing the fix 👍

Yes, those properties are related to the Serverless Framework Enterprise product, so they have their own docs.

**Comment by tetreault** [comment]
I just ran into this issue with no clear idea where to look to resolve it. I also checked out the immediate serverless.yml docs on the serverless site and saw no mention of this. 

Maybe this should be updated in the docs because my team's just using the free plan, not the enterprise plan, and I got tripped up trying to figure out what a "tenant" was and how I should get this working. 

All good after adding app and tenant in the serverless.yml though.
