### ISSUE TITLE
Changelog/release notes don't indicate breaking changes

### ISSUE THREAD

**Issue by q42jaap** [serverless/serverless#5501]
# This is a Proposal

The change log for 1.33.0 was huge, lot's of fixes! However, reading CHANGELOG.md or the release notes in github weren't that helpful.
I'm asked by the cli to update from 1.32.0 to 1.33.1, but looking over the list of fixes and changes it doesn't help me checking whether I can just upgrade or whether I need to do something to my code.

In semver, changing from 1.32 to 1.33 breaking changes should be minor, but from that long 1.33 list, I can't easily deduce if any breaking changes affect me. Even though the PR format has a nice `Is it a breaking change?` flag it took me a while to check them all off. And I'm probably not the only one.

It would be helpful if the list of issues was sorted based on the type, so docs, fixes, breaking changes, major issues being resolved etc. That would limit my search, and I could just read the PR titles, instead of clicking everything open and read all the tabs.

This will probably involve some manual work for the maintainers, but save time for all your users.

Thanks for considering, feel free to disagree or come up with reasons not to do this...

**Comment by dschep** [comment]
Hallo Jaap, you're right we can do better for this. Regarding it being a lot of work. It'll be less work if we don't wait as long between releases. The last release was so big because the team at Serverless has been focused on other things. I recently joined the team, and one of reasons is to help with maintenance issues here, so I'll be releasing more often so it hopefully we won't have as huge of releases.

**Comment by q42jaap** [comment]
Hi Daniel,
Let's hope it goes as you say, still would be nice to have a tl;dr for users!

Jaap
