### ISSUE TITLE
Ruby packaging does not include gems

### ISSUE THREAD

**Issue by dholdren** [serverless/serverless#5567]
# This is a Bug Report

## Description

When I first deployed my Ruby lambda to AWS via serverless, it did not have any of the gems available.
In order to successfully run my lambda, I had to run `bundle install --deployment` first.  At this point the `.bundle` and`vendor/bundle` directories were created, and then when I deployed they were included in the zip file uploaded to AWS

## Potential Fix

During the `package` step, detect if a `Gemfile` is present.
If so, spawn `bundle install --deployment`

**Comment by dschep** [comment]
This is out of scope for serverless framework. We don't even do this for NodeJS. Since ruby dependencies at least live in the same directory as your source code, you're lucky. I had to write [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements) because of how python manages dependencies.

If you want to automatically install dependencies on deploy, I recommend writing a plugin to do so, or using the [serverless hooks plugin](https://github.com/uswitch/serverless-hooks-plugin).

first install the plugin:
```
sls plugin install -n serverless-hooks-plugin
```
Then add this to your `serverless.yml`:
```yaml
plugins:
  - serverless-hooks-plugin
custom:
  hooks:
    package:initialize:
      - bundle install --deployment
```

**Comment by dholdren** [comment]
well they don't typically live in the same directory.
when running it locally, you just do `bundle install` and the gems are saved in a shared location.

but when you are packaging an app for deployment, you would run `bundle install --deployment` (maybe on a build server), this "vendors" the dependencies to a subdirectory

thanks for the info on the python way and the hooks plugin. I'll look into those

**Comment by jalerson** [comment]
Hey guys,

This is not a problem for nodejs apps because npm builds the `node_modules` folder inside the project with all dependencies, and, since the framework packs everything inside the project folder, it automatically tackles this problem.

I respectfully disagree that this is out of scope for serverless framework because the framework can even exclude development dependencies (still unclear for which runtimes, but Ruby isn't one of them): https://serverless.com/framework/docs/providers/aws/guide/packaging#development-dependencies

@dholdren I just published a blog post handling this problem: https://dev.to/jalerson/building-aws-lambdas-for-real-world-using-ruby-and-serverless-framework-2p49

**Comment by chitrarani** [comment]
@dholdren , doing 'bundle install --deployment' create an issue for those gem which have the dependency on native extension like pg gem. It creates the native extension based on my local machine. 
Any help would be really appreciated regarding to resolve the native extension issue on AWS lambda.

**Comment by dschep** [comment]
@jalerson, regarding this:
> framework can even exclude development dependencies
NodeJS, which as you mentioned has it's dependencies locally. And it's the language sls is built in, so yes, NodeJS does have better support.

@chitrarani, use one of the [docker-lambda](https://github.com/lambci/docker-lambda) images to accomplish that (that's what the python plugin does internally):
```
docker run --rm -it -v "$PWD:/var/task" lambci/lambda:build-ruby2.5 bundle install --deployment
```
(note, I haven't tested this command, I'm not a ruby dev 😉 )

**Comment by dholdren** [comment]
@chitrarani: :+1: to what @dschep said
My first Ruby/serverless project didn't have any native dependencies, but we built another one later that did and this is how we solved it in our serverless.yml:
```yaml
plugins:
  - serverless-hooks-plugin
custom:
  hooks:
    package:initialize:
      - docker run -v `pwd`:`pwd` -w `pwd` lambci/lambda:build-ruby2.5 bundle install --deployment
    package:finalize:
      - rm -rf vendor
      - rm -rf .bundle
```

**Comment by chitrarani** [comment]
> @chitrarani: 👍 to what @dschep said
> My first Ruby/serverless project didn't have any native dependencies, but we built another one later that did and this is how we solved it in our serverless.yml:
> 
> ```yaml
> plugins:
>   - serverless-hooks-plugin
> custom:
>   hooks:
>     package:initialize:
>       - docker run -v `pwd`:`pwd` -w `pwd` lambci/lambda:build-ruby2.5 bundle install --deployment
>     package:finalize:
>       - rm -rf vendor
>       - rm -rf .bundle
> ```

thanks 👍

**Comment by chitrarani** [comment]
> @jalerson, regarding this:
> 
> > framework can even exclude development dependencies
> 
> Only NodeJS, which as you mentioned has it's dependencies locally. And it's the language sls is built in, so yes, NodeJS does have better support.
> 
> @chitrarani, use one of the [docker-lambda](https://github.com/lambci/docker-lambda) images to accomplish that (that's what the python plugin does internally):
> 
> ```
> docker run --rm -it -v "$PWD:/var/task" lambci/lambda:build-ruby2.5 bundle install --deployment
> ```
> (note, I haven't tested this command, I'm not a ruby dev 😉 )

@dholdren , thanks for your help! 
I created one docker image with dependent library. 
A follow this link to create the docker image - https://www.stevenringo.com/ruby-in-aws-lambda-with-postgresql-nokogiri/

**Comment by ngw** [comment]
Not sure I understand this solution, should I use a different runtime for this?
I'm having:

```  Command failed: docker run -v `pwd`:`pwd` -w `pwd` lambci/lambda:build-ruby2.5 bundle install --deployment
/bin/sh: docker: command not found```

Here's my conf: https://gist.github.com/ngw/8e762faca258493c7159581aed1fccea

**Comment by waynerobinson** [comment]
Do you have Docker installed @ngw? 

This solution will build any ruby gems in an environment that very closely mimics how Lambda runs in production (the lambci/lambda images).

**Comment by joshuaflanagan** [comment]
The [serverless-ruby-package](https://www.npmjs.com/package/serverless-ruby-package) plugin is now available. It will automatically package all of your gems, including compiling native extensions for linux (using the same docker approach mentioned here), and excluding any gems not in the default bundler group.
The first project I used it on, the package size went down from 8.5MB to 28kb.
