### ISSUE TITLE
Unable to assign Deployment Manager Editor role with the existing documentation for GCP

### ISSUE THREAD

**Issue by alex-lu-amido** [serverless/serverless#5580]
# Unable to assign `Deployment Manager Editor` role with the existing documentation for GCP

## Description

* Following this page https://serverless.com/framework/docs/providers/google/guide/credentials/, `Deployment Manager Editor` is not available as a role for me to assign to a service account. 
* I found a workaround by going from IAM & roles section of the console. See [the last second comment of this issue](https://github.com/serverless/serverless-google-cloudfunctions/issues/52#issuecomment-354588910).
* I'm happy to update the correct steps as I've tried the work around.

## Similar or dependent issues:
N/A

## Additional Data
N/A

**Comment by pmuens** [comment]
Hey @alex-lu-amido thanks for opening 👍

We've recently updated the docs via https://github.com/serverless/serverless/pull/5490 which might've introduced the issue here.

It would be super nice if you could try the workaround and PR the proper changes. Cloud provider setups are always tedious and error prone.

Thanks in advance and let us know if you need any help here.

**Comment by pmuens** [comment]
Thanks @alex-lu-amido 👍

Can you fork the repo and PR the changes via your fork? You can find more information about forking [here](https://help.github.com/articles/fork-a-repo/).

Thanks in advance!

**Comment by alex-lu-amido** [comment]
PR Created.

**Comment by pmuens** [comment]
Awesome!

Thanks for the PR @alex-lu-amido 👍
