### ISSUE TITLE
Layer's Shouldn't Be Deployed on every deploy

### ISSUE THREAD

**Issue by j** [serverless/serverless#5595]
I feel that layers should be deployed differently and not on every deploy when no changes occur.  Is there a way to get a --layers-only or --no-layers option to deploy layers just once?

**Comment by dschep** [comment]
This isn't very feasible because of cloudformation. Layers are updated on each stack deploy and by default a layer is deleted if it's removed from the stack. But even if sls were to set the deletion policy to retain, it would then require you to hard code the layer's ARN in your function since you can't have a `{Ref: ..}` if the layer is not in the stack, so it would be imposible to automate :/

**Comment by dschep** [comment]
Here's how do manage it in two sls services: https://github.com/serverless/blog/blob/master/posts/2018-11-29-publish-aws-lambda-layers-serverless-framework.md#some-tips-on-working-with-layers

**Comment by pmuens** [comment]
Closing this since it's a CloudFormation issue and we can't do something about it right now. Feel free to re-open if AWS fixed this and Serverless is still re-deploying the Lambda every time.
