### ISSUE TITLE
 A valid undefined to satisfy the declaration

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#5717]
Serverless allows for default variable references, e.g.

    ${self:custom.site.FOO, self:custom.common.FOO}

But SLS complains "A valid undefined to satisfy the declaration" when variables don't appear in the first dict, even though they are correctly resolved by the second.

What's the point of having default variables if it complains in this way?

**Comment by exoego** [comment]
https://github.com/serverless/serverless/blob/d817ce08d41c8a2554da8c819cfeaef04a886df6/lib/classes/Variables.js#L818-L819

In severless 1.36.1, The message is shown when right-side default value (`self:custom.common.FOO` for this time) is null, undefined or empty plain object.

`${varType}` in the message is the infered type of variable syntax of the left-side specified value.
For your case, it supposed to be `service attribute` since the specified value matches `self:...` syntax.
However, something went wrong for your case.

To reproduce and investigate further, the following are required.

* serverless.yml 
* severless command you run
* Serverless Framework Version you're using
* Operating System

**Comment by cyberfox1** [comment]
> In severless 1.36.1, The message is shown when right-side default value (self:custom.common.FOO for this time) is null, undefined or empty plain object.

Well it also displays in my case when the RHS is not NULL, but the LHS is NULL.

E.g.

    custom:
        site: ${file(../site.yml)}
        common: ${file(../common.yml)}

    provider:
      name: aws
      runtime: python3.6
      region: ${self:custom.site.REGION, self:custom.common.REGION}

Make site.yml an empty file (or put other vars in there), and set REGION to something in common.yml, and in my case I get the warning, even though provider.region does get set to the correct value.

**Comment by cyberfox1** [comment]
I am using sls deploy and 1.36.1 on RHEL7.

**Comment by exoego** [comment]
Sounds similar https://github.com/serverless/serverless/issues/5353

**Comment by exoego** [comment]
@cyberfox1 
Could you share full content of `common.yml` to reprodue?
The issue could be due to invalid format of the file.

**Comment by cyberfox1** [comment]
This has been fixed in 1.36.3.
