### ISSUE TITLE
serverless.js files not packaged even if it isn't the config file being used

### ISSUE THREAD

**Issue by puncha** [serverless/serverless#5772]
# This is a Bug Report

## Description

* What went wrong?
If I have a folder named `serverless` and a js file named `serverless.js`. The JS file won't be packed and there is no warnings.
* What did you expect should have happened?
The JS file should be packed.
* What was the config you used?
I didn't `include/exclude` any files in my config
* What stacktrace or error message from your provider did you see?
No.

Similar or dependent issues:
None

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.3
* ***Operating System***: Mac OS
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by dschep** [comment]
This isn't because the files are of the same name (after ignoring extensions). It's that `serverless.js` is a valid configuraiton file for serverless, and as such, is [ignored by the default ignore patterns](https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js#L18) (just as `serverless.yml` is ignored).

A work around would be to explicitly add it back to the include directive:
```yaml
package:
  include:
    - serverless.js
```

But I'll leave this open as we can do better by only ignoring the config file that is used rather than all possible config files (will be useful with #5589 too, so that customized config file names are ignored too)

**Comment by ftes** [comment]
@dschep PR welcome for ignoring only the config file that is being used instead of all config files?

**Comment by dschep** [comment]
@ftes, there already is one! See #5840. I still need to test it before I merge. But you can try it out with:
```
npm i -g danielcondemarin/serverless#packaging-exclude-only-config-file-being-used
```
