### ISSUE TITLE
Don't wait for CloudFormation to finish in serverless deploy

### ISSUE THREAD

**Issue by robertmassaioli** [serverless/serverless#5778]
# This is a Feature Proposal

## Description

Please read this Stack Overflow question to understand my use-case: https://stackoverflow.com/questions/54507574/serverless-deploy-stop-watching-after-cloudformation-has-the-update

In short, I want to do CD and spend as few Build Minutes as possible.

I would love it if there was an option that was something like:

``` bash
serverless deploy --aws-push-to-cloudformation-and-exit
```

That would let me spend the minimum time possible waiting in by builds for CloudFormation to do its thing.

Similar or dependent issues:
* I could not find any.

**Comment by eahefnawy** [comment]
@robertmassaioli I don't think there's any safe way to do that. For one, it would be a HUGE breaking change for everyone. Also, just because CF accepted the stack, doesn't mean the deployment is successful. Deployment is successful when the stack completes.

I understand your use case, but Imo `--aws-push-to-cloudformation-and-exit` is beyond the scope of the Serverless Framework

**Comment by robertmassaioli** [comment]
Why would it be a huge breaking change if it was a non-default option to the deploy command?

Also, I don't want to wait for deployment to be successful, I'll monitor that another way.

If the issue is that it breaks the purpose of the deploy command, maybe a separate command should be written to do this? Could this be written as a plugin? I don't know the serverless plugin framework well yet.
