### ISSUE TITLE
File uploading doesn't work on serverless lambda

### ISSUE THREAD

**Issue by webdev522** [serverless/serverless#5820]
## Problem/Feature Request Summary
I'm using [serverless](https://serverless.com) with Koa

## Environment Information

  * koa-body: 4.0.8
  * Koa: 2.7.0
  * Node.js: 8.10.0

## Current Behavior
It works on my local machine, but It doesn't work on lambda when I use koa-body
It always returns 502 bad gateway error.

This issue is from serverless or from koa-body?

**Comment by pmuens** [comment]
Hey @webdev522 thanks for opening 👍

🤔 It looks like this issue is related to using `koa` on Lambda and not to the Serverless Framework itself. I'll close this issue for now.

Here's a useful blog post on how to use Express.js via Lambda --> https://serverless.com/blog/serverless-express-rest-api

Maybe you can adopt some of the pattern used there.
