### ISSUE TITLE
Environment variable must contain string error when pulling from Secrets Manager

### ISSUE THREAD

**Issue by josephbulger** [serverless/serverless#5869]
# This is a Bug Report

## Description

* What went wrong?

When utilizing a secret from Secrets Manager in the form of 

> SomeEnvVar: ${ssm:/aws/reference/secretsmanager//my/env/var/here~true}

whenever I try to run sls deploy with this configuration on version 1.38 it gives me the error 

> Environment variable EncoderProfiles must contain string

* What did you expect should have happened?

In serverless version1.36 this would work fine, and the secret would get pulled into my lambda env var without issue.

* What was the config you used?

> SomeEnvVar: ${ssm:/aws/reference/secretsmanager//my/env/var/here~true}

* What stacktrace or error message from your provider did you see?

Serverless Error ---------------------------------------

  Environment variable EncoderProfiles must contain string

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           11.2.0
     Serverless Version:     1.38.0

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.38 (works on 1.36)
* ***Operating System***: build agent is alpine
* ***Stack Trace***:
Serverless Error ---------------------------------------

  Environment variable EncoderProfiles must contain string

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           11.2.0
     Serverless Version:     1.38.0

* ***Provider Error messages***:

Environment variable EncoderProfiles must contain string

**Comment by dschep** [comment]
Is the secret your referencing actually a string? Or is it a JSON blob?
if it's the later, you'll need to do something like this:
```yaml
custom:
  mySecret: ${ssm:/aws/reference/secretsmanager//my/env/var/here~true}
provider:
  environment:
    SomeEnvVar: ${self:custom.mySecret.THE_NAME_OF_THE_FIELD_IN_THE_JSON_YOU_WANT}
```

To check what `SomeEnvVar` is being set to, run `sls print`

**Comment by raznerdeveloper** [comment]
Hello @dschep,

I'm having this same issue. I made a call to the secret manager like this:
`
service: someservice
provider:
  stage: staging
  region: eu-central-1
  name: aws
  runtime: nodejs6.10
custom:
  variables: ${ssm:/aws/reference/secretsmanager/somesecret~true} <== SSM call
functions:
  main:
    handler: index.serverlessHandler
    events:
      - http:
          path: v1/somepath
          method: get
`
I tried to reference a variable the way you mentioned `${self:custom.variables.THE_NAME_OF_THE_FIELD_IN_THE_JSON_YOU_WANT}`, but it wasn't working, so I printed and got this:

`service: someservice
provider:
  stage: staging
  region: eu-central-1
  name: aws
  runtime: nodejs6.10
custom:
  variables: '{"databasehost":"something","databasename":"something"}' <== response from ssm
functions:
  main:
    handler: index.serverlessHandler
    events:
      - http:
          path: v1/somepath
          method: get
`

This shows that the response from AWS is in fact a string and not a JSON blob. In my case I was a expecting a JSON since I have multiple variables in the secret manager.

**Comment by mesaugat** [comment]
Reverting back to `v1.37.0` worked for me. I was getting the same error after upgrading to `v1.38.0`.

**Comment by gudata** [comment]
this issue is also in v1.47.0

**Comment by medikoo** [comment]
Closing, as with new variables resolver it can be solved by passing `raw` option to variable config, as:

```
${ssm(raw):/aws/reference/secretsmanager/my/env/var/here}
```
