### ISSUE TITLE
I cannot verify with the code

### ISSUE THREAD

**Issue by truongthanhtungitvn** [serverless/serverless#5986]
Hi guys,
I cannot verify with provider webtask, it always says "Invalid verification code".
I tried with the latest version 1.40 and 1.39.1 but not work.

> serverless config credentials --provider webtasks

My environment 

> Your Environment Information -----------------------------
>      OS:                     darwin
>      Node Version:           11.12.0
>      Serverless Version:     1.39.1
> 
I also find the same question https://forum.serverless.com/t/unable-to-create-profile-invalid-verification-code/7624/2 but look like not solve yet.
Anyone got the same issue?

Thanks.

**Comment by eahefnawy** [comment]
hey @truongthanhtungitvn ... this is probably because webtask has been official deprecated and support for it has been removed by the webtask team. Here's the corresponding PR:

https://github.com/serverless/serverless/pull/5263

Our docs no longer include webtask as a provider. so I'm curious how you're using that feature now 🤔

**Comment by truongthanhtungitvn** [comment]
Thanks @eahefnawy for the answer 👍 . it's my bad, I followed the old tutorial to build the automation tool by serverless and webpack.
