### ISSUE TITLE
Serverless deployment fail after V1.41.0 released

### ISSUE THREAD

**Issue by cheesiangcs** [serverless/serverless#6029]
Encountered this issue after V1.41.0 released...

My serverless deployment was able to run successfully before V1.41.0 released. 

![CodeBuild_-_AWS_Developer_Tools](https://user-images.githubusercontent.com/35026330/56360520-7a788780-6217-11e9-9f5c-b6515d3c69c0.png)

I didn't enable X-way in my serverless. 

Lock to V1.40.0 then deploy successfully...

**Comment by eligan** [comment]
Hi guys

Our team develops a little more than ten AWS Lambdas. All of these based on serverless framework. And this morning all our build scripts failed because of new 1.41.0 release. 

<img width="1680" alt="Screen Shot 2019-04-19 at 18 21 20" src="https://user-images.githubusercontent.com/10174661/56430753-0352fa00-62d0-11e9-8aaf-7427d9ef6dd8.png">

With 1.40.0 everything is working perfectly.
Please take a look at this issue.

**Comment by eahefnawy** [comment]
@cheesiangcs could you share your `serverless.yml`? I can't reproduce, so I'm curious about your config.

**Comment by eahefnawy** [comment]
@eligan could you also share your yaml file? I have a theory that this might be due to the check we're doing for the Stage resource.

cc @pmuens

**Comment by pmuens** [comment]
We've just published https://github.com/serverless/serverless/releases/tag/v1.41.1 which should fix the problem.
