### ISSUE TITLE
API Gateway tags setting Stage Variables not Tags

### ISSUE THREAD

**Issue by shredder2500** [serverless/serverless#6133]
# This is a Bug Report
## Description

* What went wrong?
Updated to new version of serverless. Deploying failed due to it trying to put our tags that contain spaces into stack variables on api gateway.
* What did you expect should have happened?
api gateway tags to be set not stack variables for tags
* What was the config you used?
```
provider:
  stackTags:
    Project ID: xxxxx
```
* What stacktrace or error message from your provider did you see?
```
Serverless Error ---------------------------------------

 Invalid stage variable name: Project ID.  Please use names with only word characters.
```
Similar or dependent issues:
* PR #5851

## Additional Data

* ***Serverless Framework Version you're using***: tried with 1.42.2 and 1.42.3
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by awolden** [comment]
This is effecting us as well. Just started happening.

**Comment by jplock** [comment]
Same here

**Comment by nathanchapman** [comment]
@shredder2500 @awolden @jplock 
Are all of you using the serverless-aws-alias plugin?

**Comment by shredder2500** [comment]
@nathanchapman 
```
plugins:
  - serverless-plugin-tracing
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-offline
```

**Comment by jplock** [comment]
@nathanchapman 

```
plugins:
  - serverless-plugin-lambda-warmup
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin
  - serverless-appsync-plugin
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
```

**Comment by exoego** [comment]
The reason why `stackTags` is also used to tag API GW in #5851 is design consitency, since `stackTags` is used to tag Lambda functions too.
As an user of serverless & AWS,  I expect `stackTags` should tag all resources configured by serverless.

It looks like Lambda can be tagged even if tag name contains spaces:

```yaml
service: test-6133

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  tags:
    foo: FOO
  stackTags:
    bar bar: BAR

functions:
  hello:
    handler: handler.hello
    events: []
```

I think this is an issue in API Gateway, or design incosintency regarding tags in AWS at least.
It would be happy if you report the issue to AWS so they fix.

Until AWS fixes (may not?), what is preferable workround in serverless?

Considerable Options
1. Do not use `stackTags` for API Gateway at all.
2. Escape keys in `stackTags` automatically by replacing space to `_`
3. Translate the error like `As of 2019-5-15, API Gateway stages can not be tagged with a key containing space. Please remove spaces.`

Option 1 & 2 causes tag mismatch between API GW & Lambda, but not breaking change from user perspective.
Option 3 reminds users to use API GW-safe tag, but it requires users to change tag name, so it might be breaking change.

I think Option 1 is safer and so will opens a PR.

**Comment by shredder2500** [comment]
@exoego
The issue is not the space being in the tag name but the fact that it is trying to apply stacktags to stage variables and not tags. the api gateway tags do support spaces. We tested without spaces to see what happens and they were added as stage variables and not tags. We then tested manually adding tags and variables to see the constraints. tags support spaces but variables do not

**Comment by exoego** [comment]
Oh yeah, it's true.
However, due to limitation in CloudFormation, tags for API Gateway stages are updated via AWS SDK in #6084.
The following code uses stage variable to tag GW stage.
https://github.com/serverless/serverless/blob/572dd8761c0c8283e50b960a66712669b0daf0df/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L209

So anyway dropping stackTags to tag GW stage is required, I think.

**Comment by shredder2500** [comment]
@exoego
Tomorrow I will try using just tags but when I was looking through the code I thought it was merging stackTags and tags and running through the same code and both were going to variables instead of tags.

**Comment by exoego** [comment]
@shredder2500 
Great!!
I opened a PR #6139 but holds it from review until you give it a try.
Notify us when done.

**Comment by exoego** [comment]
@shredder2500 
I updated a PR to allow tag keys contain spaces !!

**Comment by shredder2500** [comment]
Testing your PR now, Thanks!

**Comment by thomasmichaelwallace** [comment]
n.b. it is more than just spaces, for example stage variables do not support `+`, but tags do, as I found trying to support this problem on Stack Overflow (https://stackoverflow.com/questions/56160686/serverless-deploy-failing-with-character-in-stacktags-variable)

**Comment by oba11** [comment]
I'm gettting the sam error too

```
Serverless: [AWS apigateway 200 0.471s 0 retries] getStage({ restApiId: 'abcd1234', stageName: 'dev' })
Serverless: [AWS apigateway 400 0.517s 0 retries] updateStage({ restApiId: 'abcd1234',
  stageName: 'dev',
  patchOperations:
   [ { op: 'replace', path: '/tracingEnabled', value: 'true' },
     { op: 'replace', path: '/*/*/logging/dataTrace', value: 'false' },
     { op: 'replace', path: '/*/*/logging/loglevel', value: 'OFF' },
     { op: 'replace',
       path: '/variables/owner:application-name',
       value: 'foo' },
     { op: 'replace',
       path: '/variables/owner:environment',
       value: 'dev' },
     [length]: 6 ] })

  Serverless Error ---------------------------------------

  Invalid stage variable name: owner:application-name.  Please use names with only word characters.

  Stack Trace --------------------------------------------

ServerlessError: Invalid stage variable name: owner:application-name.  Please use names with only word characters.
    at promise.catch.err (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by shredder2500** [comment]
@oba11 @thomasmichaelwallace 
try #6139
