### ISSUE TITLE
Finish API Gateway Authorizer Support

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#626]
Almost done with this.

**Comment by remicastaing** [comment]
The docs say 

> For a valid policy, API Gateway caches the returned policy, associated with the incoming token and used for the current and subsequent requests, over a pre-configured time-to-live (TTL) period of up to 3600 seconds.

There should only be double cost if the incoming token is unknown or after the TTL period. Or I am understanding it wrong?

**Comment by jackrk** [comment]
Nope you're right, caching comes out of the box. The IAM policy generated in the Lambda function on a cache miss then applies to that token + api + authorized + stage on **any** resource/method in the API for the duration of the TTL. 

Also, authorizes can be created independently, but must be applied to methods before deployment.

**Comment by kennu** [comment]
This looks very useful, but also limited on the AWS side. Apparently the Custom Authorizer can't specify the Lambda function alias (dev, prod), so it just calls the $LATEST version. That will cause problems because I keep my JWT secret different for dev and prod. I hope Serverless can solve this somehow, like maybe by creating a separate Authorizer function for every stage.

**Comment by kennu** [comment]
One of the AWS developers tweeted this Gist of how to specify Lambda version qualifiers for Custom Authorizers on AWS CLI, maybe interesting: https://gist.github.com/SAPessi/11a87ed83954461d5e43

**Comment by eahefnawy** [comment]
Custom Authorizer added. Closing...
