### ISSUE TITLE
Async functions not responding

### ISSUE THREAD

**Issue by lovelstn** [serverless/serverless#6371]
Hi, can anyone help explain what is going on here. I am using Sequelize ORM with AWS Serverless framework.

* Function1
```
async (event) => {
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: 'Function1 endpoint'
      })
    }
  }
```

* Function2
```
  async (event) => {
    let user = await userModel.find()
    // this returns the user in logs
    console.log(user)
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: 'Function2 endpoint'
      })
    }
  }
```

Function1 works perfectly... however Function2 does not respond to my http request and just times out. I see that `let user = await userModel.find()` executes and finished as I see `user` data in the logs.

Everything works locally with `sls offline` just not with `sls deploy`

Any help greatly apprieciated!

**Comment by medikoo** [comment]
> I see that let user = await userModel.find() executes and finished as I see user data in the logs.

It might be that your functions run beyond configured _timeout_, and that _user log_ is logged in next function invocation. It's actually how lambda invocations work when _async_ functions are used.

To avoid confusion I would suggest to use _callback_ interface instead of _async_ function. Then timeout won't leak remaining tasks into different invocations.

Having that, probably you should shift timeout setting for your function (I'm not sure if `sls offline` enforces any timeout, and it might be the reason it works locally)

**Comment by herebebogans** [comment]
It *feels* like sequelize is timing out the connection to your database when run inside lambda.

* Is your database target inside your VPC or is it accessed over the internet?
* If your database is inside a vpc is your lambda function vpc attached?
* Try adding 
```
environment:
  DEBUG: '*'
  DEBUG_DEPTH: 'null'
```
to your lambda function to see logging from sequelize

**Comment by pmuens** [comment]
Closing this issue since it's quite stale. Please refer to the [Serverless Forums](https://forum.serverless.com) or [Gitter](https://gitter.im/serverless/serverless) where issues like this can be discussed with our broad developer community.
