### ISSUE TITLE
ComponentCreate: Put .env files in component folders, not project root

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#639]

**Comment by eahefnawy** [comment]
Is there any reason why we should do that? Isn't that gonna cause duplication across our project? Because it's the same `.env` file in each component. The `.env` file can be different for each stage/region, but not for each component, correct?

It'll also make the `env` actions more complex, because we'll have to deal with multiple `.env` files when we load the vars from the local file system. So maybe the user will have to choose the component first?

**Comment by ac360** [comment]
@eahefnawy You're right.  Closing.
