### ISSUE TITLE
S3 events do not support multiple events for the same bucket.

### ISSUE THREAD

**Issue by hauboldj** [serverless/serverless#652]
The s3 api call putBucketNotificationConfiguration replaces all existing notifications to sns, lambda, or sqs with whatever configurations are present in the call.

Serverless should call putBucketNotificationConfiguration, detect if the notification that is going to be created already exists, update it or add it to the existing configurations as necessary and send all the configurations back in the putBucketNotificationConfiguration call.

**Comment by eahefnawy** [comment]
@hauboldj the `"bucketEvents"` property is an array that takes multiple events for the same `bucket`. So you don't need to have a separate event object for the same bucket for example:

`"bucketEvents" : ["s3:ObjectCreated:*, s3:ObjectDeleted:*, ...etc"]`

Generally speaking, the Put method is meant to replace configurations, otherwise you won't be able to delete events if you wanted to. As long as you have your events defined in `s-function.json`, you should have them available in AWS console. If you delete one of the events, the AWS console should be updated as well. This keeps your project in sync with AWS.

Also, we try to make `s-function.json` a reflection of AWS configurations, so if you think we missed something, please let us know :blush:

**Comment by hauboldj** [comment]
I guess I wasn't clear. Suppose I create via the `s-resources-cf.json` an SNS topic and an S3 bucket configured to send notifications to that SNS topic. Now if I also want a lambda function to receive notifications/events from the same S3 bucket, I configure it in the events section of `s-function.json`. But when Serverless calls `putBucketNotificationConfiguration` on that bucket it overwrites the notification I had previously setup for SNS.

Put another way, suppose an s3 bucket exists with previously configured notifications. When Serverless calls `putBucketNotificationConfiguration` only the notifications specified for that call remain. The previously configured notifications are overwritten.

**Comment by eahefnawy** [comment]
ahaaaa .. now I get it :smile: .. so the issue is that we're only assuming that you're creating events sources from scratch? and we're not handling **existing event source**.

Thanks for clearing it up. This is definitely an issue and we'll clear it out asap :)

**Comment by mineer22** [comment]
@mrowles try 
`create:
  handler: create.create
  events:
    - s3:
        bucket: someBucket
        event: s3:ObjectCreated:*
        rules:
          - prefix: original/
          - suffix: .jpg
  resize:
    handler: resize.resize
    events:
      - s3:
          bucket: someBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: resized/
            - suffix: .jpg`

If you place the resized images in the the original "folder" you will get an endless loop.

**Comment by mrowles** [comment]
Yeah that's what I ended up doing (resizing in a waterfall manner original > large > medium > small). Thanks!
