### ISSUE TITLE
Custom Bucket Configuration SourceArn 

### ISSUE THREAD

**Issue by ebisbe** [serverless/serverless#6569]
# This is a Bug Report

## Description

- What went wrong? 
 When following https://serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration you cannot define a custom name with vars for the bucket because the SourceArn of the AWS::Lambda::Permission has to be a String. If the SourceArn is an object it gets _.merge() by the configuration the SLS automatically generates.
- What did you expect should have happened? Overriding the SourceArn with !GetAtt/!Join etc would return a well formed configuration like: 
```
"SourceArn": {
           "Fn::Join": [
                  "-",
                  [
                    "s3test",
                    "dev",
                    "datalake"
                  ]
                ]
        },
```
Now returns a merge: 
```
"SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:aws:s3:::",
              {
                "Ref": "AWS::Partition",
                "Fn::Join": [
                  "-",
                  [
                    "s3test",
                    "dev",
                    "datalake"
                  ]
                ]
              },
              ":s3:::datalake"
            ]
          ]
        },
```
- What was the config you used? https://github.com/ebisbe/s3test/blob/master/serverless.yml
- What stacktrace or error message from your provider did you see?
The cloudformation stack is invalid with: 
` An error occurred: AthenaPartitionerLambdaPermissionDatalakeS3 - Value of property SourceArn must be of type String.`

## Additional Data

If already made a Fork and I have a possible fix with tests.

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by medikoo** [comment]
As I see it's due to unconditional deep merge (done via `_.merge`) being used for adding custom resources here: https://github.com/serverless/serverless/blob/66ef74b0c6f09d9435921155d8820cbc3cd77432/lib/plugins/aws/package/lib/mergeCustomProviderResources.js#L15-L18

It's indeed not great, at https://github.com/serverless/serverless/issues/6575 I've proposed some new safe solution, still it'll be breaking for existing users, so we cannot introduce it within v1.

And concerning v1, I wonder whether we can do any improvement that will not break for users.
Probably we can make this merge more controlled, so if custom resource aims to extend resource generated by framework, following steps could be taken:
- Throw if type of resources mismatch
- Extend `Properties` with `Object.assign` (so flat way) to avoid merging deeper `Fn::Join` and likes.

@pmuens what do you think?

Also some workaround for your case could be to use plain string and not `!Join`. I believe following should work:

```
 SourceArn: 'arn:aws:s3:::${self:service}-${self:provider.stage}-datalake'
```

**Comment by ebisbe** [comment]
@pmuens Your suggested solution works for me. Thanks
