### ISSUE TITLE
Condensing output of "serverless" command

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#657]
As we implement more and more functionality the output of the CLI gets more complex / confusing.

We have a lot of whitespace in the right side. Maybe we can structure the commands into groups or format them in another way so that we use the screens real estate better.

<img width="1190" alt="bildschirmfoto 2016-02-16 um 09 17 46" src="https://cloud.githubusercontent.com/assets/1606004/13070654/6e0346bc-d48e-11e5-932c-5d35483695b5.png">

**Comment by ac360** [comment]
:+1:

**Comment by akalra** [comment]
Hey -- I can tackle this. I was actually griping about the exact same issue, came here to track it, and found the existing one.

Has anyone else started on this? Or does anyone have strong thoughts on how this should be done?

Thanks!

Ankur

**Comment by pmuens** [comment]
Hey @akalra thank you for reaching out.

This issue is free to take! I don't have any thought how it should be done but a kind of grouping by functionality would be great.

Do you have any suggestions which came to your mind?

**Comment by akalra** [comment]
Open to the idea of grouping, though we might have to change the contract so that contexts and actions advertise how they want to be grouped (they don't seem to today). I'm a little uncomfortable with the idea of the CLI deciding the grouping independently. 

Having said that, not sure grouping is necessary to achieve this goal. The simplest thing we could possibly do seems to work rather well (needs some polish, but still):

![image](https://cloud.githubusercontent.com/assets/509798/14708219/5d63bad0-0797-11e6-9bad-7b2a8a9aa23b.png)

Compare to:

![image](https://cloud.githubusercontent.com/assets/509798/14708236/7e22b37a-0797-11e6-974b-89b4f0e36242.png)

I didn't exhaustively check the rest of the CLI, so it's possible it's straying from some standard display pattern we're using everywhere else. 

If this seems reasonable to you, I can build it out throughout the CLI. The extra polish I'll add would be along the lines of:

- right padding the contexts in some way, so that all the actions line up under each other
- sorting the action names alphabetically (or some other way), so that similar actions in multiple contexts are more likely to line up with each other
- padding the action names in some way, so that (for example) the third action name in a given context lines up with the third action name in the context below it

Not sure if all of those are necessary/useful, but those are the things I'd consider playing with to see what seems to work best.

Thoughts?

**Comment by akalra** [comment]
I went ahead and tried the different variations since I was already in my editor. Right padding contexts seemed useful, but padding the action names seemed to take away from readability.

Sorting the action names I'm undecided about -- it's more consistent, but I don't have enough experience with serverless projects to know if the alphabetical sort is over promoting some less-used actions ahead of more important actions.

![image](https://cloud.githubusercontent.com/assets/509798/14709113/e5c236ae-079c-11e6-914e-0c68f4b8fb1e.png)

Thoughts?

**Comment by pmuens** [comment]
That's a really great idea. Really like it!

I too think that grouping is a little bit too hard for the first implementation.

Maybe we can sort the actions alphabetically (so that they can be found faster) followed by a <hr />. The Plugin commands may come after this line break so that the user can directly see what actions are taken from PlugIns.

In my case I often use `dash deploy`, `function deploy` and `endpoint deploy`. I think that most of the Serverless users already know the most common commands so no need to sort them by usage.

Maybe @ac360 and @eahefnawy can chime in on this.

**Comment by akalra** [comment]
Sorry -- not sure I understand what you mean about the line break? 

In the screenshot (and my current implementation), actions are sorted alphabetically. We can also sort the **contexts** alphabetically, if that's what you mean?

I do think it might be interesting to visually represent 'core' contexts/actions differently from 'plugin' contexts/actions, but I'm not sure that the code actually knows the difference. I'm actually not even sure it should know the difference.

IMHO, it might be useful to have a single line after all the contexts that just said "Plugins installed: foo.v1, bar.v2, baz.v3", but keep the actual contexts/actions in the main list visually identical. So in your day to day use, the 'set of things you can do' all look the same and we aren't distracting you with what functionality is in core vs not, but there's a small reminder of what things are not in core (so if you're having trouble with it, you know where to ask for help).

Thoughts?

**Comment by pmuens** [comment]
@akalra Yep. Valid points. It's a good idea to list the installed plugins at the bottom and merge the commands into the other commands.

Totally missed that they are already sorted alphabetically though.

**Comment by akalra** [comment]
Cool. I'll wait for @ac360 and @eahefnawy to weigh in on this, and will then wrap this up and submit a PR.

In looking through this, the code doesn't actually seem to know which plugins are core (Actions.json) vs project-specific (s-project.json), so generating a "Plugins installed: x, y, z" line dynamically might require more refactoring than it's worth. 

We could just stringify the plugins array in s-project.json for a similar effect, if that would be useful. That logic will have to change if we someday want to support plugin version numbers, or plugins that can include other plugins.

Thoughts?

**Comment by eahefnawy** [comment]
@akalra I LOVE this!! it's looking really neat! What about contextual help though? how would that look like?

**Comment by pmuens** [comment]
@akalra Great! You might want to consider https://github.com/serverless/serverless/pull/968. We might remove the plugins-Array in future versions as it's not required anymore.

Maybe a check for paths might identify which one is a Plugin and which one lives insider the directory structure of Serverless. Something similar is used here: https://github.com/serverless/serverless/blob/master/lib/Serverless.js#L276

**Comment by akalra** [comment]
@eahefnawy By contextual help, do you mean the help page for each specific context/action? I'll go look into that.

@pmuens I think I understand that. I'm not super comfortable using that kind of machinery for the help section -- I think it has slightly different tradeoffs, and there's another approach that might work well. I'll try to outline that later this afternoon.

Should I go forward with this, or should I wait for @ac360 to chime in as well? Sorry, still learning the team dynamics of this particular project.

Thanks!

Ankur

**Comment by akalra** [comment]
Old 'context' help:
![image](https://cloud.githubusercontent.com/assets/509798/14750937/5cbae104-0895-11e6-88fc-37944908c0f5.png)

New 'context' help:
![image](https://cloud.githubusercontent.com/assets/509798/14750942/6c3520cc-0895-11e6-81a0-638d2e8efc51.png)


Old 'action' help:
![image](https://cloud.githubusercontent.com/assets/509798/14750958/875646ba-0895-11e6-8c34-af473b40594e.png)

New 'action' help (minimal changes):
![image](https://cloud.githubusercontent.com/assets/509798/14750971/9ab661ea-0895-11e6-8bb6-ff8479c74a0f.png)


Thoughts? 

I'll follow up a separate comment with the new main, context, and action help together so we can see if it looks cohesive as a system.

**Comment by akalra** [comment]
Main help:
![image](https://cloud.githubusercontent.com/assets/509798/14751019/db48d86e-0895-11e6-8359-61aeb4fde37b.png)

One level deeper:
![image](https://cloud.githubusercontent.com/assets/509798/14751093/421ce634-0896-11e6-9904-5aac2aa3df15.png)

Two levels deeper:
![image](https://cloud.githubusercontent.com/assets/509798/14751040/fe9dbb72-0895-11e6-9535-cd90f890fb67.png)

On each screen, I've tried to keep everything in plain white, supplementary stuff in dimmed white, and pointers to the next level deeper (and headings) in yellow.

If this looks good to you, I'll submit a PR for this. I'm going to tackle the plugin stuff in a separate PR, since that's new functionality.

Thanks!

Ankur

**Comment by pmuens** [comment]
Great job! Really like the new version and the concept with the colors.

**Comment by HyperBrain** [comment]
Could we have two different color schemes? For example on Linux I use the black background where the yellow/grey colors are perfect, but on WIndows I use a white background. There the colors (also in the current SLS) are nearly visible.

**Comment by akalra** [comment]
That's an interesting point. I was wondering about that too.

I'm going to focus mostly on condensing the length of the visual output, but we should separately also figure out what to do about the color scheme. It might make sense to have a light and a dark scheme as you suggest (and have people pick one somehow), or it might also make sense to have just one scheme that works well against both a light and a dark background. What do other similar tools you use do @HyperBrain?

Thanks!

Ankur

**Comment by akalra** [comment]
Submitted PR #1046 for condensed output.

Thanks!

Ankur

**Comment by eahefnawy** [comment]
@akalra this looks really great!! I can merge your PR right away, but you mentioned it's not complete yet?
