### ISSUE TITLE
Why is `plugin install` limited to those in serverless plugin registry?

### ISSUE THREAD

**Issue by mcjfunk** [serverless/serverless#6710]
Hey folks, thanks for the great technology! 🤖 

It appears that `sls plugin install --name <plugin>` first checks that the plugin is in the serverless registry and only npm installs if it is. Why is that? Are you open to loosening that restriction?

I work for a fairly large enterprise and am setting up a CICD pipeline for lambdas. I have a serverless plugin that I want to install and add to the serverless config for any lambda repo that uses the pipeline. I don't need or want end users to have to install this plugin since it is an implementation detail of the pipeline. Right now each lambda repo has to install it and add it to their serverless.yml manually. If `sls plugin install` loosened the aforementioned restriction, I could install it at deploy time.

Specifically, the plugin is published to our enterprise npm repository. It is scoped with an npm namespace.

Thanks!

**Comment by pmuens** [comment]
Hey @mcjfunk thanks for opening the issue :+1:

Good question. The main idea for `plugin install` is to abstract `npm` away. In the future we don't want to expose the npm dependency to end-users. That's also the reason why we're reaching out to our own registry (which currently is just a `.json` file we fetch).

The best way to be as flexible as possible is to use plain `npm` (since our `plugin install` is just a wrapper around `npm install --save-dev <plugin-name>` right now).

**Comment by pmuens** [comment]
There's also the https://www.npmjs.com/package/serverless-plugin-scripts and https://www.npmjs.com/package/serverless-scriptable-plugin which might be helpful in your case.

**Comment by mcjfunk** [comment]
The key piece to `plugin install` that I don't get with `npm install` is the plugin not only gets installed, but it also gets registered in the serverless config. Is there any workaround to that?

Again, we need the installation of certain plugins to be done in the CICD pipeline as they are an implementation detail of the pipeline. `plugin install` allows for that but limits our enterprise use case due to this registry checking.
