### ISSUE TITLE
Serverless framework deleting the already existing resource on sls deploy

### ISSUE THREAD

**Issue by jayanthck** [serverless/serverless#6810]
[serverless.yml.zip](https://github.com/serverless/serverless/files/3708077/serverless.yml.zip)

# Bug Report
 deploying  the serverless template when a  resource already exists, it is deleting the resource instead of updating it or not doing any changes

## Description

1. What did you do?
First I ran the sls deploy with out  this property
restApiResources:
      'test':	hy1234
and after this, I added the above property and ran sls deploy again
2. What happened?
 ApiGatewayResourceTest is getting deleted

3. What should've happened?
Instead of deleting the resource ApiGatewayResourceTest, it should have updated it or left the resource unchanged

4. What's the content of your `serverless.yml` file?
attached the serverless.yml.zip
service: serverlessfunction
provider:
  name: aws
  region: 'eu-central-1'
  stage: stage
  runtime: nodejs10.x
  apiGateway:
    restApiId: '6k12345678'
    restApiRootResourceId: '6j12345678'
    restApiResources:
      'test':	hy1234
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: 'test'
          method: post
          cors: true
5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
ApiGatewayResourceTest is getting deleted
and there is new AGW deployment

**Comment by tinexw** [comment]
Hi, I'm having the same issue. I have created a minimal example that reproduces the issue: https://github.com/tinexw/serverless-issue-6810/tree/master

The example performs the following steps:
- Deploy one HTTP endpoint `/bar`.
- Deploy another HTTP endpoint `/foo`.
- Deploy the first endpoint `/bar` again. **This is where the bug occurs.** The endpoint is deleted.
- Deploy the first endpoint `/bar` yet again. This will create the endpoint again.

What might cause the issue is that the `apiGateway.restApiResources` property always contains all existing resources. Thus, when deploying `/bar` for the 2nd time, it contains an entry like `bar: jg2uja`. 

I'm not quite sure if that is even the expected format or if it should be `/bar: jg2uja`. The [documentation](https://serverless.com/framework/docs/providers/aws/events/apigateway#share-api-gateway-and-api-resources) contains both formats. However, when using the format with the slash, I immediately get the error `Error: Can not find API Gateway resource from path bar`.

Please find the complete output below:
```
==== Deploying bar - 1st run ====
-- apiGateway.restApiResources --
---------------------------------
------ Available resources ------
/	4gyxjxwh0m
/bar	e7frq7
---------------------------------
=================================
========= Deploying foo =========
-- apiGateway.restApiResources --
bar: e7frq7
---------------------------------
------ Available resources ------
/	4gyxjxwh0m
/bar	e7frq7
/foo	t8np6h
---------------------------------
=================================
==== Deploying bar - 2nd run ====
-- apiGateway.restApiResources --
bar: e7frq7
foo: t8np6h
---------------------------------
------ Available resources ------
/	4gyxjxwh0m
/foo	t8np6h              <----- only foo available, bar was removed!
---------------------------------
=================================
==== Deploying bar - 3rd run ====
-- apiGateway.restApiResources --
foo: t8np6h           
---------------------------------
------ Available resources ------
/	4gyxjxwh0m
/foo	t8np6h
/bar	xcput9              <----- bar is back (with a new id)
---------------------------------
=================================
```
