### ISSUE TITLE
Is it possible to do VPC-link integration ?

### ISSUE THREAD

**Issue by mpo-deltacode** [serverless/serverless#6899]
Hello,

I use Serverless to create API's on AWS, but I can only create method with "Lambda Function" integration type. There is a resource that I need to create myself because it use "vpc-link" integration type and the endpoint is an EB endpoint, so my function is not write in my serverless folder.

I would like to know if it was possible to write this ressource and methods in my serverless.yml

(Every methods are vpc-link integration)

![Screenshot 2019-10-29 at 11 39 32](https://user-images.githubusercontent.com/49921482/67760069-e34f8080-fa40-11e9-9290-e9c35828a4d8.png)

**Comment by pmuens** [comment]
Thanks for opening this issue :+1:

Since this issue tracker on GitHub is about the Serverless Framework codebase we'd encourage you to re-open your question on Q&A platforms such as our [Serverless Forum](https://forum.serverless.com) or [StackOverflow](https://stackoverflow.com/questions/tagged/serverless).
