### ISSUE TITLE
Parameters in cloudformation

### ISSUE THREAD

**Issue by nishantjain91** [serverless/serverless#695]
I may be missing something but is there any way to pass parameters in cloudformation template.

**Comment by flomotlik** [comment]
Yes thats possible: http://docs.serverless.com/docs/templates-variables#section-variables

**Comment by antanasbrazenas** [comment]
The link goes nowhere. Is it still available in v1.4.0?

**Comment by pmuens** [comment]
Hey @antanasbrazenas you can use Serverless Variables to do this: https://serverless.com/framework/docs/providers/aws/guide/variables/

**Comment by antanasbrazenas** [comment]
Thanks for the quick reply. I don't think these can fully replace the CloudFormation parameters. The specific scenario that I would like to achieve:

If command line option is given, set the parameter to it. Otherwise, default to the CloudFormation pseudo parameter (i.e. AWS::AccountId). That does not seem to be possible since Serverless variables are evaluated before the template is built. Please correct me if I'm missing something.

**Comment by pmuens** [comment]
@antanasbrazenas yes, you're right. Right now the Serverless variable system replaces the content of the template before the template is built so CloudFormation parameters are still necessary in your use case...

**Comment by jrasillo** [comment]
Similar to this, I have a cloudformation template that I would like to embed in the resources section but the existing cloudformation template contains parameters. Is it possible to handle this?
For example:

`resources: 
   Resources: ${file(cloudformation-resources.json)}`

but cloudformation-resources.json has parameters....

**Comment by pmuens** [comment]
@jrasillo yes, you should be able to reference any variable in your embedded CloudFormation template.

**Comment by riponbanik** [comment]
@pmuens does not, serverless complain -  The CloudFormation template is invalid: Invalid template resource property 'InstanceType'

my json file is below -

{
	"Parameters" : {
	  "InstanceType" : {
	    "Type" : "String",
	    "Default" : "t2.micro",
	    "AllowedValues" : ["t2.micro", "m1.small", "m1.large"],
	    "Description" : "Enter t2.micro, m1.small, or m1.large. Default is t2.micro."
	  }
	}
}

**Comment by pmuens** [comment]
@riponbanik thanks for commenting :+1:

Could you share your `serverless.yml` file so that we can see the usage of CloudFormation parameters in the context of a Serverless service?

Thanks!

**Comment by riponbanik** [comment]
@pmuens - I just use the what example is given here - https://serverless.com/framework/docs/providers/aws/guide/variables/, particularly json 

It would have been useful if we could use something like output parameter  { "Ref" : "ServerlessDeploymentBucket"} as value of yaml attribute.

https://serverless.com/framework/docs/providers/aws/guide/functions/

         Resource:
           Fn::Join:
             - ""
             - - "arn:aws:s3:::"
               - "Ref" : "ServerlessDeploymentBucket"
               - "/*"

Currently AWS SAM allows it, passing different yaml file as parameter of different stages.

**Comment by pmuens** [comment]
Hey @riponbanik thanks for getting back. 🤔 Not entirely sure why the Parameters usage fails in that case since you've used the valid syntax.

It would be nice if you could share your whole `serverless.yml` file so that we can look into it and see why it failed in this scenario.

Yes I agree. Referencing other outputs via `Ref` would be really beneficial. We're currently working on a global `arn` parser to accomplish that in the future (the corresponding issue can be found [here](https://github.com/serverless/serverless/issues/3212)).
