### ISSUE TITLE
Serverless command "-org" not found.

### ISSUE THREAD

**Issue by simsketch** [serverless/serverless#7145]
# Bug Report
Per the instructions on the dashboard 
[https://dashboard.serverless.com/tenants/{username}/applications/{application-name}/overview]

I attempted to set the org and app names via the command line.

`serverless login` <-- this command worked

`serverless —org [username] —app [application name]`

which returns Serverless command -org not found.

I have never set the org or app in my serverless file, either manually or by other means.

I would expect the org an app to be set when I run this command, since the instructions on the live dashbaoard instruct me to do so.

**Comment by medikoo** [comment]
@simsketch thanks for report. There's bug in a docs. It should be:

```
serverless --org [username] --app [application name]
```

(note: two `-` characters, and not one `—`)

/cc @skierkowski

**Comment by sridharkalaibala** [comment]
I had similar issue. I copied command from 
```https://dashboard.serverless.com/tenants/xxxxx/applications/test/overview/service```.
you may need to just edit the page with `--` character. 
![image](https://user-images.githubusercontent.com/3402688/71649644-7a8bc980-2d4b-11ea-9a55-8f27ffe8365b.png)

**Comment by skierkowski** [comment]
Sorry about that. Looks like it was probably a copy-paste issue from an editor which replaced the `--` char. Getting it fixed now.

**Comment by ThunderLust102** [comment]
I would like to know what this Amazonaws is about. I have noticed it for a bit now. Its on my phone which my husband has done something.  Because i receive emails with Amazonaws that i cant open. I know nothing about this but just noticed he opened this account. And has beencdoing it for years.  I need help to figure out why i am seeing alot of business info. And just things i knew nothing about

**Comment by medikoo** [comment]
Closing as it was fixed
