### ISSUE TITLE
Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]

### ISSUE THREAD

**Issue by Pi-George** [serverless/serverless#7309]
**Command:**

```
$ sudo serverless invoke local --docker -f function --data '{
    "ranking_mode": "hypergraph",
    "search_engine_device_map": {
        "58": "none",
        "1": "none"
    },
    "feature_item_position_limits": {
        "none": {
            "twitterCards": 3
        }
    },
    "searches": ["810-58-2019-12-10", "954754-1-2018-11-05"],
    "base_urls": ["amazon.com", "moneysupermarket.com"],
    "s3_config": {
        "primary_bucket": "cf-templates-11e3g59cf34bh-eu-west-1",
        "fallback_bucket": "",
        "fallback": false,
        "direct_fallback_tables": []
    }
}'
```

**Response:**

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image...
START RequestId: 54df3406-4847-14c8-0bcb-d73e3c1eb6e8 Version: $LATEST

END RequestId: 54df3406-4847-14c8-0bcb-d73e3c1eb6e8
REPORT RequestId: 54df3406-4847-14c8-0bcb-d73e3c1eb6e8  Init Duration: 439.94 ms        Duration: 1.07 ms       Billed Duration: 100 ms Memory Size: 1536 MBMax Memory Used: 7 MB

{"errorType":"exitError","errorMessage":"RequestId: 54df3406-4847-14c8-0bcb-d73e3c1eb6e8 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}

 Exception -----------------------------------------------

  1

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.19.0
     Framework Version:         1.63.0
     Plugin Version:            3.3.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

Seems to be the same issue as here https://github.com/gkrizek/bash-lambda-layer/issues/3

**Comment by anaynayak** [comment]
My understanding of the issue and the workaround that worked for me for https://github.com/gkrizek/bash-lambda-layer/issues/3:

1. serverless builds a `sls-docker-provided` image which is used in the subsequent step to launch a container via `sls invoke local`.
2. If your project didn't use any layers and you introduce a new layer later, the sls-docker-provided image is not rebuilt. 
3. When you run the invoke command it doesn't find the bootstrap since the sls-docker-provided image doesnt have it.

Steps to fix this issue:
1. rm -rf .serverless/layers/bash/8
2. rm -rf ~/Library/Caches/serverless/invokeLocal/layers/bash/8
3. rm -rf .serverless/invokeLocal/artifact
4. `docker rmi sls-docker-provided` and any related containers
5. Rerun `sls invoke local`
