### ISSUE TITLE
Remove Node.js 6 and Node.js 8 support

### ISSUE THREAD

**Issue by rdsedmundo** [serverless/serverless#7362]
# Feature Proposal

## Description

Both versions have already reached End-of-Life and no longer receive security updates. Supporting those versions, especially 6.x, stops the codebase of leveraging useful features from new ES versions, namely `async..await` for instance.

See: https://github.com/nodejs/Release#end-of-life-releases

Similar or dependent issues:

- #6076 (this targetted Node.js 6 as well, but only deprecated Node.js 4)

**Comment by medikoo** [comment]
Yes we plan to do that with shortly coming v2.0.0 release. I'll keep it open for reference

**Comment by medikoo** [comment]
I've also renamed it to "Remove .. support", as technically we plan to remove support, not just deprecate.

Also as v6 and v8 are EOL'd I think they're naturally assumed as deprecated, I assume it's no point to add some extra warning logs in v1 for that.

**Comment by ronkorving** [comment]
@medikoo Since you refered to this from #7486, which seems to be getting extra attention due to vulnerabilities in dependencies, could you share with us the current timeline for v2? In February you said "shortly". We're not half a year in, so I would just like to ask if there is a more precise time you can share?

**Comment by medikoo** [comment]
@ronkorving I hope we will release v2 within 1 month time frame. Stay tuned

**Comment by ronkorving** [comment]
Thanks for sharing that, good luck!
