### ISSUE TITLE
functionAddress.startsWith is not a function when destinations is used

### ISSUE THREAD

**Issue by Ivan-Strahovsky** [serverless/serverless#7627]
# Bug Report

## Description
When `destinations` property defined in serverless.yml it fails to deploy.

### What did you do?
Add destination to my serverless.yml

### What happened?
`sls deploy` failed with error ` TypeError: functionAddress.startsWith is not a function`

### What should've happened?
Lambda function is deployed.

### What's the content of your `serverless.yml` file?
```yml
service:
  name: my-lambda

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  my-function:
    handler: handler.sqsHannlder
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - TriggerQueue
              - Arn
    destinations:
      onFailure:
        Fn::GetAtt:
          - DeadLetterQueue
          - Arn      
resources:
  Resources:
    TriggerQueue:
      Type: "AWS::SQS::Queue"
    DeadLetterQueue:
      Type: "AWS::SQS::Queue"          
```
            

### What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```stacktrace
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 7155ms
Built at: 04/26/2020 5:20:44 PM
         Asset      Size  Chunks                   Chunk Names
    handler.js  4.51 MiB       0  [emitted]        handler
handler.js.map  1.54 MiB       0  [emitted] [dev]  handler
Entrypoint handler = handler.js handler.js.map
  [0] ./node_modules/aws-sdk/lib/core.js 2.43 KiB {0} [built]
  [1] ./node_modules/aws-sdk/lib/node_loader.js 3.81 KiB {0} [built]
  [2] ./node_modules/aws-sdk/lib/util.js 31.6 KiB {0} [built]
  [4] ./node_modules/aws-sdk/clients/sts.js 573 bytes {0} [built]
  [6] external "fs" 42 bytes {0} [built]
  [8] ./node_modules/aws-sdk/lib/model/shape.js 11.6 KiB {0} [built]
  [9] ./node_modules/aws-sdk/lib/protocol/rest.js 4.45 KiB {0} [built]
 [10] external "stream" 42 bytes {0} [built]
 [23] ./node_modules/aws-sdk/lib/protocol/json.js 2.17 KiB {0} [built]
 [24] ./node_modules/aws-sdk/lib/json/builder.js 1.51 KiB {0} [built]
 [66] ./node_modules/aws-sdk/lib/aws.js 159 bytes {0} [built]
 [67] ./handler.ts 4.93 KiB {0} [built]
[149] ./node_modules/aws-sdk/clients/all.js 8.76 KiB {0} [built]
[893] ./node_modules/source-map-support/register.js 25 bytes {0} [built]
[894] ./node_modules/source-map-support/source-map-support.js 19.3 KiB {0} [built]
    + 890 hidden modules
Serverless: Invoke webpack:package
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
  TypeError: functionAddress.startsWith is not a function
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:604:28
      at AwsCompileFunctions.ensureTargetExecutionPermission (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:611:7)
      at AwsCompileFunctions.memoized [as ensureTargetExecutionPermission] (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:10552:27)
      at AwsCompileFunctions.compileFunctionDestinations (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:587:12)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:555:56
      at ReadStream.<anonymous> (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:465:15)
      at ReadStream.emit (events.js:210:5)
      at ReadStream.EventEmitter.emit (domain.js:475:20)
      at internal/fs/streams.js:218:14
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:555:40
  From previous event:
      at AwsCompileFunctions.compileFunction (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:121:25)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:635:62
  From previous event:
      at AwsCompileFunctions.compileFunctions (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:635:22)
  From previous event:
      at Object.package:compileFunctions [as hook] (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:32:12)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.<anonymous> (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/bin/serverless.js:82:30
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Object.<anonymous> (/Users/ivan.strahovsky/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
      at Module.load (internal/modules/cjs/loader.js:815:32)
      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
      at internal/main/run_main_module.js:17:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.14.0
     Framework Version:         1.66.0
     Plugin Version:            3.6.8
     SDK Version:               2.3.0
     Components Version:        2.30.1
```

If I remove destinations property it works fine. Tried on version 1.68.0 fails with same error.

**Comment by medikoo** [comment]
@Ivan-Strahovsky thanks for report. The issue is in error reporting (which will be fixed once we have https://github.com/serverless/serverless/issues/6562 addressed, with corresponding schema provided).

Currently there's no support for CloudFormation instructions in destinations configuration. It either has to be ARN input literally (or referenced via Serverless variables), or name of a function also deployed with same stack which we want to point

**Comment by Ivan-Strahovsky** [comment]
@medikoo  thanks for the explanation. If I can't use Fn::GetAtt in destinations, it there a way to get ARN of resources created in the same stack, assing it to Serverless variable and use this variable in destinations?

**Comment by medikoo** [comment]
>  there a way to get ARN of resources created in the same stack,

Are they created via `resources.Resources` section?

**Comment by Ivan-Strahovsky** [comment]
> > there a way to get ARN of resources created in the same stack,
> 
> Are they created via `resources.Resources` section?

Yes.

**Comment by medikoo** [comment]
In such case you may assign destinations configuration to lambda via `resources.extensions`. See: https://serverless.com/framework/docs/providers/aws/guide/resources/#aws---resources

**Comment by theipster** [comment]
@medikoo The mention of the word "workaround" here suggests to me there is room for improvement, which is something I'd be happy to try and contribute towards. 😃 

https://github.com/serverless/serverless/blob/c64d6d5f0137add235579274f5fe4e3d343c51cf/lib/plugins/aws/package/compile/functions/index.js#L651-L653

Just so that I've understood this workaround correctly, does the "target function" in the comment here 👆 refer _specifically_ to the use case where the destination target is a Lambda (and in particular, only Lambdas that are managed by the framework)?

In my use case where the destination target is _not_ a Lambda managed by the framework, I can't see where a circular dependency would occur. For context, I'm looking to use an `onFailure` SQS queue, which feels to me like a reasonable DLQ solution that I would also imagine is a common ask (e.g. the example above, as well as https://github.com/serverless/serverless/issues/7492#issuecomment-741687292, both seem to suggest their intention was for a DLQ too).

I think there is room to refactor `ensureTargetExecutionPermission()` in order to reduce the scope and impact of the current workaround. IMO, the benefits of enabling broader support for external targets will massively outweigh any added complexity from handling that single edge case.

WDYT?

**Comment by theipster** [comment]
I've implemented a proof of concept to show what I mean: theipster/serverless#3.

If there's anything I've misunderstood, I'm more than happy to tweak it. 😄

**Comment by medikoo** [comment]
@theipster thanks for refreshing this issue. 

I believe main reason why current we do not support CF instrinsic functions, is because if not lambda is referenced, we need on basis of ARN be able to seclude what type of resource is destination, as we need to setup needed IAM permissions.

I think this requirement may be lifted if service has custom IAM role used (via`provider.role` setting), or we can probably imply some offline resolution of `Ref`, and eventually `Fn::GetAtt` as you propose in PR (still note that we already have reusable resolver for `Ref`: https://github.com/serverless/serverless/blob/8444735295404ca61cac8ec7b5fe500c196a7746/lib/plugins/aws/utils/resolveCfRefValue.js, for`Fn::GetAtt` we may need to introduce one)

**Comment by theipster** [comment]
Thanks @medikoo for the feedback!

At least it sounds like the door is still open, which is good. Would you be happy for me to explore a bit further in this area? For housekeeping, is it worth re-opening this issue, or perhaps create a new one?

I agree it's a good idea to standardise the resolution logic, and I would be happy to contribute towards implementing a `resolveCfGetAttValue()` resolver for general purposes.

However, for this situation, my gut feeling is that if the information is already available such that the resource type can be sufficiently resolved _offline_ (like you say, and like I effectively proposed in my PR), thereby avoiding the coupling and roundtrip overhead of invoking the CloudFormation API, that would be cleaner.

I admit that the offline approach by nature can only be a "best guess" attempt, but I can imagine that many users are defining their resources (or at least, their destination target resources) locally within each stack anyway, with minimal shared infrastructure? Of course, this is a bold and opinionated assumption, so I'm happy to be proven wrong on this. 😅 It would be interesting to see some stats...

Alternatively, we could explore a hybrid approach whereby the initial attempt is done using local resolution, then fallback to API lookup resolution. Obviously, this hybrid solution would add more complexity, but again depending on the usage stats, it may be worth it?

**Comment by theipster** [comment]
Zooming out a bit, there is also a third option: follow the same pattern used by the Lambda `DeadLetterConfig` implementation (i.e. the `onError` property) (see #4120).

For `onError`, when a non-string value is provided, this implies that the framework will _not_ manage permissions on behalf of the user, and therefore the user must enable permissions via other means (e.g. manually declare a `provider.iamRoleStatements` entry).

Funnily enough, from my own experience of implementing a Lambda destination for the first time, my first action was to declare a new entry under `provider.iamRoleStatements`, even before declaring the function's `destinations` property. My point is that from a developer experience perspective, I wasn't expecting the framework to manage permissions on my behalf. This workflow of manually setting the permissions feels ingrained and somewhat natural - or at least, _acceptable_ - to me, because I'm already forced to manage permissions for other resources anyway.

However, I appreciate that this DIY mentality might not align with the general vision and direction of the framework, which is what I'm slowly realising. This can also be evidenced by users raising bug reports (e.g. #4770) expecting the permission to be automatically added. I guess there will always be people in both camps, so it's impossible to please everyone! 😄

But either way, for the sake of completeness, this approach is a potential solution to consider too.

**Comment by medikoo** [comment]
> For housekeeping, is it worth re-opening this issue, or perhaps create a new one?

I'd categorize this one as bug report about flawed error reporting, which was fixed with introduction of schema based validation.

If we want to extend `destinations` configuration support with other formats, let's open a new feature request for it.

>  when a non-string value is provided, this implies that the framework will not manage permissions on behalf of the user

Thanks for pointing this. It was not obvious to me that we already have such convention paved in some places.
We may though make it slightly more strict, e.g. crash if we detect that `iamRoleStatements` is not extended (or at least issue a warning).

Summarizing I propose that we add permissions automatically if that's straightforward and can be done offline. Otherwise allow any recognized CF intrinsic functions input but either throw or show warning (to be discussed) if `iamRoleStatements` is not extended (after we have https://github.com/serverless/serverless/issues/4313 we may require IAM role settings to be extended at function level)

**Comment by oca159** [comment]
> In such case you may assign destinations configuration to lambda via `resources.extensions`. See: https://serverless.com/framework/docs/providers/aws/guide/resources#override-aws-cloudformation-resource

could you please provide an example ?, the documentation is not clear for me

**Comment by ceoworks** [comment]
> If we want to extend destinations configuration support with other formats, let's open a new feature request for it.

@medikoo any update on this?
it is still an issue and it's pretty annoying

**Comment by medikoo** [comment]
@ceoworks no, as no one really requested this feature. If you feel it's valuable, please open feature request (as I stated in linked comment)

**Comment by mbasadi** [comment]
> > In such case you may assign destinations configuration to lambda via `resources.extensions`. See: https://serverless.com/framework/docs/providers/aws/guide/resources#override-aws-cloudformation-resource
> 
> could you please provide an example ?, the documentation is not clear for me

```  
  extensions:
    MyDashfunctionLambdaEvConf:
      Properties:
        DestinationConfig:
          onFailure:
            destinations:
              Fn::GetAtt:
                - DeadLetterQueue
                - Arn
        
 ```

**Comment by medikoo** [comment]
@mbasadi please post in the discussions section an example that doesn't work for you, while you expect it should. Hopefully someone will be able to help

**Comment by metaory** [comment]
simply forming the `arn` works fine:
`onFailure: arn:aws:sqs:${aws:region}:${aws:accountId}:my-queue-dlq`

instead of 
`onFailure: !Ref MyQueueDLQ`
