### ISSUE TITLE
Allow different formats of id in httpApi config

### ISSUE THREAD

**Issue by Michsior14** [serverless/serverless#7791]
### Use case description

Allow different values than plain string in `httpApi.id` property. While the stack creation works perfectly fine with external variables references, the `deploy` fails because `info` [command](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/info/getStackInfo.js#L31) expects the property to be string.

### Proposed solution

Request `ApiGatewayV2.getApi` only if provided id is string or resolve property to plain id and then request aws api.

**Comment by medikoo** [comment]
@Michsior14 looks good! AFAIK for packaging we do not need resolve real HTTP API id, so without issues we should be able to support specific CloudFormation instructions as you proposed.

PR’s welcome!

**Comment by Michsior14** [comment]
@medikoo The only thing that worries me is if we do not set `externalHttpApiEndpoint` then we don't have information about routes created. How should we handle it?

**Comment by medikoo** [comment]
> @medikoo The only thing that worries me is if we do not set externalHttpApiEndpoint then we don't have information about routes created. How should we handle it?

@Michsior14 can you clarify? I think we can get information about created routes from service config (?)

**Comment by Michsior14** [comment]
@medikoo Compare those outputs:

- `stackData.externalHttpApiEndpoint` not set at all in [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/info/getStackInfo.js#L36)
```sh
Service Information
service: sample
stage: dev
region: eu-central-1
stack: sample-dev
resources: 38
api keys:
  None
endpoints:
  None
functions:
  create: sample-dev-create
  delete: sample-dev-delete
  getAll: sample-dev-getAll
  getOne: sample-dev-getOne
  updateOne: sample-dev-updateOne
layers:
  None
```

- `stackData.externalHttpApiEndpoint` set to `/` in [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/info/getStackInfo.js#L36)
```sh
Service Information
service: sample
stage: dev
region: eu-central-1
stack: sample-dev
resources: 38
api keys:
  None
endpoints:
  POST - //sample
  DELETE - //sample/{id}
  GET - //sample
  GET - //sample/{id}
  PATCH - //sample/{id}
functions:
  create: sample-dev-create
  delete: sample-dev-delete
  getAll: sample-dev-getAll
  getOne: sample-dev-getOne
  updateOne: sample-dev-updateOne
layers:
  None
```
As you can see above the endpoints are not visible if the variable is not set. I am not sure if there is anything else that decides if they are shown or not (I don't know the code base that well) and how to tackle this problem.

**Comment by medikoo** [comment]
@Michsior14 I understand that you point that if we start to support CF instructions for external id, then this will break the _info_ endpoints resolution (where we only support HTTP API id provided as literal string)

Yes, that's true. I believe that together with that we need to introduce a CF instruction resolver, that resolves the id from that, so that _info_ functionality remains working

As I think of it, it's only `Fn::ImportValue` that should be supported (or do we have some other valuable cases?) We may prepare a generic `lib/plugins/aws/utils/resolveCfImportValue.js` and rely on it in _info_ when we approach HTTP API id configured that way.

You may take hint from this unmerged branch on how to implement such resolution: https://github.com/serverless/serverless/blob/482f0356af77185594de949d4969e59da39054ed/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L106
