### ISSUE TITLE
Config schema: Define AWS "alexaSkill" function event properties

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8023]
### Use case description

It'll be nice to have `alexaSkill` event fully covered by schema validation

### Proposed solution

Follow up to https://github.com/serverless/serverless/issues/6562, with which only schema placeholder for event was configured.

 Define schema of all `alexaSkill` event properties

Should be done directly in: `lib/plugins/aws/package/compile/events/alexaSkill/index.js`:
https://github.com/serverless/serverless/blob/d403d9c6d3dccdfc9f79d7c42b3cbc1a06fcfac0/lib/plugins/aws/package/compile/events/alexaSkill/index.js#L14-L17

**Comment by pgrzesik** [comment]
Hello :wave: I took a look as I was trying to implement this piece of schema and I noticed that it's an event that is quite different from all the others supported by `serverless` framework in that it also supports configuration via just providing a string `alexaSkill` instead of an object in `events` list in configuration. Looking at `defineFunctionEvent`, it's written in a way that assumes that each event is an object, which poses a question - what is more preferrable here:

1. Extending `defineFunctionEvent` so it supports such configurations
2. Deprecating the support for configuration of `alexaSkill` event without `appId`. It seems like it's only kept at the moment for backwards compatibility but I'm not sure for how long that should be supported

**Comment by medikoo** [comment]
@pgrzesik thanks for pointing. I was quite surprised when I saw that. That's a very good question

I'd say, let's not try to support this format in config schema, as it complicates things too much (and nobody complained about that, while we already issue a warning), and let's add there [deprecation notice](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations), so we can with clean conscience remove support for it in v3
