### ISSUE TITLE
Minor Security/Availability Issue with CI/CD Pipelines

### ISSUE THREAD

**Issue by Frichetten** [serverless/serverless#8061]
Hello, sorry to bug you folks. I apologize in advance if you guys are aware of this, or you're okay with it. I'm not really familiar with your repository or the work you guys do. That being said, your GitHub Actions logs are leaking a pre-signed URL that can be used to clobber whatever data you are storing (doesn't seem sensitive, but could be a nuisance).

Let me explain. If you take a look at your latest [Action](https://github.com/serverless/serverless/runs/954523649?check_suite_focus=true) run, and then open the second drop down ("Resolve last validated commit hash (for `git diff` purposes)"). You'll see that there are two curl requests that are being made.

![Showing Code](https://frichetten.com/images/misc/showing_code.png)

The $PUT_LAST_VALIDATED_COMMIT_HASH_URL variable is masked at the bottom of the picture. However, the curl request was made with `-v` which (obviously) increases the verbosity. It does this so much, it actually spits out the pre-signed URL. 

![Showing URL](https://frichetten.com/images/misc/showing_url.png)

Looking into the rest of the build pipeline, I didn't identify a way someone could do something more malicious, like insert shell commands which may be evaluated later. That being said, someone can still overwrite the hash stored there, or could make continuous requests and upload large files.

**Comment by medikoo** [comment]
@Frichetten great thanks for reporting that! We weren't aware about that, assumed it's not exposed, after all it comes from a secret (e.g. in Travis CI secret strings are masked across any output, it appears logging in GitHub actions is not as bulletproof).

As you pointed it hardly can be harmful, but indeed there's no need for this request to be logged verbosily so we can easily prevent that, will be fixed with follow up commit
