### ISSUE TITLE
Use v8 options to limit memory usage based on Lambda configuration

### ISSUE THREAD

**Issue by patoncrispy** [serverless/serverless#808]
I have no idea if this is possible and am only just starting to dig, so please correct me if I get anything wrong here. Would it be possible for Serverless to limit memory usage when running functions based on the memory size set in s-function.json using the v8 options like `--max-old-space-size` or `--max-executable-size`? I've been using the serverless-offline plugin to test my API and Lambda methods coupled with the amazing dynalite to test DynamoDB integration, but it would be fantastic if there were also some way to test memory limitation requirements without having to deploy to AWS every time.

I would be happy to help with this, but not sure where to start looking or if this is even possible, so if someone with a greater awareness of this could shed some light, I would greatly appreciate it.

**Comment by TheSharpieOne** [comment]
Some things to note when testing locally:
- Memory and CPU are tied together in Lambda. Less memory, less CPU power. So if you are hoping to restrict memory to the bare minimum your function needs, it may increase execution time (and costs).
- Lambda runs nodejs v0.10.36 (you may want to use nvm or something similar to help manage multiple node versions). I for one have been bitten by this, banging my head since everything worked locally, but the native method I was using wasn't added until a later version of node. Not to mention different memory usage and performance.

**Comment by patoncrispy** [comment]
Lambda [pricing structure](https://aws.amazon.com/lambda/pricing/) is a combo of memory usage and computation time (GB-seconds), so ideally I'd like to find a sweet spot where both memory and time limit are as low as possible. 

I've pulled the source code for Serverless and an initial idea would be to run the requested function as a child process, which would allow you to specify Node v8 options... Maybe...

**Comment by patoncrispy** [comment]
Also, thanks for the tip about nodejs versions, @TheSharpieOne. I actually have done as you once did and stick with latest version but that's probably a bit of a naive approach...

**Comment by flomotlik** [comment]
@patoncrispy I don't think we're going to implement this in the core of serveless, as its a niche feature, but if you would like to contribute it as a plugin we'd be interested to take a look. Going to close this issue for now though, let us know if you keep digging into this and have something to share.
