### ISSUE TITLE
Automatically exclude 'aws-sdk' from Node.js lambda bundles

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8096]
### Use case description

Currently we package all service folder unconditionally, eventually excluding dev dependencies. It'll also be good to automatically ignore `node_modules/aws-sdk`  if it's in a project

### Proposed solution

Probably the easiest way is to add `node_modules/aws-sdk/**` exclude rule on top in https://github.com/serverless/serverless/blob/f091c07992a414f2534c9de80caf76faf2744367/lib/plugins/package/lib/packageService.js#L31

**Comment by dashmug** [comment]
@Yogendra0Sharma @medikoo How do we force inclusion of `aws-sdk`?

**Comment by medikoo** [comment]
> @Yogendra0Sharma @medikoo How do we now include aws-sdk in the package?

I believe adding `node_modules/aws-sdk/**` to `package.include` will reset that. Why do you want to include it?

**Comment by dashmug** [comment]
As of this comment, the `aws-sdk` in Lambda runtime is [v2.721.0](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) while `aws-sdk` in npm is [v2.471.0](https://www.npmjs.com/package/aws-sdk).

In most cases, I would also just use the `aws-sdk` in Lambda runtime. I ran into one special case which needed to use a new AWS service at that time (API Gateway websockets) and it wasn't yet available in the `aws-sdk` inside Lambda.

Since then, I have adopted the practice of putting `aws-sdk` as a `devDependency` in my projects and pinned to the version that the runtime provides as the regular case. 

If I needed new SDK versions, I would put it in `dependencies`. This PR has broken the assumption that `dependencies` will always be bundled.

**Comment by medikoo** [comment]
@dashmug great thanks for explanation. I wasn't aware that what's included in Lambda runtime drags that much behind latest.

> If I needed new SDK versions, I would put it in dependencies. 

That's a good point, we'll revert that change (see https://github.com/serverless/serverless/pull/8145 ).

Other thing is, that many devs may put it to dependencies simply for local invocations to work, but for that  probably Framework could ensure an `aws-sdk` that matches given Lambda runtime

Sorry for interruption given change caused.

**Comment by JoshuaAlzate** [comment]
So, what are we suppose to set to exclude the aws-sdk's? The one in the AWS node runtime is enough for my use case.

**Comment by medikoo** [comment]
@JoshuaAlzate best solution is to not install it into `node_modules` but if that's needed for some reason, you can enforce to exclude it via `package.patterns`

**Comment by JoshuaAlzate** [comment]
@medikoo, doesn't it rely on the `serverless-webpack` plugin?

**Comment by medikoo** [comment]
> @medikoo, doesn't it rely on the serverless-webpack plugin?

This plugin is totally unrelated here

**Comment by JoshuaAlzate** [comment]
I've been trying to do this: 

```
package:
 patterns:
   - '!node_modules/@aws-sdk/**'
```

But whenever I run the build command, the `@aws-sdk` is still included.
