### ISSUE TITLE
Remove "slss" binary alias

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8122]
### Use case description

Our `serverless` binary already has `sls` alias. Supporting also `slss` seems confusing, it doesn't seem to bring additional value and doesn't seem to be really used

### Proposed solution

1. [x] In v1 Show deprecation message if `slss` alias is used (Done with #8156)
2. [ ] Remove configuration of `slss` alias in v2 branch

**Comment by crash7** [comment]
@medikoo to clarify, this involves adding the deprecation message and then removing the `slss` command mentioned in the `package.json`:
```
  "bin": {
    "serverless": "./bin/serverless.js",
    "slss": "./bin/serverless.js",
    "sls": "./bin/serverless.js"
  },
```

Apart for that, the only other mention for this is the tabtab completition

Am I missing something?

**Comment by medikoo** [comment]
@crash7 I believe you got it right! In first PR (against `master`) we should just show deprecation. Then after it is merged (into `master` and then `v2`) In v2 branch we should remove deprecation and configuration of it

**Comment by crash7** [comment]
@medikoo thanks for the clarification, added part one on https://github.com/serverless/serverless/pull/8156 but I'm not sure about the log messages. Let me know.

**Comment by delroh** [comment]
What was the original intention of the `slss` alias? The "additional value" it had in my case was to not conflict with Powershell's `sls` alias it has for the `Select-String` command, so I only had to type `slss` instead of `serverless`. 

Coming back to work with serverless, I noticed the `slss` alias is no more while using vscode to develop. Powershell is the default terminal in vscode and so `sls` won't alias to `serverless` unless you manually change the terminal to use cmd or override the `sls` alias somehow.  I have changed vscode's default to be cmd because I'd rather type less characters. Yes I know I am late to say anything here and no I am not asking for it to be brought back. Just thought worth commenting since I thought the `slss` alias existence was because of Powershell.

**Comment by medikoo** [comment]
> What was the original intention of the slss alias?

@delroh great thanks for this comment.

To be honest, original intention was not clear to me. I called for removal of it, just to simplify things, and I felt there's no value on having `slss` when we already have `sls`.

Before doing that, I've asked around and no one had an answer why we support it in first place, and no one I've approached was really relying on it. I've also searched the project history, and was not able to find an answer on that. Hence we simply removed it (with help of a community)

Still, now after it's removal, it's a second voice now, I hear, that signals that  `sls` cannot work in Powershell, and it's why probably `slss` was introduced in first place.

If there's a demand for it, I'll be happy to introduce it back (now understanding it's original purpose). Therefore if you see it as really useful, please open a new issue, explaining the use case. If we have some more extra voices (+1's) we'll definitely put it back :)
