### ISSUE TITLE
Clean up config validation CLI output

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#8205]
The new config validation feature is great, but has a very verbose and hard to understand CLI output which goes against the simplicity of the CLI we have always held as a goal.

Here is what it looks like:

<img width="1453" alt="Screen Shot 2020-09-08 at 10 50 38 PM" src="https://user-images.githubusercontent.com/2752551/92559976-74c57c80-f226-11ea-8f50-78c41db80aec.png">

The issues are:

* Warnings should not be in red, which is a color reserved for errors.
* This language is verbose and contains grammatical errors that make it unclear.  It should be made succinct and clear:
```
Serverless: If you prefer to not continue ensure "configValidationMode: error" in your config
Serverless: If errors are influenced by an external plugin, enquiry at plugin repository so schema extensions are added (https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema)
Serverless: If errors seem invalid, please report at https://github.com/serverless/serverless/issues/new?template=bug_report.md
Serverless: If you find this functionality problematic, you may turn it off with "configValidationMode: off" setting
```
* `outputs` is a supported property and should not throw a warning.

**Proposed Solution:**

* `outputs` should be added as acceptable configuration.
* Simplify configuration validation errors to include, all of this text should be in orange:

```
Serverless:  Configuration Warning:
  at root: unrecognized property 'tenant'

  Learn more about configuration validation here: [insert a short url to docs describing the configuration validation settings]
```

**Comment by medikoo** [comment]
@ac360 thanks for report

> Warnings should not be in red, which is a color reserved for errors.

It actually was configured to look as _orangered_, e.g. it looks like that on my side:

![Screenshot 2020-09-09 at 13 18 46](https://user-images.githubusercontent.com/122434/92604316-ae42ca00-f2b0-11ea-98e9-c722557c36b5.png)

Still it appears, that not all shells support that color, and anyway I agree that introducing another shade is controversial. I've updated it all to _orange_ here: https://github.com/serverless/serverless/pull/8207

> This language is verbose and contains grammatical errors that make it unclear

As proposed I've moved notes to website docs at #8207, can you review the page content: https://github.com/serverless/serverless/pull/8207/files#diff-5492f2b42438d45ea110534cea664044 ? (@garethmcc can you also review that one?)

> `outputs` is a supported property and should not throw a warning.

Fixed in https://github.com/serverless/enterprise-plugin/pull/494
