### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by B-Scan** [serverless/serverless#83]
First, awesome work guys!

I've been trying out JAWS and at the beginning was a bit hard to debug what are the errors that AWS API  Gateway returns. 

Since `context.fail` expects a message (string) and all examples (sign in, signup...) are returning an object [1], as a response you usually get something like:

```
{
  "errorMessage": "[object Object]"
}
```

[1] Example error thrown:
```
{
      status: 401,
      message: 'Invalid login credentials'
}
```

Temporarily I changed some of the functions to return a string instead of object (e.g. `401: Invalid login credentials`). With that I'm able to use "Integration response" that uses lambda regex and on the end returns proper response.

Also a mapping template like this:
```
{
    "error" : $input.json('$.errorMessage'),
    "status" : 401
}
```

This seems like an ugly hack. Is there any other way to do this? Like with using the error model lambda has or anything else? Otherwise, it is obviously a limitation on AWS' side.

**Comment by ac360** [comment]
@B-Scan This is something I need to research as well, but have been too busy working on other components for JAWS v1.

With your mapping template approach, are you able to get API Gateway to return the same HTTP response code?  I believe you must return an error string to trigger the lambda error regex and render the right status code, correct?  It's been about a month since I've looked into this issue, so I'm a bit rusty.

@B-Scan If you find a good solution for this, please put it in here. :+1:

**Comment by B-Scan** [comment]
@ac360 yes, with setting custom integration response that was triggered with lambda error regex, I was able to get the right status code.

I posted a [thread](https://forums.aws.amazon.com/thread.jspa?threadID=215388) on AWS forum to see is there any other way to return an object instead of a string for errors. If not, I can make some changes and submit a PR with string only version. If you are happy with that.

**Comment by mumoshu** [comment]
@B-Scan @ac360 Hi. I've had the same issue and here's the workaround I use:

In your lambda function:, use:

```
context.fail(JSON.stringify(error));
# Instead of:
# context.fail(error);
```

For your integration response's Lambda Error Regex and Method response status, use:

* `\{"status":4.*` => 400
* `\{"status":5.*` => 500
* and so on...

It works as far as the `status` is the first property in the error object.

Finally, in your integration response's mapping template, use:

```
$input.path('$.errorMessage')
```

Very ugly and incomplete, but now you can pass your error as is from lambda to API gateway's HTTP response body.

**Comment by ialmetwally** [comment]
is there anyway to put the Lambda Error Regex in the s_function.json?

**Comment by iongion** [comment]
I have the same question as @ialmetwally - where is this to be placed ? what do you place in there ?
```
...
         "responses": {
           "400": {
             "statusCode": "400"
           },
           "default": {
             "statusCode": "200",
             "responseParameters": {},
             "responseModels": {},
             "responseTemplates": {
               "application/json": "IT GOES HERE"
             }
           }
         }
....
```

**Comment by ialmetwally** [comment]
@iongion I found out how to do it

"404" : {
              "selectionPattern" : "pattern_here",
              "statusCode": "404"
            }

**Comment by iongion** [comment]
@ialmetwally I do not understand, I see no response template velocity stuff, do you have a complete s-function.json ?

**Comment by ialmetwally** [comment]
@iongion I just put the statusCode, you can add the rest of params inside the same object  

"404" : {
"selectionPattern" : "pattern_here",
"statusCode": "404"
}

or

"pattern_here" : {
"statusCode": "404"
"responseParameters": {},
             "responseModels": {},
             "responseTemplates": {
               "application/json": "IT GOES HERE"
             }
}

**Comment by iongion** [comment]
@ialmetwally awesome !!!

**Comment by iongion** [comment]
To be able to have my own custom error responses with at least a 400 error status code I do the following:

- in case of error, from the lambda I return an expected Error object
```
var fault = { type: 'api', message: 'could not continue', detail: 'not-allowed', code: 4332 };
var error = new Error(JSON.stringify({ status: 'failure', fault: fault }));
context.fail(error);
```
- then my s-function.json I have the responses section as following:
```
...
       "responses": {
         "400": {
           "selectionPattern": "(.|\\n)*\\\"status\\\"\\:\\s*\\n*\\s*\\\"failure\\\"(.|\\n)*",
           "statusCode": "400",
           "responseParameters": {},
           "responseModels": {},
           "responseTemplates": {
             "application/json": "#set($inputRoot = $input.path('$.errorMessage'))\n$inputRoot"
           }
         },
         "default": {
           "statusCode": "200",
           "responseParameters": {},
           "responseModels": {},
           "responseTemplates": {
           }
         }
       }
...
```

- This means that whenever a complete match of `errorMessage` value is found against this regex:
```
(.|\n)*\"status\"\:\s*\n*\s*\"failure\"(.|\n)*
```
- Then the response should be the `$input.path('$.errorMessage')`, but the `$.errorMessage` coresponds to the unserialized JSON string that was passed to the `Error` constructor
- This should result in an error object that is returned to the client which looks like this:
```
{
  status: 'failure', 
  fault: { 
    type: 'api', 
    message: 'could not continue', 
    detail: 'not-allowed', 
    code: 4332
  }
}
```
which is awesome.

Now, the problem is that the `s-function.json` configuration is not loaded at API Gateway configuration, the integration response has no 400 handling defined, how did you get that loaded by API Gateway ?

**Comment by andela-tolotin** [comment]
My take on time is to find a way to pass `context.fail` with a string value
