### ISSUE TITLE
Incorrect schema for AWS tags

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8304]
It was reported at Slack, that tags with format as below are rejected:

```yaml
tags:
    "mycompany:team": myteam
    "mycompany:service": ${self:service}
```

Current schema definition is:

https://github.com/serverless/serverless/blob/8c4d97211aa3dd4c41d9205a3ca0ccaab3564225/lib/plugins/aws/provider/awsProvider.js#L364-L369

and indeed _key_ pattern seems to not allow `:`, which seems not correct. Also I think _value_ can be any string (at least I do not see any restriction documented on AWS side), so probably `pattern` should be removed there.

I'd follow closely restrictions as described here: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html

(cc @fredericbarthelet )

**Comment by jproberts** [comment]
@medikoo Sorry, it's not entirely clear to me whether you're referring to tags on the Cloudformation stack or the Lambda functions. The snippet you provided is labeled `awsResourceTags` so I think this might actually be the better resource to follow: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html .

Notably, as seen in the [Properties section](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html#w2ab1c34c10d264c13c17), resource tags do not need to contain a value and have a restricted character set.

However, the character set listed doesn't include `:`, which is strange since that goes against the initial bug report. Maybe that should be added to their documentation, since it's clearly supported (at least internally) with `aws:*` tags.

I've been using the project recently, but I'm not familiar with the codebase and schemas to say how this new information changes things. It seemed worth calling out though.

**Comment by dashmug** [comment]
@medikoo I can confirm that there is no pattern restriction on the value for a tag. 

<img width="479" alt="Screen Shot 2020-10-01 at 9 33 15 am" src="https://user-images.githubusercontent.com/1972844/94751266-73bde000-03cb-11eb-9707-0a03e501364d.png">

**Comment by dashmug** [comment]
As @jproberts pointed out, it is strange that the User Guide contradicts the API Reference. I tend to believe that the API Reference is auto-generated from code (or from comments in the code) so it is probably better than the User Guide.

**Comment by jproberts** [comment]
@dashmug Good call, I hadn't realized I was looking at a User Guide vs an API Reference.

I do think those links are referring to two different things though. The difference seems to come down to stack tags requiring a value, while resource tags make them optional. (The API Reference for resource tags doesn't show any character restrictions)  Intuitively, you would expect the two types be the same, but that doesn't appear to be the case. I don't think it affects the fix, but the distinction may be important for future development referencing the issue or possibly reveal other issues with the current implementation.

Stack Tag API Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html
Resource Tag API Reference: https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_Tag.html

**Comment by medikoo** [comment]
Thanks @jproberts for sharing other resource.

My assumption is that User guide provides more validation details (which are missing form API doc), however I think it contains an error when detailing rules for _value_, they seem copied from _key_, and that's probably copy/paste error.

In light of above I'd:
- Fix _pattern_ for _key_, so it closely follows one outlined at user guide
- Do not impose any _pattern_ for _value_

**Comment by rohit-gohri** [comment]
Whitespace is also not allowed currently by `serverless` even though AWS allows it.

```
  Serverless Error ---------------------------------------

  Configuration error at 'provider.tags': unrecognized property 'Cost Center'
```

**Comment by medikoo** [comment]
@rohit-gohri please open a new issue that reports that
