### ISSUE TITLE
Support CloudFront CachePolicy

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8317]
### Use case description

Currently Framework relies on deprecated [`ForwardedValues`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-forwardedvalues.html):

https://github.com/serverless/serverless/blob/dd9a011f6073d33db9043f102e0cce84743a8a6b/lib/plugins/aws/package/compile/events/cloudFront/index.js#L294-L296

We should rely on [Cache Policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-cachepolicy.html) instead

### Proposed solution

- Deprecate `functions[].events[].cloudfront.behavior.ForwardedValues`
- If there's no `functions[].events[].cloudfront.behavior.ForwardedValues` provided, do not set default `ForwardedValues`, but if needed (to be investigated) introduce cache policy
- Allow to introduce/customize cache policy (to be specified)

**Comment by fredericbarthelet** [comment]
## Default

Regarding the replacement of the default `ForwardedValues.QueryString` parameter :

- current cloudFront event includes setting `ForwardedValues.QueryString` to false if no override is specified.
- if you specify false for `QueryString`, CloudFront doesn't forward any query string parameters to the origin, and doesn't cache based on query string parameters - *from [Cloudfront ForwardedValues documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-forwardedvalues.html#cfn-cloudfront-distribution-forwardedvalues-querystring)*
- in order to prevent cloudFront to send queryStrings to the origin, you should add a CachePolicy with a QueryStringConfig including the parameter `QueryStringBehavior` to `'none'`- *from [Cloudfront QueryStringConfig documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachepolicy-querystringsconfig.html#cfn-cloudfront-cachepolicy-querystringsconfig-querystringbehavior)*

### Important note

The documentation does not say anything about it, but you're actually required to create a Cache Policy and reference it using `CachePolicyId` field within CacheBehavior configuration if you're not using any of the now deprecated fields (DefaultTTL, MinTTL, MaxTTL, ForwardedValues). Trying to create a CloudFront distribution without those deprecated fields and without a cache policy referenced will actually trigger an error

![image](https://user-images.githubusercontent.com/23530626/95662820-eb151180-0b39-11eb-8b80-467329476694.png)

You can also observe this behavior in this issue : https://github.com/aws/aws-sdk-js/issues/3388#issuecomment-672856138 

Specifying both a CachePolicyId, and any of the deprecated fields `MinTTL`, `MaxTTL`, `DefaultTTL` and `ForwardedValues` results in referenced Cache Policy being used and the deprecated fields ignored.

- In order to ensure backward compatibility, I ensured default Cache policy being used only if those fields are not present.
- I also implement a throw if both `cachePolicy` described bellow is used when one the above deprecated fields is found in `behavior`.

### Proposed default Cache policy

In order to reference a default cache policy, I suggest using one of the new [managed Cache Policy](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-policies-list) : **Managed-CachingOptimized**.
This policy does not forward query strings (current behavior).

## CachePolicy customization

As for the Cache Policy specs, I followed an implementation similar to httpApi authorizers.
A new `provider.cloudFront.cachePolicies` key allows the user to specify an object which keys are names and corresponding values custom CachePolicy. When specified, a new `AWS::CloudFront::CachePolicy` will be created with the corresponding definition, and it will be attached to the cloudfront distribution using the [`CachePolicyId` property of the AWS::CloudFront::Distribution CacheBehavior
](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-cachepolicyid).

Then, using `events[].cloudFront.cachePolicy` key with either an `id` or `name` property, the corresponding cache policy can be attached to the behavior. `id` should be used for AWS managed policies. `name` can be used to reference user defined policies in the provider section.

**Comment by medikoo** [comment]
@fredericbarthelet that's excellent insight. Thanks for all the details, proposal looks really good. I will look into PR shortly
