### ISSUE TITLE
V0.5 - Existing Project On Project Init Stage Prompt Repeating Input

### ISSUE THREAD

**Issue by ac360** [serverless/serverless#834]
When initializing an existing project, ProjectInit calls StageCreate, which prompts the user for a stage name.  When the user types a letter, it is repeated twice.  Can't track the source of this down.

**Comment by HyperBrain** [comment]
I tried to reproduce the issue on my Windows machine but was not able to see the repeated characters.
Maybe it is related to Unix shells only.

**Comment by ajagnanan** [comment]
This happened to me on a mac. `dev` ends up being `ddeevv` for stage create.

**Comment by nirmalgoswami** [comment]
This happened to me also

**Comment by eahefnawy** [comment]
woah! I've seen this bug way ago back in the days with JAWS, but it mathematically disappeared. I've done some research back then and now, and it seems to be a bug in the prompt module. A certain combination of prompts in a certain order produces this bug.

In this case, this bug only appears when we prompt for stage name after we prompt to choose whether we want to create a stage or not (I confirmed this by commenting out the "do u want to create a stage" prompt), However, for some reason if we prompt for a project name before all that (like in ProjectCreate), we don't see that bug. It's a little strange.

I've tried to eliminate this bug without removing prompts with no luck. We need all those prompts for best UX. So I think the best thing to do here is to just always prompt for a project name whether it's projectCreate or projectInit. We used to do that initially (which is why we didnt see this bug on projectInit before), but I guess we thought it'd offer a better user experience to auto populate the project name on projectInit since we already have it. But this bug makes it really hard to create a stage for the project, which is essential.

**Comment by AlperKarapinar** [comment]
on next stage, profile select stage, still we have double input (i have 4 profiles, but i can only choose first and third profiles, because it jumps). same behaviour on region select.

**Comment by ac360** [comment]
@eahefnawy We can't rename existing projects.  This confuses teams collaborating on the same project.  Also, we can't upgrade prompt at this time because their new major release has lots of breaking changes.  Instead, this bug must be fixed.

**Comment by eahefnawy** [comment]
We've looked into this and it seems that it's caused by a deeper issue. Will open a separate issue for that
