### ISSUE TITLE
Consider dropping autocomplete (tab tab) support

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8473]
### Use case description

It's a feature that doesn't seem to work well, and it's unlikely many s are using it, while attributes to technical debt

### Proposed solution

Simply remove all it's related  implementation located at following locations:

- https://github.com/serverless/serverless/blob/c0a2ecf453fa82d46bf2fda34708864bc440203d/scripts/serverless.js#L11-L14
- https://github.com/serverless/serverless/tree/c0a2ecf453fa82d46bf2fda34708864bc440203d/lib/utils/tabCompletion
- https://github.com/serverless/serverless/blob/c0a2ecf453fa82d46bf2fda34708864bc440203d/lib/plugins/interactiveCli/tabCompletion.js
- https://github.com/serverless/serverless/blob/c0a2ecf453fa82d46bf2fda34708864bc440203d/lib/plugins/config/config.js#L51-L77

**Comment by sblask** [comment]
It just took me half an hour to figure out how to get completions to work. If it's unlikely that they are used it's probably because of that. They should not be dropped, but improved instead. They should  just work and it should be documented how to get them to work as part of the quickstart.

**Comment by medikoo** [comment]
> It just took me half an hour to figure out how to get completions to work.

@sblask Thanks for feedback. I understand that it was not clear that you can setup it with `serverless config tabcompletion`, and once you've found it, you've managed to configure it quickly?

Autocompletion setup is also part of interactive setup (which could be invoked via `serverless`)

Once configured do they work for you as intended?

**Comment by sblask** [comment]
Yes, it wasn't clear and Google didn't bring it up either. I think tab completion is not super common a name or it's just me. I searched for shell completion or ZSH completion and only ended up on old articles or issues long closed so I thought it was abandoned. Then I found `serverless config tabcompletion` but it didn't work for me either. Being a ZSH user it still only installed completions for bash by default which still didn't work for some reason when I just started bash from me shell. When I looked at the code I got even more confused because it pointed to `.zsh` files in `~/.config/...`. And then I stumbled upon this issue and I saw there is a command line flag you have to pass for the right shell. So adding `--shell zsh` did the trick. Now it works as expected in ZSH. A bit slow, but good enough.

What's the interactive setup, running `serverless config`? I think I did that, but I am working on an existing project with all files in place already, so maybe not. Running it again didn't do anything.

**Comment by medikoo** [comment]
@sblask great thanks for that feedback! We'll think how we can improve that, definitely we need better documentation.

>What's the interactive setup, running serverless config?

It's when you input just `serverless`, still once you have completion setup it obviously won't propose its setup

**Comment by gerbenoostra** [comment]
Best to update the documentation about the `--shell zsh` , because if one runs `serverless config tbcompletion install` from a zsh, it still only installs the bash autocompletion.

**Comment by medikoo** [comment]
@gerbenoostra suggestions are welcome, how would you improve it?

**Comment by medikoo** [comment]
Internally we've agreed to remove this feature completely, main reason is that `tabtab` package is no longer maintained and shares security issues (see https://github.com/serverless/serverless/issues/10182).
Additionally currently this functionality performs poor due to slow command startup time (this will be fixed at some point, but ETA is unknown)

It'll stay as is in v2, but starting from v3 release tab autocompletion support will be gone

**Comment by medikoo** [comment]
Closing as functionality was removed with #10414
