### ISSUE TITLE
`TypeError: Cannot convert undefined or null to object` when defining validation schema via `defineFunctionEventProperties`

### ISSUE THREAD

**Issue by DianaIonita** [serverless/serverless#8485]
## Description

I am updating a plugin with a validation schema and trying to hook it up to the serverless framework. The code I am using:

```
const schema = {
  type: 'object',
  properties: {
    someProperty: {
      type: 'object',
      properties: {
        otherPropertyOne: { type: 'number' },
        otherPropertyTwo: { type: 'number' }
      }
    }
  }
}
this.serverless.configSchemaHandler.defineFunctionEventProperties('aws', 'http', schema);
```

The serverless framework fails with stack trace:
```
TypeError: Cannot convert undefined or null to object
      at Function.assign (<anonymous>)
      at addPropertiesToSchema (C:\path\node_modules\serverless\lib\classes\ConfigSchemaHandler\index.js:275:33)
      at ConfigSchemaHandler.defineFunctionEventProperties (C:\path\node_modules\serverless\lib\classes\ConfigSchemaHandler\index.js:235:5)
      at MyPlugin.defineValidationSchema (C:\path\node_modules\my-plugin\src\my-plugin.js:59:41)
      at new MyPlugin (C:\path\node_modules\my-plugin\src\my-plugin.js:18:10)
      at PluginManager.addPlugin (C:\path\node_modules\serverless\lib\classes\PluginManager.js:94:28)
[...]
```

## Debug info

I managed to trace the issue to the code which selects the function event definition:

![image](https://user-images.githubusercontent.com/2750493/98445503-fd21aa00-210f-11eb-977c-3d7aa7e12c32.png)

Which results in `subSchema.properties` being `undefined`:

![image](https://user-images.githubusercontent.com/2750493/98445522-16c2f180-2110-11eb-9644-4e586e9c87e8.png)

<b>Installed version</b>

```
Framework Core: 2.11.0 (local)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

**Comment by fredericbarthelet** [comment]
@DianaIonita thanks for reporting this issue.
Indeed, some AWS events JSON schema definition are not straight `'object'` JSON schema definitions.
Going over the existing schemas :

✅ OK, `defineFunctionEventProperties` will work as expected, only `'object'` defined as event root definition
❌ KO, `defineFunctionEventProperties` will crash, root definition is not an `'object'` definition

- alb ✅ 
- alexaSkill ❌ - anyOf `'string'` or `'object'`
- alexaSmartHome ❌ - anyOf `'string'` or `'object'`
- http ❌ - anyOf `'string'` or `'object'`
- cloudFront ✅ 
- cloudwatchEvent ✅ 
- cloudwatchLog ❌ - anyOf `'string'` or `'object'`
- cognitoUserPool ✅ 
- eventBridge ✅ 
- httpApi ❌ - anyOf `'string'` or `'object'`
- iot ✅ 
- msk ✅ 
- s3 ❌ - anyOf `'string'` or `'object'`
- schedule ❌ - anyOf `'string'` or `'object'`
- sns ❌ - anyOf `'string'` or `'object'`
- sqs ❌ - anyOf `'string'` or `'object'`
- stream ❌ - anyOf `'string'` or `'object'`
- websocket ❌ - anyOf `'string'` or `'object'`

@medikoo I implemented a fix to this issue. It should convert all ❌ to ✅ in the previous list.
However it does not prevent futur fails for JSON schema definition not yet included in the existing events (array for exemple, or the use of `oneOf` instead of `anyOf`). WDYT ?
