### ISSUE TITLE
Inconsistent error checking in 'serverless function create' command

### ISSUE THREAD

**Issue by jbharper86** [serverless/serverless#854]
I'm using version 0.5.

Running the following command fails when entering the function name because path separators aren't allowed.

```
serverless function create
Serverless: Enter a new function name:  abc/xyz
error:   Function name must contain only letters, numbers, hyphens, or underscores. It should not be longer than 20 characters.
```

However, if the function name is specified as part of the command then the error check is skipped and the user is allowed to select a runtime.

```
serverless function create abc/xyz
Serverless: Please, select a runtime for this new Function
  > nodejs
    python2.7
```

**Comment by HyperBrain** [comment]
In the second case `function create abc/xyz` the function `xyz` will be created in folder `abc`.
I agree that the first approach should lead to the same result (folder+function).

**Comment by HyperBrain** [comment]
@eahefnawy @ac360 I checked the code. If a path is given (case 2 above) it is parsed and the folder structure is created correctly. If `function create` is called without any parameter (interactive mode) it prompts for the function name and validates that in the Function object's validateName() by matching the allowed function name regex. In this case no path is set at all. That's why case 1 does not work as expected.
There are two valid solutions for the problem:
(1) Prompt for an optional path additionally to the function name
(2) Disallow calling function create without path
Solution (1) seems more consistent to me.

**Comment by eahefnawy** [comment]
@HyperBrain what you've mentioned is correct, but it's actually by design. The reason is that if you don't provide a function **path**, you'll be prompted for a function name, *and then the function will be created in the cwd*. I believe this is an enhancement in itself because we want to give the user the ability to create functions by traversing the file tree (rather than having to always remember the function path).

So now users have two options, either provide a function path directly, or provide a function name but in that case the function will be created in the cwd. So there's a distinction between function path and function name.

I hope this makes sense, what you think about all this? :blush:

**Comment by HyperBrain** [comment]
What we could do, is to add a hint in the SCI before the function name prompt that just tells that the function will be created in CWD. Then it should be clear to everyone without having to change the implementation.

**Comment by eahefnawy** [comment]
@HyperBrain woaah! Definitely! How did we miss this! :smile: ... Just added it!
