### ISSUE TITLE
v0.5 - function logs -t ignores declared function

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#878]
Executed (cwd is project root):
`$sls function logs -s [stage] -r [region] -i 500 -t [functionName]`

Expected: logs for the declared function (`[functionName]`).

Observed:
```
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

ServerlessError: You must be in a function folder to run this command
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionLogs._validateAndPrepare (/usr/local/lib/node_modules/serverless/lib/actions/FunctionLogs.js:110:17)
From previous event:
    at FunctionLogs.functionLogs (/usr/local/lib/node_modules/serverless/lib/actions/FunctionLogs.js:95:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:181:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:180:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:178:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:424:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:393:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by erikerikson** [comment]
Probably the command expects something after -t

**Comment by erikerikson** [comment]
^ confirmed

**Comment by HyperBrain** [comment]
Shouldn't have to do anything with the *tail* option (use that regularly here), but just the lack of asking the project for the function when you're out of the function's folder.

**Comment by HyperBrain** [comment]
@erikerikson I tried a bit and found the problem. If you put the parameters behind the function name it works as expected.
```
serverless function logs testfct -t -s dev -r us-east-1 -i 500
```

**Comment by HyperBrain** [comment]
Nevertheless I agree that the error message is a bit misleading here

**Comment by erikerikson** [comment]
Yeah, I traced in and confirmed that the -t argument had my
"[functionName]" as its value while the name argument was undefined.

**Comment by HyperBrain** [comment]
It seems to be a problem introduced "by design". The `-t, --tail` option semantically is a boolean option where its sole existence should define the value. The given command line is parsed by `minimist` in the first place which without configured explicitly will put the option/value pairs into a map and add the found parameters into the `_` array (see `bin/serverless`). It does not make any difference about the option types (boolean or with value).
@eahefnawy I see a more sophisticated option parsing here that could solve these problems:
(1) `bin/serverless` should only parse the _action_ and _command_
(2) The `Serverless` object that gets the actual command/action config (including options and parameters) should use `minimist` a second time to parse the specific _action_/_command_ parameters that could be defines in the action's configuration in more detail, i.e. add an `optionType` to the option declaration that would allow having explicit boolean options.

What do you think about that approach?

**Comment by HyperBrain** [comment]
@minibikini Forgot to mention you here as assignee ;-)

**Comment by eahefnawy** [comment]
@HyperBrain thanks for thinking this through, I agree this is an issue, however I personally think it's very very specific issue (happens whenever there's a boolean option right before a parameter) and easy to avoid. I'm not sure it's worth adding an extra `optionType` (which I'm guessing is critical for the fix) for all our actions configuration.

cc @ac360

**Comment by minibikini** [comment]
This seems like a big change, maybe even a breaking one (for the plugin authors), but with a little benefit. I'm agree with @eahefnawy that it doesn't worth it.

**Comment by flomotlik** [comment]
As part of V1 we're also looking into better CLI frameworks to build on top of so we won't run into this specific issue any more.
