### ISSUE TITLE
resource output values not updating upon running sls resources remove then sls resources deploy.

### ISSUE THREAD

**Issue by neostorm** [serverless/serverless#886]
```
sls project create  (serverless-bug-test, Existing Profile, default, us-east-1)
cd serverless-bug-test
```
Edit s-resources-cf.json add the following to output.
```
,
    "testOutput": {
      "Description": "ARN of the lambda IAM role",
      "Value": {
        "Fn::GetAtt": [
          "IamRoleLambda",
          "Arn"
        ]
      }
    }
```
```
cat _meta/variables/s-variables-dev-useast1.json 
sls resources deploy -s dev
```
No resource updates (this does not appear to be correct as diff shows changes).
```
sls resources remove
sls resources deploy -s dev
cat _meta/variables/s-variables-dev-useast1.json
``` 
You should now see your output variable and both arns the same.

```
sls resources remove
sls resources deploy -s dev
```
You should now see that the lambda was updated but testOutput is not updated.

**Comment by Christoph-Schabert** [comment]
+1  i have the same problem 
<img width="911" alt="bildschirmfoto 2016-03-26 um 09 33 26" src="https://cloud.githubusercontent.com/assets/5402091/14059072/0f0aef4a-f336-11e5-8af6-8e5f4645440b.png">

**Comment by c-knowles** [comment]
At least some of that may be explained by AWS not updating CloudFormation stacks if just the Outputs are changed. If you add an output to your project, run `sls resources deploy -c` so the resources get updated by not deployed, then try to run the resulting CloudFormation template inside `_meta` into the AWS console directly you will also receive a message about no resources to update. I've hit the same issue several times before, suggest you also report to AWS. I'm not sure serverless can do much to avoid that part apart from perhaps doing a remove and redeploy.

@neostorm in your flow, I think this is happening:
1. After you edit the s-resources-cf.json to add the `testOutput`, the `cat` command will only reveal something new after the `sls resources deploy` since that is the bit that joins all your relevant sls files together to form the CloudFormation inside `_meta`
2. The first `resources deploy` will not do anything despite the sls diff due to the above mentioned AWS issue
3. After your first `sls resources remove`, the stack has been deleted so it will be completely recreated with your new output
4. The very last bit of the lambda `testOutput` not being updated does sound like a potential bug, I would suggest running with `--debug` enabled

To confirm the above, try this order:
```
sls project create  (serverless-bug-test, Existing Profile, default, us-east-1)
cd serverless-bug-test
Edit s-resources-cf.json to add output
sls resources deploy -s dev # no updates due to AWS issue above
cat _meta/variables/s-variables-dev-useast1.json # should still see the new output definition if sls is generating correctly
sls resources diff # should show your changes
sls resources remove
sls resources deploy -s dev
sls resources diff # should be the same now
```

**Comment by neostorm** [comment]
I want to point out there are two different problems here. I only mentioned the deploy / resources diff issue as it takes place in the middle of reproducing the actual problem. @c-knowles 

The real issue is that when sls resources deploy is ran for a 2nd time after a remove. It does not refresh all of the output values already stored in the _meta/variables/s-variables-dev-useast1.json file. In this case the testOutput variable does not get updated. It will update IamRoleLambda but not testOutput. What this proves is that while both of them should always return the same arn. When you run remove then deploy it for the 2nd time. It appears to only updated the value of IamRoleLambda leaving the testOutput value unchanged to the new arn.

**Comment by BlueBlock** [comment]
I have a fix for this that I'll be submitting.
