### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by brettneese** [serverless/serverless#895]
When I deploy my function and attempt to "test" it in the AWS console, I get:

```  
"errorMessage": "Cannot find module 'slack-node'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._resolveFilename (module.js:338:15)",
    "Function.Module._load (module.js:280:25)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)",
    "Object.<anonymous> (/var/task/handler.js:3:13)",
    "Module._compile (module.js:456:26)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)"
  ]
}
```

It's in my package.json and I've NPM-installed it locally; have tried redeploying several times. Am I including it wrongly, or something?

**Comment by joostfarla** [comment]
@brettneese Is the `package.json` file in your function dir? Otherwise these dependencies won't be included in the deployment package by default. You can modify the `handler` property to change this. You can read more here: https://serverless.readme.io/docs/function-configuration (Chapter "The Handler Property Is Very Flexible")

**Comment by brettneese** [comment]
Yep, that was it! 

Also: really cool. 

Closing.
