### ISSUE TITLE
not skipping deployment because of aws permissions

### ISSUE THREAD

**Issue by trigaut** [serverless/serverless#8993]
The issue is related to the AWS plugin.
If your deployment user does not have the permission `lambda:GetFunction`,
and if you deploy twice the same Serverless stack on AWS without changing anything, the deployment won't be skipped.

This is because Serverless is not able to get the last modified date of the already deployed Lambdas.
The problem is that `getFunctionsEarliestLastModifiedDate` fails silently.

https://github.com/serverless/serverless/blob/13444caa28a5fdb268599c8fa67f4bfef1dd5e36/lib/plugins/aws/deploy/lib/checkForChanges.js#L90-L99

If appears that the request `getFunction` returns a 404 when the function is not found and a 403 when the user does not have the permissions.

Should'nt we improve the error catch of `getFunctionsEarliestLastModifiedDate` to warn that permissions are missing to be able to skip deployments ?

**Comment by pgrzesik** [comment]
Hello @trigaut :wave: Thanks a lot for reporting. This is a great catch and I believe we should definitely emit a warning in such a situation to highlight to the developer that they don't have proper permission instead of blindly assuming the function doesn't exist which forces new deployment. 

We'd be happy to accept a PR for this one :raised_hands:
