### ISSUE TITLE
`sls function run` local execution is broken

### ISSUE THREAD

**Issue by leslie-fugue** [serverless/serverless#902]
Using v0.5.1, when I run `sls function run` in a function directory with no parameters, it prompts me to choose one of my stages. The [documentation](http://docs.serverless.com/docs/function-run) says it should execute the function locally, and this used to work in v0.4.

**Comment by ac360** [comment]
Hi @leslie-fugue - We've changed how ENV vars work in `V0.5`.  The reason it prompts you for a stage is only because it wants to know which stage's ENV vars to use when you run your function locally.  If you want to run your function remotely, just add the `-d` flag.  

Thanks for using the Framework :)

**Comment by c-knowles** [comment]
Maybe the CLI message and/or documentation could be improved for this? It's definitely a bit confusing currently.

**Comment by eahefnawy** [comment]
👍
