### ISSUE TITLE
ignoring everything in `_meta` prevents team dev

### ISSUE THREAD

**Issue by doapp-ryanp** [serverless/serverless#928]
With the release of `v0.5` the `_meta` dir has been [added back](https://github.com/serverless/serverless/pull/720) to `.gitignore` on project create (and `serverless project install serverless-starter`).

I am aware that env vars are no longer forced to be stored in S3 (which is cool) however blanket `_meta` ignore prevents teams from collaboratively working on stages within a serverless project.

Pre `v.0.5`, my [PR](https://github.com/serverless/serverless/pull/684/files) in https://github.com/serverless/serverless/issues/564 addressed this issue by using convention (over configuration) to selectively ignore any stage that started with `dev`.

Even though sls no longer auto-creates the `dev` stage, there still needs to be a way for teams of devs to indicate what assets in meta need to be committed to version control, and what should not.

I propose we solve this issue again with convention over configuration:

-  `_meta/variables` dir is always ignored. API keys, pws etc should never be in version control
-  files inside `_meta/resouces` that start with `dev` should be ignored. This is the convention any serverless developer can use to clearly indicate this stage is not to be shared with others.

The resulting modifications to the `.gitignore` would look like:
```
...
_meta/variables
_meta/resouces/*-dev*
```  

As an aside [serverless-meta-sync](https://github.com/serverless/serverless-meta-sync) solves the collaborative dev for env vars.  I think it would be a mistake to make this proj also sync non env var stuff as IMO non var stuff in `_meta` that teams need to collaborate should be in version control

I have to admit I'm just starting to research `v0.5.1` so I wan't to make sure I am not missing something before I make a PR.

**Comment by doapp-ryanp** [comment]
I just realized there is a `_tmp` dir under `_meta` as well.  PR coming soon

**Comment by erikerikson** [comment]
Because of our security consciousness we check in all of _meta (_meta/_tmp being deleted).  To do this securely, we only check in references to our secure items and then load them from secure locations via secure mechanisms.  A less secure means is to encrypt the items before they go into your lambda package and securely obtain the key with which to decrypt them for use.

Are your devs unable to download and unzip the lambda code?
What level of sensitivity/paranoia are you running at here?

**Comment by doapp-ryanp** [comment]
I like your idea of checking in the vars with the values empty (I assume) as a stop gap.  I'm just trying to flesh out a way for servless to more elegantly facilitate this.  It would be a shame for everyone to have to roll their own way of getting sensitive info into their zip wile still being able to collaborate on track a history of what attrs are in what `variables/s-*.json` files.

To satisfy your use case, and ours, what if serverless (during the deployment phase) could load an external file and use the values in that file to set the values of attrs in the `variables/s-*.json` files.  This would allow var metdata to be tracked in version control (if you so wanted) as well as standardizing / giving best practice out of the box.

What about something like:

`<project root>/.secret_vars`
```
[default]
GOOGLE_API_SECRET = AAAAA

[prod]
GOOGLE_API_SECRET = BBBBB
```

`s-variables-prod.json`:
```json
{
  "stage": "prod",
  "googleApiSecret":"${SECRET_VARS:GOOGLE_API_SECRET}"
}
```

the serverless deployment process would be modified to check for existence of `<project root>/.secret_vars` and if it exists replace all references of `${SECRET_VARS:<key>}` in `variables/s-*.json` files.

The `<project root>/.secret_vars` could follow the exact same format as `~/.aws/credentials`

what do you think?

**Comment by erikerikson** [comment]
We are checking the stage-specific variables with values those values are paths into an S3 bucket, a token service, or some other similar controlled and secure source.  I was and am talking about literal references in text form.

I probably should have been a lot more explicit about this but I think your use case is entirely valid and I think you're on to something with a set of `s-variables-secret-common.json`, `s-variables-secret-${stage}.json`, `s-variables-secret-${stage}-${region}.json` files that would be combined (`s-variables-common.json` with `s-variables-secret-common.json` overriding, followed by `s-variables-secret-${region}.json`, et cetera).  This would be the shadow config.

As for a single .secret_vars vs these shadow files standpoint, I don't have a bone in that decision but I think that we ended up with the 'inheriting' separated file structures for good reasons and the .secret_vars approach seems to lose that advantage.

Beyond being helpful, part of what I was hoping to do was selfishly head off the furtherance of a spreading convention of avoiding pushing project assets into source control.

Maybe you can disabuse me of a misunderstanding but anything that goes directly into the lambda package should be of a low security risk nature.  Otherwise the asset is being written unencrypted on to an unknown number of potentially shared disks and its use becomes irrevocable (to at least the published version of the lambda).  Am I missing something on this point?

**Comment by doapp-ryanp** [comment]
> Maybe you can disabuse me of a misunderstanding but anything that goes directly into the lambda package should be of a low security risk nature. Otherwise the asset is being written unencrypted on to an unknown number of potentially shared disks and its use becomes irrevocable (to at least the published version of the lambda).

From the standpoint of a developer working on serverless project a team, when it comes to environment vars, all I care about is the variable name, not the contents (nor should I ever know the contents).  I also need to know when a variable name was added.  In the most secure case, the value of the vars should be injected into the zip by a CI server (or similar).  Dev's should not have access to the place that stores these values nor should they be able to download the lambda zip.

This scenario may be too extreme for most (is for us), so I'm trying to come up with an architecture that allows the variable keys (not values) be in version control, while giving the company the ability to be as secure as they wish with the storage/retrieval of values.

Ex: If you and I are working on the same code, in the same feature branch, and you add code that relies on a new env var `googleApiKey`, I need to know that.  If we go down the route of adding `s-variables-secret-*.json` files, you are proposing that these files are `.gitignored` correct? I would say they'd have to be ignored to prevent accidental checkin of secret creds.  With this as an assertion, I would have no way to know that I need to create a `s-variables-secret-*.json` file with the attr `googleApiKey` other than looking at your entire commit and noticing you are referencing a new var.

If we want to keep the keys in version control, but the values not, the values have to be outside obviously. The `<project root>/.secret_vars` combined with the special `${SECRET_VARS:<key>}` values  would standardize how they got into the zip on deploy.  How the `<project root>/.secret_vars` gets onto the file system is up to the company and their security policies.

> .. head off the furtherance of a spreading convention of avoiding pushing project assets into source control

The inheritance of `s-variables-common.json`, `s-variables-${stage}.json`, `s-variables-${stage}-${region}.json` would continue to work as is. `${SECRET_VARS:<key>}` could be used in any of them.  Can you elaborate a bit more on what you mean by this sentence? I don't see how more project assets would be going into source control...

**Comment by erikerikson** [comment]
> I'm trying to come up with an architecture that allows the variable keys (not values) be in version control

What you mentioned before about defining the attributes with empty strings for values seems like an excellent way to finesse this and the necessary concerns involved.  Given that the `...-secret-...` file's values would override the standard files, you'd get the expected behavior.  A check for empty string values could produce a helpful warning for a coder that didn't notice the key addition.

> If we go down the route of adding s-variables-secret-*.json files, you are proposing that these files are .gitignored correct?

Correct - I would expect to .gitignore the `...-secret-...` files.

> > Beyond being helpful, part of what I was hoping to do was selfishly head off the furtherance of a spreading convention of avoiding pushing project assets into source control.

> Can you elaborate a bit more on what you mean by this sentence? I don't see how more project assets would be going into source control...

Sorry to be arcane.  The *dev* assets are .gitignored by default.  I have removed that line from .gitignore for us (thereby more assets are going into source control [as I desire]).  I would prefer that at least the number of ignored-but-created-by-default-and-needed (i.e. non-`...-secret-...`) files not increase.  In general, I view the contents of the variables files as necessary project content for successful deployment.
The handling of `...-secret-...` files (including inheritability) seems like a great way to satisfy both of our use cases.  It provides you with the ability to specify attributes that must be defined without insecurely propagating the values those attributes will take.  Likewise, for someone like me that will only put something that can be publicly known into those files, I can check in all my stage files and git control my project, less the set of items requiring greater security that are identified by the publicly knowable string references that are my values.

> In the most secure case, the value of the vars should be injected into the zip by a CI server (or similar).

I'm suggesting this isn't very secure at all.  In the most secure case you wouldn't want your assets unencrypted outside of process memory ever (you know, except in generation and encryption).  In the paranoid case you should, at any moment, be able to immediately revoke use of the asset(s) and all usage of those assets must be thoroughly logged for later auditing.  There are far more secure cases and toolsets.  I believe I have only described the paranoid strategy at an entry level.

> Dev's should not have access to the place that stores these values nor should they be able to download the lambda zip.

I'm not sure that downloading is controllable.  I don't see anything so scoped here that wouldn't disrupt necessary rights: http://docs.aws.amazon.com/lambda/latest/dg/lambda-api-permissions-ref.html

**Comment by BlueBlock** [comment]
Shouldn't devs have a separate IAM account key for their dev deployment? Then the production people would use their account key to deploy to staging and production?

**Comment by erikerikson** [comment]
@BlueBlock individual credentials (even temporarily valid credentials) are definitely best practice but those credentials are not checked in to source control.  Those credentials are also used temporarily in an orthogonal manner to other assets like API or SSL keys that the system needs ongoing access to.  What we're discussing here, so far as I understand, is how to provide such assets (and other secrets) to the code in our lambdas.

**Comment by doapp-ryanp** [comment]
@erikerikson if we add the `...-secret-...` files and they are `.gitignored` how do teams of dev's know when new variable's are added to the codebase?  Per my example, how do I know if you added a var with the key `googleApiKey` if the `...-secret-...` file that you added it to is not in version control?

**Comment by erikerikson** [comment]
> if we add the ...-secret-... files and they are .gitignored how do teams of dev's know when new variable's are added to the codebase? Per my example, how do I know if you added a var with the key googleApiKey if the ...-secret-... file that you added it to is not in version control?

from: https://github.com/serverless/serverless/issues/928#issuecomment-205540961

>> What you mentioned before about defining the attributes with empty strings for values seems like an excellent way to finesse this and the necessary concerns involved. Given that the ...-secret-... file's values would override the standard files, you'd get the expected behavior. A check for empty string values could produce a helpful warning for a coder that didn't notice the key addition.

was referencing your comment: https://github.com/serverless/serverless/issues/928#issuecomment-205438564

>>> I like your idea of checking in the vars with the values empty (I assume) as a stop gap.

The scheme would be that a dev would create a new variable that contains a secret in deployment.  They would define that variable with an empty string (or null or whatever) value in the public file and add the secret to their `...-secret-...` file(s).  Then they would write the code that uses that secret.  Before doing anything with the secret, the dev would first check if the secret has the value that was set in the public file.  To address initialization or "haven't hit that code path yet" gotchas, the code could validate that all secrets are provided and provide feedback/warnings if not in the handler's static space (or the equivalent).  The manner of doing so would allow for the need to fill in the secret to be communicated to the engineer that is missing a secret for that attribute.

I think that very it's fair to call that a stop gap solution.  It would work with the current version of SLS but requires code.  That makes your solution of a special variable type or loading scheme **far more attractive** as a means of avoiding it.  There was talk awhile back to move templates from using the syntax "$${TEMPLATE}" to "$T{TEMPLATE}" and variables from "${VARIABLE}" to "$V{VARIABLE}".  It would be trivial in that context to add a "$S{SECRET}" to facilitate the use of `...-secret-...` files.  That solution would be much better, more instructive, and less "hidden-rules-y".

**Comment by doapp-ryanp** [comment]
Thanks @erikerikson 

> The scheme would be that a dev would create a new variable that contains a secret in deployment. They would define that variable with an empty string (or null or whatever) value in the public file and add the secret to their ...-secret-... file(s). 

What do you mean by "public file"? Is it one of: `s-variables-common.json`, `s-variables-${stage}.json`, `s-variables-${stage}-${region}.json`?

So for example:
`s-variables-common.json`:
```json
{
  "mySecretVar":null
}
```

`s-variables-secret-prod-useast1.json`
```json
{
  "mySecretVar":"mypassword"
}
```

Is this what you mean?  The value defined in `s-variables-secret-prod-useast1.json` would override the value in `s-variables-common.json`? If so how would the code "validate that all secrets are provided", since `...-secret-*` files are ignored?  Or are you saying `s-variables-common.json` would be changed to this to communicate it needs to be overridden with a `...-secret-...` file?
```json
{
  "mySecretVar":"$S{SECRET}"
}
```

I have to be honest, I'm not a fan of either, but maybe if you can give a concrete example it will point out something I'm missing.  In addition, IMO the number of files in `/variables` is already borderline overwhelming.

**Comment by erikerikson** [comment]
Sorry.  Busy day.

> What do you mean by "public file"? Is it one of: s-variables-common.json, s-variables-${stage}.json, s-variables-${stage}-${region}.json?

Yes, exactly - those are the public (maybe non-secret would be more clear) files.

However (as a niggle-pick), I was thinking that you would imply the proper level of definition for a variable by declaring the null or empty valued secret variable.  Concretely: if you defined the "null version" of the secret variable in `s-variables-${stage}-${region}.json` then you would expect fellow developers to define the non-null value in `s-variables-secret-${stage}-${region}.json`.  This isn't an important point, I could see an argument for wanting to declare the variable once and allow it to optionally be multiply defined.

To be concrete about the **short term (suboptimal)** solution...
`s-variables-common.json`:
```
{
  "mySecretVar": null
}
```
`s-variables-secret-common.json`:
```
{
  "mySecretVar":"mypassword"
}
```

The SLS code could load and parse `s-variables-common.json` first and then `s-variables-secret-common.json`, overwriting any values duplicated across the two so that the secret value would override the null value.  Then you would inject the variables into your lambda's environment variables.
`s-function.json` (note existing var syntax):
```
{
  "environment": {
    "mySecretVar":"${mySecretVar}"
  }
}
```

In your code you would then check for the environment variable having been defined and complain if it is not:
```
if(!process.env.mySecretVar) {
  throw new Error('CODING ERROR: the "secret" mySecretVar must be defined.');
}
```

This has the advantage of being new functionality and new code without really changing anything that has come before.  The advantage conferred by those attributes is that there are fewer regression concerns to worry about and the new feature with `...-secret-...` files could be bolted on the side looking just like existing project config and migrated later to use a new secret variable format in the future.

I suppose technically that the new `$S{VAR}` format could easily be implemented on the side to go straight to the more optimal solution but then you would have to edit existing code and risk impacting existing users that haven't opted into the code and also the config would have an inconsistent look.

**Your more optimal solution** would use explicit secret variable references:

`s-variables-secret-common.json`:
```
{
  "mySecretVar":"mypassword"
}
```
`s-function.json` (note "$S{VAR}" syntax):
```
{
  "environment": {
    "mySecretVar":"$S{mySecretVar}"
  }
}
```

Now, the SLS framework would identify the case where `$S{mySecretVar}` cannot be resolved and thereby display an informative message and refuse to deploy as a result of the failed variable resolution (!I believe the current behavior for missing variables is only to display a warning!).  Like I've said, your solution is far superior in my opinion, despite a greater impact on the codebase: it's probably the right way to go.

**Comment by erikerikson** [comment]
Actually, I think you could get away with this today after a few changes:
`s-variables-secret-common.json`:
```
{
  "mySecretVar":"mypassword"
}
```
`s-function.json` (note old "${VAR}" syntax):
```
{
  "environment": {
    "mySecretVar":"${mySecretVar}"
  }
}
```
Since you haven't checked the variable definition into source control, you would get the warning during deployment with today's implementation and that could potentially be sufficient heads up for your teammates.

This would limit the changes to reading in the secret files during variable loading.

Maybe you could upgrade the warning to a fatal event in that PR to abort deployment.  That seems like appropriate behavior to me.

Regardless of using this or the other solutions, you would always .gitignore the `...-secret-...` files.

**Comment by doapp-ryanp** [comment]
Thanks for the concrete examples - we are definitely on the same page now :)

I think this would be an OK solution, but I'm still not super excited about it due to the additional `...-secret-...` JSON files because:
*  it adds multiple `...-secret-...` JSON config files per stage
*  I don't like even getting my secret strings close to getting into version control.  imagine a dev fat fingering the name of one of the `...-secrets-...` files and doing a `git push`! or making a `.gitignore` mistake.  

I'm still a fan of loading creds from a single external file (like AWS CLI does with `~/.aws/credentials`) for these reasons.

HOWEVER, as you mention `...-secret-...` files would be optional, so I'm totally cool with serverless going the `...-secret-...` direction.  I could create a new `serverless-var-secrets-plugin` that would populate `$S{mySecretVar}` from a single internal file (`<project root>/.secret_vars`) and then users could use whatever method they like.

**Comment by flomotlik** [comment]
I really think something like a #472 would be a great addition here. I would really like to remove the _meta folder as its just inconvenient and hard to understand. General environment values should be stored in serverless.env.yml and all secrets in a file that is set up and synced with KMS (or the option to talk to a DynamoDB that stores them)

I think this would allow us to completely drop _meta then wouldn't it?

**Comment by flomotlik** [comment]
Closing this issue in favor of of #472
