### ISSUE TITLE
How do I use node modules within a function?

### ISSUE THREAD

**Issue by cevatkerim** [serverless/serverless#948]
It is mentioned in the documentation but there is no example of its usage. Do I create a package.json within every function as I do with lambda functions today? Documentation suggests sharing of node modules but there is no example of it.

Thanks.

**Comment by eahefnawy** [comment]
Hey Kerim! You handle your dependecies however you want. You can have a `package.json` in your function folder for simple projects. In that case the `s-function.json` handler property would look like this: `"handler" : "handler.handler"`

Or you can share dependencies between different lambdas by having the `package.json` file in the parent folder containing all your functions, in that case the handler property of all of those functions would look like this: `"handler" : "functionName/handler.handler"`

Just remember to run `npm install` in the folder containing that `package.json` file before deploying your lambda so that the `node_modules` folder would be available to AWS.

I hope this helps clear this up :blush: ... we'll do our best to improve our docs and make it less confusing

Cheers!

**Comment by nirmalgoswami** [comment]
@eahefnawy can you please provide simple example of `package.json` for adding `node-modules` or particular `module` of `node-modules` folder

**Comment by cdichiara** [comment]
@nirmalgowsami, here's an example:

```
{
  "name": "client api",
  "version": "0.0.1",
  "description": "Serverless module dependencies",
  "author": "me",
  "license": "MIT",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git://github.com/"
  },
  "keywords": [],
  "devDependencies": {},
  "dependencies": {
    "bluebird": "~3.3.4",
    "crypto": "~0.0.3",
    "https": "~1.0.0",
    "is-my-json-valid": "~2.13.1",
    "node-uuid": "~1.4.7",
    "utf8": "~2.1.1"
  }
}
```

This `package.json` resides at `/clientApi/package.json`.

**Comment by nirmalgoswami** [comment]
@cdichiara Thanks for example :+1: 

but this will also add all node modules in all lambda function.i am assuming that `clientApi` is parent folder of all lambda functions.i want to add module in specific in lambda function not in all lambda functions

**Comment by cdichiara** [comment]
Oh, yes, good question ... you may have to ask someone more experienced than I to help with that. I think that might be a separate question from what @cevatkerim was asking, too.

**Comment by eahefnawy** [comment]
@nirmalgoswami you can add `node_modules` inside your function folder and have the `handler` be set like this: `"handler":"handler.handler"` ... of course this means that this particular lambda function won't access the other `node_module` folder in the parent directory.

**Comment by nirmalgoswami** [comment]
@cdichiara @eahefnawy i have used `excludepattern` property of `s-function.json`,but in this case i have to add entry when new functions will be added in project,right now `opimizer` plugin have some bug related parent folder so i am using `excludepatten`.i wonder it there is any oppsite property exists in `s-function.json` eg - `includepattern`

**Comment by flomotlik** [comment]
Currently there isn't, but it will be on V1 of the framework. I will close this issue as we'll open others to track the progress on those tasks
