### ISSUE TITLE
Deprecation warning: CLI options definitions were upgraded with "type" property

### ISSUE THREAD

**Issue by tetiana-fomina-photobox** [serverless/serverless#9540]
Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessOffline for "apiKey", "binPath", "cacheInvalidationRegex", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "exec", "hideStackTraces", "host", "httpsProtocol", "location", "noAuth", "noEnvironment", "port", "prefix", "preserveTrailingSlash", "printOutput", "providedRuntime", "region", "resourceRoutes", "showDuration", "skipCacheInvalidation", "stage", "useSeparateProcesses", "websocketPort"

**Comment by pgrzesik** [comment]
Hello @tetiana-fomina-photobox, it looks like an issue with `serverless-offline` plugin. I believe it was already fixed in the latest version, if that's not the case, please report the problem at `serverless-offline` repository. 

For the future, please follow the issue template that is visible when you create a new one, it helps debugging and evaluating the problems tremendously.

I'm going to close this one as it's not directly related to Framework core.
