### ISSUE TITLE
How to reduce lambda function size

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#964]
so many people have this issue so i am creating this issue for discussion

suppose you are using lots of third party module which are located in `node-modules` 

but in some case lambda function require two or three third party module,how to include only few of them in lambda function

`serverless-optimizer-plugin` can solve issue but it have issue like parent folder does not support right now see [bug](https://github.com/serverless/serverless-optimizer-plugin/issues/29)

we can use like this
`s-function.json`

```
"custom": {
    "excludePatterns": [],
    "envVars": [],
    "optimize ": {
      "exclude": [
        "aws-sdk",
        "mysql"
      ],
      "includePaths": [
        "../node_modules/abc",
        "../node_modules/pqr"
      ]
    }

  },
```

but `serverless-optimizer-plugin` does not support url like `../node_modules`

we know that `The Handler Property Is Very Flexible` but it should not good to include all unnecessary folder.look like there is also option by making more `s-project.json` file in sub folder but there is any document about how to use it

what is solution to reduce lambda function zip size ? Thank You

**Comment by neaghfoz** [comment]
My solution is that add a new option to do this. You can use the ```disableModules``` branch in my own repo: https://github.com/neaghfoz/serverless-optimizer-plugin.git

The example usage:
```
"optimize": {
      "exclude": [
        "aws-sdk"
      ],
      "includePaths": [
        "restApi/assets"
      ],
      "disableModules": [
        "gm",
        "debug",
        "array-parallel",
        "array-series",
        "ms",
        "bwip-js"
      ]
    }
```

The option will exclude the modules and add the ```${project_root}/node_modules/your_module``` to your function package. So it won't reduce the lambda code, only for skipping some modules which not support optimizer plugin.

**Comment by HyperBrain** [comment]
Another approach would be to have separate function roots (see magic handlers), each with different `package.json` definitions. So you could group your functions. These function groups most likely will reflect your logical application layout as different functionalities use different dependencies whereas similar functionalities most probably use the same dependencies.
This would not make the available amount and use of options more complex as new options would do.

**Comment by hollanddd** [comment]
+1 for being able to group functions in a way that they would be able to access shared dependencies. I would like to add to this conversation but it applies more to packaging for deploy than reducing function size so my apologies in advance if this isn't the right place. For my use case I want to package a binary w/ multiple functions but as it stands I must include the binary in each function directory. Additionally, when I use `includesPath` option from `sls-optimizer-plugin` to include the binary I must be inside the function directory when running `sls function deploy`.  This prevents me from being able to deploy my functions with `-a` option.

**Comment by flomotlik** [comment]
@hollanddd we're planning to decouple the code for a function and a function configuration in the future so you should have a much easier time with this in the future.

In my opinion by default serverless shouldn't try to be smart about limiting what you're putting into the zip file deployed into your lambda. Basically with multi-language support built into it we want to make sure we give a great experience to everyone out of the box. Zip size is something that isn't necessarily a problem for everyone so we can help with the optimizer plugin, but I don't think it should be in the core.

It sounds like the optimizer plugin is going a long way towards that problem though?

**Comment by license2e** [comment]
@flomotlik What about only zipping directories with certain patterns (only if they exist)? 

For example:
`node_module`
`lib`
`shared`

**Comment by flomotlik** [comment]
yeah we're implementing an include/exclude functionality into V1 of the service. So you can easily include or exclude whatever you want to. This should also help with cross-language setup as it easily allows to build language specific packages for different functions

**Comment by hatembr** [comment]
+1 for including/excluding folders. But here is another scenario not dealing with shared code.
Today while experimenting with the framework, we noticed that when selecting a specific function to be deployed, the whole folder with all the other functions' code was being uploaded. 
It makes more sense to deploy only the desired function's code (folder) along with any shared lib in the parent folder, depending on how the handler is set.

Let's say we have this structure:
/project
/project/functions
/project/functions/lib
/project/functions/lib/node_modules
/project/functions/resource1/method1
/project/functions/resource1/method2
/project/functions/resource1/method3

Given we were using shared code from the /project/functions/lib folder,  we've set the handler like this: "resource1/method2/handler.handler". 
This way /project/functions/lib was also going to be included in the deployed code.

Now what surprised us is when downloading the deployed code, we found out the zip file contained all the functions inside the /project/functions/resource1 folder. All folders on the same level as method2 were included as well as the files inside them.

We were expecting this structure:
/project/functions/lib
/project/functions/lib/node_modules
/project/functions/resource1/method2

instead of:
/project/functions/lib
/project/functions/lib/node_modules
/project/functions/resource1/method1
/project/functions/resource1/method2
/project/functions/resource1/method3

Which obviously increases the code size and would be terrible of you had dozens and dozens of functions and resources in a complex project.

Unless we are missing something from the documentation or misunderstanding how to set the handler path, SLS should filter out those folders and exclude them from the deployed code in order to reduce the size.

Any feedback or clarification is appreciated.
Thanks

**Comment by license2e** [comment]
@hatembr: Here is an example of how you can set up your exclude paths:
```
  "custom": {
    "excludePatterns": [
      "project/functions/resource1/(?!method2).*", // exclude all but method2 directory
      "project/functions/(?!resource1).*", // exclude all but resource1 directory
      "project/\\..*", // dot files
      "project/other",
      "project/test"
    ]
  },
```

You may have to play around with the regex a bit to make it work..

Note: I had to edit `lib/Runtime.js` - function: `_processExcludePatterns` to add `- using: ${sRegex}` so that when I add `--debug` flag it would tell me the exact regex pattern that excluded that path:

```
          if (willExclude) {
            S.utils.sDebug(`"${stage} - ${region} - ${func.name}": Excluding - ${filePath} - using: ${sRegex}`);
          }
```

Lmk, if you have some problems with that, and I can take a closer look at your setup...

**Comment by hatembr** [comment]
Thank you @license2e , this is very helpful. 

So if I understand well, SLS by default would deploy all the code in the parent folder and it's up to the developer to exclude whatever they want?
If so, why not doing it the other way around? ie. deploy only the targeted function and leave it up to the developer to include whatever else they want?

**Comment by flomotlik** [comment]
You can see the include/exclude functionality of V1 here: https://github.com/serverless/serverless/blob/master/docs/understanding-serverless/serverless-yml.md

**Comment by robbieaverill** [comment]
^ this link is broken now. Up to date reference: https://www.serverless.com/plugins/serverless-python-requirements#optimising-packaging-time
