### ISSUE TITLE
Refactor: Seclude `plugin install` & `plugin uninstall` commands out of internals

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9740]
### Use case description

While service dependent, those commands are specific. They do not require service to be fully setup (we just need accessible `plugins` section), they also should not be hack-able by the plugins.

Having them handled with lifecycle engine, brings unwanted side effects as reported with https://github.com/serverless/serverless/issues/9731

Ideally those (same as not service specific commands -> https://github.com/serverless/serverless/issues/9738) should be secluded out of internals

### Proposed solution

Refactor into `commands/plugin-install.js` and `commands/plugin-uninstall.js`. Those modules should simply take context object that provides access to `configuration`, `serviceDir` and `configurationFilename`.

Having that handling of those commands should be propagated to those commands in `scripts/serverless.js`

**Comment by issea1015** [comment]
Hello @medikoo 👋 - I have read the flow around this topic in the code. I think all you described make sense, 
one thing I can't follow up is:

> Having that handling of those commands should be propagated to those plugins in scripts/serverless.js

- I'm not sure which plugins you meant here. Installed/Uninstalled plugin?
- Do we want to propagate to those plugins through `event-hook` mechanism? It would let any plugin hack the behavior of `plugin-(un)install` command. So I think 'no' in the context of your description.
- Then you could have mentioned the telemetry system. But not much likely.
- I totally have no idea :joy:

And can I take a chance to handle this if you can spare time to guide me? :)

**Comment by medikoo** [comment]
@issea1015 great thanks for interest!

> I'm not sure which plugins you meant here. Installed/Uninstalled plugin?

Sorry, actually this instruction was badly formed. I've updated it.

Idea is to implement logic for `plugin install` and `plugin uninstall` as a standalone commands in `commands` folder.
For that e.g. `commands/plugin-install.js` module should export function which takes needed input as:

```javascript
module.exports = { serviceDir, serviceFilename, configuration options }` => {
 // plugin-install implementaiotn
}
```

And then simply to invoke those commands directly in context of `scripts/serverless.js` (which is an entry main module for `serverless` CLI). It can happen somewhere here: https://github.com/serverless/serverless/blob/5155e0180e0cd5e3130bc74e308a97c0ea1a5c2b/scripts/serverless.js#L491

**Comment by issea1015** [comment]
@medikoo Crystal clear now. Let me have some fun and come back with PR!

**Comment by issea1015** [comment]
Hello @medikoo 👋 - I have some questions before go further
- Is it good to migrate current plugin logic as much without touch as possible into the standalone command?
    - Is it good to import internal library modules in the standalone command?
        - https://github.com/serverless/serverless/pull/9942/files#diff-0eaec7938b8410881ba876915c3000cc4d3e167ab0a147ce4becac6e39cff580R13-R18
- Does it make sense to have a more depth-ical directory structure for command modules? In order to put utility modules in the correct scope.
    - https://github.com/serverless/serverless/pull/9942/files#diff-0b1fc7e22cb04b1c5421384939f93b7a31e28963238a4605b5f67f07dc8ef1dd
- Meaning of `externalCommand` seems not aligned with `externalPlugin` in `PluginManager`. As `externalCommand`’s implementation is in the `serverless` repo while `externalPlugin`’s one is out of the repo. Better idea?
    - (It seems a bit dedicated to PR, but posting here just for cases that this could be helpful in the future)
    - https://github.com/serverless/serverless/pull/9942/files#diff-3da8af62fdab1ee0823e15aa68df1bbe66321e70b857fb1453351ba2a35e3f51R44

**Comment by medikoo** [comment]
> Is it good to migrate current plugin logic as much without touch as possible into the standalone command? 

Ideally we if take the logic, but simplify it and rely purely on native promises. So let's not do 1:1 copy

> Is it good to import internal library modules in the standalone command?

That's totally ok 👍 

> Does it make sense to have a more depth-ical directory structure for command modules? In order to put utility modules in the correct scope. 

If there's a need to seclude some utils which are common to both commands. Let's put themmaybe  into `lib/commands/plugin-management.js` (idea is to keep all _private_ modules in `/lib`, and we can assume everything that's exposed in `/commands` is _public_)

> Meaning of externalCommand seems not aligned with externalPlugin in PluginManager

I think it'll be better to name it `standaloneCommands`, as by no means they're external

**Comment by issea1015** [comment]
@medikoo Every line of the feedback is clear to me.

> (idea is to keep all private modules in /lib, and we can assume everything that's exposed in /commands is public)

Thanks to share even the reasoning! 💯

**Comment by issea1015** [comment]
Current test suites and cases for plugin management dedicate to checking all internal methods and details. But now [we don't want to rely on internal methods in tests in any way because it makes refactoring harder in the future (we've already been bitten by it multiple times)](https://github.com/serverless/serverless/pull/9909#discussion_r706177956). If we want to stick to testing the topmost interface without mock any internal method, we have to endure NPM calls every time we run the tests. There are few options:
- O1: Have not unit test for plugin management commands, which are dealing with NPM command
- O2: Mock methods dealing with NPM command, while test topmost interface and not internal methods
     - -> This option is still not aligned with our new test policy

@medikoo What do you think?

**Comment by medikoo** [comment]
@issea1015 I've just saw your comment. In PR review I've proposed how to go with that. Let me know
