### ISSUE TITLE
Master Branch - `serverless dash deploy` is not working

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#976]
before it was working fine with few lambda functions,now i have `16` lambda functions,i am `not able to select function and endpoint` to deploy on aws

if i will use `down` key then it will automatically make duplicate of my lambda functions entries in terminal.i am not able to go at bottom.strange issue :(

**Comment by eahefnawy** [comment]
@nirmalgoswami yeah we're aware of this issue. It's really hard to make a fully fledge UI using the CLI because of issues like that. That's why we started this project: (However it's not active currently)
https://github.com/serverless/serverless-dashboard

We recommend making use of how you organize your functions by grouping them in folders and run `sls dash deploy` inside those folders. This will filter the list of functions to only include the functions in that folder.

I hope this helps! And I'm really sorry for your bad experience :/

**Comment by nirmalgoswami** [comment]
@eahefnawy Thanks again for quick response.your work is fantastic.You dont need say sorry :)
