### ISSUE TITLE
Externalize Serverless Components CLI

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9855]
### Use case description

Currently `serverless` package, under the hood exposes three distinct CLI programs:
- Serverless Framework
- Legacy, no longer evolved version of Serverless Components (aka v1 of Serverless Components)
- Serverless Components (which internally provides different deployment engines for AWS and Tencent providers)

At the beginning of `serverless` command processing [CLI triage logic](https://github.com/serverless/serverless/blob/1aa24b8991032ba3fe6f2c4b65bf0e70bc4171dd/bin/serverless.js#L34-L53) jumps in, and decides which CLI program should be run for given CLI invocation.

Fact of installing and handling three different CLI programs with `serverless` package imposes following issues for Serverless Framework users
- CLI triage logic noticeably affects command start up time (e.g. it makes tab auto-completion feature baked into Framework near not usable). I observe 0.4-0.9s time taken just on loading the CLI modules, and that can be cut off completely when we will not require those modules
- Dependencies which are not related to the Serverless Framework are installed with the `serverless` package. Biggest issue is that some of those dependencies are heavy, pursue a compilation step (come with C++ addons) and include reported security vulnerabilities, and that we (Serverless Framework maintainers) cannot reliably control what new dependencies will eventually be added in context of those other CLI programs.

Ideally if it's only Serverless Framework that's unconditionally installed with `serverless` package, and the other CLI's are resolved and eventually installed on demand. This will also allow to separate update process for the detached CLI's, as when stored separately we can individually upgrade it with dedicated commands without a need of upgrading `serverless` package.

### Proposed solution

1. Move CLI triage resolution logic fully to Serverless Framework, so it's fully independent of any other modules, and so no modules from other CLI programs are loaded unconditionally as it's the case now (it's responsible for a slow startup of our CLI)  - _(This should not be considered as breaking change, and can be released in context of v2)_
1. In context of [Serverless Components v1 CLI](https://github.com/serverless/cli):
   - Configure a binary standalone generation (similar as one on Framework grounds), and ensure that generated assets  are uploaded github to release assets
   - Configure [update-notifier](https://www.npmjs.com/package/update-notifier) based new version notifications, which depending on installation type used (npm or maybe standalone) list accurate update method
   - Configure `upgrade-legacy-components` and `uninstall-legacy-components` commands for controlled binary standalone updates (at same time ensure that those commands are recognized as given CLI specific in Framework CLI triage logic)
1. In context of [Serverless Components v2](https://github.com/serverless/components):
   - Configure a binary standalone generation which with each release is added to release assets and uploaded to Tencent cloud (this should mirror functionality we have setup for the Framework)
   - Configure [update-notifier](https://www.npmjs.com/package/update-notifier) based new version notifications, which depending on installation type used (npm or maybe standalone) list accurate update method
   - Configure `upgrade-components` and `uninstall-components` commands for controlled binary standalone updates (at same time ensure that those commands are recognized as given CLI specific in Framework CLI triage logic)
1. _As it's a significant shift, and may stop component command from working (automatically) in some corner-case scenarios, it should be considered as breaking change to be implemented in v3 branch._
Upgrade triage logic, so any other CLI programs aside of Serverless Framework are resolved (and eventually installed on demand). If CLI triage will point non Serverless Framework CLI, resolve the target program with following logic:
   - If target CLI is installed locally, fallback to it
   - If target CLI is installed globally on npm grounds, fallback to it
   - If for a target CLI there's a downloaded binary available, fallback to it.
   - If we're in an environment for which no standalone binary is built (corner-case scenario) present user with message asking to install target CLI manually via npm. Otherwise present user with a notice that CLI program is being installed, and download a CLI standalone to `~/.serverless` folder. After it's downloaded, fallback to it.

--- 

@pgrzesik @mnapoli @ole3021 let me know your thoughts

**Comment by pgrzesik** [comment]
Thanks for the proposal @medikoo :bow: There's one thing I think I'm not getting which is how the new triage logic should behave? If I'm not mistaken, in the current logic (https://github.com/serverless/serverless/blob/1aa24b8991032ba3fe6f2c4b65bf0e70bc4171dd/bin/serverless.js#L34-L53) it depends on the actual implementation in the corresponding CLIs (`@serverless/cli` and `@serverless/components`), so I'm assuming that we will have to keep the logic that is responsible for e.g. loading configuration and interpreting it be a part of the Framework. One problem I see with that is potentially breaking change when that logic changes on the corresponding CLI side as the same change on Framework side will have to follow.

**Comment by medikoo** [comment]
> Did you measure that the majority of time is 'wasted' on loading external modules or rather on executing logic that tries to load the config file and determine if it's ComponentsV1 or V2?

Yes, it's just following part that eats 0.4-0.9s:

https://github.com/serverless/serverless/blob/00fdba154655b15b5b2de4b9ceca08f8bfce599e/bin/serverless.js#L37-L38

You can check on your own :)

Otherwise remaining triage logic closes on my side below 10ms usually. Still there are some potential performance problems in there as well.. e.g. with certain commands it attempts to check all subfolders, still I think it's very rare scenario that there will be hundreds of folders to check 

> One additional problem I see with that is potentially breaking change when that logic changes on the corresponding CLI side then the same change on the Framework side will have to follow

It's about _moving_ CLI triage logic completely, so it's no longer hosted in component CLI's. If such CLI is run it would unconditionally assume it's the target.
This will require a major bump in Components but we anyway should bump they're major to drop support for Node.js v10 as it's the case in Framework.

**Comment by pgrzesik** [comment]
> Yes, it's just following part that eats 0.4-0.9s:

Perfect, thank you for all clarifications :+1:

**Comment by ole3021** [comment]
@medikoo  Sorry for reply later, was busy with something else. After i check the proposed solution you provide above, i think here are following problems to consider as well.

1. Tencent insist to keep using `serverless` or `sls` as the command for Serverless Tencent.
2. Currently the default Serverless Framework CLI usually cause issues for some use cases, eg: it keep showing different commands in english when user execute the command in a incorrect folder. 
3. Hard to tell and let user understand the right way to user components CLI. eg: User need to know there a product called Serverless Framework and need to use `sls` in components folder to avoid goes into the Framework CLI. As the Serverless Framework is not available, this is make user confuse at beginning. 
4. User from China cant have consistent user experience. User not fell the same way when use serverless CLI, as the display, commands, and usage are kind of different.  

With the proposed solution 
* i think it can fix the problem 1, 2, but with demand package install, it still big for users from China. currently our package is 4.4M and competitive tool is 700kb. 
* for problem 3, i guess it could be fixed, but still may have issue there shows Serverless Framework CLI commands, and confuse users. (eg: before success install the demon package)
For problem 4, i think it is also quite important to branding serverless and give user the experience, and more importantly, we don't need to re-implement the same feature twice. 

There is an idea in my mind, i think it can be a better solution, but need help to check and verify if it possible to implementation.

The idea is let the Serverless Framework CLI work as an Interface without product customized implementation. 

* The product related feature (`deploy`, `remove`) implemented on server side, and share the same Interface as inputs and outputs.
* The general feature (`init`, `config`) implemented on the CLI and shared between different products.
* Use a white list for different products users to see different set of commands. (Users in China won't see the commands designed specific for AWS) 
* The CLI can show translated content based on their timezone/location.

As the same time:

The logic how we save and track user event will be the same, and the design will keep the same. 

I think this can be a good way to keep the Serverless Framework CLI works in the same way we designed, and user also can share the CLI user experience between different products (User don't need to learn and tell different products from Serverless Framework on CLI usage.)

**Comment by medikoo** [comment]
Thanks @ole3021 for your points, below is my answer

> 1. Tencent insist to keep using serverless or sls as the command for Serverless Tencent.

Yes this will not change

> 2. Currently the default Serverless Framework CLI usually cause issues for some use cases, eg: it keep showing different commands in english when user execute the command in a incorrect folder.

Technically there's no way to solve it as long as same CLI command provides two different products under the hood, and via triage logic decides which is run. There's always a scenario where triage will favor Framework

> 3. Hard to tell and let user understand the right way to user components CLI. 

I think Serverless Components CLI misses good documentation website. Is that correct? Have you considered providing one for Chinese users?

> with demand package install, it still big for users from China. currently our package is 4.4M and competitive tool is 700kb.

It's a one time operation (just on first time use), and we will download a package from Tencent region, so if user is on relatively fast network, it should be fast enough.

> The product related feature (deploy, remove) implemented on server side,

Can you provide more details? Framework works with local user files, and such logic cannot be run on server-side

> and share the same Interface as inputs and outputs.

Those are two very different programs, and I don't think it's possible to change both so e.g. exactly same set of commands and flags are used.

> Users in China won't see the commands designed specific for AWS

Serverless Framework has also users in China, and timezone detection is also subject to errors. So such change will make impossible to use Serverless Framework all around the world. 

In general as long as we're using same CLI command for two very different programs, things just cannot work perfectly, it's always subject to some compromises for both sides.

**Comment by ole3021** [comment]
@medikoo  

answer for the questions `I think Serverless Components CLI misses good documentation website` : Yes, I have add those content in the documentation, and keeping working on it. but you know that user always wants to hands on quickly, and usually not read doc a lot unless they have some problem. I just want to say for user to use Serverless in China but needs to 

1. understand there are two different CLI in the same CLI tool, and they should always use the hide one (the components)
2. To use the components user need to tell which folder currently it is, otherwise the CLI may not work as expected, which is a pain for user to focus on development. 

For my propose Here are more details.

* I think we can take the CLI as an UI, and just like the proxy design pattern, The CLI defined the commands (user inputs), and the result structure needed for each commands, leave the implementation on the server side. No matter how the logic changes/differently, the usage and result of CLI keep the same. 

To achieve this, we need to 

1. Define list of commands and inputs(parameters), outputs (response) structure. 
2. Define a way to auto tell is Tencent User or Global User. (We can make this a config in the CLI, and user can change easily)
3. For some Client side feature (like `init`), it will show an interactive command for user to init a project from a template. 
    * [For AWS] shows the AWS lambada list templates in English
    * [For Tencent] shows the Tencent list template in Chinese
    * > This will only need to save different url to fetch template, and the other process will be the same. 
3.1 For help doc, base on user location and default product, the CLI will show different URL. 
4. For Serverless side feature (like `deploy`), it will do the same upload with different target URL.
    * [For AWS] the global platform will get notify after upload user code and start do the deploy process
    * [For Tencent] the tencent platform will do tencent specific deploy process
    * Both Tencent and AWS deploy logic use the same structure for the deploy result. which will handled by CLI and show as completed result.
4.1 For feature (`logs --tails`), The CLI just pass the app info and waiting for a socket URL to connect and show the message from the socket. 
5. For product specific commands (like `plugin`), there should have a white list for each product that which commands are available. 
    * [For AWS] the command will be show (as we auto set the user to Global and the Serverless Framework Product) 
    * [For Tencent] the command will not be show.
    
With this approach i think there are following pros
* There no need to implement the track, config logic twice, which can reduce the package size.
* No need to worries about which folder should user which CLI to handle.
* It will avoid commands, parameter, behaves difference and make it easier for user to use Serverless different Products. (user no need to think but commands works as expected)
* The interface and usage are same, it make user easier to pick up the CLI knowledge from different channels (No need to read Tencent specific docs, and examples)

Also there are cons like
* For the feature change (new command, update response structure), Both team need to review and update.

**Comment by medikoo** [comment]
> The CLI defined the commands (user inputs), and the result structure needed for each commands, leave the implementation on the server side.

@ole3021 can you clarify what do you mean by that? Note that many of the Framework commands are local only (do not require internet to work), and most of the commands  access user file system, such tasks cannot be run on some external server.

Additionally note that we cannot introduce any vast breaking changes to Serverless Framework, so reshape of that product (so those two different programs can meet some way) is not a table.

Concerning your other points, we had at some point initiative of which goal was similar. We planned to merge Components CLI logic into the Framework CLI. So we somehow merge the command schema of both CLIs and that way provide unified experience.
Necessary refactors in that direction were made, however we didn't pursue any further steps, and it was not yet deeply investigated how well we can merge those CLI's, I believe there still will be compromises to be met. On that matter it's best if you discuss with @ac360 and @mnapoli directly

> to use Serverless in China user needs understand there are two different CLI in the same CLI tool, and they should always use the hide one (the components)

Improvements we can make in that area is to:
1. introduce an environment variable, which when set in system, will restrict the CLI to run Components all the time. e.g. `SLS_CLI_ENGINE=components`.
2. Introduce a user config setting, so after user runs `sls config --engine=components`, triage will unconditionally assume Components

**Comment by mnapoli** [comment]
@ole3021 thanks for the clear details, that helps understand (and I know we discussed that before as well so that helps too).

> I think we can take the CLI as an UI, and just like the proxy design pattern

That is a clever idea, that would allow unifying the whole user experience across both CLIs. However, both CLIs work very differently today. Unifying the features and behaviors behind a single UI would be a huge task, and would mean breaking a lot of things for users, possibly also plugins (which is something we want to avoid at the moment).

Additionally, as Mariusz mentioned, the Framework CLI is designed to run everything locally. Shifting all logic to a backend is a drastic change.

At the moment I think we need to deal with the situation that the 2 CLIs are different projects, and try to improve the painful details. Keeping the requirement of sharing the same CLI name (`serverless`), what can we do to improve the user experience?

> Currently the default Serverless Framework CLI usually cause issues for some use cases, eg: it keep showing different commands in english when user execute the command in a incorrect folder.

Maybe we should make the selection between Framework CLI / Tencent CLI more persistent? For example, when users install the CLI and run their first command we could ask them (based on location) if they want to use the Tencent CLI or not?

If they say `yes`, then Tencent CLI is installed and used for all future commands. Would that work?

> Hard to tell and let user understand the right way to user components CLI. eg: User need to know there a product called Serverless Framework and need to use sls in components folder to avoid goes into the Framework CLI. As the Serverless Framework is not available, this is make user confuse at beginning.

Indeed maybe documentation + having a default selection of Tencent CLI could help a bit here?

> User from China cant have consistent user experience. User not fell the same way when use serverless CLI, as the display, commands, and usage are kind of different.

I'm not sure we would be able to solve this unfortunately, as features of both CLIs are indeed different.

**Comment by medikoo** [comment]
> For example, when users install the CLI and run their first command we could ask them (based on location) if they want to use the Tencent CLI or not?

+1

Also for users in China we can present such question as first, when they run `serverless` command

**Comment by ole3021** [comment]
@medikoo  For your questions above

> can you clarify what do you mean by that? Note that many of the Framework commands are local only (do not require internet to work), and most of the commands access user file system, such tasks cannot be run on some external server.

Let me explain with some example.
* [`deploy`] This that need to be handled by the server, and from CLI perspective, CLI just need to upload the code and notify the server to complete the deploy process and then show the result. 
* [`invoke local`] This is a pure local command, and it just to execute user function locally and show the result. 

So what I mean is that each of the commands can be abstract to a behaviour not  bind to a product.  For the implementation:

* For local commands we may have separate the implementation, but not much commands need to be fully run local.
* For server commands, The CLI just need to call different URL, and pass different project Meta Info then wait and show the response. 
    * and once we have a fixed object structure for the response object, the CLI output can be compatible with different products.
    
> There will still have different config (like server endpoint) and implementation (how to read project meta info, handling local commands different) but it will be quite small. There won't have the package size, load time, and maintain complexity.

--- 

@mnapoli 

> the Framework CLI is designed to run everything locally. Shifting all logic to a backend is a drastic change.

What i mean is that the product specific logic (eg: deploy user code to Tencent / AWS) are implemented on server, and the CLI does run fully local. And this is what we do currently (at least on component CLI implementation). The point i like to mention is we can split all the product related feature from the CLI commands, parameters and results.
* For local commands (eg: `invoke local`) we can have separate implementation. 

* For server based commands (eg: `deploy`, `remove`), if we unify the commands, and result info structure, we can use them for different products, and it should has no issue. And user won't feed any difference by execute the CLI command, just we deploy them to different cloud vendor, different products.

**I think for this change is we need to unify the commands, parameters and what info should be handled for each commands result, also the behavior of each commands needs to be same in different products.**

> For example, when users install the CLI and run their first command we could ask them (based on location) if they want to use the Tencent CLI or not?

This does work, but still not fix the large package, startup slow, and brand consistent CLI experience (without another implementation). 

> Indeed maybe documentation + having a default selection of Tencent CLI could help a bit here?
We have this, but still require user to read and understand this. I think if we can build something meet "don't make me think" thats will be great. 

Instead ask user to choice which product (serferless framework or components) we should ask which cloud provider and language they like to use. Which also could help users use cloud vendors other than AWS from Global as well (There may have different support and implementation as well). 

> as features of both CLIs are indeed different
There are base commands (`init`, `deploy`, `remove`) and product specific commands (`plugin`, `metrics`, etc). I think 
* For base commands there has no different in abstract level. 
* For the Product specific commands, we can hide them based on user location and preferred products/vendor.
* The the commands shared in different products (eg: `invoke local`) we can use different implementation, and those commands are little. 

--- 

@medikoo @mnapoli 

> We planned to merge Components CLI logic into the Framework CLI. So we somehow merge the command schema of both CLIs and that way provide unified experience.

This is what im looking for with my proposal. I think its a good time to consider this, otherwise for following couple years, we still have this issue. also i know there will have other compromises we need to make, and it may cause lots works to complete, but i think it worth it (will check with Austen and Maciej as well).  I propose this solution is wondering 

* Technically , if is possible. 
* Does it has any conflict with our product roadmap. 

If it looks good from technically and no conflict with our roadmap, i think we can have a future design and evaluation on this proposal then discuss with Team if we will do it or not. 

Extra thoughts: The are few popular and widely used commands by developers (eg: `deploy`, `dev`, `logs`, etc).  I think we can start from those popular commands, once we build a consistent great experience in those popular commands, we can have compromises on the other commands. 

cc: @ac360 @skierkowski  please have a check when you got time and love to get feedbacks from you as well.

**Comment by mnapoli** [comment]
> What i mean is that the product specific logic (eg: deploy user code to Tencent / AWS) are implemented on server, and the CLI does run fully local. And this is what we do currently (at least on component CLI implementation).

Right, definitely understand that. The Framework CLI however works very differently, so this is what I meant by "drastic change".

As for the roadmap, I think it's safe to assume it would have a large impact on the product roadmap (because of the fact that these would be large changes to the framework). It would also be a large impact on the product itself (again, some commands will change, and more importantly many plugins would be impacted): we are talking about a complete change in how the Framework would work.

But still, let's discuss it indeed with Austen and Maciej, it's only fair to give this suggestion proper consideration. I wanted to bring that up at the last product meeting but we did not have time to discuss it. I will be off in the next product meeting, so Oliver maybe try to reach out to them directly? If not, I will try to bring it up at the following meeting in 2 weeks.

**Comment by ole3021** [comment]
@mnapoli 

Thx for updates. as I'm not very clear about how we build the CLI  serverless framework, so i just assume based on the component implementation, and i just think this is a good time to consider a solution that can solve all the issues we have today. 

I will follow up with the team, thx again for your help and clarification.

**Comment by ole3021** [comment]
@medikoo  after discuss with Austen, we will try build a CLI plugin serverless-tencent for components support, also we may need extra support from CLI to make user from China get a good UX without aware there are too many difference but can easily start coding and deploy with serverless CLI. 

i think we are good to close this ticket, and i will propose the plugin solution later. 

cc: @mnapoli

**Comment by medikoo** [comment]
@ole3021 this issue is about fixing important performance and security issues for Framework users, I believe it should stay in consideration. It doesn't collide in any way with whatever roadmap is taken for Tencent provider implementation

**Comment by mnapoli** [comment]
Anything left here or can we close this?

**Comment by medikoo** [comment]
Indeed, can be closed. Thanks @mnapoli for heads up
