### ISSUE TITLE
The link to "referencing environment variables" is broken in the documentation

### ISSUE THREAD

**Issue by shashank-b** [serverless/serverless#9944]
The link to "referencing environment variables" is broken in the documentation (https://serverless.com/framework/docs/providers/aws/guide/functions/#environment-variables).

Link to the code: https://github.com/serverless/serverless/blob/3cad518d0d81f4fecdf966545591d7e7303adb4a/docs/providers/aws/guide/functions.md#environment-variables

**Comment by mnapoli** [comment]
It seems like the problem comes from the trailing slash:

- https://serverless.com/framework/docs/providers/aws/guide/functions
- https://serverless.com/framework/docs/providers/aws/guide/functions/

Both of these links point to the same page, but the second one has a trailing slash. That means that relative links in the page are broken (I can find a few others in the page).

I'll report that internally to see what we can do, thank you for the report!

Out of curiosity, how did you land on that URL? Was it linked from somewhere else?

**Comment by shashank-b** [comment]
I clicked on a link on this page - https://www.serverless.com/blog/serverless-express-rest-api#converting-an-existing-express-application

Look for the text "likely via Environment Variables.", which leads to https://serverless.com/framework/docs/providers/aws/guide/functions/#environment-variables

**Comment by mnapoli** [comment]
Thank you!

**Comment by staff0rd** [comment]
It appears header links in the docs are broken on serverless.com - for example [browse here](https://www.serverless.com/framework/docs/providers/aws/guide/intro) and hover over the first header. You'll see a link to

```
https://www.serverless.com/framework/docs/providers/aws/guide/intro.md#aws---introduction
```

However, the `.md` should not be there. Clicking the link immediately displays a 404. The links rendered should not include `.md`.

**Comment by mnapoli** [comment]
@shashank-b: the problem has been solved thank you for the report.

@staff0rd thanks for reporting this separate issue, I've reported it too.

**Comment by domdomegg** [comment]
Probably related - clicking the link to 'HTTP API guide' on the [API gateway page](https://www.serverless.com/framework/docs/providers/aws/events/apigateway) takes the user to https://www.serverless.com/framework/docs/providers/aws/events/http-api.md which 404s. This should not have a trailing `.md`.

**Comment by mnapoli** [comment]
@staff0rd just an update, this has been fixed.

@domdomegg thank you I'm on it.

**Comment by mnapoli** [comment]
All good now, thank you all!
